### ISSUE TITLE
Unable to run job template

### ISSUE THREAD

**Issue by ghost** [MrMEEE/awx-build#10]
Hi,

I can run following playbook from command line and it executes fine. However, it fails when running through AWX. Here is my playbook:

---
- hosts: all
  gather_facts: no
  connection: local

  vars:
    ansible_connection: network_cli
    ansible_network_os: ios
    ansible_user: cisco
    ansible_ssh_pass: cisco
    ansible_become: yes
    ansible_become_method: enable
    ansible_become_pass: cisco

  tasks:

  - name: SYS | Define provider
    set_fact:
      provider:
        host: "{{ inventory_hostname }}"
        username: "cisco"
        password: "cisco"

  - name: Change Hostname
    ios_config:
      provider: "{{ provider }}"
      lines: hostname myios1

  - name: Gather facts
    register: facts
    ios_facts:
      provider: "{{ provider }}"
      gather_subset: all
  - debug: msg="{{ facts.ansible_facts.ansible_net_hostname }}"

=================================================

[root@localhost ios]# cat ansible.cfg
[defaults]
hostfile = ./inventory
deprecation_warnings=False

=============================================

the error that i see in the job_status is:

Using /var/lib/awx/projects/ios/ansible.cfg as config file
SSH password:
Loading callback plugin awx_display of type stdout, v2.0 from /opt/awx/embedded/lib/python2.7/site-packages/ansible/plugins/callback/__init__.pyc

PLAYBOOK: test.yml *************************************************************
1 plays in test.yml

PLAY [all] *********************************************************************
META: ran handlers

TASK [SYS | Define provider] ***************************************************
task path: /var/lib/awx/projects/ios/test.yml:17
ok: [172.24.25.116] => {
    "ansible_facts": {
        "provider": {
            "host": "172.24.25.116",
            "password": "cisco",
            "username": "cisco"
        }
    },
    "changed": false
}

TASK [Change Hostname] *********************************************************
task path: /var/lib/awx/projects/ios/test.yml:24
<172.24.25.116> using connection plugin network_cli
<172.24.25.116> socket_path: /var/lib/awx/.ansible/pc/c18dc059cc
open_shell() returned 1  Traceback (most recent call last):
  File "/bin/ansible-connection", line 27, in <module>
    from ansible.module_utils.connection import Connection, ConnectionError, send_data, recv_data
ImportError: cannot import name Connection

fatal: [172.24.25.116]: FAILED! => {
    "changed": false,
    "failed": true,
    "msg": "unable to open shell. Please see: https://docs.ansible.com/ansible/network_debug_troubleshooting.html#unable-to-open-shell",
    "rc": 1
}

PLAY RECAP *********************************************************************
172.24.25.116              : ok=1    changed=0    unreachable=0    failed=1

**Comment by MrMEEE** [comment]
Have you tried defining the connection options (username, password ansible_connection) in the inventory or on the host instead???

Does "normal" connections (ssh) work???

**Comment by ghost** [comment]
I think the problem is embedded ansible. The version of embedded Ansible is 2.3.1.0  with AWX 1.0.2.0. While my system ansible is 2.5.0 and that works fine. 

is there a way to update embedded version or direct awx to use system ansible instead of embedded one?

**Comment by MrMEEE** [comment]
Hi

Can you please try to update to AWX 1.0.5.X.. in the dev-repo: 

wget -O /etc/yum.repos.d/awx-rpm.repo https://copr.fedorainfracloud.org/coprs/mrmeee/awx-dev/repo/epel-7/mrmeee-awx-dev-epel-7.repo

The stable is currently not being updated, as the upstream awx project doesn't release any stable releases...

in 1.0.5 there is Ansible 2.4.3... I will soon update to 2.5.. just waiting a little to see if any bugs comes up...

**Comment by ghost** [comment]
Question: All I have to do is to remove /opt/awx folder, reinstall awx and migrate? Would these commands work for migration?

yum update
sudo -u awx /opt/awx/bin/awx-manage makemigrations
sudo -u awx /opt/awx/bin/awx-manage migrate

**Comment by MrMEEE** [comment]
Don't remove the /opt/awx folder.. the yum update will replace your installation..
So add the new repo file into /etc/yum.repos.d/
and run

yum update
sudo -u awx /opt/awx/bin/awx-manage makemigrations
sudo -u awx /opt/awx/bin/awx-manage migrate

That should do it

**Comment by ghost** [comment]
migrate is failing.

sudo -u awx /opt/awx/bin/awx-manage migrate
Operations to perform:
  Apply all migrations: auth, conf, contenttypes, djcelery, main, network_ui, oauth2_provider, sessions, sites, social_django, sso, taggit
Running migrations:
  Applying djcelery.0001_initial... OK
  Applying main.0009_v322_add_setting_field_for_activity_stream... OK
  Applying main.0010_v322_add_ovirt4_tower_inventory...2018-03-28 22:03:17,172 DEBUG    awx.main.models.credential adding Red Hat Virtualization credential type
2018-03-28 22:03:17,186 DEBUG    awx.main.models.credential adding Ansible Tower credential type
 OK
  Applying main.0011_v322_encrypt_survey_passwords...Traceback (most recent call last):
  File "/opt/awx/bin/awx-manage", line 11, in <module>
    sys.exit(manage())
  File "/opt/awx/embedded/lib/python2.7/site-packages/awx/__init__.py", line 109, in manage
    execute_from_command_line(sys.argv)
  File "/opt/awx/embedded/lib64/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/opt/awx/embedded/lib64/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/awx/embedded/lib64/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/awx/embedded/lib64/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/opt/awx/embedded/lib64/python2.7/site-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/opt/awx/embedded/lib64/python2.7/site-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/opt/awx/embedded/lib64/python2.7/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/opt/awx/embedded/lib64/python2.7/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/opt/awx/embedded/lib/python2.7/site-packages/awx/main/migrations/__init__.py", line 12, in apply
    return Migration.apply(self, project_state, schema_editor, collect_sql)
  File "/opt/awx/embedded/lib64/python2.7/site-packages/django/db/migrations/migration.py", line 129, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/opt/awx/embedded/lib64/python2.7/site-packages/django/db/migrations/operations/special.py", line 193, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/opt/awx/embedded/lib/python2.7/site-packages/awx/main/migrations/_reencrypt.py", line 102, in encrypt_survey_passwords
    apps.get_model('main', 'WorkflowJobTemplate'),
  File "/opt/awx/embedded/lib/python2.7/site-packages/awx/main/migrations/_reencrypt.py", line 109, in _encrypt_survey_passwords
    for jt in _type.objects.exclude(survey_spec={}):
  File "/opt/awx/embedded/lib64/python2.7/site-packages/django/db/models/query.py", line 250, in __iter__
    self._fetch_all()
  File "/opt/awx/embedded/lib64/python2.7/site-packages/django/db/models/query.py", line 1118, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/opt/awx/embedded/lib64/python2.7/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
  File "/opt/awx/embedded/lib64/python2.7/site-packages/django/db/models/sql/compiler.py", line 899, in execute_sql
    raise original_exception
django.db.utils.ProgrammingError: column main_jobtemplate.credential_id does not exist
LINE 1: ...urvey_enabled", "main_jobtemplate"."survey_spec", "main_jobt...

**Comment by MrMEEE** [comment]
sry.. I have no idea howto fix that.. something not nice, has apparently been changed in the database structure... :(...

**Comment by ghost** [comment]
No worries. Thank you for the help. I am spinning up a new VM and reinstall everything from scratch. Will let you know if I make any progress.

**Comment by MrMEEE** [comment]
Great.. 

I have been updating my server from 1.0.3 and up to the newest version... had no migration issues.. :)

**Comment by ranarashid** [comment]
I am getting following error, both from the command line and UI.

[root@localhost bin]# ./ansible-playbook -vvv -i /var/lib/awx/projects/ios/inventory /var/lib/awx/projects/ios/test.yml
ansible-playbook 2.4.3.0
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/awx/embedded/lib/python2.7/site-packages/ansible
  executable location = ./ansible-playbook
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
No config file found; using defaults
Parsed /var/lib/awx/projects/ios/inventory inventory source with ini plugin

PLAYBOOK: test.yml *************************************************************************************************************************************************************************************************************************************************************
1 plays in /var/lib/awx/projects/ios/test.yml
Read vars_file 'credentials.yml'
Read vars_file 'credentials.yml'

PLAY [initial connections] *****************************************************************************************************************************************************************************************************************************************************
META: ran handlers
Read vars_file 'credentials.yml'

TASK [configure provider] ******************************************************************************************************************************************************************************************************************************************************
task path: /var/lib/awx/projects/ios/test.yml:9
ok: [172.24.25.116] => {
    "ansible_facts": {
        "provider": {
            "host": "172.24.25.116",
            "password": "cisco",
            "username": "cisco"
        }
    },
    "changed": false
}
Read vars_file 'credentials.yml'

TASK [Change Hostname] *********************************************************************************************************************************************************************************************************************************************************
task path: /var/lib/awx/projects/ios/test.yml:16
<172.24.25.116> using connection plugin network_cli
The full traceback is:
Traceback (most recent call last):
  File "/opt/awx/embedded/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 130, in run
    res = self._execute()
  File "/opt/awx/embedded/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 528, in _execute
    result = self._handler.run(task_vars=variables)
  File "/opt/awx/embedded/lib/python2.7/site-packages/ansible/plugins/action/ios_config.py", line 45, in run
    result = super(ActionModule, self).run(tmp, task_vars)
  File "/opt/awx/embedded/lib/python2.7/site-packages/ansible/plugins/action/ios.py", line 66, in run
    socket_path = connection.run()
  File "/opt/awx/embedded/lib/python2.7/site-packages/ansible/plugins/connection/persistent.py", line 90, in run
    rc, out, err = self._do_it('RUN:')
  File "/opt/awx/embedded/lib/python2.7/site-packages/ansible/plugins/connection/persistent.py", line 46, in _do_it
    p = subprocess.Popen(["ansible-connection"], stdin=slave, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

fatal: [172.24.25.116]: FAILED! => {
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}
	to retry, use: --limit @/var/lib/awx/projects/ios/test.retry

PLAY RECAP *********************************************************************************************************************************************************************************************************************************************************************
172.24.25.116              : ok=1    changed=0    unreachable=0    failed=1

[root@localhost bin]#

**Comment by MrMEEE** [comment]
ahh... network_cli is new from Ansible 2.5...

I have pushed changes to implement Ansible 2.5.. Will notify you when the build is done...

**Comment by ghost** [comment]
Here is the update. I have solved the problem by installing ansible version 2.4.3.0, same as embedded, system wide too. Now the playbook seems to run ok. Apparently the subprocess.py was outdated in the default OS modules.

Thank you for your help! will love to hear when 2.5 build is done.

**Comment by MrMEEE** [comment]
It seemed to build ok in my setup.. awx-1.0.5.19 has been pushed to the COPR build service and should be available within the next half hour...

Let me hear how it goes... :)

**Comment by ghost** [comment]
Thanks for the heads up, will give it a shot!
