### ISSUE TITLE
ssh permissions issue

### ISSUE THREAD

**Issue by krisfish1** [MrMEEE/awx-build#101]
Environment:
OS: All CentOS 7.6 machines.
AWX version: latest
User: ldap user with the ability to ssh without a password and sudo without a password.

Situation: I have a job/template to modify a file using the lineinfile module. Anytime, that I run a job with that requires sudo/ admin privileges, the job fails. I don't understand why its failing to access a python module in the users home directory.

It fails with this specific error. module_stdout: "/usr/bin/python: can't open file 'home/username/.ansible/tmp/ansible-tmp-1556202947.6377037-262264000562182/AnsiballZ_lineinfile.py [Errno 13] Permission Denied\r\n

**Comment by MrMEEE** [comment]
I would guess that it's because of the isolation.. 

Try to add /home to the "Paths to expose to isolated Jobs" under Settings->Jobs

**Comment by MrMEEE** [comment]
Did you get this to work?

**Comment by MrMEEE** [comment]
Please reopen if this issue persists
