### ISSUE TITLE
Invalid virtual environment selected: /opt/rh/rh-python36/root/ (4.0.0.354)

### ISSUE THREAD

**Issue by dominiquearpin** [MrMEEE/awx-build#104]
Hi,

After upgrading from 4.0.0.227 to 4.0.0.354, I got this error when executing a win_ping:
Invalid virtual environment selected: /opt/rh/rh-python36/root/

Here the path I follow for upgrading:
4.0.0.227 -> 4.0.0.299
4.0.0.299 -> 4.0.0.347 (with workaround)
4.0.0.347 -> 4.0.0.354

Regards,

**Comment by MrMEEE** [comment]
Hi..

Could you please check that the following is set in your /etc/tower/settings.py

and that "Enable job isolation" under Settings -> Jobs is enabled...

**Comment by dominiquearpin** [comment]
Same problem…  However, the setting "Enable job isolation" is now activated..

And I install the latest RPM (4.0.0.440-1) this morning.

CentOS 7.6.1810

[root@ ~]# tower-cli setting get AWX_PROOT_ENABLED
================= =====
       id         value
================= =====
AWX_PROOT_ENABLED  true
================= =====

[root@ ~]# cat /etc/tower/settings.py |  egrep 'VENV|PROOT'
AWX_PROOT_ENABLED = True
ANSIBLE_VENV_PATH = '/opt/rh/rh-python36/root/'
BASE_VENV_PATH = '/opt/rh/rh-python36/'
CUSTOM_VENV_PATHS = ['/var/lib/awx/venv']

[root@ ~]# rpm -qa |  egrep 'awx|rh-python|bubble'
rh-python36-pyasn1-0.4.5-1.noarch
rh-python36-slackclient-1.1.2-1.noarch
rh-python36-django-pglocks-1.0.2-1.noarch
rh-python36-python-djangorestframework-yaml-1.0.3-1.el7.noarch
rh-python36-msrestazure-0.6.0-1.noarch
rh-python36-urllib3-1.24.1-1.noarch
rh-python36-ansible-tower-cli-3.3.4-1.noarch
rh-python36-jsonpickle-0.9.6-1.noarch
rh-python36-pyrad-2.1-1.noarch
rh-python36-uwsgitop-0.10-1.noarch
rh-python36-ntlm-auth-1.0.6-1.noarch
rh-python36-adal-1.2.1-1.noarch
rh-python36-ptyprocess-0.6.0-1.noarch
rh-python36-python-setuptools-36.5.0-1.el7.noarch
rh-python36-jaraco.logging-2.0-1.noarch
rh-python36-django-jsonfield-1.0.1-1.noarch
rh-python36-six-1.12.0-1.noarch
rh-python36-pexpect-4.7.0-1.noarch
rh-python36-asn1crypto-0.24.0-1.noarch
rh-python36-lxml-4.2.3-1.x86_64
rh-python36-requests-kerberos-0.12.0-1.noarch
rh-python36-pyparsing-2.4.0-1.noarch
bubblewrap-0.3.0-1.el7.x86_64
rh-python36-jaraco.classes-2.0-1.noarch
rh-python36-pyasn1-modules-0.2.4-1.noarch
rh-python36-jaraco.collections-2.0-1.noarch
rh-python36-python3-openid-3.1.0-1.noarch
rh-python36-websocket_client-0.47.0-1.noarch
rh-python36-PyYAML-5.1-1.x86_64
rh-python36-celery-4.2.1-1.noarch
rh-python36-azure-nspkg-3.0.2-2.noarch
rh-python36-msrest-0.6.6-1.noarch
rh-python36-prometheus_client-0.6.0-1.noarch
rh-python36-python-jinja2-2.10.1-1.noarch
rh-python36-Click-7.0-1.noarch
rh-python36-jaraco.text-3.0-1.noarch
rh-python36-cffi-1.12.3-1.x86_64
rh-python36-certifi-2019.3.9-1.noarch
rh-python36-azure-common-1.1.20-1.noarch
rh-python36-cryptography-2.6.1-1.x86_64
rh-python36-python-libs-3.6.3-3.el7.x86_64
rh-python36-autobahn-19.2.1-1.noarch
rh-python36-python-ldap-3.1.0-1.x86_64
rh-python36-django-taggit-0.22.2-1.noarch
rh-python36-jsonbfield-0.1.0-1.noarch
rh-python36-channels-1.1.8-1.noarch
rh-python36-incremental-17.5.0-1.noarch
rh-python36-django-oauth-toolkit-1.1.3-1.noarch
rh-python36-social-auth-app-django-2.1.0-1.noarch
rh-python36-twilio-6.10.4-1.noarch
rh-python36-python-devel-3.6.3-3.el7.x86_64
rh-python36-ansiconv-1.0.0-1.noarch
rh-python36-asgi_amqp-1.1.3-1.noarch
rh-python36-uwsgi-2.0.17-1.x86_64
rh-python36-django-radius-1.3.3-1.noarch
rh-python36-tacacs_plus-1.0-1.noarch
rh-python36-defusedxml-0.5.0-1.noarch
rh-python36-pywinrm-0.3.0-2.noarch
rh-python36-bcrypt-3.1.4-1.x86_64
rh-python36-pykerberos-1.2.1-1.x86_64
rh-python36-social-auth-core-3.0.0-1.noarch
rh-python36-billiard-3.5.0.5-1.noarch
rh-python36-PyJWT-1.7.1-1.noarch
rh-python36-wheel-0.30.0-1.noarch
rh-python36-ansible-2.7.10-1.noarch
rh-python36-python-markupsafe-1.1.1-1.x86_64
rh-python36-colorama-0.4.1-1.noarch
rh-python36-amqp-2.4.2-1.noarch
rh-python36-more-itertools-7.0.0-1.noarch
rh-python36-attrs-19.1.0-1.noarch
rh-python36-ansible-runner-1.3.4-1.noarch
rh-python36-txaio-18.8.1-1.noarch
rh-python36-jaraco.itertools-4.4.1-1.noarch
rh-python36-runtime-2.0-1.el7.x86_64
rh-python36-jaraco.stream-2.0-1.noarch
rh-python36-python-3.6.3-3.el7.x86_64
rh-python36-inflect-2.1.0-1.noarch
rh-python36-Twisted-18.9.0-1.x86_64
rh-python36-PyHamcrest-1.9.0-1.noarch
rh-python36-jsonschema-2.6.0-1.noarch
rh-python36-python-djangorestframework-3.7.7-1.el7.noarch
rh-python36-oauthlib-3.0.1-1.noarch
rh-python36-kombu-4.2.1-1.noarch
rh-python36-psycopg2-2.7.3.2-1.x86_64
rh-python36-requests-futures-0.9.7-1.noarch
rh-python36-chardet-3.0.4-1.noarch
rh-python36-django-solo-1.1.3-1.noarch
rh-python36-idna-2.8-1.noarch
rh-python36-constantly-15.1.0-1.noarch
rh-python36-scldevel-2.0-1.el7.x86_64
rh-python36-django-qsstats-magic-0.7.2-1.noarch
rh-python36-msgpack-python-0.5.5-1.x86_64
rh-python36-hyperlink-18.0.0-1.noarch
rh-python36-future-0.17.1-1.noarch
rh-python36-python3-saml-1.4.0-1.noarch
rh-python36-isodate-0.6.0-1.noarch
rh-python36-boto-2.47.0-1.noarch
rh-python36-pygerduty-0.37.0-1.noarch
rh-python36-django-crum-0.7.2-1.noarch
rh-python36-python-logstash-0.4.6-1.noarch
rh-python36-azure-keyvault-1.1.0-2.noarch
rh-python36-requests-2.21.0-1.noarch
rh-python36-Django-1.11.20-1.noarch
rh-python36-psutil-5.6.2-1.x86_64
rh-python36-django-split-settings-0.3.0-1.noarch
rh-python36-Automat-0.6.0-1.noarch
rh-python36-xmlsec-1.3.3-1.x86_64
rh-python36-pyvmomi-6.5-2.noarch
rh-python36-vine-1.3.0-1.noarch
rh-python36-python-dateutil-2.8.0-1.noarch
ansible-awx-4.0.0.440-1.el7.x86_64
rh-python36-tempora-1.14-1.noarch
rh-python36-django-auth-ldap-1.7.0-1.noarch
rh-python36-django-polymorphic-2.0.2-1.noarch
rh-python36-daphne-1.3.0-1.noarch
rh-python36-requests-oauthlib-1.2.0-1.noarch
rh-python36-irc-16.2-1.noarch
rh-python36-build-2.0-1.el7.x86_64
rh-python36-python-memcached-1.59-1.noarch
rh-python36-asgiref-1.1.2-1.noarch
rh-python36-netaddr-0.7.19-1.noarch
rh-python36-xmltodict-0.11.0-1.noarch
rh-python36-requests_ntlm-1.1.0-1.noarch
rh-python36-pytz-2019.1-1.noarch
rh-python36-python-pygments-2.3.1-1.noarch
rh-python36-zope.interface-4.6.0-1.x86_64
rh-python36-python-pip-9.0.1-2.el7.noarch
rh-python36-jaraco.functools-2.0-1.noarch
rh-python36-django-extensions-2.0.0-1.noarch
rh-python36-django-cors-headers-2.4.0-1.noarch

[root@ ~]# ls -al /opt/rh/rh-python36/root/
total 0
dr-xr-xr-x 15 root root 202 Apr 30 08:42 .
dr-xr-xr-x  3 root root  32 Apr 30 08:43 ..
lrwxrwxrwx  1 root root   7 Mar  1 18:05 bin -> usr/bin
dr-xr-xr-x  2 root root   6 Jul 27  2017 boot
drwxr-xr-x  2 root root   6 Jul 27  2017 dev
drwxr-xr-x  2 root root   6 Jul 27  2017 home
lrwxrwxrwx  1 root root   7 Mar  1 18:05 lib -> usr/lib
lrwxrwxrwx  1 root root   9 Mar  1 18:05 lib64 -> usr/lib64
drwxr-xr-x  2 root root   6 Jul 27  2017 media
drwxr-xr-x  2 root root   6 Jul 27  2017 mnt
drwxr-xr-x  2 root root   6 Jul 27  2017 opt
dr-xr-xr-x  2 root root   6 Jul 27  2017 proc
dr-xr-x---  2 root root   6 Jul 27  2017 root
drwxr-xr-x  3 root root  18 Mar  1 18:05 run
lrwxrwxrwx  1 root root   8 Mar  1 18:05 sbin -> usr/sbin
drwxr-xr-x  2 root root   6 Jul 27  2017 srv
drwxr-xr-x  2 root root   6 Jul 27  2017 sys
drwxrwxrwt  2 root root   6 Jul 27  2017 tmp
drwxr-xr-x 13 root root 155 Mar  1 18:05 usr


Not much info in the log file...

Regards,

**Comment by MrMEEE** [comment]
Try to update the rh-python36-ansible package to version: 2.7.10-2

**Comment by dominiquearpin** [comment]
Your right!  I updated the package and everything goes well!  Thanks!
