### ISSUE TITLE
how to shutdown AWX with systemd

### ISSUE THREAD

**Issue by andysmagana** [MrMEEE/awx-build#105]
How can AWX be shutdown with systemd?

**Comment by mjaperta** [comment]
systemctl stop awx-cbreceiver
systemctl stop awx-dispatcher
systemctl stop awx-channels-worker
systemctl stop awx-daphne
systemctl stop awx-web

**Comment by andysmagana** [comment]
Is there a systemd service script to shut them all down ?

**Comment by MrMEEE** [comment]
Not right now..

**Comment by bluikko** [comment]
This should be a simple task of creating a dummy unit file "awx" and modifying the existing awx-* unit files to contain PartOf & correct ordering of "child" unit files with After/Before.

Is this something @MrMEEE would accept as a pull request, should I have time for it?

**Comment by andysmagana** [comment]
Thanks but is there a template or example so should I start with creating for example  awe_shutdown.target first ?

**Comment by bluikko** [comment]
`man systemd.unit` has everything you need. A fully correct implementation should probably use Requires so that components that do not work without other components cannot be enabled piecemeal.

I've just started to look into AWX so cannot comment on unit file inter-dependencies, but I am looking to test this instead of vanilla AWX since I do not want to install Docker just for this.

Edit: not Depends but Requires.

**Comment by bluikko** [comment]
@andysmagana To be clear, and I am by no means a systemd expert, I would implement this with a top-level "dummy" service unit file, and set the existing awx-* service unit files to be linked to it and to other awx-* services so that they start and stop in the correct order.

I believe this would make for example stopping/restarting the whole AWX easier than using a target?

**Comment by MrMEEE** [comment]
This IS a very simple task, just haven't had the need or time to do it..

@bluikko you are most welcome to do a pull request against my awx-rpm repo

**Comment by MrMEEE** [comment]
Would prefer a self-service file though

**Comment by andysmagana** [comment]
I just don’t know which of the 4 or 5 awx services go in order there is awx
web and awx daphne and awx channels worker awx cbreceiver awx dispatcher .

**Comment by mjaperta** [comment]
@andysmagana There is no order.. it doesn't matter... but you probably need to include nginx, postgresql and rabbitmq as well

**Comment by andysmagana** [comment]
Still trying to come up with something so far I have moved the services over to /etc/systemd/system/ and created a awx.target and put in [UNIT] PartOf=awx.target in everything how about that?

awe-cbreceiver
awx-channels-worker
awx-daphne
awx-dispatcher
ax-web 

nginx.service
memcached.service
rabbitmq-server.service
rh-postgresql10-postgressql.service

**Comment by MrMEEE** [comment]
If it works, it sound pretty good.. we have to move the services back to /usr/lib/system/systemd/ when I package them, but I'll take care of that..

Why did you move them?

**Comment by andysmagana** [comment]
Back a while I came across RedHat talking about best practices for systems services when you modify them to move them there but I just copied them not move the original services are still in /usr/lib/systemd/system.

**Comment by MrMEEE** [comment]
Ah.. That was exactly what I would have done.. :).. you just wrote moved :)

**Comment by andysmagana** [comment]
I have just tested this and It works please make sure to add to ALL THE services the "WantedBy=awx.target"

**Comment by andysmagana** [comment]
For example for the cbreceiver service 
[Unit]
Description=AWX cbreceiver service
After=syslog.target network.target
PartOf=awx.target

[Service]
User=awx
Group=awx
EnvironmentFile=-/etc/sysconfig/awx
Environment=PYTHONPATH=/opt/awx/embedded/lib/python2.7/site-packages:/opt/awx/embedded/lib64/python2.7/site-packages
Environment=AWX_SETTINGS_FILE=/etc/awx/settings.py
Environment=PATH=/opt/awx/bin:/bin:/sbin:/usr/bin:/usr/sbin
ExecStart=/opt/awx/bin/awx-manage run_callback_receiver
KillMode=process
Restart=on-failure
RestartSec=2s

[Install]
WantedBy=awx.target

**Comment by MrMEEE** [comment]
Does this also work for shutting down and restarting?

Could you do a pull request?

**Comment by andysmagana** [comment]
Good Morning Martin, 

Yes, 

It is able to shutdown all services then you can either reboot or shutdown the box.

**Comment by MrMEEE** [comment]
Just to be sure

systemctl start awx:
Starts all services

systemctl restart awx:
Restarts all services

systemctl stop awx:
Stops all services

??

**Comment by andysmagana** [comment]
Yes it does that. Its very convenient now.

**Comment by MrMEEE** [comment]
Cool.. Could you do a pull request?

**Comment by andysmagana** [comment]
Oh yes I will let me get there and do that now. Thanks for reminding me.

**Comment by andysmagana** [comment]
Hello Martin, 

I did a pull request. Hope I did the pull request right.  I have some question about CentOS Atom Host. Do you have any place I can go to ask questions. thanks. 

Respectfully, 

Andy Magana 
Oklahoma City, Oklahoma.

**Comment by MrMEEE** [comment]
Hi 

The pull request is missing some stuff.. look at what I have written in it.. 

In regards to the questions.. either create an issue at: [ https://github.com/MrMEEE/awx-build/issues | https://github.com/MrMEEE/awx-build/issues ] 

or join the "AWX RPM Users"-group on Linkedin :) 

/Martin 


Fra: "Andy S Magana" <notifications@github.com> 
Til: "MrMEEE/awx-build" <awx-build@noreply.github.com> 
Cc: "m@rtinjuhl dk" <m@rtinjuhl.dk>, "Assign" <assign@noreply.github.com> 
Sendt: torsdag, 9. maj 2019 15:15:38 
Emne: Re: [MrMEEE/awx-build] how to shutdown AWX with systemd (#105) 

Hello Martin, 

I did a pull request. Hope I did the pull request right. I have some question about CentOS Atom Host. Do you have any place I can go to ask questions. thanks. 

Respectfully, 

Andy Magana 
Oklahoma City, Oklahoma.

**Comment by MrMEEE** [comment]
@andysmagana ?

**Comment by MrMEEE** [comment]
@andysmagana any update?

**Comment by MrMEEE** [comment]
I have reworked the work done by @andysmagana .. and it's now in ansible-awx-5.0.0.49-2.el7.x86_64..

Please reopen, if something doesn't work

**Comment by andysmagana** [comment]
Hey I have a had a spinal cord injury so I have been trying to recover just so sorry for being out of the loop every one!!!

**Comment by andysmagana** [comment]
Hey I have a had a spinal cord injury so I have been trying to recover just so sorry for being out of the loop every one!!!

Thanks for working on the start/stop systemd  script for Awx !
