### ISSUE TITLE
dynamic inventory script not working after upgrade 

### ISSUE THREAD

**Issue by flynn1973** [MrMEEE/awx-build#107]
i updated to 4.0.0.503 and now my dynamic inventory script is not working anymore. it is a python script which needs a few extra modules (pymysql,argpars...) so i created a venv with the needed modules included with awx-create-venv and activated the env in the awx inventory section. still no fun. could it be that the default venv is used to run the script? any ideas? in the old version (3.something) this worked flawlessly.

**Comment by MrMEEE** [comment]
Hi..

It should work with the venv.. Did you do a python2 or python3 venv?? ..

What error do you get?

**Comment by flynn1973** [comment]
````
 2.912 INFO     Updating inventory 3: AIX Inventory
    3.339 INFO     Reading Ansible inventory source: /tmp/awx_17_g6sfepwh/tmpvk5tu2_8
    3.342 INFO     Using VIRTUAL_ENV: /var/lib/awx/venv/venv_dyninv_aix/
    3.342 INFO     Using PATH: /var/lib/awx/venv/venv_dyninv_aix/bin:/var/lib/awx/venv/awx/bin:/opt/rh/rh-postgresql10/root/usr/bin:/opt/rh/rh-python36/root/usr/bin:/opt/awx/bin:/bin:/sbin:/usr/bin:/usr/sbin
    3.342 INFO     Using PYTHONPATH: /var/lib/awx/venv/venv_dyninv_aix/lib/python2.7/site-packages:
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/bin/awx-manage", line 11, in <module>
    load_entry_point('awx==4.0.0', 'console_scripts', 'awx-manage')()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/__init__.py", line 140, in manage
    execute_from_command_line(sys.argv)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 1148, in handle
    raise exc
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 1038, in handle
    venv_path=venv_path, verbosity=self.verbosity).load()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 214, in load
    return self.command_to_json(base_args + ['--list'])
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 197, in command_to_json
    self.method, proc.returncode, stdout, stderr))
RuntimeError: ansible-inventory failed (rc=1) with stdout:

stderr:
bwrap: Can't find source path /var/lib/awx/venv/awx: No such file or directory
````

**Comment by flynn1973** [comment]
mkdir "/var/lib/awx/venv/awx" fixes this error, but i doubt this is the desired workaround.

**Comment by 6sossomons** [comment]
I ran into the same problem after an upgrade and moving all virtual environments to a new home path (/usr/local/venv/*)

I overcame it by:
1. creating an AWX named venv in the new path
2. symbolically linking /var/lib/awx/venv/awx to the new awx venv in the specified location.

Janky, but it works now.

**Comment by MrMEEE** [comment]
Can you try to do a 

ln -s /opt/rh/rh-python36/root /var/lib/awx/venv/awx and use that environment?

**Comment by flynn1973** [comment]
making the link works also. please consider this in future builds, will close this issue.

**Comment by MrMEEE** [comment]
Cool, thanks for the feedback.. I have already made the change, so the link will be included in the next release

**Comment by gpavinteractiv** [comment]
I had the pb on awx 8
I made the link and that solved the pb

I guess the fix has to be reviewed once more?

**Comment by MrMEEE** [comment]
I think it's fixed now..

**Comment by MrMEEE** [comment]
Thanks for following up

**Comment by unixsysadmin** [comment]
I recently upgraded from ansible-awx-7.0.0.599-1.el7 to ansible-awx-8.0.0.119-1.el7.  It appeared as though I needed to recreate the following link post-upgrade.  Is that expected?

`ln -s /opt/rh/rh-python36/root /var/lib/awx/venv/awx`

**Comment by MrMEEE** [comment]
Hi

I'm aware of this, and it's fixed going forward..

Thanks for reporting

**Comment by gpavinteractiv** [comment]
I sync inventory from a github project
The error I got today from a fresh install (awx 9.0.1) is : 

````
bwrap: Can't mkdir parents for /var/lib/awx/venv/awx: No such file or directory
````

but : 

````
[root@vs-inf-prd-awx-fr-501 ~]# ll /var/lib/awx/venv/awx
lrwxrwxrwx. 1 root root 24 Nov  6 08:20 /var/lib/awx/venv/awx -> /opt/rh/rh-python36/root
````

edit : it seems that I am maybe hitting this https://access.redhat.com/solutions/3317651
I do have a symlink on /var/lib/awx to put that on /opt/...
