### ISSUE TITLE
awx-cli not working

### ISSUE THREAD

**Issue by ayaseen** [MrMEEE/awx-build#110]
I try to backup awx using : awx-cli receive --all > awx-$(date +%F_%R).json

The output:

Error: There was a network error of some kind trying to connect to Tower.

The most common reason for this is a settings issue; is your "host" value in `tower-cli config` correct?
Right now it is: "192.168.1.8".

**Comment by MrMEEE** [comment]
Try with "http://192.168.1.8:8052" instead

**Comment by ayaseen** [comment]
Thanks, I miss the port.

**Comment by MrMEEE** [comment]
cool..
