### ISSUE TITLE
update to rh-python36-ipaddress-1.0.22-1 fails

### ISSUE THREAD

**Issue by 6sossomons** [MrMEEE/awx-build#113]
This morning, when trying to run a yum update:

[root@vrh7awxchqd01 ~]# yum update *
Resolving Dependencies
--> Running transaction check
<--truncated -->
---> Package rh-python36-ipaddress.noarch 0:1.0.22-1 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

===================================================
 Package                                                          Arch                                              Version                                              Repository                                                     Size
=================================================================================================================
Installing:
 rh-python36-ipaddress                                            noarch                                            1.0.22-1                                             mrmeee-ansible-awx                                             34 k

Transaction Summary
==============================================================
Install 1 Packages

Is this ok [y/d/N]: y
Downloading packages:
Running transaction check
Running transaction test

Transaction check error:
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/__pycache__/ipaddress.cpython-36.opt-1.pyc from install of rh-python36-ipaddress-1.0.22-1.noarch conflicts with file from package rh-python36-python-ipaddress-1.0.19-1.el7.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/__pycache__/ipaddress.cpython-36.pyc from install of rh-python36-ipaddress-1.0.22-1.noarch conflicts with file from package rh-python36-python-ipaddress-1.0.19-1.el7.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/ipaddress.py from install of rh-python36-ipaddress-1.0.22-1.noarch conflicts with file from package rh-python36-python-ipaddress-1.0.19-1.el7.noarch

Error Summary
-------------
Uploading Enabled Repositories Report

Removed that version entirely and still getting the same problem, even after AWX stop and re-attempt at installtion.

[root@vrh7awxchqd01 bin]# yum install rh-python36-ipaddress
Resolving Dependencies
--> Running transaction check
---> Package rh-python36-ipaddress.noarch 0:1.0.22-1 will be installed
--> Finished Dependency Resolution

Dependencies Resolved
===================================================
 Package                                                          Arch                                              Version                                              Repository                                                     Size
===================================================
Installing:
 rh-python36-ipaddress                                            noarch                                            1.0.22-1                                             mrmeee-ansible-awx                                             34 k

Transaction Summary
===================================================
Install  1 Package

Total size: 34 k
Installed size: 209 k
Is this ok [y/d/N]: y
Downloading packages:
Running transaction check
Running transaction test

Transaction check error:
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/__pycache__/ipaddress.cpython-36.opt-1.pyc from install of rh-python36-ipaddress-1.0.22-1.noarch conflicts with file from package rh-python36-python-ipaddress-1.0.19-1.el7.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/__pycache__/ipaddress.cpython-36.pyc from install of rh-python36-ipaddress-1.0.22-1.noarch conflicts with file from package rh-python36-python-ipaddress-1.0.19-1.el7.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/ipaddress.py from install of rh-python36-ipaddress-1.0.22-1.noarch conflicts with file from package rh-python36-python-ipaddress-1.0.19-1.el7.noarch

Error Summary
-------------
Uploading Enabled Repositories Report

Even after reboot, the problem remained.  I worked around it with downloading the package and installing via RPM.

[root@vrh7awxchqd01 tmp]# rpm -Uvh rh-python36-ipaddress-1.0.22-1.noarch.rpm
Preparing...                          ################################# [100%]
        file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/__pycache__/ipaddress.cpython-36.opt-1.pyc from install of rh-python36-ipaddress-1.0.22-1.noarch conflicts with file from package rh-python36-python-ipaddress-1.0.19-1.el7.noarch
        file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/__pycache__/ipaddress.cpython-36.pyc from install of rh-python36-ipaddress-1.0.22-1.noarch conflicts with file from package rh-python36-python-ipaddress-1.0.19-1.el7.noarch
        file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/ipaddress.py from install of rh-python36-ipaddress-1.0.22-1.noarch conflicts with file from package rh-python36-python-ipaddress-1.0.19-1.el7.noarch
[root@vrh7awxchqd01 tmp]# rpm -Uvh rh-python36-ipaddress-1.0.22-1.noarch.rpm  --replacefiles
Preparing...                          ################################# [100%]
Updating / installing...
   1:rh-python36-ipaddress-1.0.22-1   ################################# [100%]

**Comment by MrMEEE** [comment]
The correct way to work around this would be:

yum remove -y rh-python36-python-ipaddress
yum install -y rh-python36-ipaddress

**Comment by 6sossomons** [comment]
Yes, i did that first and the error remained.   Files didn't exist and
rebuild of rpm database failed.

**Comment by MrMEEE** [comment]
What file didn't exist?

**Comment by 6sossomons** [comment]
I ran into the issue during the update, so I:
Uninstalled via yum remove -y   rh-python36-ipaddress
Updated the system
Rebooted
Tried to install again  (yum -y install rh-python36-ipaddress)
Same Error
Removed the files: 
/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/pycache/ipaddress.cpython-36.opt-1.pyc 
/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/pycache/ipaddress.cpython-36.pyc
/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/ipaddress.py
Rebuilt the RPM database  (rpm --rebuilddb)
Ran install again (Same error)
Downloaded the package
rpm -Uvh --replacefiles rh-python36-ipaddress-1.0.22-1.noarch.rpm

Not sure which database/package still had the erroneous files in them, but it is installed at the newest version now.

**Comment by MrMEEE** [comment]
there are two different names.. 

first you should uninstall/remove "rh-python36-python-ipaddress"
and then install "rh-python36-ipaddress"

**Comment by 6sossomons** [comment]
oh son of a .....

I hate lack of sleep days..  Thanks, I don't know how many times I read that and missed the -python- on the first package...

**Comment by MrMEEE** [comment]
:P
