### ISSUE TITLE
Transaction error: yum -y install --disablerepo='*' --enablerepo='mrmeee-ansible-awx, base' -x *-debuginfo rh-python36*

### ISSUE THREAD

**Issue by sjohnsen** [MrMEEE/awx-build#114]
Hi.

Just followed the installastion guide on CentOS 7. And this step failed with a transaction check error `yum -y install --disablerepo='*' --enablerepo='mrmeee-ansible-awx, base' -x *-debuginfo rh-python36*`

Transaction check error:                                                                                                                                                       
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/rest_framework/__init__.py conflicts between attempted installs of rh-python36-python-djangorestframework-3.7.7$
1.el7.noarch and rh-python36-djangorestframework-3.9.4-1.noarch                                                                                                                
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/rest_framework/__pycache__/__init__.cpython-36.opt-1.pyc conflicts between attempted installs of rh-python36-py$
hon-djangorestframework-3.7.7-1.el7.noarch and rh-python36-djangorestframework-3.9.4-1.noarch                                                                                  
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/rest_framework/__pycache__/__init__.cpython-36.pyc conflicts between attempted installs of rh-python36-python-dj
angorestframework-3.7.7-1.el7.noarch and rh-python36-djangorestframework-3.9.4-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/rest_framework/__pycache__/apps.cpython-36.opt-1.pyc conflicts between attempted installs of rh-python36-python-
djangorestframework-3.7.7-1.el7.noarch and rh-python36-djangorestframework-3.9.4-1.noarch                                                                                      
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/rest_framework/__pycache__/apps.cpython-36.pyc conflicts between attempted installs of rh-python36-python-django
restframework-3.7.7-1.el7.noarch and rh-python36-djangorestframework-3.9.4-1.noarch

....

Error Summary
-------------

**Comment by MrMEEE** [comment]
Hi

Thanks for reporting..

Should be fixed now..

Try to do a "yum clean all" and try again

**Comment by sjohnsen** [comment]
Works now. Thank you!

**Comment by ayaseen** [comment]
Still the issue exist, I try yum clean all

**Comment by chandrashekar-cohesity** [comment]
Same. Still getting this error after yum clean all

**Comment by pankajps** [comment]
This seems because of rh-python36-gitdb-4.0.2-1.noarch and rh-python36-msgpack packages.

**Comment by Raptor8532** [comment]
Same for me 

> file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/typ.py conflicts between attempted installs of rh-python36-gitdb2-2.0.6-1.noarch and rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/util.py conflicts between attempted installs of rh-python36-gitdb2-2.0.6-1.noarch and rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/utils/__pycache__/__init__.cpython-36.opt-1.pyc conflicts between attempted installs of rh-python36-gitdb2-2.0.6-1.noarch and rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/utils/__pycache__/__init__.cpython-36.pyc conflicts between attempted installs of rh-python36-gitdb2-2.0.6-1.noarch and rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/utils/__pycache__/encoding.cpython-36.opt-1.pyc conflicts between attempted installs of rh-python36-gitdb2-2.0.6-1.noarch and rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/utils/__pycache__/encoding.cpython-36.pyc conflicts between attempted installs of rh-python36-gitdb2-2.0.6-1.noarch and rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/utils/encoding.py conflicts between attempted installs of rh-python36-gitdb2-2.0.6-1.noarch and rh-python36-gitdb-4.0.2-1.noarch

**Comment by pankajps** [comment]
try excluding these two packages, rh-python36-gitdb and rh-python36-msgpack 


yum -y install --disablerepo='*' --enablerepo='mrmeee-ansible-awx, base' -x *-debuginfo,rh-python36-gitdb,rh-python36-msgpack rh-python36*
