### ISSUE TITLE
Yum broken dependencies

### ISSUE THREAD

**Issue by sjohnsen** [MrMEEE/awx-build#115]
Hi

Tried to follow the Installation guide, and I get this error when running `yum install -y ansible-awx`
This is on Centos 7.

Error: Package: ansible-awx-4.0.0.721-1.el7.x86_64 (mrmeee-ansible-awx)
           Requires: rh-python36-python-djangorestframework-yaml
Error: Package: ansible-awx-4.0.0.721-1.el7.x86_64 (mrmeee-ansible-awx)
           Requires: rh-python36-python-djangorestframework
 You could try using --skip-broken to work around the problem

**Comment by vladimir2009** [comment]
Hi
My RHEL7 has the same problem when installing, ansible-awx
-> Completed dependency resolution
Error: Package: ansible-awx-4.0.0.721-1.el7.x86_64 (mrmeee-ansible-awx)
Required: rh-python36-python-djangorestframework-yaml
Error: Package: ansible-awx-4.0.0.721-1.el7.x86_64 (mrmeee-ansible-awx)
Required: rh-python36-python-djangorestframework

**Comment by MrMEEE** [comment]
Could you please try again with ansible-awx-4.0.0.721-**2**

**Comment by vladimir2009** [comment]
> Could you please try again with ansible-awx-4.0.0.721-**2**

I`m, install AWX, OK
Installed:
  ansible-awx.x86_64 0:4.0.0.731-1.el7

**Comment by sjohnsen** [comment]
Working now, with ansible-awx.x86_64 0:4.0.0.731-1.el7.

Thanks.
