### ISSUE TITLE
Upgrade to 5.0.0.49-2 hangs in "AWX is Upgrading"

### ISSUE THREAD

**Issue by bluikko** [MrMEEE/awx-build#118]
I have a new instance of AWX 4 that had almost nothing in it; just LDAP configured and 1 project (import which seemed to hang at "detect requirements.yml" for some reason, even when roles disabled but that's another issue).

After doing `yum update` and loading the AWX web page it detected the upgrade and showed the page "AWX is Upgrading" "AWX is currently upgrading. This page will refresh when complete". But it looks like it is hung - I've been waiting for 15 minutes and the login page still does not appear.

Now I could easily rebuild this VM with Ansible and putting in the documented configuration changes but was wondering are you interested in getting to the bottom of why the upgrade doesn't seem to complete?

The only possible non-standard issue is that I noticed I did not kill the last attempt to sync the project from git. So there was one "ansible-playbook" process hanging in the "detect requirements.yml" step when the upgrade was done.

I am also using Apache as reverse proxy and not the nginx but I don't think that would cause issues?

Edit: I am also using PGSQL11 from PGDG and not the SCL PGSQL10.

Edit 2: nothing interesting in `/var/log/tower`.

**Comment by bluikko** [comment]
Duh, just noticed out of #100 that I need to run migrations manually. That of course made it work.

Sorry about that. I think this step should be noted in the documentation, even though it is probably noted somewhere in the reams of Tower documentation.

**Comment by bluikko** [comment]
I note that now with AWX 5 the project sync also works.

Thanks a lot for your efforts!

**Comment by MrMEEE** [comment]
Good that you got it to work..

It's already in the docs:
https://awx.wiki/upgrade/standard-upgrade-method
