### ISSUE TITLE
install older awx 

### ISSUE THREAD

**Issue by vladimir2009** [MrMEEE/awx-build#119]
Hi, i can install older version awx? 
example: ansible-awx-4.0.0.746-1.el7

**Comment by MrMEEE** [comment]
Well, I have the rpm, which I can send you.. But I wouldn't be certain that it will work.. Dependency rpm's might be too new...

Why do you need this??

**Comment by vladimir2009** [comment]
i have trouble whith modul  "copy" ansible 2.8.1
{
    "msg": "Could not find or access '/tmp/file_to_copy/linuxRH' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option",
    "exception": "Traceback (most recent call last):\n  File \"/opt/rh/rh-python36/root/lib/python3.6/site-packages/ansible/plugins/action/copy.py\", line 464, in run\n    source = self._find_needle('files', source)\n  File \"/opt/rh/rh-python36/root/lib/python3.6/site-packages/ansible/plugins/action/__init__.py\", line 1166, in _find_needle\n    return self._loader.path_dwim_relative_stack(path_stack, dirname, needle)\n  File \"/opt/rh/rh-python36/root/lib/python3.6/site-packages/ansible/parsing/dataloader.py\", line 319, in path_dwim_relative_stack\n    raise AnsibleFileNotFound(file_name=source, paths=[to_text(p) for p in search])\nansible.errors.AnsibleFileNotFound: Could not find or access '/tmp/file_to_copy/linuxRH' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option\n",
    "invocation": {
        "src": "/tmp/file_to_copy/lRH",
        "dest": "/tmp",
        "owner": "root",
        "group": "root",
        "mode": "u=rwx,g=rwx,o=rwx",
        "module_args": {
            "src": "/tmp/file_to_copy/lRH",
            "dest": "/tmp",
            "owner": "root",
            "group": "root",
            "mode": "u=rwx,g=rwx,o=rwx"
        }
    },
    "_ansible_no_log": false,
    "changed": false
}

$ ls -al /tmp/file_to_copy/lRH/
total 16
drwxr-xr-x 2 root root    23 Jun 26 15:51 .
drwxr-xr-x 3 root root   121 Jun 26 15:51 ..
-rwxr-xr-x 1 root root 16203 Jun 26 15:51 linuxRH.sh

**Comment by MrMEEE** [comment]
I will look into this issue next week, but try look into venvs.. That way you can run an different version of ansible

https://awx.wiki/tools/awx-create-venv

**Comment by vladimir2009** [comment]
Interesting, I will try. many thanks

**Comment by MrMEEE** [comment]
Are you trying to copy a file on the AWX server to the AWX server??

**Comment by MrMEEE** [comment]
@vladimir2009 ???

**Comment by vladimir2009** [comment]
@MrMEEE sorry for such a long answer. AWX updated to the latest version, but the copy module does not work as before.
ansible-playbook 2.8.2
  config file = None
  configured module search path = ['/var/lib/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/rh/rh-python36/root/lib/python3.6/site-packages/ansible
  executable location = /opt/rh/rh-python36/root/bin/ansible-playbook
  python version = 3.6.3 (default, May 31 2019, 13:05:43) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

{
    "msg": "Could not find or access '/tmp/file_to_copy/lRH' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option",
    "exception": 
"Traceback (most recent call last):\n  File \"/opt/rh/rh-python36/root/lib/python3.6/site-packages/ansible/plugins/action/copy.py\", line 464, in run\n    source = self._find_needle('files', source)\n  File \"/opt/rh/rh-python36/root/lib/python3.6/site-packages/ansible/plugins/action/__init__.py\", line 1166, in _find_needle\n    return self._loader.path_dwim_relative_stack(path_stack, dirname, needle)\n  File \"/opt/rh/rh-python36/root/lib/python3.6/site-packages/ansible/parsing/dataloader.py\", line 319, in path_dwim_relative_stack\n    raise AnsibleFileNotFound(file_name=source, paths=[to_text(p) for p in search])\nansible.errors.AnsibleFileNotFound: Could not find or access '/tmp/file_to_copy/lRH' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option\n",
    "invocation": {
        "src": "/tmp/file_to_copy/lRH",
        "dest": "/tmp",
        "owner": "root",
        "group": "root",
        "mode": "u=rwx,g=rwx,o=rwx",
        "module_args": {
            "src": "/tmp/file_to_copy/lRH",
            "dest": "/tmp",
            "owner": "root",
            "group": "root",
            "mode": "u=rwx,g=rwx,o=rwx"
        }
    },
    "_ansible_no_log": false,
    "changed": false
}

ls -la /tmp/file_to_copy/lRH/
total 16
drwxr-xr-x 2 root root    23 Jul 16 12:45 .
drwxr-xr-x 3 root root   121 Jul 16 12:45 ..
-rwxr-xr-x 1 root root 16203 Jul 16 12:45 linuxRH.sh

**Comment by vladimir2009** [comment]
> I will look into this issue next week, but try look into venvs.. That way you can run an different version of ansible
> 
> https://awx.wiki/tools/awx-create-venv

When using venv & ansible 2.7.4, I get the same error
ansible-playbook 2.7.4
  config file = None
  configured module search path = ['/var/lib/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /var/lib/awx/venv/2.7.4/lib/python3.6/site-packages/ansible
  executable location = /var/lib/awx/venv/2.7.4/bin/ansible-playbook
  python version = 3.6.3 (default, May 31 2019, 13:05:43) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
No config file found; using defaults
The full traceback is:
Traceback (most recent call last):
  File "/var/lib/awx/venv/2.7.4/lib/python3.6/site-packages/ansible/plugins/action/copy.py", line 457, in run
    source = self._find_needle('files', source)
  File "/var/lib/awx/venv/2.7.4/lib/python3.6/site-packages/ansible/plugins/action/__init__.py", line 1051, in _find_needle
    return self._loader.path_dwim_relative_stack(path_stack, dirname, needle)
  File "/var/lib/awx/venv/2.7.4/lib/python3.6/site-packages/ansible/parsing/dataloader.py", line 322, in path_dwim_relative_stack
    raise AnsibleFileNotFound(file_name=source, paths=[to_text(p) for p in search])
ansible.errors.AnsibleFileNotFound: Could not find or access '/tmp/file_to_copy/lRH' on the Ansible Controller.
If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [kzltest]: FAILED! =>

**Comment by MrMEEE** [comment]
Could you show me the playbook?

**Comment by vladimir2009** [comment]
---
- hosts: all
  remote_user: ans
  become: yes

  tasks:
    - copy:
        src: /tmp/file_to_copy/linuxRH
        dest: /tmp
        owner: root
        group: root
        mode: u=rwx,g=rwx,o=rwx

    - shell: . linuxRH.sh > /tmp/linuxRH/$(hostname).out
      args:
        chdir: /tmp/linuxRH/
        executable: /bin/bash

    - fetch:
       src: /tmp/linuxRH/{{ ansible_facts [ 'nodename'] }}.out
       dest: /tmp/rh_out/
       flat: yes

    - name: Ansible remove file glob
      file:
        path: /tmp/linuxRH
        state: absent

**Comment by MrMEEE** [comment]
This is probably because newer versions of AWX-RPM has job isolation enabled, which basically means that the process running on the local machine (the awx-rpm host) can't see the entire filesystem..

Under Settings->jobs, you can configure which folders show be visiable for the jobs..

I think that is your issue

**Comment by vladimir2009** [comment]
![image](https://user-images.githubusercontent.com/51476803/61282185-b1414800-a7dc-11e9-93e5-87063c5e5bce.png)
by default, enable job isolation "on", after switching "off" the file is copied

**Comment by MrMEEE** [comment]
Exactly, but for security you would use job isolation
