### ISSUE TITLE
Issues with HA

### ISSUE THREAD

**Issue by MrMEEE** [MrMEEE/awx-build#121]

**Comment by MrMEEE** [comment]
> 
> 
> Looks like the issue has to do with the fact - awx requires 'tower' vhost. Currently we're using host (default) '/'. So getting a bunch of closing AMQP connections.
> 
> 2019-06-27 15:30:29.289 [info] <0.2130.0> connection <0.2130.0> (127.0.0.1:47012 -> 127.0.0.1:5672): user 'guest' authenticated and granted access to vhost '/'
> 2019-06-27 15:30:49.603 [info] <0.2139.0> accepting AMQP connection <0.2139.0> (127.0.0.1:47390 -> 127.0.0.1:5672)
> 2019-06-27 15:30:49.610 [info] <0.2139.0> connection <0.2139.0> (127.0.0.1:47390 -> 127.0.0.1:5672): user 'guest' authenticated and granted access to vhost '/'
> 2019-06-27 15:30:49.619 [info] <0.2139.0> closing AMQP connection <0.2139.0> (127.0.0.1:47390 -> 127.0.0.1:5672, vhost: '/', user: 'guest')
> 2019-06-27 15:30:49.687 [info] <0.2150.0> accepting AMQP connection <0.2150.0> (127.0.0.1:47394 -> 127.0.0.1:5672)
> 2019-06-27 15:30:49.695 [info] <0.2150.0> connection <0.2150.0> (127.0.0.1:47394 -> 127.0.0.1:5672): user 'guest' authenticated and granted access to vhost '/'
> 2019-06-27 15:30:49.710 [info] <0.2150.0> closing AMQP connection <0.2150.0> (127.0.0.1:47394 -> 127.0.0.1:5672, vhost: '/', user: 'guest')
> 2019-06-27 15:30:49.748 [info] <0.2161.0> accepting AMQP connection <0.2161.0> (127.0.0.1:47396 -> 127.0.0.1:5672)
> 2019-06-27 15:30:49.755 [info] <0.2161.0> connection <0.2161.0> (127.0.0.1:47396 -> 127.0.0.1:5672): user 'guest' authenticated and granted access to vhost '/'
> 2019-06-27 15:30:49.771 [info] <0.2161.0> closing AMQP connection <0.2161.0> (127.0.0.1:47396 -> 127.0.0.1:5672, vhost: '/', user: 'guest')

I actually think I remember having this issue at one point in the past.. 

have you tried changing it back??

**Comment by MrMEEE** [comment]
@dnc92301 any feedback??

**Comment by dnc92301** [comment]
Haven’t gotten the chance to look at it for 2 weeks . Will pick it up and report back status ..

**Comment by dnc92301** [comment]
Still puzzle as to why "new" node goes into "unavailable" state as soon as Job finished executing on the new node.  I've disabled primary node: hostnameA [DISABLED]. You can see all traffic are redirected to hostnameB. As soon as a Job finished executing, hostnameB goes into "zero" Capacity. I had to go into GUI and toggle OFF -> ON, to re-enable it. It then goes back to "UNAVAILABLE" state short time later (minutes). It seems as though the rabbitmq lost its heartbeat but this is NOT case since I enabled rabbitmq console and both nodes are marked as healthy. 

[root@hostnameA ansible-tower-setup-bundle-3.5.0-1.el7]# sudo -u awx scl enable rh-python36 rh-postgresql10 "awx-manage list_instances"
[tower capacity=1267]
	hostnameB capacity=1267 version=5.0.0 heartbeat="2019-07-12 19:33:11"
	[DISABLED] hostnameA capacity=0 version=5.0.0

[tower_testing capacity=1267]
	hostnameB capacity=1267 version=5.0.0 heartbeat="2019-07-12 19:33:11"
	[DISABLED] hostnameA capacity=0 version=5.0.0

[root@hostnameA ansible-tower-setup-bundle-3.5.0-1.el7]# sudo -u awx scl enable rh-python36 rh-postgresql10 "awx-manage list_instances"
[tower capacity=0]
	hostnameB capacity=0 version=5.0.0
	[DISABLED] hostnameA capacity=0 version=5.0.0

[tower_testing capacity=0]
	hostnameB capacity=0 version=5.0.0
	[DISABLED] hostnameA capacity=0 version=5.0.0


[root@hostnameA ansible-tower-setup-bundle-3.5.0-1.el7]# rabbitmqctl cluster_status
Cluster status of node rabbitmq@hostnameA ...
[{nodes,[{disc,[rabbitmq@ hostnameB,rabbitmq@hostnameA]}]},
 {running_nodes,[rabbitmq@hostnameB,rabbitmq@hostnameA]},
 {cluster_name,<<"rabbitmq@hostnameA.bnymellon.net">>},
 {partitions,[]},
 {alarms,[{rabbitmq@hostnameB,[]},{rabbitmq@hostnameA,[]}]}]
[root@hostnameA ansible-tower-setup-bundle-3.5.0-1.el7]#

**Comment by MrMEEE** [comment]
I can see the tower installation on your machine "ansible-tower-setup-bundle-3.5.0-1.el7".. are you using that?

**Comment by MrMEEE** [comment]
Still getting the errors in rabbitmq?

**Comment by MrMEEE** [comment]
> 
> 
> > Looks like the issue has to do with the fact - awx requires 'tower' vhost. Currently we're using host (default) '/'. So getting a bunch of closing AMQP connections.
> > 2019-06-27 15:30:29.289 [info] <0.2130.0> connection <0.2130.0> (127.0.0.1:47012 -> 127.0.0.1:5672): user 'guest' authenticated and granted access to vhost '/'
> > 2019-06-27 15:30:49.603 [info] <0.2139.0> accepting AMQP connection <0.2139.0> (127.0.0.1:47390 -> 127.0.0.1:5672)
> > 2019-06-27 15:30:49.610 [info] <0.2139.0> connection <0.2139.0> (127.0.0.1:47390 -> 127.0.0.1:5672): user 'guest' authenticated and granted access to vhost '/'
> > 2019-06-27 15:30:49.619 [info] <0.2139.0> closing AMQP connection <0.2139.0> (127.0.0.1:47390 -> 127.0.0.1:5672, vhost: '/', user: 'guest')
> > 2019-06-27 15:30:49.687 [info] <0.2150.0> accepting AMQP connection <0.2150.0> (127.0.0.1:47394 -> 127.0.0.1:5672)
> > 2019-06-27 15:30:49.695 [info] <0.2150.0> connection <0.2150.0> (127.0.0.1:47394 -> 127.0.0.1:5672): user 'guest' authenticated and granted access to vhost '/'
> > 2019-06-27 15:30:49.710 [info] <0.2150.0> closing AMQP connection <0.2150.0> (127.0.0.1:47394 -> 127.0.0.1:5672, vhost: '/', user: 'guest')
> > 2019-06-27 15:30:49.748 [info] <0.2161.0> accepting AMQP connection <0.2161.0> (127.0.0.1:47396 -> 127.0.0.1:5672)
> > 2019-06-27 15:30:49.755 [info] <0.2161.0> connection <0.2161.0> (127.0.0.1:47396 -> 127.0.0.1:5672): user 'guest' authenticated and granted access to vhost '/'
> > 2019-06-27 15:30:49.771 [info] <0.2161.0> closing AMQP connection <0.2161.0> (127.0.0.1:47396 -> 127.0.0.1:5672, vhost: '/', user: 'guest')
> 
> I actually think I remember having this issue at one point in the past..
> 
> have you tried changing it back??

This error

**Comment by dnc92301** [comment]
I use the tower installation ( just the ansible role) for installing rabbitmq. The role installed it with rabbitmq@ username NOT rabbit@ - don’t think that matters. No errors from both rabbit mq logs

**Comment by MrMEEE** [comment]
rpm -qa rabbitmq-server

**Comment by dnc92301** [comment]
[root@hostnameA]# rpm -qa rabbitmq-server
rabbitmq-server-3.7.15-1.el7.noarch
[root@rhostnameA]#

**Comment by MrMEEE** [comment]
Does the role apply any form of configuration?

**Comment by dnc92301** [comment]
yes, its a Ansible playbook (role) . I modified it to configure guest rabbitmq user - guest
[all:vars]

rabbitmq_username=guest
rabbitmq_password='guest'

**Comment by MrMEEE** [comment]
Does it do anything else?

**Comment by dnc92301** [comment]
Do you know if this BROKER_URL still server any purpose - since celery is deprecated. I've modified both nodes to point to rabbitmq cluster -

/etc/tower/settings - 
CELERY_BROKER_URL = 'amqp://guest:guest@hostnameA:5672/%2F'

**Comment by powertim** [comment]
Hi guys,

Finally the playbook is here: https://github.com/powertim/deploy_awx-rpm
Currently designed for RHEL7 x86_64 with Satellite repos.
I will try to update it with manual repos as described on https://awx.wiki/installation/repositories/rhel7-x86_64.
And why not in the future for the different OS supported on the awx.wiki...

Please try first to adapt the playbook before opening an issue.
I'll fill up the README soon.

Best,

Tim

**Comment by brunowcs** [comment]
there is problem /var/lib/awx/venv/awx/usr/lib/python3.6/site-packages/awx/settings/defaults.py
BROKER_URL not working list HA rabbitmq server, somebody know because?

**Comment by bryanasdev000** [comment]
Hi everbody!

Did anyone get HA/Clustering running with AWX 11.X.X and redis?

**Comment by bryanasdev000** [comment]
> Hi everbody!
> 
> Did anyone get HA/Clustering running with AWX 11.X.X and redis?

Responding to myself, and leaving reference material for those who need it, issue of [https://github.com/sujiar37/AWX-HA-InstanceGroup/issues/26](url) seems to shed some light.

I will test asap.

**Comment by dnc92301** [comment]
> Hi guys,
> 
> Finally the playbook is here: https://github.com/powertim/deploy_awx-rpm
> Currently designed for RHEL7 x86_64 with Satellite repos.
> I will try to update it with manual repos as described on https://awx.wiki/installation/repositories/rhel7-x86_64.
> And why not in the future for the different OS supported on the awx.wiki...
> 
> Please try first to adapt the playbook before opening an issue.
> I'll fill up the README soon.
> 
> Best,
> 
> Tim

Hi Tim, thanks much for your playbook it was working as expected for few months now! However, I have been struggling to use it for new installation. I'm also unable to replicate my existing installation - AWX 6*.  I've tried installing both AWX6 and the latest AWX 9.* using mrmee repos. Problem is coming from the packages -  rh-python36-Django-3, rh-python36-django-jsonfield. 

  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/consumers.py", line 4, in <module>
    from channels import Group
ImportError: cannot import name 'Group'

  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/oauth2_provider/models.py", line 11, in <module>
    from django.utils.encoding import python_2_unicode_compatible
ImportError: cannot import name 'python_2_unicode_compatible'

I've attempted to update all files that are referencing to  "django.utils imports six" - which is no longer supported in django3.

/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/oauth2_provider/models.py
#from django.utils.encoding import python_2_unicode_compatible
from six import python_2_unicode_compatible

  /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/jsonfield/widgets.py 
#from django.utils import six
import six

I got through  the "six" module issue - by now running into another problem -

  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/consumers.py", line 4, in <module>
    from channels import Group
ImportError: cannot import name 'Group'

when running the task -
scl enable rh-python36 rh-postgresql10 "awx-manage migrate"

mrmee repo now is using "rh-python36-Django-3.0.4-1.noarch" (previously it was rh-python36-Django-2.2.4-1.noarch) and causing problems.  I've attempted to downgrade using - pip3.6 install django==2.2.4

However, the ansible-awx* will pickup the latest django version 3-
Dependencies Resolved

============================================================================================================================================================================================================
 Package                                             Arch                          Version                                   Repository                                                                Size
============================================================================================================================================================================================================
Installing:
 ansible-awx                                         x86_64                        9.3.0.104-1.el7                           copr:copr.fedorainfracloud.org:mrmeee:ansible-awx                         13 M
Installing for dependencies:
 rh-python36-Django                                  noarch                        3.0.4-1                                   copr:copr.fedorainfracloud.org:mrmeee:ansible-awx                        7.4 M

Any help would be greatly appreciated here - as I've be struck trying to fix this past couple days.

Thanks much!

**Comment by amieltahir** [comment]
> > Hi guys,
> > Finally the playbook is here: https://github.com/powertim/deploy_awx-rpm
> > Currently designed for RHEL7 x86_64 with Satellite repos.
> > I will try to update it with manual repos as described on https://awx.wiki/installation/repositories/rhel7-x86_64.
> > And why not in the future for the different OS supported on the awx.wiki...
> > Please try first to adapt the playbook before opening an issue.
> > I'll fill up the README soon.
> > Best,
> > Tim
> 
> Hi Tim, thanks much for your playbook it was working as expected for few months now! However, I have been struggling to use it for new installation. I'm also unable to replicate my existing installation - AWX 6*. I've tried installing both AWX6 and the latest AWX 9.* using mrmee repos. Problem is coming from the packages - rh-python36-Django-3, rh-python36-django-jsonfield.
> 
> File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/consumers.py", line 4, in
> from channels import Group
> ImportError: cannot import name 'Group'
> 
> File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/oauth2_provider/models.py", line 11, in
> from django.utils.encoding import python_2_unicode_compatible
> ImportError: cannot import name 'python_2_unicode_compatible'
> 
> I've attempted to update all files that are referencing to "django.utils imports six" - which is no longer supported in django3.
> 
> /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/oauth2_provider/models.py
> #from django.utils.encoding import python_2_unicode_compatible
> from six import python_2_unicode_compatible
> 
> /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/jsonfield/widgets.py
> #from django.utils import six
> import six
> 
> I got through the "six" module issue - by now running into another problem -
> 
> File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/consumers.py", line 4, in
> from channels import Group
> ImportError: cannot import name 'Group'
> 
> when running the task -
> scl enable rh-python36 rh-postgresql10 "awx-manage migrate"
> 
> mrmee repo now is using "rh-python36-Django-3.0.4-1.noarch" (previously it was rh-python36-Django-2.2.4-1.noarch) and causing problems. I've attempted to downgrade using - pip3.6 install django==2.2.4
> 
> However, the ansible-awx* will pickup the latest django version 3-
> Dependencies Resolved
> 
> # ============================================================================================================================================================================================================
> Package Arch Version Repository Size
> Installing:
> ansible-awx x86_64 9.3.0.104-1.el7 copr:copr.fedorainfracloud.org:mrmeee:ansible-awx 13 M
> Installing for dependencies:
> rh-python36-Django noarch 3.0.4-1 copr:copr.fedorainfracloud.org:mrmeee:ansible-awx 7.4 M
> 
> Any help would be greatly appreciated here - as I've be struck trying to fix this past couple days.
> 
> Thanks much!

Hi There,

I was following your thread as I am facing the same problem while trying to run 
sudo -u awx scl enable rh-python36 rh-postgresql10 "awx-manage migrate"

I am getting this error

File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/consumers.py", line 5, in <module>
    from channels import Group
ImportError: cannot import name 'Group'


This is my setup

django-channels-presence 1.0.0
django-cors-headers      3.7.0
django-oscar             3.0.2
djangorestframework      3.12.4
channels                 3.0.3

Is there any way to work around it as I really need to install AWX on RHEL 7.9 as Im not allowed to use containers. 

Thanks a lot
