### ISSUE TITLE
awx-rpm .spec files should Automatically generate  Requires: and BuildRequires: lines

### ISSUE THREAD

**Issue by nkadel** [MrMEEE/awx-build#122]
This may not be the right place to put the Issue, but since awx-rpm does not have an "Issues" list, and it's used by this software I thought I'd put it here fo MrMEEE can see it.

The awx-rpm .spec files are very difficult to read the dependencies for due to overlong Requires: and BuildRequires: lines. I've submitted a pull request with that repaired, and with a .gitignore enabled as well.

**Comment by MrMEEE** [comment]
You are correct.. also these dependencies should be generated from the requirements.txt files, and not maintained manually..

**Comment by nkadel** [comment]
Sadly, whatever you are using to auto-generate .spec files does not seem to track dependencies. It's tricky work, because some are woven into the setup.py and not listed in any "requirements.txt", and because requirements.txt is often written with stanzas. So it's often.

I've done most of this work, along with creating a "mock" setup, in my attempts to arrange and update the layout of ansible-awx-depends the way I think it should be. You're welcome to ignore the layout work, but I did wind up resolving dependencies for *all* of the .spec files, at https://github.com/nkadel/nkadel-ansible-awx-depends/tree/nkadel-mock

It wouldn't be trivial to revert my layout changes if you don't like them, but the Requires settings may be useful to you for immediate reference.
