### ISSUE TITLE
Guide to shutdown/restart services

### ISSUE THREAD

**Issue by franzcisco** [MrMEEE/awx-build#125]
Hi, this is not really an issue, but a request for instructions.
My AWX install has a bit of an issue, not sure if it is behaving as it should.
The issue is simple: if I power off the VM (without stopping any services) when I power it up again AWX is not working anymore.
I tried to restart the services:

systemctl start awx-cbreceiver
systemctl start awx-dispatcher
systemctl start awx-channels-worker
systemctl start awx-daphne
systemctl start awx-web

... without success. A snapshot of the VM does work though.
So I wonder, is there a "safe" procedure" to shut down services/DB before powering off the VM?
Can you provide a list of the services I need to stop (and the ones I need to activate on power up)?

Thanks and congrats for the great guides!

**Comment by MrMEEE** [comment]
Hi

You shouldn't need to stop anything manually, this should all be handled by systemd..

AWX-RPM has recently gotten a common service for starting/stopping: https://awx.wiki/blog/new-systemd-service

to be sure everything starts with the server:
```
systemctl enable awx
```

**Comment by franzcisco** [comment]
Maybe I need to upgrade my installa, because the "enable awx" instruvtion does not seem to work for me:

[root@VMW-DEVNET-AWX /]# 
[root@VMW-DEVNET-AWX /]# systemctl enable awx
Failed to execute operation: No such file or directory
[root@VMW-DEVNET-AWX /]# 
[root@VMW-DEVNET-AWX /]# pwd

Back to your answer (thanks for that!) do you mean that once I have the systemd service running OK, powering off/on the VM will not be an issue?

**Comment by MrMEEE** [comment]
Yes, everything should be started (and stopped) automatically with the awx systemd service
