### ISSUE TITLE
Big thanks

### ISSUE THREAD

**Issue by muzzol** [MrMEEE/awx-build#127]
Hi,

I just wanna give a big props to Martin and all other involved devs for this package!

Since awx is oblivion to non docker installation (see https://github.com/ansible/awx/issues/882) this is the fastest/easiest way to install and run AWX.

I've installed it in a PROXMOX (lxd) container with Centos 7 and the only thing different from docs (https://awx.wiki/installation) was that sudo isn't installed by default :)

I didn't know the proper way to give this huge thanks so I opened this issue, pls @MrMEEE feel free to close it after reading it.
:D

**Comment by MrMEEE** [comment]
Thanks a lot, it really means something that people out there are enjoying AWX-RPM..
