### ISSUE TITLE
Fix python dependency naming

### ISSUE THREAD

**Issue by MrMEEE** [MrMEEE/awx-build#128]
https://github.com/MrMEEE/ansible-awx-depends/issues/3

**Comment by nkadel** [comment]
Copying over the original ticket description, so it's apparent here:

SCLO would normally name a python RPM such as "adal" something like "rh-python36-python-adal". This would avoid potential conflict with RHEL or EPEL python module names that lack the standard "python2-" or "python3-" prefixes, of which there are some left, and allow setting dependencies consistently for thee particular modules.

**Comment by MrMEEE** [comment]
This is actually on purpose, as I have had issues with packages with the same name in the official repo, having newer, incompatible versions... 

I will rework this when I move to CentOS8/RHEL8.. but for now I will proberly keep this, unless someone comes up with a simple solution..
