### ISSUE TITLE
urllib3 InsecureRequestWarning error since upgrade to AWX 6.0.0

### ISSUE THREAD

**Issue by ldouchy** [MrMEEE/awx-build#129]
Hi,

Since the update to AWX 6.0.0 the following logs appeared:
```
Jul 15 15:40:10 servername scl[28131]: 2019-07-15 13:40:10,907 ERROR    awx.main.consumers Request user is not authenticated to use websocket.
Jul 15 15:40:17 servername scl[28131]: /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/urllib3/connectionpool.py:851: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
Jul 15 15:40:17 servername scl[28131]: InsecureRequestWarning)
```

I can't figure how to request from urllib3 to ignore this type of error. Is there a way to configure the  "ignore:Unverified HTTPS request" parameter?

**Comment by MrMEEE** [comment]
hmmm.. good question... 

I will look into it..

**Comment by ldouchy** [comment]
Thanks.

**Comment by MrMEEE** [comment]
I think this is fixed in newer versions:
https://github.com/ansible/awx/commit/90af9a9e337aa423241f0309d7ab532f53008a2f

Can you confirm?

**Comment by ldouchy** [comment]
Hi,

Thanks for your answer.

We plan to update our AWX cluster next week or in the worst case the week after. I will let you know as soon as the update is done.

Cheers.

**Comment by MrMEEE** [comment]
Please reopen, if this persists
