### ISSUE TITLE
AWX install broken after latest django 2.2.2 update

### ISSUE THREAD

**Issue by bigHosting** [MrMEEE/awx-build#130]
Hi,

I updated to latest Django yesterday and I AWX is broken. I tried removing all packages and reinstalling, and I am running into this issue

Anything I can do to resolve ?
Thank you!

root@deployment[/etc/yum.repos.d]# rpm -q rh-python36-Django-2.2.2-1.noarch
rh-python36-Django-2.2.2-1.noarch

root@deployment[/etc/yum.repos.d]# rpm -q ansible-awx
ansible-awx-6.0.0.703-1.el7.x86_64

root@deployment[/etc/ansible]# sudo -u awx scl enable rh-python36 rh-postgresql10 "awx-manage migrate"
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/bin/awx-manage", line 11, in <module>
    load_entry_point('awx==6.0.0', 'console_scripts', 'awx-manage')()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 570, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2751, in load_entry_point
    return ep.load()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2405, in load
    return self.resolve()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2411, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/__init__.py", line 43, in <module>
    and may not work in newer Django versions.".format(django.__version__))
RuntimeError: Django version other than 1.11.20 detected 2.2.2.                 Subclassing BaseDatabaseSchemaEditor is known to work for Django 1.11.20                 and may not work in newer Django versions.

**Comment by MrMEEE** [comment]
Hi

Works fine here:
```
[root@akiva ~]# sudo -u awx scl enable rh-postgresql10 rh-python36 "awx-manage migrate"
Operations to perform:
  Apply all migrations: auth, conf, contenttypes, main, oauth2_provider, sessions, sites, social_django, sso, taggit
Running migrations:
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
[root@akiva ~]# rpm -qa ansible-awx
ansible-awx-6.0.0.703-1.el7.x86_64
```

Have you remembered to do the complete upgrade method (in particular the yum install line??)
https://www.awx.wiki/upgrade/standard-upgrade-method

**Comment by bigHosting** [comment]
I am going to try on a VM and report back within an hour. Thank you very much for the fast reply!

**Comment by bigHosting** [comment]
By installing on a different VM, it works as expected. I'll have to do more troubleshooting ( remove packages, remove data folders etc ) on the existing server.

Thank you, ticket can be closed!

**Comment by tjyang** [comment]
Following are the commands in sequence to resolve same error I countered.

```
sudo yum remove rh-python36-python-ipaddress -y 
sudo yum install --disablerepo='*' --enablerepo='mrmeee-ansible-awx, base' -x *-debuginfo rh-python36*
sudo yum update ansible-awx -y
sudo -u awx scl enable rh-postgresql10 rh-python36 "awx-manage makemigrations"
sudo -u awx scl enable rh-postgresql10 rh-python36 "awx-manage migrate"

```

**Comment by bigHosting** [comment]
Thank you!

**Comment by powertim** [comment]
Hi guys,

I had the same issue when re-running my playbook to install a HA cluster of AWX RPM.
I think that there's a step somewhere which updates a django component and which makes impossible to run this command again. 

To be more clear for me it was when I was trying to import Database data. If I did it a second time (re-run the playbook due to errors later) it threw the same error code you have: 
`RuntimeError: Django version other than 1.11.20 detected 2.2.2. Subclassing BaseDatabaseSchemaEditor is known to work for Django 1.11.20 and may not work in newer Django versions.`

I'm sorry to have no solution for that, but just to share that you're not the lonely guy that met this problem.

Best,

Tim.

**Comment by MrMEEE** [comment]
Django should be updated: https://github.com/ansible/awx/blob/devel/requirements/requirements.in .. 

Are you sure that you have updated all the other dependencies and ansible-awx?

**Comment by MrMEEE** [comment]
Please reopen if this persists..
