### ISSUE TITLE
New version or roll-back version

### ISSUE THREAD

**Issue by 6sossomons** [MrMEEE/awx-build#132]
When I ran the update this morning, I received the following error:
---> Package ansible-awx.x86_64 0:6.0.0.671-1.el7 will be updated
---> Package ansible-awx.x86_64 0:6.1.0.46-1.el7 will be an update
---> Package erlang.x86_64 0:21.3.8.5-1.el7 will be updated
---> Package erlang.x86_64 0:21.3.8.6-1.el7 will be an update
---> Package sqlite.x86_64 0:3.7.17-8.el7 will be updated
---> Package sqlite.x86_64 0:3.29.0-1.el7 will be an update
--> Finished Dependency Resolution
Error:  Multilib version problems found. This often means that the root
       cause is something else and multilib version checking is just
       pointing out that there is a problem. Eg.:

         1. You have an upgrade for sqlite which is missing some
            dependency that another package requires. Yum is trying to
            solve this by installing an older version of sqlite of the
            different architecture. If you exclude the bad architecture
            yum will tell you what the root cause is (which package
            requires what). You can try redoing the upgrade with
            --exclude sqlite.otherarch ... this should give you an error
            message showing the root cause of the problem.

         2. You have multiple architectures of sqlite installed, but
            yum can only see an upgrade for one of those architectures.
            If you don't want/need both architectures anymore then you
            can remove the one with the missing update and everything
            will work.

         3. You have duplicate versions of sqlite installed already.
            You can use "yum check" to get yum show these errors.

       ...you can also use --setopt=protected_multilib=false to remove
       this checking, however this is almost never the correct thing to
       do as something else is very likely to go wrong (often causing
       much more problems).

       Protected multilib versions: sqlite-3.29.0-1.el7.x86_64 != sqlite-3.7.17-8.el7.i686
----

When I tell it to exclude sqlite, I get the following error after the installs finish and I try to run     sudo -u awx scl enable rh-postgresql10 rh-python36 "awx-manage makemigrations"
#  sudo -u awx scl enable rh-postgresql10 rh-python36 "awx-manage makemigrations"
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/bin/awx-manage", line 11, in <module>
    load_entry_point('awx==6.1.0', 'console_scripts', 'awx-manage')()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/__init__.py", line 142, in manage
    execute_from_command_line(sys.argv)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/oauth2_provider/__init__.py", line 4, in <module>
    __version__ = pkg_resources.require("django-oauth-toolkit")[0].version
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 981, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 867, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'sqlparse' distribution was not found and is required by django

Unfortunately when I hit rpm on sqlite:
sqlite-3.7.17-8.el7.i686
sqlite-3.7.17-8.el7.x86_64

While I can upgrade to the newest on x86_64, I'm stuck on i686 from your repo...

So, I either need a way to safely DOWNGRADE everything to version 4, or I'll need a i686 of sqlite that doesn't break:
 BelMonitor                                            x86_64                                           6.1.25-0                                                     
 libcurl                                               i686                                             7.29.0-46.el7                          nss                                                   i686                                             3.36.0-7.el7_5                                              nss-pem                                               i686                                             1.0.3-4.el7                                                 nss-softokn                                           i686                                             3.36.0-5.el7_5                                                openldap                                              i686                                             2.4.44-15.el7_5

**Comment by MrMEEE** [comment]
Why do you have the i686 packages installed?? Can't you just uninstall the sqlite i686 package?

**Comment by 6sossomons** [comment]
Unfortunately not, they are required for our systems packages for corporate
compliance.

**Comment by MrMEEE** [comment]
Unfortunately, the copr build service doesn't support i686 packages for CentOS7..

My best suggestion is that you download the source rpm: https://copr-be.cloud.fedoraproject.org/results/mrmeee/ansible-awx/epel-7-x86_64/00972892-sqlite/sqlite-3.29.0-1.el7.src.rpm

And rebuild it for i686:
rpmbuild --rebuild --target=i686 sqlite-3.29.0-1.el7.src.rpm

**Comment by MrMEEE** [comment]
Did you ever get this to work?

**Comment by 6sossomons** [comment]
No, did not get it to work with the source build.  We identified the
package requiring the 32-bit sqlite and have gotten the vendor to dig into
their code to get the application updated to use just the 64-bit version so
that we don't have to worry about multi-lib issues.

**Comment by dimasmir** [comment]
Unfortunately in centos7 sqlite-3.7.17-8.el7.x86_64 and sqlite-3.7.17-8.el7.i686 are installed. And both are used by the system and cannot be deleted. Is it possible to compile sqlite-3.29.0-1.el7.i686 and put into the repository?
