### ISSUE TITLE
https://awx.wiki/installation does not work

### ISSUE THREAD

**Issue by riahc3** [MrMEEE/awx-build#134]
Followed it by basically copying and pasting the commands as root in a SSH terminal.

If I hit the IP, it says connection refused. netstat doesnt show anything listening on port 80 (nginx is installed, enabled and running)

**Comment by MrMEEE** [comment]
By default the webinterface is on port 8052 :)

**Comment by MrMEEE** [comment]
Please reopen if this issue persists
