### ISSUE TITLE
Hi finally i completely installed AWX in centos 7 but i can't able to access AWX dashboard

### ISSUE THREAD

**Issue by Ashjoker24** [MrMEEE/awx-build#137]
The log shows,

Aug 13 07:53:31 beat scl: Traceback (most recent call last):
Aug 13 07:53:31 beat scl: File "/opt/rh/rh-python36/root/usr/bin/awx-manage", line 11, in <module>
Aug 13 07:53:31 beat scl: load_entry_point('awx==6.1.0', 'console_scripts', 'awx-manage')()
Aug 13 07:53:31 beat scl: File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/__init__.py", line 142, in manage
Aug 13 07:53:31 beat scl: execute_from_command_line(sys.argv)
Aug 13 07:53:31 beat scl: File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
Aug 13 07:53:31 beat scl: utility.execute()
Aug 13 07:53:31 beat scl: File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
Aug 13 07:53:31 beat scl: self.fetch_command(subcommand).run_from_argv(self.argv)
Aug 13 07:53:31 beat scl: File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
Aug 13 07:53:31 beat scl: self.execute(*args, **cmd_options)
Aug 13 07:53:31 beat scl: File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
Aug 13 07:53:31 beat scl: output = self.handle(*args, **options)
Aug 13 07:53:31 beat scl: File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/management/commands/run_dispatcher.py", line 123, in handle
Aug 13 07:53:31 beat scl: reaper.reap()
Aug 13 07:53:31 beat scl: File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/dispatch/reaper.py", line 36, in reap
Aug 13 07:53:31 beat scl: me = instance or Instance.objects.me()
Aug 13 07:53:31 beat scl: File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/managers.py", line 116, in me
Aug 13 07:53:31 beat scl: raise RuntimeError("No instance found with the current cluster host id")
Aug 13 07:53:31 beat scl: RuntimeError: No instance found with the current cluster host id
Aug 13 07:53:32 beat systemd: awx-dispatcher.service: main process exited, code=exited, status=1/FAILURE
Aug 13 07:53:32 beat systemd: Unit awx-dispatcher.service entered failed state.
Aug 13 07:53:32 beat systemd: awx-dispatcher.service failed.

**Comment by MrMEEE** [comment]
Doublecheck that you did run the stuff under: https://awx.wiki/installation/configuration... especially the  lines:
```
sudo -u awx scl enable rh-python36 rh-postgresql10 "awx-manage provision_instance --hostname=$(hostname)"
sudo -u awx scl enable rh-python36 rh-postgresql10 "awx-manage register_queue --queuename=tower --hostnames=$(hostname)"
```

**Comment by Ashjoker24** [comment]
Thanks MrMEEE now awx-dispatcher become in running state but i can't able to access dashboard? all service are in active state. what can i do?

**Comment by Ashjoker24** [comment]
[root@beat bin]# netstat -plntu
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:25672           0.0.0.0:*               LISTEN      26049/beam.smp
tcp        0      0 0.0.0.0:11211           0.0.0.0:*               LISTEN      22020/memcached
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN      1/systemd
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      30811/nginx: master
tcp        0      0 0.0.0.0:4369            0.0.0.0:*               LISTEN      26217/epmd
tcp        0      0 127.0.0.1:8050          0.0.0.0:*               LISTEN      11197/uwsgi
tcp        0      0 127.0.0.1:8051          0.0.0.0:*               LISTEN      11188/python3
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      3028/sshd
tcp        0      0 127.0.0.1:5432          0.0.0.0:*               LISTEN      22004/postmaster
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      3001/master
tcp6       0      0 :::5672                 :::*                    LISTEN      26049/beam.smp
tcp6       0      0 :::11211                :::*                    LISTEN      22020/memcached
tcp6       0      0 :::111                  :::*                    LISTEN      1/systemd
tcp6       0      0 :::4369                 :::*                    LISTEN      26217/epmd
tcp6       0      0 :::22                   :::*                    LISTEN      3028/sshd
tcp6       0      0 ::1:5432                :::*                    LISTEN      22004/postmaster
tcp6       0      0 ::1:25                  :::*                    LISTEN      3001/master
udp        0      0 0.0.0.0:11211           0.0.0.0:*                           22020/memcached
udp        0      0 0.0.0.0:68              0.0.0.0:*                           2832/dhclient
udp        0      0 0.0.0.0:111             0.0.0.0:*                           1/systemd
udp        0      0 127.0.0.1:323           0.0.0.0:*                           2601/chronyd
udp        0      0 0.0.0.0:642             0.0.0.0:*                           2599/rpcbind
udp6       0      0 :::11211                :::*                                22020/memcached
udp6       0      0 :::111                  :::*                                1/systemd
udp6       0      0 ::1:323                 :::*                                2601/chronyd
udp6       0      0 :::642                  :::*                                2599/rpcbind

but when i try to open AWX dashboard it automatically open 8052 port and the awx webui not working

**Comment by MrMEEE** [comment]
seems like nginx is not running?

**Comment by MrMEEE** [comment]
or.. it seems like you haven't installed the correct nginx configuration

**Comment by MrMEEE** [comment]
Doublecheck that you have followed the installation instructions

**Comment by Ashjoker24** [comment]
nginx service status 

[root@beat bin]# systemctl status nginx
● nginx.service - The nginx HTTP and reverse proxy server
   Loaded: loaded (/usr/lib/systemd/system/nginx.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2019-08-13 05:50:04 UTC; 2h 34min ago
 Main PID: 30811 (nginx)
   CGroup: /system.slice/nginx.service
           ├─30811 nginx: master process /usr/sbin/nginx
           └─30812 nginx: worker process

Aug 13 05:50:04 beat.novalocal systemd[1]: Stopped The nginx HTTP and reverse proxy server.
Aug 13 05:50:04 beat.novalocal systemd[1]: Starting The nginx HTTP and reverse proxy server...
Aug 13 05:50:04 beat.novalocal nginx[30807]: nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
Aug 13 05:50:04 beat.novalocal nginx[30807]: nginx: configuration file /etc/nginx/nginx.conf test is successful
Aug 13 05:50:04 beat.novalocal systemd[1]: Started The nginx HTTP and reverse proxy server.

**Comment by Ashjoker24** [comment]
nginx config file,


[root@beat bin]# cat /etc/nginx/nginx.conf
######################
# By Waderni Lotfi
######################
#user awx;

worker_processes  1;

error_log  /var/log/nginx/error_log warn;
pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access_log  main;

    map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
    }

    sendfile        on;
    #tcp_nopush     on;
    #gzip  on;

    upstream uwsgi {
        server 127.0.0.1:8050;
        }

    upstream daphne {
        server 127.0.0.1:8051;
    }

    server {
 #       listen 8052 default_server;
#Modified to listen on port 80
        listen 80 default_server;

        # If you have a domain name, this is where to add it
        server_name _;
        keepalive_timeout 65;

        # HSTS (ngx_http_headers_module is required) (15768000 seconds = 6 months)
        add_header Strict-Transport-Security max-age=15768000;

        location /static/ {
            alias /opt/awx/static/;
        }

        location /favicon.ico { alias /opt/awx/static/favicon.ico; }

        location /websocket {
            # Pass request to the upstream alias
            proxy_pass http://daphne;
            # Require http version 1.1 to allow for upgrade requests
            proxy_http_version 1.1;
            # We want proxy_buffering off for proxying to websockets.
            proxy_buffering off;
            # http://en.wikipedia.org/wiki/X-Forwarded-For
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            # enable this if you use HTTPS:
            proxy_set_header X-Forwarded-Proto https;
            # pass the Host: header from the client for the sake of redirects
            proxy_set_header Host $http_host;
            # We've set the Host header, so we don't need Nginx to muddle
            # about with redirects
            proxy_redirect off;
            # Depending on the request value, set the Upgrade and
            # connection headers
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
        }

        location / {
            # Add trailing / if missing
            rewrite ^(.*)$http_host(.*[^/])$ $1$http_host$2/ permanent;
            uwsgi_read_timeout 120s;
            uwsgi_pass uwsgi;
            include /etc/nginx/uwsgi_params;
        }
    }
}

**Comment by MrMEEE** [comment]
and it's not working on port 80?

**Comment by Ashjoker24** [comment]
no it's not working

**Comment by Ashjoker24** [comment]
it directly open 8052
not 80

**Comment by MrMEEE** [comment]
Are you getting anything?

I have just tried changing the port here.. it works fine... 

must be something that your client caches... 

Are you sure that you have disabled or configured the firewall?

**Comment by Ashjoker24** [comment]
I completely disabled the firewall in my machine, when i try to brows ip of my AWX machine it navigate it into http://ipofAWX:8052

**Comment by Ashjoker24** [comment]
there is something error in nginx config file but i can't find it

**Comment by MrMEEE** [comment]
I was talking of the firewall on the awx machine???

If you have just used the nginx conf from awx.wiki, and just changed the port from 8052->80, it works..

**Comment by Ashjoker24** [comment]
yeah i completely disabled the firewall in my AWX machine. shall i change the nginx conf file from 8052 to 80?

**Comment by MrMEEE** [comment]
You don't have to.. it works either way.. 

Can you please test from the command line:

```
curl http://localhost:80
or
curl http://localhost:8052
```

**Comment by Ashjoker24** [comment]
http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access_log  main;

    map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
    }

    sendfile        on;
    #tcp_nopush     on;
    #gzip  on;

    upstream uwsgi {
        server 127.0.0.1:8050;
        }

    upstream daphne {
        server 127.0.0.1:8051;
    }

    server {
 #       listen 8052 default_server;
#Modified to listen on port 80
        listen 80 default_server;
here shall i change listen 8052 default_server port number??

**Comment by MrMEEE** [comment]
If you like to.. it works no matter what

**Comment by Ashjoker24** [comment]
curl http://localhost:80 -> it print the HTML page and 
curl http://localhost:8052 -> connection refused

**Comment by MrMEEE** [comment]
then it works... your browser must be caching the 8052 address

**Comment by Ashjoker24** [comment]
yup you are right my chrome navigate to me in  8052 but when i try to open it in firefox it works!!!!.....
100000000000000 times thanksssss Mr.MEEE

**Comment by Ashjoker24** [comment]
it works

**Comment by MrMEEE** [comment]
Chrome is weird sometimes.. Enjoy :)
