### ISSUE TITLE
What is the username and password to access AWX dashboard?

### ISSUE THREAD

**Issue by Ashjoker24** [MrMEEE/awx-build#138]
I successfully installed AWX dashboard in centos. what is the username and password for access dashboard i tried with admin and password

**Comment by MrMEEE** [comment]
You have set it yourself in:
https://awx.wiki/installation/configuration

**Comment by Ashjoker24** [comment]
echo "from django.contrib.auth.models import User; User.objects.create_superuser('admin', 'root@localhost', 'password')" | sudo -u awx scl enable rh-python36 rh-postgresql10 "awx-manage shell"
i run above command what you mentioned in installation step. now i tried to login through admin,password credentials but AWX dashboard shows invalid username and password

**Comment by Ashjoker24** [comment]
when i try to change password for admin user it print error like,
# /opt/rh/rh-python36/root/usr/bin/awx-manage changepassword admin
 raise ImproperlyConfigured("Error loading psycopg2 module: %s" % e)
django.core.exceptions.ImproperlyConfigured: Error loading psycopg2 module: libpq.so.rh-postgresql10-5: cannot open shared object file: No such file or directory

**Comment by MrMEEE** [comment]
You have to use the scl command:

https://awx.wiki/tools/reset-admin-password

**Comment by Ashjoker24** [comment]
no it is not working, even i changed my admin password dashboard shows invalid username and/or password

**Comment by Ashjoker24** [comment]
how can i login into postgresql in AWX & how can i check the db & webui works fine. There is no error in logs.

**Comment by MrMEEE** [comment]
you can enter the postgres db with:
```
su - postgres
scl enable rh-postgresql10 "psql"
```

**Comment by sklnk** [comment]
I have same problem, did you sort it out somehow?

**Comment by MrMEEE** [comment]
@sklnk Any errors in the logs?

Which version of ansible-awx?

**Comment by sklnk** [comment]
I have incorectly added your repo , because I have not installed half of python modules. I see it now from the logs. But i follow the install instructions, so what is wrong?

```
[root@awx-rpm centos]# yum -y install --disablerepo='*' --enablerepo='ansible-awx, base' -x *-debuginfo rh-python36*
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: ftp.upjs.sk
Nothing to do
[root@awx-rpm centos]# yum -y install --disablerepo='*' --enablerepo='ansible-awx' -x *-debuginfo rh-python36*
Loaded plugins: fastestmirror


Error getting repository data for ansible-awx, repository not found
```

**Comment by MrMEEE** [comment]
hmmm.. have you looked in the /etc/yum.repos.d/ ?

**Comment by sklnk** [comment]
Yes the repo is present there. This is the content:
```
[copr:copr.fedorainfracloud.org:mrmeee:ansible-awx]
name=Copr repo for ansible-awx owned by mrmeee
baseurl=https://copr-be.cloud.fedoraproject.org/results/mrmeee/ansible-awx/epel-7-$basearch/
type=rpm-md
skip_if_unavailable=True
gpgcheck=1
gpgkey=https://copr-be.cloud.fedoraproject.org/results/mrmeee/ansible-awx/pubkey.gpg
repo_gpgcheck=0
enabled=1
enabled_metadata=1
```

**Comment by MrMEEE** [comment]
Then it should probably be:
```
yum -y install --disablerepo='*' --enablerepo='copr:copr.fedorainfracloud.org:mrmeee:ansible-awx, base' -x *-debuginfo rh-python36*
```

**Comment by sklnk** [comment]
That solve my problem.

 Thank you!

**Comment by MrMEEE** [comment]
Cool.. thanks for the feedback @Ashjoker24 , maybe the same works for you?

**Comment by bwosborne2** [comment]
That worked for me too. Please update the installation instructions for CentOS 7 x64 with the new command.
