### ISSUE TITLE
Upgrading from 2.1.2 to 3.0.0.0 and from 3.0.0.0 to 4.0.0.347 -> 6.1.0.18

### ISSUE THREAD

**Issue by Neurozone** [MrMEEE/awx-build#139]
Hello.
I have and old installation of awx tower.
And I don't kinow how to upgrade from 2.1.2 to 3.0.0.0 and from 3.0.0.0 to 4.0.0.347 -> 6.1.0.18

Do you have a guide ? Or some help ?

**Comment by MrMEEE** [comment]
Have you seen this?
https://www.awx.wiki/upgrade/workarounds

**Comment by Neurozone** [comment]
Didn't see that, thank you !

Followed that:

2.1.2.44 -> 3.0.0.0

But after:

Upgrade to the new AWX-RPM:

yum -y install ansible-awx

Cleanup:

yum -y remove rh-postgresql96* postgresql96* awx

Start Services and upgrade db:

systemctl start rh-postgresql10-postgresql.service
systemctl enable rh-postgresql10-postgresql.service

sudo -u awx scl enable rh-postgresql10 rh-python36 "awx-manage makemigrations"
sudo -u awx scl enable rh-postgresql10 rh-python36 "awx-manage migrate"
I got that:

root@*** systemctl start rh-postgresql10-postgresql.service
root@*** systemctl enable rh-postgresql10-postgresql.service
Created symlink from /etc/systemd/system/multi-user.target.wants/rh-postgresql10-postgresql.service to /usr/lib/systemd/system/rh-postgresql10-postgresql.service.
root@*** sudo -u awx scl enable rh-postgresql10 rh-python36 "awx-manage makemigrations"
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/bin/awx-manage", line 11, in <module>
    load_entry_point('awx==6.1.0', 'console_scripts', 'awx-manage')()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/__init__.py", line 126, in manage
    prepare_env()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/__init__.py", line 91, in prepare_env
    if not settings.DEBUG: # pragma: no cover
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/conf/__init__.py", line 79, in __getattr__
    self._setup(name)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/conf/__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/conf/__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/settings/production.py", line 14, in <module>
    from split_settings.tools import optional, include
ModuleNotFoundError: No module named 'split_settings'

root@*** sudo -u awx scl enable rh-postgresql10 rh-python36 "/opt/rh/rh-python36/root/usr/bin/awx-manage makemigrations"
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/bin/awx-manage", line 11, in <module>
    load_entry_point('awx==6.1.0', 'console_scripts', 'awx-manage')()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/__init__.py", line 126, in manage
    prepare_env()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/__init__.py", line 91, in prepare_env
    if not settings.DEBUG: # pragma: no cover
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/conf/__init__.py", line 79, in __getattr__
    self._setup(name)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/conf/__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/conf/__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/settings/production.py", line 14, in <module>
    from split_settings.tools import optional, include
ModuleNotFoundError: No module named 'split_settings'

**Comment by MrMEEE** [comment]
You forgot the:
```
yum install --disablerepo='*' --enablerepo='mrmeee-ansible-awx, base' -x *-debuginfo rh-python36*
```

**Comment by Neurozone** [comment]
I did that:

yum install --disablerepo='*' --enablerepo='mrmeee-ansible-awx, base' -x *-debuginfo rh-python36*
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
There are no enabled repos.
 Run "yum repolist all" to see the repos you have.
 To enable Red Hat Subscription Management repositories:
     subscription-manager repos --enable <repo>
 To enable custom repositories:
     yum-config-manager --enable <repo>
root@*** yum repolist all
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * centos-sclo-rh: centos.crazyfrogs.org
 * centos-sclo-sclo: centos.mirrors.proxad.net
repo id                                                  repo name                                                   status
bintraybintray-rabbitmq-erlang-rpm                       bintray-rabbitmq-erlang-rpm                                 enabled:      5
bintraybintray-rabbitmq-rpm                              bintray-rabbitmq-rpm                                        enabled:     18
centos-7.6-extras                                        Internal Repository for CentOS 7.6 extras                   enabled:    435
centos-7.6-main                                          Internal Repository for CentOS 7.6 os                       enabled: 10,019
centos-7.6-updates                                       Internal Repository for CentOS 7.6 updates                  enabled:  2,500
centos-sclo-rh/x86_64                                    CentOS-7 - SCLo rh                                          enabled:  8,451
centos-sclo-rh-debuginfo/x86_64                          CentOS-7 - SCLo rh Debuginfo                                disabled
centos-sclo-rh-source                                    CentOS-7 - SCLo rh Sources                                  disabled
centos-sclo-rh-testing/x86_64                            CentOS-7 - SCLo rh Testing                                  disabled
centos-sclo-sclo/x86_64                                  CentOS-7 - SCLo sclo                                        enabled:    786
centos-sclo-sclo-debuginfo/x86_64                        CentOS-7 - SCLo sclo Debuginfo                              disabled
centos-sclo-sclo-source                                  CentOS-7 - SCLo sclo Sources                                disabled
centos-sclo-sclo-testing/x86_64                          CentOS-7 - SCLo sclo Testing                                disabled
copr:copr.fedorainfracloud.org:mrmeee:ansible-awx/x86_64 Copr repo for ansible-awx owned by mrmeee                   enabled:    615
elasticsearch-2.x-el7                                    Elasticsearch Repository for Enterprise Linux 7 - x86_64    disabled
elasticsearch-5.x-el7                                    Elasticsearch Repository for Enterprise Linux 7 - x86_64    disabled
epel                                                     epel                                                        enabled: 20,803
erlang-21-el7                                            Erlang 21 el7                                               enabled:      3
!mariadb-10.3-el7                                        Mariadb Repository for Enterprise linux 7 os                disabled
mariadb-10.4-el7                                         Mariadb Repository for Enterprise linux 7 os                enabled:     64
mongodb-3.0-el7                                          MongoDB 3.0 Repository for CentOS 7                         disabled
mongodb-3.2-el7                                          MongoDB 3.2 Repository for CentOS 7                         disabled
mongodb-3.4-el7                                          MongoDB 3.4 Repository for CentOS 7                         disabled
mongodb-3.6-el7                                          MongoDB 3.6 Repository for CentOS 7                         disabled
mysql-5.5-el7                                            Mysql Repository for Enterprise Linux 7 - x86_64            disabled
mysql-5.6-el7                                            Mysql Repository for Enterprise Linux 7 - x86_64            disabled
mysql-5.7-el7                                            Mysql Repository for Enterprise Linux 7 - x86_64            disabled
nginx-mainline-centos-7                                  nginx Repository for CentOS 7                               enabled:    573
nginx-stable-centos-7                                    nginx Repository for CentOS 7                               disabled
nodejs-4.x-el7                                           NodeJS 4.X el7 Server                                       disabled
nodejs-6.x-el7                                           NodeJS 6.X el7 Server                                       disabled
nodejs-8.x-el7                                           NodeJS 8.X el7 Server                                       disabled
postgresql-10-el7                                        PostgreSQL 10 el7                                           enabled:    819
remi-php-7.1-el7                                         Remi's PHP 7.1 RPM repository for Enterprise Linux 7 - x86_ disabled
!remi-php-7.2-el7                                        Remi's PHP 7.2 RPM repository for Enterprise Linux 7 - x86_ disabled
remi-php-7.3-el7                                         Remi's PHP 7.3 RPM repository for Enterprise Linux 7 - x86_ enabled:    842
remi-safe-el7                                            Safe Remi's RPM repository for Enterprise Linux 7 - x86_64  enabled:  9,656
zabbix-2.4                                               Zabbix Repository for CentOS 7.6 os                         disabled
zabbix-3.4                                               Zabbix Repository for CentOS 7.6 os                         enabled:    236
repolist: 55,825

But we are behind a proxy with local repositories

**Comment by MrMEEE** [comment]
Then you have to replace:
mrmeee-ansible-awx : with the local repo name
base: local CentOS base repo

**Comment by Neurozone** [comment]
wait oO

sudo -u awx scl enable rh-postgresql10 rh-python36 "/opt/rh/rh-python36/root/usr/bin/awx-manage version"
6.1.0

It did succeed :o
Wow you rocks !

Thank you !!!!

**Comment by MrMEEE** [comment]
Cool :)..
