### ISSUE TITLE
Backup and Restore database of AWX

### ISSUE THREAD

**Issue by Rpera** [MrMEEE/awx-build#14]
Hello, 

Do you manage to backup and restore awx postgres database?
I want to create a script that backup all the necessary to use on prior installations of awx.

Do you use already anything for this?

Thank-you
Best Regards
R&P

**Comment by MrMEEE** [comment]
Hi

I haven't looked into backup (yet, on the todo list).. 

I would suggest that you look into the backup/restore playbooks from Ansible Tower:

http://releases.ansible.com/ansible-tower/setup/ansible-tower-setup-3.2.3.tar.gz

I think they will work with a little modification..

**Comment by rthill** [comment]
You can backup your database content using the dumpdata functionality integrated in the Django manage command. In case of AWX you may run `awx-manage dumpdata -o /tmp/dump.json` to dump the data. JSON is the default format, but you can also switch to YAML, which I prefer for readability reasons.

For more options check the Django documentation:
https://docs.djangoproject.com/en/2.1/ref/django-admin/#dumpdata
https://docs.djangoproject.com/en/2.1/ref/django-admin/#loaddata
