### ISSUE TITLE
scl files in /var/tmp

### ISSUE THREAD

**Issue by dnc92301** [MrMEEE/awx-build#141]
hi all

We noticed a tons of files written to /var/tmp with the scl* naming. This is normal behavior?

Contens of the file -
[root@tmp]# cat sclBo8Sf6
eval "SCLS=( ${X_SCLS[*]} )"
/usr/bin/scl_enabled rh-python36
if [ $? != 0 ]; then
  SCLS+=(rh-python36)
  export X_SCLS=$(printf '%q ' "${SCLS[@]}")
. /opt/rh/rh-python36//enable
fi
/usr/bin/scl_enabled rh-postgresql10
if [ $? != 0 ]; then
  SCLS+=(rh-postgresql10)
  export X_SCLS=$(printf '%q ' "${SCLS[@]}")
. /opt/rh/rh-postgresql10//enable
fi
uwsgi          --socket 127.0.0.1:8050          --module=awx.wsgi:application          --logto=/var/log/tower/web.log          --die-on-term          --vacuum          --uid awx          --gid awx          --processes=5          --harakiri=120          --no-orphans          --master          --max-requests=1000          --master-fifo=/var/lib/awx/awxfifo          --lazy-apps -b 32768

root@tmp]# pwd && ls|wc -l
/var/tmp
250300

-rw-------. 1 root    root       736 Jul 20 14:28 sclzzZCL8
-rw-------. 1 awx     awx        400 Jul 21 05:32 sclZzZill
-rw-------. 1 awx     awx        400 Jun 25 11:54 sclZzZlJa
-rw-------. 1 root    root       736 Jul 23 15:48 sclZZZlTq
-rw-------. 1 awx     awx        400 Jul 20 15:04 sclZZzpru
-rw-------. 1 awx     awx        382 Jul 22 20:55 sclzzZQUB
-rw-------. 1 awx     awx        400 Jul 19 19:54 sclzZZvY8
-rw-------. 1 awx     awx        382 Jul 21 02:13 sclzZzZD5

**Comment by MrMEEE** [comment]
I have them too.. they are the "jails" of the scl processes.. I might need to implement some automated cleanup.. but it's quite normal..
