### ISSUE TITLE
Many works of DEBUG

### ISSUE THREAD

**Issue by varobo8** [MrMEEE/awx-build#144]
Hello,

I have many of these DEBUG logs running constantly, I would like to know if this process is normal.

Thank you.

Aug 19 14:44:52 awxans01 scl: 2019-08-19 20:44:52,378 DEBUG    awx.main.dispatch publish awx.main.tasks.awx_periodic_scheduler(7e245729-b751-46c9-b4d4-162faabcac54, queue=awx_private_queue)
Aug 19 14:44:52 awxans01 scl: [2019-08-19 20:44:52,378: DEBUG/Process-1] publish awx.main.tasks.awx_periodic_scheduler(7e245729-b751-46c9-b4d4-162faabcac54, queue=awx_private_queue)
Aug 19 14:44:52 awxans01 scl: 2019-08-19 20:44:52,412 DEBUG    awx.main.dispatch delivered 7e245729-b751-46c9-b4d4-162faabcac54 to worker[12927] qsize 0
Aug 19 14:44:52 awxans01 scl: 2019-08-19 20:44:52,419 DEBUG    awx.main.dispatch task 7e245729-b751-46c9-b4d4-162faabcac54 starting awx.main.tasks.awx_periodic_scheduler(*[])
Aug 19 14:44:52 awxans01 scl: 2019-08-19 20:44:52,432 DEBUG    awx.main.tasks Starting periodic scheduler
Aug 19 14:44:52 awxans01 scl: 2019-08-19 20:44:52,438 DEBUG    awx.main.tasks Last scheduler run was: 2019-08-19 20:44:22.430807+00:00
Aug 19 14:44:52 awxans01 scl: 2019-08-19 20:44:52,457 DEBUG    awx.main.dispatch task 7e245729-b751-46c9-b4d4-162faabcac54 is finished

**Comment by MrMEEE** [comment]
Thanks for the feedback...

This must be some leftover from some debugging work...

In your /etc/tower/settings.py:
```
LOGGING['handlers']['console'] = {
    '()': 'logging.StreamHandler',
    'level': 'DEBUG',
    'formatter': 'simple',
}
```
can be changed to:
```
LOGGING['handlers']['console'] = {
    '()': 'logging.StreamHandler',
    'level': 'INFO',
    'formatter': 'simple',
}
```
and then restart awx (systemctl restart awx)... I have corrected this in the settings.py included in the RPM, so it will be fixed from the next release..

Thanks

**Comment by varobo8** [comment]
Hi,

Thanks for the support,

I made the change, now I continue seeing only this DEBUG:

Aug 20 09:30:37 awxans02.example.com scl[1164]: [2019-08-20 15:30:37,863: DEBUG/Process-1] publish awx.main.scheduler.tasks.run_task_manager(3eb8458f-2b45-424b-9f7c-5b5813fe4b21, queue=awx_private_queue)
Aug 20 09:30:47 awxans02.example.com scl[1164]: [2019-08-20 15:30:47,825: DEBUG/Process-1] publish awx.main.tasks.awx_periodic_scheduler(f367b1b9-fd50-409e-a0e1-6ff9d315468c, queue=awx_private_queue)
Aug 20 09:30:57 awxans02.example.com scl[1164]: [2019-08-20 15:30:57,838: DEBUG/Process-1] publish awx.main.scheduler.tasks.run_task_manager(d659f14a-03e0-4f7a-b10d-8a4fdd68fa95, queue=awx_private_queue)
Aug 20 09:31:18 awxans02.example.com scl[1164]: [2019-08-20 15:31:17,824: DEBUG/Process-1] publish awx.main.tasks.cluster_node_heartbeat(d89e5b63-cc8b-4b96-978f-8ae9668aae23, queue=awxans02.example.com)
Aug 20 09:31:18 awxans02.example.com scl[1164]: [2019-08-20 15:31:18,143: DEBUG/Process-1] publish awx.main.tasks.awx_periodic_scheduler(ae71edc0-2699-40f1-9ae4-9fd616523114, queue=awx_private_queue)

Thanks

**Comment by MrMEEE** [comment]
Ok.. I have to dig a little deeper for this
