### ISSUE TITLE
default PATH and su

### ISSUE THREAD

**Issue by roumano** [MrMEEE/awx-build#146]
on a fresh centos7 OS, this command is failling if we don't change the path (/root/ by default ) 
```
[root@localhost ~]# scl enable rh-postgresql10 "su postgres -c \"createuser -S awx\""
could not change directory to "/root": Permission non accordée
```

I think you should add a ` - ` for `su` command :  `scl enable rh-postgresql10 "su - postgres -c \"createuser -S awx\""`

**Comment by MrMEEE** [comment]
Hi..

Actually the command is not failing.. it's actually doing what it's supposed to.. but you are correct.. this should be changed

**Comment by tjyang** [comment]
@roumano 

* Adding "-" after "su" doesn't help
```
[root@awx01 ~]# scl enable rh-postgresql10 "su  postgres -c \"createuser -S awx2\""
could not change directory to "/root": Permission denied
[root@awx01 ~]# scl enable rh-postgresql10 "su -  postgres -c \"createuser -S awx3\""
-bash: createuser: command not found
[root@awx01 ~]# date
Fri Sep  6 09:45:30 EDT 2019
[root@awx01 ~]#

```
* the fix is to run the command in /tmp. But I don't know WHY.

```
[root@awx01 tmp]# scl enable rh-postgresql10 "su  postgres -c \"createuser -S awx4\""
[root@awx01 tmp]#

```

**Comment by ranmses** [comment]
On a rhel7 system, running that way prevented the error message no matter the current path:
```
su - postgres -c "scl enable rh-postgresql10 \"createuser -S awx\""
su - postgres -c "scl enable rh-postgresql10 \"createdb -O awx awx\""
```
