### ISSUE TITLE
How to add instances only?

### ISSUE THREAD

**Issue by rchaud** [MrMEEE/awx-build#147]
Since everything was changed to AWX service and everything starts as once, how do we create systems that will only be working as instances that do not need the webui service, etc?

**Comment by MrMEEE** [comment]
That is a good question... I should probably separate service for this.. for now you could just disable the awx.service, and individually enable the needed services?

**Comment by rchaud** [comment]
Yes, I think the best option will be to disable the awx service and each service in the instance node.
