### ISSUE TITLE
rh-python36* RPMs consolidation 

### ISSUE THREAD

**Issue by tjyang** [MrMEEE/awx-build#149]
Hi @MrMEEE 

* I was doing another fresh install of ansible-awx yesterday. I found there are packages conflicts among different repoistories. This happens when doing rh-python36* install from ansible-awx.repo

```
[root@awx01 tmp]# ls -l  /etc/yum.repos.d/{CentOS-SCLo-scl.repo,epel.repo,CentOS-SCLo-scl.repo,ansible-awx.repo}
-rw-r--r--  1 root root  369 Sep  6 00:02 /etc/yum.repos.d/ansible-awx.repo
-rw-r--r--  1 root root 1009 Sep  6 00:38 /etc/yum.repos.d/CentOS-SCLo-scl.repo
-rw-r--r--  1 root root 1009 Sep  6 00:38 /etc/yum.repos.d/CentOS-SCLo-scl.repo
-rw-r--r--. 1 root root  951 Oct  2  2017 /etc/yum.repos.d/epel.repo
[root@awx01 tmp]#

```
* Can you shift  over to use rh-python36-* in SCL repos ?

**Comment by MrMEEE** [comment]
To be sure that the correct versions of the packages are installed, I can't just switch to the versions in the sclo repos...

In time I will try if I can move to a different scl namespace.. or maybe to the dnf modules when CentOS 8 is out..

**Comment by Neurozone** [comment]
Hello.
As of CentOS / rhel 7.7, python 3.6 is the default interpreter .
Maybe you need to update the installation / documentation ?

**Comment by MrMEEE** [comment]
Hi.. 

Python 3.6 is not the default interpreter.. but you are correct that it's included.. 

As we still need to stay pretty locked down to the versions of the python packages defined by the AWX team, I believe that the SCL is the right solution for now..

When CentOS8 is out, I will begin to look into the migration from SCL to modules..

**Comment by Neurozone** [comment]
https://wiki.centos.org/Manuals/ReleaseNotes/CentOS7.1908?action=show&redirect=Manuals%2FReleaseNotes%2FCentOS7#head-15a98690d8f7f5aeb60b7bd0acb9a13b799d0177

Quote : "Python 3 is now available. Installing the python3 package gives you the Python 3.6 interpreter. "

**Comment by MrMEEE** [comment]
Available, yes.. Default, no..

**Comment by Neurozone** [comment]
My bad. 
I apologize.
We always install python3 at my organization
