### ISSUE TITLE
Can not synchronous machines from vcenter

### ISSUE THREAD

**Issue by ManMaster** [MrMEEE/awx-build#155]
I add an empty inventory, uses source control function to synchronous machines from vmware vcenter, but it throws a TypeError,  do you know how to solve it?

>    1.818 INFO     Updating inventory 3: New Vcenter HY stage Machines
    2.626 DEBUG    Using base command: python /opt/rh/rh-python36/root/bin/ansible-inventory -i /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/plugins/inventory/vmware_inventory.py --playbook-dir /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/plugins/inventory -vvvvv
    2.627 INFO     Reading Ansible inventory source: /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/plugins/inventory/vmware_inventory.py
    2.628 INFO     Using VIRTUAL_ENV: /opt/rh/rh-python36/root/
    2.628 INFO     Using PATH: /opt/rh/rh-python36/root/bin:/var/lib/awx/venv/awx/bin:/opt/rh/rh-postgresql10/root/usr/bin:/opt/rh/rh-python36/root/usr/bin:/opt/awx/bin:/bin:/sbin:/usr/bin:/usr/sbin
    2.628 INFO     Using PYTHONPATH: /opt/rh/rh-python36/root/lib/python3.6/site-packages:
    2.660 DEBUG    Using private credential data in '/tmp/awx_16__e14jjoo'.
    2.663 DEBUG    Using fresh temporary directory '/tmp/awx_proot_oh8yy98g' for isolation.
    2.664 DEBUG    Running from `/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/plugins/inventory` working directory.

> Traceback (most recent call last):

  File "/var/lib/awx/venv/awx/bin/awx-manage", line 11, in <module>
    load_entry_point('awx==7.0.0', 'console_scripts', 'awx-manage')()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/__init__.py", line 142, in manage
    execute_from_command_line(sys.argv)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 1148, in handle
    raise exc
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 1038, in handle
    venv_path=venv_path, verbosity=self.verbosity).load()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 214, in load
    return self.command_to_json(base_args + ['--list'])
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 197, in command_to_json
    self.method, proc.returncode, stdout, stderr))
RuntimeError: ansible-inventory failed (rc=1) with stdout:
stderr:
ansible-inventory 2.8.4
  config file = None
  configured module search path = ['/var/lib/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/rh/rh-python36/root/lib/python3.6/site-packages/ansible
  executable location = /opt/rh/rh-python36/root/bin/ansible-inventory
  python version = 3.6.3 (default, May 31 2019, 13:05:43) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
No config file found; using defaults
setting up inventory plugins
 [WARNING]:  * Failed to parse /opt/rh/rh-python36/root/usr/lib/python3.6/site-
packages/awx/plugins/inventory/vmware_inventory.py with script plugin:
Inventory script (/opt/rh/rh-python36/root/usr/lib/python3.6/site-
packages/awx/plugins/inventory/vmware_inventory.py) had an execution error:
Traceback (most recent call last):   File "/opt/rh/rh-
python36/root/usr/lib/python3.6/site-
packages/awx/plugins/inventory/vmware_inventory.py", line 772, in <module>
print(VMWareInventory().show())   File "/opt/rh/rh-
python36/root/usr/lib/python3.6/site-
packages/awx/plugins/inventory/vmware_inventory.py", line 145, in __init__
self.do_api_calls_update_cache()   File "/opt/rh/rh-
python36/root/usr/lib/python3.6/site-
packages/awx/plugins/inventory/vmware_inventory.py", line 184, in
do_api_calls_update_cache     self.inventory =
self.instances_to_inventory(self.get_instances())   File "/opt/rh/rh-
python36/root/usr/lib/python3.6/site-
packages/awx/plugins/inventory/vmware_inventory.py", line 351, in get_instances
return self._get_instances(kwargs)   File "/opt/rh/rh-
python36/root/usr/lib/python3.6/site-
packages/awx/plugins/inventory/vmware_inventory.py", line 393, in
_get_instances     for instance in sorted(instances): TypeError: '<' not
supported between instances of 'vim.VirtualMachine' and 'vim.VirtualMachine'

  File "/opt/rh/rh-python36/root/lib/python3.6/site-packages/ansible/inventory/manager.py", line 268, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/opt/rh/rh-python36/root/lib/python3.6/site-packages/ansible/plugins/inventory/script.py", line 161, in parse
    raise AnsibleParserError(to_native(e))

 [WARNING]: Unable to parse /opt/rh/rh-python36/root/usr/lib/python3.6/site-
packages/awx/plugins/inventory/vmware_inventory.py as an inventory source

ERROR! No inventory was parsed, please check your configuration and options.

**Comment by ManMaster** [comment]
I contrast the same job between awx and tower I found one differnet，is the PYTHONPATH variables，
awx PYTHONPATH is /opt/rh/rh-python36/root/lib/python3.6/site-packages:
tower  PYTHONPATH is /var/lib/awx/venv/ansible/lib/python2.7/site-packages:
is this the reason of the problem？

**Comment by MrMEEE** [comment]
AWX-RPM is running purely python3 as default, where awx and tower are running python2..

This might be an issue of the vmware inventory script not being updated to python3..

You can create a python2 venv, and use that for the inventory, and see if that helps?

**Comment by ldouchy** [comment]
Hi,

I had a similar issue and found help there: [https://github.com/ansible/awx/issues/4156](https://github.com/ansible/awx/issues/4156). 

It boils down to replacing the script vmware_inventory.py

I didn't kept the error stack to check if it's exactly the same issue but I hope this will help.

**Comment by ManMaster** [comment]
Thanks very much， I will create a python2.7 venv and try to solve it

**Comment by MrMEEE** [comment]
Did you get it to work??

**Comment by MrMEEE** [comment]
Please reopen, if this still doesn't work
