### ISSUE TITLE
Error when changing hostname of AWX host

### ISSUE THREAD

**Issue by GIT-448482** [MrMEEE/awx-build#156]
I have deployed a fresh install of AWX on RHEL7.7 following the guides on https://awx.wiki/

The installation is successful, and everything works well.

I have then changed the IP address of the host server, and everything is still functional. However when i go to change the hostname of the RHEL server. I can no longer log into the AWX web gui. The page loads, with the username/password prompt box. Then once I enter my credentials, I get a pop up error saying:

ERROR! Failed to get dashboard jobs list: 502
or
ERROR! Failed to get: Undefined GET returned: 502

It appears that the awx-dispatcher.service is constantly restarting.

The error i see on the host from the logs is;

``Sep 19 14:15:58 hostname.domain.local scl[2282]: 2019-09-19 04:15:58,489 INFO     Starting server at tcp:port=8051:interface=127.0.0.1, channel layer awx.asgi:channel_layer.
Sep 19 14:15:58 hostname.domain.local scl[2282]: 2019-09-19 04:15:58,489 INFO     HTTP/2 support not enabled (install the http2 and tls Twisted extras)
Sep 19 14:15:58 hostname.domain.local scl[2282]: 2019-09-19 04:15:58,489 INFO     Using busy-loop synchronous mode on channel layer
Sep 19 14:15:58 hostname.domain.local scl[2282]: 2019-09-19 04:15:58,489 INFO     Listening on endpoint tcp:port=8051:interface=127.0.0.1
Sep 19 14:15:59 hostname.domain.local scl[2278]: 2019-09-19 04:15:59,536 WARNING  awx.main.commands.run_callback_receiver scaling up worker pid:2400
Sep 19 14:15:59 hostname.domain.local scl[2278]: 2019-09-19 04:15:59,536 WARNING  awx.main.commands.run_callback_receiver scaling up worker pid:2400
Sep 19 14:15:59 hostname.domain.local scl[2278]: 2019-09-19 04:15:59,543 WARNING  awx.main.commands.run_callback_receiver scaling up worker pid:2401
Sep 19 14:15:59 hostname.domain.local scl[2278]: 2019-09-19 04:15:59,543 WARNING  awx.main.commands.run_callback_receiver scaling up worker pid:2401
Sep 19 14:15:59 hostname.domain.local scl[2278]: 2019-09-19 04:15:59,550 WARNING  awx.main.commands.run_callback_receiver scaling up worker pid:2402
Sep 19 14:15:59 hostname.domain.local scl[2278]: 2019-09-19 04:15:59,550 WARNING  awx.main.commands.run_callback_receiver scaling up worker pid:2402
Sep 19 14:15:59 hostname.domain.local scl[2278]: 2019-09-19 04:15:59,559 WARNING  awx.main.commands.run_callback_receiver scaling up worker pid:2403
Sep 19 14:15:59 hostname.domain.local scl[2278]: 2019-09-19 04:15:59,559 WARNING  awx.main.commands.run_callback_receiver scaling up worker pid:2403
Sep 19 14:15:59 hostname.domain.local scl[2279]: Traceback (most recent call last):
Sep 19 14:15:59 hostname.domain.local scl[2279]: File "/opt/rh/rh-python36/root/usr/bin/awx-manage", line 11, in <module>
Sep 19 14:15:59 hostname.domain.local scl[2279]: load_entry_point('awx==7.0.0', 'console_scripts', 'awx-manage')()
Sep 19 14:15:59 hostname.domain.local scl[2279]: File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/__init__.py", line 142, in manage
Sep 19 14:15:59 hostname.domain.local scl[2279]: execute_from_command_line(sys.argv)
Sep 19 14:15:59 hostname.domain.local scl[2279]: File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
Sep 19 14:15:59 hostname.domain.local scl[2279]: utility.execute()
Sep 19 14:15:59 hostname.domain.local scl[2279]: File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
Sep 19 14:15:59 hostname.domain.local scl[2279]: self.fetch_command(subcommand).run_from_argv(self.argv)
Sep 19 14:15:59 hostname.domain.local scl[2279]: File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
Sep 19 14:15:59 hostname.domain.local scl[2279]: self.execute(*args, **cmd_options)
Sep 19 14:15:59 hostname.domain.local scl[2279]: File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
Sep 19 14:15:59 hostname.domain.local scl[2279]: output = self.handle(*args, **options)
Sep 19 14:15:59 hostname.domain.local scl[2279]: File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/management/commands/run_dispatcher.py", line 123, in handle
Sep 19 14:15:59 hostname.domain.local scl[2279]: reaper.reap()
Sep 19 14:15:59 hostname.domain.local scl[2279]: File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/dispatch/reaper.py", line 36, in reap
Sep 19 14:15:59 hostname.domain.local scl[2279]: me = instance or Instance.objects.me()
Sep 19 14:15:59 hostname.domain.local scl[2279]: File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/managers.py", line 116, in me
Sep 19 14:15:59 hostname.domain.local scl[2279]: raise RuntimeError("No instance found with the current cluster host id")
Sep 19 14:15:59 hostname.domain.local scl[2279]: RuntimeError: No instance found with the current cluster host id
Sep 19 14:15:59 hostname.domain.local scl[2281]: 2019-09-19 04:15:59,786 - INFO - runworker - Using single-threaded worker.
Sep 19 14:15:59 hostname.domain.local scl[2281]: 2019-09-19 04:15:59,786 - INFO - runworker - Running worker against channel layer default (asgi_amqp.core.AMQPChannelLayer)
Sep 19 14:15:59 hostname.domain.local scl[2281]: 2019-09-19 04:15:59,787 - INFO - worker - Listening on channels websocket.connect, websocket.disconnect, websocket.receive
Sep 19 14:16:00 hostname.domain.local systemd[1]: awx-dispatcher.service: main process exited, code=exited, status=1/FAILURE
Sep 19 14:16:00 hostname.domain.local systemd[1]: Unit awx-dispatcher.service entered failed state.
Sep 19 14:16:00 hostname.domain.local systemd[1]: awx-dispatcher.service failed.
Sep 19 14:16:02 hostname.domain.local systemd[1]: awx-dispatcher.service holdoff time over, scheduling restart.
Sep 19 14:16:02 hostname.domain.local systemd[1]: Stopping AWX channels worker service...
-- Subject: Unit awx-channels-worker.service has begun shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit awx-channels-worker.service has begun shutting down.
Sep 19 14:16:02 hostname.domain.local scl[2278]: 2019-09-19 04:16:02,112 WARNING  awx.main.commands.run_callback_receiver received SIGTERM, stopping
Sep 19 14:16:02 hostname.domain.local scl[2278]: 2019-09-19 04:16:02,112 WARNING  awx.main.commands.run_callback_receiver received SIGTERM, stopping
Sep 19 14:16:02 hostname.domain.local scl[2281]: 2019-09-19 04:16:02,101 - INFO - worker - Shutdown signal received while idle, terminating immediately
Sep 19 14:16:02 hostname.domain.local systemd[1]: Stopped AWX Dispatcher.
-- Subject: Unit awx-dispatcher.service has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit awx-dispatcher.service has finished shutting down.
Sep 19 14:16:02 hostname.domain.local systemd[1]: Stopping AWX cbreceiver service...
-- Subject: Unit awx-cbreceiver.service has begun shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit awx-cbreceiver.service has begun shutting down.
Sep 19 14:16:02 hostname.domain.local systemd[1]: Stopping AWX web service...
-- Subject: Unit awx-web.service has begun shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit awx-web.service has begun shutting down.
Sep 19 14:16:02 hostname.domain.local systemd[1]: Stopping AWX daphne service...
-- Subject: Unit awx-daphne.service has begun shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit awx-daphne.service has begun shutting down.
Sep 19 14:16:02 hostname.domain.local systemd[1]: Stopped AWX channels worker service.
-- Subject: Unit awx-channels-worker.service has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit awx-channels-worker.service has finished shutting down.
Sep 19 14:16:02 hostname.domain.local systemd[1]: Stopped AWX cbreceiver service.
-- Subject: Unit awx-cbreceiver.service has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit awx-cbreceiver.service has finished shutting down.
Sep 19 14:16:03 hostname.domain.local systemd[1]: Stopped AWX web service.
-- Subject: Unit awx-web.service has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit awx-web.service has finished shutting down.
Sep 19 14:16:03 hostname.domain.local systemd[1]: Stopped AWX daphne service.
-- Subject: Unit awx-daphne.service has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit awx-daphne.service has finished shutting down.
Sep 19 14:16:03 hostname.domain.local systemd[1]: Stopped Application.
-- Subject: Unit awx.service has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit awx.service has finished shutting down.
Sep 19 14:16:03 hostname.domain.local systemd[1]: Stopping Application...
-- Subject: Unit awx.service has begun shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit awx.service has begun shutting down.
Sep 19 14:16:03 hostname.domain.local systemd[1]: Starting Application...
-- Subject: Unit awx.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit awx.service has begun starting up.
Sep 19 14:16:03 hostname.domain.local systemd[1]: Started Application.
-- Subject: Unit awx.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit awx.service has finished starting up.
--
-- The start-up result is done.
Sep 19 14:16:03 hostname.domain.local systemd[1]: Started AWX web service.
-- Subject: Unit awx-web.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit awx-web.service has finished starting up.
--
-- The start-up result is done.
Sep 19 14:16:03 hostname.domain.local systemd[1]: Started AWX cbreceiver service.
-- Subject: Unit awx-cbreceiver.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit awx-cbreceiver.service has finished starting up.
--
-- The start-up result is done.
Sep 19 14:16:03 hostname.domain.local systemd[1]: Started AWX Dispatcher.
-- Subject: Unit awx-dispatcher.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit awx-dispatcher.service has finished starting up.
--
-- The start-up result is done.
Sep 19 14:16:03 hostname.domain.local systemd[1]: Started AWX channels worker service.
-- Subject: Unit awx-channels-worker.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit awx-channels-worker.service has finished starting up.
--
-- The start-up result is done.
Sep 19 14:16:03 hostname.domain.local systemd[1]: Started AWX daphne service.
-- Subject: Unit awx-daphne.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit awx-daphne.service has finished starting up.
``

Has anyone seen similar issues, or have a workaround/solution?

Thanks

Version:

ansible-awx-7.0.0.173-1.el7.x86_64

**Comment by GIT-448482** [comment]
I discovered that if I re-run the initial configuration of AWX, then the GUI becomes stable and usable.

``
echo "from django.contrib.auth.models import User; User.objects.create_superuser('admin', 'root@localhost', 'password')" | sudo -u awx scl enable rh-python36 rh-postgresql10 "GIT_PYTHON_REFRESH=quiet awx-manage shell"
sudo -u awx scl enable rh-python36 rh-postgresql10 rh-git29 "GIT_PYTHON_REFRESH=quiet awx-manage create_preload_data" # Optional Sample Configuration
sudo -u awx scl enable rh-python36 rh-postgresql10 rh-git29 "GIT_PYTHON_REFRESH=quiet awx-manage provision_instance --hostname=$(hostname)"
sudo -u awx scl enable rh-python36 rh-postgresql10 rh-git29 "GIT_PYTHON_REFRESH=quiet awx-manage register_queue --queuename=tower --hostnames=$(hostname)"

``

**Comment by MrMEEE** [comment]
Yes, you need to reregister the server if you rename it.. (And remove the old instance)

**Comment by gpavinteractiv** [comment]
I'm hitting the same problem, could you elaborate on how to re-register the server?

````awx-manage list_instances````  is showing the old hostname

**Comment by gpavinteractiv** [comment]
I manage to make it work 
I did : 
```` 
$awx-manage provision_instance --hostname new_hosname

$ awx-manage list_instances
[tower capacity=0]
	old_hotname capacity=0 version=9.0.1

[ungrouped capacity=0]
	new_hosname capacity=0 version=?

$awx-manage deprovision_instance --hostname old_hotname 

$awx-manage set_default_site --system-fqdn

$awx-manage list_instances
[tower capacity=0]

[ungrouped capacity=57]
	new_hosname capacity=57 version=9.0.1 heartbeat="2020-01-30 17:05:50"

$ awx-manage register_queue --queuename=tower --instance_percent=100
Instance Group already registered tower
(changed: True)

$ awx-manage list_instances
[tower capacity=57 policy=100%]
	new_hostname capacity=57 version=9.0.1 heartbeat="2020-01-30 17:28:11"
````

I can now connect to awx, and jobs are running 
Did I miss anything?
