### ISSUE TITLE
mrmeee-awx-epel-7.repo not found

### ISSUE THREAD

**Issue by lubry** [MrMEEE/awx-build#157]
Hi Please help.

Base link reference: https://github.com/MrMEEE/awx-build/blob/1aec216f04632b22415b9809920d098e950887c2/install-guide-v2.md

File mrmeee-awx-epel-7.repo not found

Output command bellow:
```
[root@localhost ~]# wget -O /etc/yum.repos.d/awx-rpm.repo https://copr.fedorainfracloud.org/coprs/mrmeee/awx/repo/epel-7/mrmeee-awx-epel-7.repo
--2019-09-23 22:42:29--  https://copr.fedorainfracloud.org/coprs/mrmeee/awx/repo/epel-7/mrmeee-awx-epel-7.repo
Resolving copr.fedorainfracloud.org (copr.fedorainfracloud.org)... 209.132.184.54
Connecting to copr.fedorainfracloud.org (copr.fedorainfracloud.org)|209.132.184.54|:443... connected.
HTTP request sent, awaiting response... 404 NOT FOUND
2019-09-23 22:42:31 ERROR 404: NOT FOUND.

[root@localhost ~]#
```

Thanks.

**Comment by MrMEEE** [comment]
https://copr.fedorainfracloud.org/coprs/mrmeee/ansible-awx/repo/epel-7/mrmeee-ansible-awx-epel-7.repo

**Comment by lubry** [comment]
Thank you @MrMEEE

**Comment by MrMEEE** [comment]
Do not use the Installation guide in the git repo...

Use this instead:

https://www.awx.wiki/installation
