### ISSUE TITLE
Retrieve old builds to test upgrade path

### ISSUE THREAD

**Issue by ldouchy** [MrMEEE/awx-build#158]
Hi,

This is not really an issue more a feature request but I'm not sure where to register it.

Is there a way to retrieve olds builds versions? Some sort of repository for deprecated versions for example.

Our use case: 
The repository https://copr-be.cloud.fedoraproject.org/results/mrmeee/ansible-awx/epel-7-$basearch/ seems to be aggressively purged from older builds, this prevent us to install older version to train on upgrade path before going for the production machine.

Best regards,
Laurent.

**Comment by MrMEEE** [comment]
Hi

This is something I can definitely provide.. unfortunately the COPR repo doesn't allow it.. so I will have to do a separate repo.. 

I will do this soon..

**Comment by christophe2049** [comment]
> 
> 
> Hi,
> 
> This is not really an issue more a feature request but I'm not sure where to register it.
> 
> Is there a way to retrieve olds builds versions? Some sort of repository for deprecated versions for example.
> 
> Our use case:
> The repository https://copr-be.cloud.fedoraproject.org/results/mrmeee/ansible-awx/epel-7-$basearch/ seems to be aggressively purged from older builds, this prevent us to install older version to train on upgrade path before going for the production machine.
> 
> Best regards,
> Laurent.

Hi , I've got a similar issue: I need to upgrade awx rpm 5 to awx rpm 7 but since version 6 is no longer on repo , i can't upgrade it without issues
Thank you

**Comment by MrMEEE** [comment]
Hi @christophe2049 and @ldouchy 

The complete history of rpms are now available at:

https://awx.wiki/repository/

A repo file can be downloaded here: 

https://awx.wiki/repository/ansible-awx-nogpg.repo

Please notice that these files are NOT GPG signed.. might get to it in time..

**Comment by ldouchy** [comment]
Great! Thanks a lot.
