### ISSUE TITLE
Jobs fail due to "project_update failed for git* with ID *"

### ISSUE THREAD

**Issue by franzcisco** [MrMEEE/awx-build#159]
Hi,

I've been running awx on a lab environment without any issue for some time (at least a couple of months). As of yesterday, multiple jobs are failing (same jobs some times finish OK and other times fail).
When the job fails the error is always the same: "project_update failed for <my_git> with ID xxx", so actually the playbooks do not even start.

If I check the project, I do get an occasional fault also on this one if I try to update it, and for the git project the error is: 
"Too many open files: '/var/lib/awx/projects/tmpohgek40b'"

I guess this error message makes sense with what I see on the VM (via ssh):
[devnet@vmw-devnet-awx ~]$ cat /proc/sys/fs/file-nr
7072    0       381749

I believe that this is the root cause for the failing jobs.

So... my question is: did someone else run into such issue?
I guess all will start to work fine again if I reboot my AWX Virtual Machine, but I wonder if there might be a workaround to close these "opened files". If needed I can attach logs/screenshots.

Thanks and Regards,

Franz

![image](https://user-images.githubusercontent.com/6647453/65588079-2ff9f480-df87-11e9-9285-c96ff3fd8210.png)

![image](https://user-images.githubusercontent.com/6647453/65588154-4b64ff80-df87-11e9-81c9-75d39bfa3e19.png)

**Comment by MrMEEE** [comment]
https://github.com/MrMEEE/awx-build/issues/163

Might be related.. could you try the fix suggested?

**Comment by MrMEEE** [comment]
Project has been updated and moved...

Please move to the new version and report any issues

PROJECT MOVED: https://github.com/miracle-as/AWX-RPM

Issues at: https://github.com/miracle-as/AWX-RPM/issues

**Install guide, tools, utilities are located at: https://awx.wiki

**LinkedIn group for Questions, support, talk and more: https://www.linkedin.com/groups/13694893/**
