### ISSUE TITLE
CentOS 8 support

### ISSUE THREAD

**Issue by bigHosting** [MrMEEE/awx-build#164]
Hi,

Are there any plans to support CentOS 8 ?
Thanks

**Comment by MrMEEE** [comment]
Hi

I simply think that there are currently too many issues with CentOS 8, and it will be double work to maintain both, as I will have to move to application streams/modules..

My plan is to have something ready around CentOS 8.1..

**Comment by bigHosting** [comment]
Thank you! Much appreciated

**Comment by MrMEEE** [comment]
I will keep this open for tracking :)

**Comment by riahc3** [comment]
I tried to install using CentOS 8 for laughs but yeah, things are currently way too broken to even attempt it.

One day :)

**Comment by gripenk** [comment]
CentOS 8.1 is out.  May I know if there is any progress? I really want to run awx on standalone CentOS 8. 
Thx

**Comment by MrMEEE** [comment]
Hi

I'm still doing the redesign of the dependency building.. Haven't got so much time these days, but hope to get around to it sooner rather than later..

**Comment by MrMEEE** [comment]
Project has been updated and moved...

Please move to the new version and report any issues

PROJECT MOVED: https://github.com/miracle-as/AWX-RPM

Issues at: https://github.com/miracle-as/AWX-RPM/issues

**Install guide, tools, utilities are located at: https://awx.wiki

**LinkedIn group for Questions, support, talk and more: https://www.linkedin.com/groups/13694893/**
