### ISSUE TITLE
Missing awxkit 

### ISSUE THREAD

**Issue by tjyang** [MrMEEE/awx-build#165]
Hi 
awx-cli look interesting. Can you include this tool ? 
* awxkit is not in ansible-awx-7.0.599 rpm
[me@awx01 ~]$ rpm -qil ansible-awx |egrep 'awxkit|cli|Version'
Version     : 7.0.0.599
/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/migrations/0046_v330_remove_client_credentials_grant.py
/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/migrations/__pycache__/0046_v330_remove_client_credentials_grant.cpython-36.pyc
/usr/share/doc/awx/azure-cli-core.txt
/usr/share/doc/awx/azure-cli-nspkg.txt
/usr/share/doc/awx/ip-associations-python-novaclient-ext
/usr/share/doc/awx/ncclient.txt
/usr/share/doc/awx/prometheus-client.txt
/usr/share/doc/awx/slackclient.txt
/usr/share/doc/awx/websocket-client.txt
[me@awx01 ~]$

**Comment by MrMEEE** [comment]
It's actually already there:
[root@akiva ~]# rpm -aq |grep tower
rh-python36-ansible-tower-cli-3.3.6-1.noarch
[root@akiva ~]# sudo -u awx scl enable rh-postgresql10 rh-python36 rh-git29 "tower-cli"

**Comment by tjyang** [comment]
Hi @MrMEEE 

I was referring to [awx-cli one, not tower-cli](https://groups.google.com/forum/?hl=en#!topic/awx-project/ZAlhpLMBzVw)

**Comment by MrMEEE** [comment]
Project has been updated and moved...

Please move to the new version and report any issues

PROJECT MOVED: https://github.com/miracle-as/AWX-RPM

Issues at: https://github.com/miracle-as/AWX-RPM/issues

**Install guide, tools, utilities are located at: https://awx.wiki

**LinkedIn group for Questions, support, talk and more: https://www.linkedin.com/groups/13694893/**
