### ISSUE TITLE
Cannot see all playbooks in directory

### ISSUE THREAD

**Issue by riahc3** [MrMEEE/awx-build#166]
I have a strange issue happening.

I build the structure using: 

ansible-galaxy init test-role-1

But, it only gets me the test.yml

While in tasks, I have a whole bunch of playbooks (including one called main.yml)

If I copy it out and put it on the root, awx-rpm does seem them so it isnt a syntax error....

Ive checked permissions and they are good as well.

So, why doesnt awx-rpm see all the playbooks?

Thanks

**Comment by riahc3** [comment]
Ive gone a step further:

Ive made a new project directing pointing to that directory. It shows me the test.yml and a main.yml but it didnt show me the main.yml it was talking about so I went ahead and renamed all the main.yml  .....and it still shows me there is a main.yml !!

**Comment by MrMEEE** [comment]
Where have you created the project dir?

**Comment by riahc3** [comment]
That would be in:

/var/lib/awx/projects

**Comment by MrMEEE** [comment]
Project has been updated and moved...

Please move to the new version and report any issues

PROJECT MOVED: https://github.com/miracle-as/AWX-RPM

Issues at: https://github.com/miracle-as/AWX-RPM/issues

**Install guide, tools, utilities are located at: https://awx.wiki

**LinkedIn group for Questions, support, talk and more: https://www.linkedin.com/groups/13694893/**
