### ISSUE TITLE
Device or resource busy

### ISSUE THREAD

**Issue by EdHunter87** [MrMEEE/awx-build#168]
I am getting the following error after a job is run: 

```File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/ansible_runner/runner.py", line 253, in _delete shutil.rmtree(self.config.process_isolation_path_actual) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 480, in rmtree _rmtree_safe_fd(fd, path, onerror) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 418, in _rmtree_safe_fd _rmtree_safe_fd(dirfd, fullname, onerror) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 422, in _rmtree_safe_fd onerror(os.rmdir, fullname, sys.exc_info()) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 420, in _rmtree_safe_fd os.rmdir(name, dir_fd=topfd) OSError: [Errno 16] Device or resource busy: 'awx_31_adcaobht'```

I am able to delete the files manually, and I tried running the job with escalated privileges.

**Comment by MrMEEE** [comment]
Have you seen this?
https://github.com/MrMEEE/awx-build/issues/163

**Comment by EdHunter87** [comment]
Updating the timeout to 10 seconds worked. I will have to do better searching next time. 

Thanks for the help.

Awesome job by the way.
