### ISSUE TITLE
Every time a service awx restarted, resource temporarily unavailable "beat.db".

### ISSUE THREAD

**Issue by marcosshpak** [MrMEEE/awx-build#169]
Hello,
I have been following the project for a long time and have never come across this error, whenever I restart the awx service, this message appears in the system log.
NOTE: this does not prevent the service from working.

awx-el7 scl: 2019-10-17 11:41:45,136 ERROR    celery.beat Removing corrupted schedule file '/var/lib/awx/beat.db': error(11, 'Resource temporarily unavailable')
awx-el7 scl: Traceback (most recent call last):
awx-el7 scl: File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/beat.py", line 485, in setup_schedule
awx-el7 scl: self._store = self._open_schedule()
awx-el7 scl: File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/beat.py", line 475, in _open_schedule
awx-el7 scl: return self.persistence.open(self.schedule_filename, writeback=True)
awx-el7 scl: File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shelve.py", line 243, in open
awx-el7 scl: return DbfilenameShelf(filename, flag, protocol, writeback)
awx-el7 scl: File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shelve.py", line 227, in __init__
awx-el7 scl: Shelf.__init__(self, dbm.open(filename, flag), protocol, writeback)
awx-el7 scl: File "/opt/rh/rh-python36/root/usr/lib64/python3.6/dbm/__init__.py", line 94, in open
awx-el7 scl: return mod.open(file, flag, mode)
awx-el7 scl: _gdbm.error: [Errno 11] Resource temporarily unavailable

**Comment by MrMEEE** [comment]
This is a race-condition.. the Celery beat client starts sending requests before the server is up.. 

These requests will be resend when the server is up.. 

Shouldn't have any influence on the service (as you mention), but would be nice to fix this in the systemd service files (probably have to put in some waits)..

Will keep this open as a reminder

**Comment by angystardust** [comment]
Fixed in https://github.com/ansible/awx/pull/5200

**Comment by MrMEEE** [comment]
Project has been updated and moved...

Please move to the new version and report any issues

PROJECT MOVED: https://github.com/miracle-as/AWX-RPM

Issues at: https://github.com/miracle-as/AWX-RPM/issues

**Install guide, tools, utilities are located at: https://awx.wiki

**LinkedIn group for Questions, support, talk and more: https://www.linkedin.com/groups/13694893/**
