### ISSUE TITLE
Broken Upgrade

### ISSUE THREAD

**Issue by 6sossomons** [MrMEEE/awx-build#171]
Upgraded and continued to get issues with loading the inventory sources (Get error)...

I followed the instructions here:
https://awx.wiki/upgrade/standard-upgrade-method

Stupidity ensued, errors in starting, and uswgi didn't install..

The steps:
systemctl stop awx
yum -y remove rh-python36*
yum -y install rh-python36 ansible-awx

**Should be changed to:**
systemctl stop awx
yum -y remove rh-python36*
yum clean all
rm -rf /var/cache/yum
rm -rf /opt/rh-rh-python36

yum -y install rh-python36
yum -y install --disablerepo='*' --enablerepo='copr:copr.fedorainfracloud.org:mrmeee:ansible-awx, rhel-7-server-rpms' -x *-debuginfo ansible-awx rh-python36*
sudo -u awx scl enable rh-postgresql10 rh-python36 rh-git29 "GIT_PYTHON_REFRESH=quiet awx-manage makemigrations"
sudo -u awx scl enable rh-postgresql10 rh-python36 rh-git29 "GIT_PYTHON_REFRESH=quiet awx-manage migrate"
systemctl restart awx

While definitely more contrived, these steps work to solve out the requirements and stay in-line with the original install/upgrade instructions.

**Comment by MrMEEE** [comment]
Hi

From which version and to which version did you upgrade?

**Comment by 6sossomons** [comment]
I first upgraded from ansible-awx-4.0.0.490-1.el7.x86_64 to ansible-awx-7.0.0.329-1.el7.x86_64

The upgrade went smoothly, however the system had many issues in review sources for inventory and other weird /api/v2/<multiple>/.GET server errors.  When I go further into them, it was tied to a json errors with django.  Removing and destroying the /opt/rh/rh-python36 was the ONLY way to clean them out entirely from happening.  Not sure if that is a step you want to add into the removal, but it definitely was needed to go from ansible-awx-3.0.1.309-1.el7.x86_64 (My original install base) to working clean in ansible-awx-7.0.0.329-1.el7.x86_64.

BTW, I did update my original comment/steps as well, as they now handle the removal of the directory and the migration commands.

**Comment by MrMEEE** [comment]
Did you follow the instructions here:
https://awx.wiki/upgrade/workarounds

??

**Comment by 6sossomons** [comment]
No, there wasn't one that matched the whole jump process, those looked more like minor to shifts, not a vast jump like I performed...  Maybe a new "workarounds" section or caveat in that if jumping major versions, do a the steps above.

**Comment by MrMEEE** [comment]
Basically, if jumping multiple version, you have to implement all the special cases in between
