### ISSUE TITLE
SSL and port 80 as default

### ISSUE THREAD

**Issue by MrMEEE** [MrMEEE/awx-build#172]
move default port to 80 and enable SSL

**Comment by Dofamin** [comment]
You can remove this portion as well, it purpose only for redirection. In my case, it was from http 80 to 443 https.
```
server {
    listen 443 default_server;

    server_name _;

    return 301 https://$host$request_uri;
}
```

**Comment by MrMEEE** [comment]
Project has been updated and moved...

Please move to the new version and report any issues

PROJECT MOVED: https://github.com/miracle-as/AWX-RPM

Issues at: https://github.com/miracle-as/AWX-RPM/issues

**Install guide, tools, utilities are located at: https://awx.wiki

**LinkedIn group for Questions, support, talk and more: https://www.linkedin.com/groups/13694893/**
