### ISSUE TITLE
Instance Capacity display page

### ISSUE THREAD

**Issue by EdHunter87** [MrMEEE/awx-build#175]
When looking at the Instance Groups > Tower > Instances page I am seeing the following. 

![Screen Shot 2019-10-23 at 9 28 59 AM](https://user-images.githubusercontent.com/32676311/67403629-d382f880-f577-11e9-85bf-8580b28a645c.png)

I am running the new AWX 8.0.0 release, was on 7.0.0, prior to upgrading and saw the same thing. 

Any idea how I can change update to make the forks, and used capacity show correctly?

Thanks.

**Comment by MrMEEE** [comment]
I'm pretty sure that this is because the capasity is related to the subscriptions in Ansible Tower.. And here you have unlimited or maybe zero subscription..

**Comment by EdHunter87** [comment]
I was referring to the way the page renders. For some reason the sliders are really small, and the used capacity are not shown in full.

**Comment by MrMEEE** [comment]
hmmm.. 

Looks good here on the 9 series?

![capacity](https://user-images.githubusercontent.com/768031/71700828-58835d00-2dc6-11ea-9562-c99856af2349.png)

**Comment by EdHunter87** [comment]
Hey @MrMEEE I just upgraded to the latest version and everything looks good. I will close this case. 

Thanks
