### ISSUE TITLE
roles/requirements.yml not found

### ISSUE THREAD

**Issue by dolgovas** [MrMEEE/awx-build#178]
When pull project from git.
playbook `project_update.yml` placed in `/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/playbooks/`
not found `roles/requirements.yml`
But if i comment condition `when: roles_enabled|bool` it work well

switcher in `settings->jobs` is turn ON.

**Comment by MrMEEE** [comment]
I don't really get it.. can you tell more??

**Comment by dolgovas** [comment]
Ok, sure
I have a couple of repos with ansible projects...
`repo1` - have only roles and file `meta/main.yml`
`repo2` - have inventory files, group(host)vars and `playbooks.yml` files

example of playbook.yaml:
```
   ---
   - hosts:
       - all
     roles:
       - repo1/install-prometheus
```
role `install-prometheus` placed in repo1.
in `repo2` i have file `roles/requirements.yml`

requirements.yml:
```
src: git+https://gitlab.lan/general.git
```
I expect when i clone repo2 like project from scm-git into AWX. It will be pull depencies from roles/requirements.yml also, but before my fix in `project_update.yml` it was look like this:
```
PLAY [all] *********************************************************************
TASK [detect requirements.yml] *************************************************
skipping: [localhost,] => {"changed": false, "skip_reason": "Conditional result was False"}
TASK [fetch galaxy roles from requirements.yml] ********************************
skipping: [localhost,] => {"changed": false, "skip_reason": "Conditional result was False"}
TASK [detect collections/requirements.yml] *************************************
skipping: [localhost,] => {"changed": false, "skip_reason": "Conditional result was False"}
TASK [fetch galaxy collections from collections/requirements.yml] **************
skipping: [localhost,] => {"changed": false, "skip_reason": "Conditional result was False"}
```
after fix - i have this
```
PLAY [all] *********************************************************************
TASK [detect requirements.yml] *************************************************
ok: [localhost, -> localhost] => {"changed": false, "stat": {"atime": 1572280613.5254962, "attr_flags": "e", "attributes": ["extents"], "block_size": 4096, "blocks": 8, "charset": "us-ascii", "checksum": "28996653fc68eada36304009d101fd47995ce9bd", "ctime": 1572280613.1314974, "dev": 64768, "device_type": 0, "executable": false, "exists": true, "gid": 991, "gr_name": "awx", "inode": 284708, "isblk": false, "ischr": false, "isdir": false, "isfifo": false, "isgid": false, "islnk": false, "isreg": true, "issock": false, "isuid": false, "mimetype": "text/plain", "mode": "0644", "mtime": 1572280613.1314974, "nlink": 1, "path": "/var/lib/awx/projects/_8__repo2/roles/requirements.yml", "pw_name": "awx", "readable": true, "rgrp": true, "roth": true, "rusr": true, "size": 84, "uid": 993, "version": "941894922", "wgrp": false, "woth": false, "writeable": true, "wusr": true, "xgrp": false, "xoth": false, "xusr": false}}
TASK [fetch galaxy roles from requirements.yml] ********************************
changed: [localhost, -> localhost] => {"changed": true, "cmd": ["ansible-galaxy", "install", "-r", "requirements.yml", "-p", ".", "-v"], "delta": "0:00:06.462985", "end": "2019-10-28 16:37:06.600508", "rc": 0, "start": "2019-10-28 16:37:00.137523", "stderr": "", "stderr_lines": [], "stdout": "No config file found; using defaults\n- extracting repo1 to /var/lib/awx/projects/_8_repo2/roles/repo1\n- repo1 was installed successfully", "stdout_lines": ["No config file found; using defaults", "- extracting repo1 to /var/lib/awx/projects/_8__repo2/roles/repo1", "- repo1 was installed successfully"]}
TASK [detect collections/requirements.yml] *************************************
skipping: [localhost,] => {"changed": false, "skip_reason": "Conditional result was False"}
TASK [fetch galaxy collections from collections/requirements.yml] **************
skipping: [localhost,] => {"changed": false, "skip_reason": "Conditional result was False"}
```

**Comment by dolgovas** [comment]
Sorry for my English from google translate )

**Comment by MrMEEE** [comment]
Does this seem like the same error? https://github.com/ansible/awx/issues/1632

**Comment by dolgovas** [comment]
i think - no.
i think that all trouble in incorrect work switch-button 
![изображение](https://user-images.githubusercontent.com/43605609/67749647-a2566c80-fa3e-11e9-9f20-4bf6ff865a93.png)
i think that when button turn on, variable `roles_enabled` must be `true`, but it is `false`

https://github.com/ansible/awx/issues/1632 have many comments (like this https://github.com/ansible/awx/issues/1632#issuecomment-545064169) that have same problem like me. But the ticket itself about other problem

**Comment by ghost** [comment]
I have tried versions 7, 8 and 9 and roles/requirements.yml is not being detected by AWX the last version that does work is 6.1

`
TASK [detect requirements.yml] *************************************************
skipping: [localhost,] => {"changed": false, "skip_reason": "Conditional result was False"}
TASK [fetch galaxy roles from requirements.yml] ********************************
skipping: [localhost,] => {"changed": false, "skip_reason": "Conditional result was False"}
TASK [detect collections/requirements.yml] *************************************
skipping: [localhost,] => {"changed": false, "skip_reason": "Conditional result was False"}
`

`
 $ ll
 total 64
 -rw-r--r--  1 user  staff    72B Nov 13 15:23 ansible.cfg 
 drwxr-xr-x  3 user  staff    96B Nov 13 13:36 environments
 -rw-r--r--  1 user  staff   152B Nov 13 16:33 install_atlantis.yml
 -rw-r--r--  1 user  staff   587B Nov 13 16:32 install_clouds.yml 
 drwxr-xr-x  3 user  staff    96B Nov 13 15:15 roles
 -rw-r--r--  1 user  staff   154B Nov 13 15:05 setup-atlantis.yml
  
 $ ls roles/
 requirements.yml

 $ cat roles/requirements.yml
 - src: https://artifactory.dev.com/artifactory/generic-ansible-roles/atlantis-0.1.0.tgz
   name: atlantis
`

**Comment by christianhuth** [comment]
I can confirm this issue with awx v.9.0.1.

**Comment by dolgovas** [comment]
I have installed AWX v.9.0.1
![изображение](https://user-images.githubusercontent.com/43605609/70905437-e7e1ef80-2014-11ea-960e-4174d091896b.png)
And fetch from roles/requirements.yml now work fine.
After clone project i can use roles from requirements.yml

But awx clone roles in temp directory )
