### ISSUE TITLE
`roles_destination: variable is not defined` when use roles/requirements.yml

### ISSUE THREAD

**Issue by dolgovas** [MrMEEE/awx-build#179]
To fix this bug i make some changes:
`{{roles_destination|quote}} -> {{roles_destination|default('.')|quote}}`

**Comment by MrMEEE** [comment]
A fix is on the way... https://github.com/ansible/awx/pull/5078

**Comment by dolgovas** [comment]
i was update soon to 
```# rpm -qa|grep awx
ansible-awx-9.0.1.2-1.el7.x86_64
```

but https://github.com/ansible/awx/pull/5078 is closed

but trouble not going...
