### ISSUE TITLE
Configure AWX - Import Database data Problem

### ISSUE THREAD

**Issue by cddisk2000** [MrMEEE/awx-build#181]
Using the system: CentOS 7 1908 
uses the command "sudo -u awx scl enable rh-python36 rh-postgresql10 "awx-manage migrate""
Python will instruction error。

![image](https://user-images.githubusercontent.com/32296520/68058878-6b7da080-fd35-11e9-89f8-4cea5e72d158.png)

I found another way can be completed Proceed as follows

su - awx

scl enable rh-python36 rh-postgresql10 "/opt/rh/rh-python36/root/usr/bin/awx-manage migrate"

scl enable rh-python36 rh-postgresql10 "/opt/rh/rh-python36/root/usr/bin/awx-manage shell"

from django.contrib.auth.models import User; User.objects.create_superuser('admin', 'root@localhost', 'password')

I hope I can help have this problem friend

**Comment by MrMEEE** [comment]
Project has been updated and moved...

Please move to the new version and report any issues

PROJECT MOVED: https://github.com/miracle-as/AWX-RPM

Issues at: https://github.com/miracle-as/AWX-RPM/issues

**Install guide, tools, utilities are located at: https://awx.wiki

**LinkedIn group for Questions, support, talk and more: https://www.linkedin.com/groups/13694893/**
