### ISSUE TITLE
Failure to sync new satellite6 repo

### ISSUE THREAD

**Issue by sredmo01bsc** [MrMEEE/awx-build#182]
I am having an issue when trying to sync a new inventory from satellite 6 server.  Please forgive my python ignorance, I believe the following are the important errors from the failed job.
RuntimeError: ansible-inventory failed (rc=1) with stdout:
stderr:
ansible-inventory 2.9.0
  config file = None
  configured module search path = ['/var/lib/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/rh/rh-python36/root/lib/python3.6/site-packages/ansible
  executable location = /opt/rh/rh-python36/root/bin/ansible-inventory
  python version = 3.6.3 (default, Apr 10 2019, 14:37:36) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
No config file found; using defaults
[WARNING]:  * Failed to parse /opt/rh/rh-python36/root/usr/lib/python3.6/site-
packages/awx/plugins/inventory/foreman.py with script plugin: Inventory script
(/opt/rh/rh-python36/root/usr/lib/python3.6/site-
packages/awx/plugins/inventory/foreman.py) had an execution error: /opt/rh/rh-
python36/root/lib/python3.6/site-packages/urllib3/connectionpool.py:1004:
InsecureRequestWarning: Unverified HTTPS request is being made. Adding
certificate verification is strongly advised. See:
https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
InsecureRequestWarning, /opt/rh/rh-python36/root/lib/python3.6/site-
packages/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified
HTTPS request is being made. Adding certificate verification is strongly
advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-
warnings   InsecureRequestWarning, /opt/rh/rh-python36/root/lib/python3.6/site
......
HTTPError(http_error_msg, response=self) requests.exceptions.HTTPError: 500
Server Error: Internal Server Error for url:
https://uinf901p.bsc.bscal.com/api/v2/hosts/1409?per_page=250&page=1
  File "/opt/rh/rh-python36/root/lib/python3.6/site-packages/ansible/inventory/manager.py", line 280, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/opt/rh/rh-python36/root/lib/python3.6/site-packages/ansible/plugins/inventory/script.py", line 161, in parse
    raise AnsibleParserError(to_native(e))
[WARNING]: Unable to parse /opt/rh/rh-python36/root/usr/lib/python3.6/site-
packages/awx/plugins/inventory/foreman.py as an inventory source
ERROR! No inventory was parsed, please check your configuration and options.

This url returns an error
https://uinf901p.bsc.bscal.com/api/v2/hosts/1409?per_page=250&page=1

{
  "error": {"message":"undefined method `split' for nil:NilClass"}
}

**Comment by sredmo01bsc** [comment]
If I update the url to a higher host number it appears to work, is there a limit to number of hosts?
https://uinf901p.bsc.bscal.com/api/v2/hosts/2600?per_page=250&page=1

**Comment by MrMEEE** [comment]
Project has been updated and moved...

Please move to the new version and report any issues

PROJECT MOVED: https://github.com/miracle-as/AWX-RPM

Issues at: https://github.com/miracle-as/AWX-RPM/issues

**Install guide, tools, utilities are located at: https://awx.wiki

**LinkedIn group for Questions, support, talk and more: https://www.linkedin.com/groups/13694893/**
