### ISSUE TITLE
"ruby" is not recognized as an internal or external command on Window Hosts

### ISSUE THREAD

**Issue by MrSaintJCode** [MrMEEE/awx-build#185]
Hello,

 Hopefully you guys can help me here. We have two version of Ansible AWX, one with docker and one without. The one with docker works flawlessly which makes me believe that this has to be a bug with how the one without was configured or installed. (Followed the steps on awx.wiki) This error doesn't seem to happen on all Windows hosts, just a select few.

`
{
    "ansible_facts": {},
    "msg": "The following modules failed to execute: setup\n",
    "failed_modules": {
        "setup": {
            "exception": "'ruby' is not recognized as an internal or external command,\r\nAt line:243 char:9\r\n+         &facter -j | Tee-Object  -Variable facter_output > $null\r\n+         ~~~~~~~~~~\r\n    + CategoryInfo          : NotSpecified: ('ruby' is not r...ternal command,:String) [], RemoteException\r\n    + FullyQualifiedErrorId : NativeCommandError\r\n\r\nScriptStackTrace:\r\nat <ScriptBlock>, <No file>: line 243\r\n",
            "msg": "Unhandled exception while executing module: 'ruby' is not recognized as an internal or external command,",
            "failed": true
        }
    },
    "_ansible_verbose_override": true,
    "_ansible_no_log": false,
    "changed": false
}
` 

 I've tried reinstalling Ruby, updating to a new version which is now ruby 2.6.1p33. Double checked our GPO setting, doesn't seem to be anything related to WinRM as it works on the docker version.

Any help will be much appreciated. Let me know if you need anymore information 👍

**Comment by MrMEEE** [comment]
Project has been updated and moved...

Please move to the new version and report any issues

PROJECT MOVED: https://github.com/miracle-as/AWX-RPM

Issues at: https://github.com/miracle-as/AWX-RPM/issues

**Install guide, tools, utilities are located at: https://awx.wiki

**LinkedIn group for Questions, support, talk and more: https://www.linkedin.com/groups/13694893/**
