### ISSUE TITLE
Linkedin is not a valid forum, for, well anything.

### ISSUE THREAD

**Issue by fake-name** [MrMEEE/awx-build#191]
Linkedin is a creepy, scammy site, and you cannot access anything there without a account, which I refuse to make because they require too much personal information.

Could you folks maybe use a forum host that's not actively horrible?

------

TL;DR No, I don't want to be a part of your professional network.

**Comment by MrMEEE** [comment]
Well.. I think the LinkedIn group works great for what it is.. along with awx.wiki and this bugtracking, I think everyone should be covered..
