### ISSUE TITLE
unable to log in

### ISSUE THREAD

**Issue by eseyman** [MrMEEE/awx-build#197]
I've installed AWX-RPM trying to stick to the instructions as much as possible but I'm unable to log to the web interface. I'ld appreciate any help in trying to figure out what went. Attached is the relevant part of the log.
[web.log](https://github.com/MrMEEE/awx-build/files/3984359/web.log)

**Comment by MrMEEE** [comment]
Looks like you are missing some dependencies or are using some old packages..

Are you running RHEL7 or CentOS7??

**Comment by eseyman** [comment]
I'm running RHEL7. Since opening the issue, I've realized that xmlsec1 is provided by several repos in an incomplete state. Enabling the rhel7_optional repo allowed me to update xmlsec1 to 1.2.20 but I'm now hitting an upgrade error in awx.

Jan 17 09:13:08 ehls1nfr scl[28942]: Traceback (most recent call last):
Jan 17 09:13:08 ehls1nfr scl[28942]: File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
Jan 17 09:13:08 ehls1nfr scl[28942]: return self.cursor.execute(sql, params)
Jan 17 09:13:08 ehls1nfr scl[28942]: psycopg2.errors.UndefinedColumn: column main_unifiedjob.canceled_on does not exist
Jan 17 09:13:08 ehls1nfr scl[28942]: LINE 1: ...fiedjob"."started", "main_unifiedjob"."finished", "main_unif...
Jan 17 09:13:08 ehls1nfr scl[28942]: ^
Jan 17 09:13:08 ehls1nfr scl[28942]: The above exception was the direct cause of the following exception:
Jan 17 09:13:08 ehls1nfr scl[28942]: Traceback (most recent call last):
Jan 17 09:13:08 ehls1nfr scl[28942]: File "/opt/rh/rh-python36/root/usr/bin/awx-manage", line 11, in <module>
Jan 17 09:13:08 ehls1nfr scl[28942]: load_entry_point('awx==9.1.1', 'console_scripts', 'awx-manage')()

I'm going to scratch that machine, start from scratch and see if I can reproduce this.

**Comment by eseyman** [comment]
Having re-installed from scratch, I now go further along by configuring my yum repos (we have a slightly weird internal setup). Now, configuration fails when I run the command:

sudo -u awx scl enable rh-python36 rh-postgresql10 rh-git29 "GIT_PYTHON_REFRESH=quiet awx-manage register_queue --queuename=tower --hostnames=$(hostname)"

This fails with the error messsage:

Instance Group already registered tower
Instance does not exist: ehls1nfr

And, sure enough, I get the following in the system logs:

Jan 29 16:59:32 ehls1nfr scl[12958]: Traceback (most recent call last):
Jan 29 16:59:32 ehls1nfr scl[12958]: File "/opt/rh/rh-python36/root/usr/bin/awx-manage", line 11, in <module>
Jan 29 16:59:32 ehls1nfr scl[12958]: load_entry_point('awx==9.1.1', 'console_scripts', 'awx-manage')()
Jan 29 16:59:32 ehls1nfr scl[12958]: File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/__init__.py", line 152, in manage
Jan 29 16:59:32 ehls1nfr scl[12958]: execute_from_command_line(sys.argv)
Jan 29 16:59:32 ehls1nfr scl[12958]: File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
Jan 29 16:59:32 ehls1nfr scl[12958]: utility.execute()
Jan 29 16:59:32 ehls1nfr scl[12958]: File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
Jan 29 16:59:32 ehls1nfr scl[12958]: self.fetch_command(subcommand).run_from_argv(self.argv)
Jan 29 16:59:32 ehls1nfr scl[12958]: File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
Jan 29 16:59:32 ehls1nfr scl[12958]: self.execute(*args, **cmd_options)
Jan 29 16:59:32 ehls1nfr scl[12958]: File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
Jan 29 16:59:32 ehls1nfr scl[12958]: output = self.handle(*args, **options)
Jan 29 16:59:32 ehls1nfr scl[12958]: File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/management/commands/run_dispatcher.py", line 123, in handle
Jan 29 16:59:32 ehls1nfr scl[12958]: reaper.reap()
Jan 29 16:59:32 ehls1nfr scl[12958]: File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/dispatch/reaper.py", line 38, in reap
Jan 29 16:59:32 ehls1nfr scl[12958]: (changed, me) = Instance.objects.get_or_register()
Jan 29 16:59:32 ehls1nfr scl[12958]: File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/managers.py", line 134, in get_or_register
Jan 29 16:59:32 ehls1nfr scl[12958]: return (False, self.me())
Jan 29 16:59:32 ehls1nfr scl[12958]: File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/managers.py", line 116, in me
Jan 29 16:59:32 ehls1nfr scl[12958]: raise RuntimeError("No instance found with the current cluster host id")
Jan 29 16:59:32 ehls1nfr scl[12958]: RuntimeError: No instance found with the current cluster host id
Jan 29 16:59:32 ehls1nfr scl[12956]: 2020-01-29 15:59:32,495 - INFO - runworker - Using single-threaded worker.
Jan 29 16:59:32 ehls1nfr scl[12956]: 2020-01-29 15:59:32,495 - INFO - runworker - Running worker against channel layer default (asgi_amqp.core.AMQPChannelLayer)
Jan 29 16:59:32 ehls1nfr scl[12956]: 2020-01-29 15:59:32,496 - INFO - worker - Listening on channels websocket.connect, websocket.disconnect, websocket.receive
Jan 29 16:59:32 ehls1nfr systemd[1]: awx-dispatcher.service: main process exited, code=exited, status=1/FAILURE
Jan 29 16:59:32 ehls1nfr systemd[1]: Unit awx-dispatcher.service entered failed state.
Jan 29 16:59:32 ehls1nfr systemd[1]: awx-dispatcher.service failed.

**Comment by eseyman** [comment]
After a do-over, the commands run fine and I have a working AWX instance.
