### ISSUE TITLE
duplicate instance after change hostname

### ISSUE THREAD

**Issue by dolgovas** [MrMEEE/awx-build#198]
![изображение](https://user-images.githubusercontent.com/43605609/71254979-aff0ea00-233d-11ea-99e6-94fb1b195b41.png)
hello! after changing hostname i found some trouble...
in group_instances i found instance with old hostname (unavailable instance) and instance with h new hostname

this issue crossed with https://github.com/MrMEEE/awx-build/issues/192

**Comment by MrMEEE** [comment]
Something like the below should fix it:
```
sudo -u awx scl enable rh-postgresql10 rh-python36 "GIT_PYTHON_REFRESH=quiet awx-manage deprovision_instance <old_hostname>"
```

**Comment by dolgovas** [comment]
This help for me. Snx
