### ISSUE TITLE
about ssh 

### ISSUE THREAD

**Issue by ypsliu** [MrMEEE/awx-build#199]
PLAY [all] *********************************************************************
[WARNING]: Unhandled error in Python interpreter discovery for host dalian_01:
Failed to connect to the host via ssh: Warning: Permanently added
'192.168.23.86' (ECDSA) to the list of known hosts.  Permission denied
(publickey,gssapi-keyex,gssapi-with-mic,password).
TASK [Gathering Facts] *********************************************************
fatal: [dalian_01]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"192.168.23.86\". Make sure this host can be reached over ssh: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).\r\n", "unreachable": true}
[WARNING]: Unhandled error in Python interpreter discovery for host test_1:
Failed to connect to the host via ssh: Warning: Permanently added
'10.200.22.42' (ECDSA) to the list of known hosts.  Permission denied
(publickey,gssapi-keyex,gssapi-with-mic,password).
fatal: [test_1]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"10.200.22.42\". Make sure this host can be reached over ssh: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).\r\n", "unreachable": true}

**Comment by MrMEEE** [comment]
Can you try to ssh from the AWX server to the servers from the terminal???

**Comment by ypsliu** [comment]
Yes, it ’s weird. I can run it with ansible. I do n’t know why this is the case.

**Comment by ypsliu** [comment]
The configuration is also direct username, password and ping module successfully

**Comment by MrMEEE** [comment]
sure that you have entered the credentials correctly?

**Comment by MrMEEE** [comment]
Project has been updated and moved...

Please move to the new version and report any issues

PROJECT MOVED: https://github.com/miracle-as/AWX-RPM

Issues at: https://github.com/miracle-as/AWX-RPM/issues

**Install guide, tools, utilities are located at: https://awx.wiki

**LinkedIn group for Questions, support, talk and more: https://www.linkedin.com/groups/13694893/**
