### ISSUE TITLE
curl: (35) TCP connection reset by peer and 503 errors

### ISSUE THREAD

**Issue by sammic30** [MrMEEE/awx-build#2]
I'm trying to use AWX with Openstack and while running bootstrap as a adhoc command I'm getting curl: (35) TCP connection reset by peer and 503 errors but when I execute manually directly on the server everything works fine.

on server if I do export http_proxy=http://xyz.com:8080 and export https_proxy=http://xyz.com:8080 than everything is working but from AWX I'm getting errors.

Can we use something like https://github.com/ansible/awx/blob/devel/installer/inventory? If yes, than where I can put it?

# Proxy
#http_proxy=http://proxy:3128
#https_proxy=http://proxy:3128
#no_proxy=mycorp.org

Any suggestion will be appreciated.

**Comment by sammic30** [comment]
FYI,
yum -y install git curl autoconf gcc gcc-c++ nc python2 python2-devel openssl-devel libffi-devel libselinux-python
https://copr-be.cloud.fedoraproject.org/results/mrmeee/awx-dev/epel-7-x86_64/repodata/repomd.xml: [Errno 14] curl#35 - "TCP connection reset by peer"
Trying other mirror.
https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-7-x86_64/repodata/repomd.xml: [Errno 14] curl#35 - "TCP connection reset by peer"
Trying other mirror.

+ curl --silent --show-error --retry 5 https://bootstrap.pypa.io/get-pip.py
curl: (35) TCP connection reset by peer
+ curl --silent --show-error --retry 5 https://raw.githubusercontent.com/pypa/get-pip/master/get-pip.py
curl: (35) TCP connection reset by peer

**Comment by MrMEEE** [comment]
Try to create the file "/etc/sysconfig/awx" with the following content:

http_proxy=http://proxy:3128
https_proxy=http://proxy:3128
no_proxy=mycorp.org

and restart all the services (or reboot).. see if that helps :)

**Comment by sammic30** [comment]
Tried the above solution but still facing the same issue :-(

[awx-centos-v2 ~]# cat /etc/sysconfig/awx

http_proxy=http://xyz.com:8080
https_proxy=http:/xyz.com:8080
no_proxy=localhost,127.0.0.1,0.0.0.0

**Comment by MrMEEE** [comment]
think I misunderstood you the first time, you are getting this issue under the installation, right???

Try putting the proxy lines in /etc/environment and do a logout/login

**Comment by sammic30** [comment]
Thanks, looks like it's resolved now.....
but will run one more test and confirm :)

**Comment by MrMEEE** [comment]
I will close this.. please re-open if this issue is not solved
