### ISSUE TITLE
AWX behind F5 - callback job failure

### ISSUE THREAD

**Issue by mpunix** [MrMEEE/awx-build#201]
Hi,
I have installed awx using RPM method and added F5 for the SSL termination. It seems I can't get the callback job working and seeing nginx status 400 when I issue the curl command in the client.

```
10.124.36.7 - - [07/Jan/2020:14:45:23 +0000] "POST /api/v2/job_templates/365/callback/ HTTP/1.1" 400 42 "-" "curl/7.29.0" "-"
10.122.36.9 - - [07/Jan/2020:14:45:24 +0000] "GET /" 400 3881 "-" "-" "-"
``` 
using nginx.conf one provided in the link https://raw.githubusercontent.com/MrMEEE/awx-build/master/nginx.conf.

I have tried adding the HTTP_X_FORWARDED_FOR in the setting, still no luck.

Anyone come across this before?

**Comment by mpunix** [comment]
Solution is enable Insert X-Forwarded-For in the F5 http profile. It works now.

**Comment by MrMEEE** [comment]
Great.. thanks for the feedback..
