### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by vosetrov-mdlive** [MrMEEE/awx-build#202]
Hello,

I'm trying to create a network interface on Azure, but getting the error. I noticed that runpy.py is running under python 2.7, but the rest of python scripts are running under python 3.6. Any suggestion how to fix the issue?

{
    "module_stdout": "",
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible-tmp-1578420706.8446586-61843903276439/AnsiballZ_azure_rm_networkinterface.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/tmp/ansible-tmp-1578420706.8446586-61843903276439/AnsiballZ_azure_rm_networkinterface.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/tmp/ansible-tmp-1578420706.8446586-61843903276439/AnsiballZ_azure_rm_networkinterface.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.cloud.azure.azure_rm_networkinterface', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python2.7/runpy.py\", line 176, in run_module\n    fname, loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 82, in _run_module_code\n    mod_name, mod_fname, mod_loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/tmp/ansible_azure_rm_networkinterface_payload_CopMPq/ansible_azure_rm_networkinterface_payload.zip/ansible/modules/cloud/azure/azure_rm_networkinterface.py\", line 459, in <module>\n  File \"/opt/rh/rh-python36/root/lib/python3.6/site-packages/msrestazure/__init__.py\", line 28, in <module>\n    from .azure_configuration import AzureConfiguration\n  File \"/opt/rh/rh-python36/root/lib/python3.6/site-packages/msrestazure/azure_configuration.py\", line 34, in <module>\n    from msrest import Configuration\n  File \"/opt/rh/rh-python36/root/lib/python3.6/site-packages/msrest/__init__.py\", line 28, in <module>\n    from .configuration import Configuration\n  File \"/opt/rh/rh-python36/root/lib/python3.6/site-packages/msrest/configuration.py\", line 35, in <module>\n    from typing import TYPE_CHECKING, Optional, Dict, List, Any, Callable, Union  # pylint: disable=unused-import\n  File \"/opt/rh/rh-python36/root/lib/python3.6/site-packages/typing.py\", line 134\n    def __new__(cls, name, bases, namespace, *, _root=False):\n                                              ^\nSyntaxError: invalid syntax\n",
    "exception": "Traceback (most recent call last):\n  File \"/tmp/ansible-tmp-1578420706.8446586-61843903276439/AnsiballZ_azure_rm_networkinterface.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/tmp/ansible-tmp-1578420706.8446586-61843903276439/AnsiballZ_azure_rm_networkinterface.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/tmp/ansible-tmp-1578420706.8446586-61843903276439/AnsiballZ_azure_rm_networkinterface.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.cloud.azure.azure_rm_networkinterface', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python2.7/runpy.py\", line 176, in run_module\n    fname, loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 82, in _run_module_code\n    mod_name, mod_fname, mod_loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/tmp/ansible_azure_rm_networkinterface_payload_CopMPq/ansible_azure_rm_networkinterface_payload.zip/ansible/modules/cloud/azure/azure_rm_networkinterface.py\", line 459, in <module>\n  File \"/opt/rh/rh-python36/root/lib/python3.6/site-packages/msrestazure/__init__.py\", line 28, in <module>\n    from .azure_configuration import AzureConfiguration\n  File \"/opt/rh/rh-python36/root/lib/python3.6/site-packages/msrestazure/azure_configuration.py\", line 34, in <module>\n    from msrest import Configuration\n  File \"/opt/rh/rh-python36/root/lib/python3.6/site-packages/msrest/__init__.py\", line 28, in <module>\n    from .configuration import Configuration\n  File \"/opt/rh/rh-python36/root/lib/python3.6/site-packages/msrest/configuration.py\", line 35, in <module>\n    from typing import TYPE_CHECKING, Optional, Dict, List, Any, Callable, Union  # pylint: disable=unused-import\n  File \"/opt/rh/rh-python36/root/lib/python3.6/site-packages/typing.py\", line 134\n    def __new__(cls, name, bases, namespace, *, _root=False):\n                                              ^\nSyntaxError: invalid syntax\n",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1,
    "_ansible_no_log": false,
    "changed": false
}

**Comment by MrMEEE** [comment]
Have you tried using a python2 venv??

**Comment by vosetrov-mdlive** [comment]
No, I haven't. Where I can change the venv?

**Comment by MrMEEE** [comment]
https://www.awx.wiki/tools/awx-create-venv

You might have to create two alternative venvs.. as there is a bug, so that they don't show up before there are 3...

After that you should be able to see a new venv dropdown in inventories, templates and so on...

**Comment by vosetrov-mdlive** [comment]
That helped, but I had to install a lot of dependencies to the new venv including /var/lib/awx/venv/<venv name>bin/pip install ansible[azure]

**Comment by MrMEEE** [comment]
Yeah, I know.. I have to add some stuff to the venv, so that I can automatically install those dependencies...
