### ISSUE TITLE
awx-rpm and isollated nodes 

### ISSUE THREAD

**Issue by MalfuncEddie** [MrMEEE/awx-build#204]
Can you use awx-rpm build to enable isollation nodes since these are not supported in the docker awx version?

To install "installation nodes" you need to "rerun" the installer with an extra section in the inventory file of the installation. Can you do that with the rpm build

**Comment by MrMEEE** [comment]
Hi

Isolated node functionality should be enabled by default..

I don't know what a "installation node" is?

**Comment by MalfuncEddie** [comment]
Hi,

That was a typo:
This is the procedure I have:
```
To add isolated node after Ansible Tower installation, your Isolated nodes must be specified in the same inventory file that you used for the installation before.

You can add the isolated node in the instance group which is prefixed with isolated_group_.

Below is an example of an inventory file with an isolated instance group.

Raw
[tower]
towerA
towerB
towerC

[instance_group_security]
towerB
towerC

[isolated_group_govcloud]
isolatedA
isolatedB

[isolated_group_govcloud:vars]
controller=security
Once you have the correct inventory file, you need to rerun the ./setup.sh installer script again, to get isolated nodes added to your Ansible Tower cluster.
```

Now I want to implement this with AWX-rpm but where is the inventory file or the  ./setup.sh installer

**Comment by MrMEEE** [comment]
Hi

The setup and inventory file is only in the Ansible Tower installation.. this is not used in AWX-RPM

My best answer would be to look into the script for Ansible Tower, and see what it does with those nodes...

**Comment by MalfuncEddie** [comment]
Hi 

thanks for the clear answer.
