### ISSUE TITLE
AWX v1.0.6.8 - Import Database data failed

### ISSUE THREAD

**Issue by shibinj** [MrMEEE/awx-build#21]
I have created a new CentOS 7.5 and followed the install guide instruction.  

My AWX version is as shown below:

> Name        : awx
> Arch        : x86_64
> Version     : 1.0.6.8
> Release     : 1.el7
> Size        : 374 M
> Repo        : installed
> From repo   : mrmeee-awx-dev
> Summary     : Ansible AWX
> License     : GPLv3
> Description : Ansible AWX
 

When I followed the section `import database data`, it failed with following error.

> [root@awx01 ~]# sudo -u awx /opt/awx/bin/awx-manage migrate
> Traceback (most recent call last):
>   File "/opt/awx/bin/awx-manage", line 11, in <module>
>     sys.exit(manage())
>   File "/opt/awx/embedded/lib/python2.7/site-packages/awx/__init__.py", line 93, in manage
>     prepare_env()
>   File "/opt/awx/embedded/lib/python2.7/site-packages/awx/__init__.py", line 48, in prepare_env
>     if not settings.DEBUG: # pragma: no cover
>   File "/opt/awx/embedded/lib64/python2.7/site-packages/django/conf/__init__.py", line 56, in __getattr__
>     self._setup(name)
>   File "/opt/awx/embedded/lib64/python2.7/site-packages/django/conf/__init__.py", line 41, in _setup
>     self._wrapped = Settings(settings_module)
>   File "/opt/awx/embedded/lib64/python2.7/site-packages/django/conf/__init__.py", line 110, in __init__
>     mod = importlib.import_module(self.SETTINGS_MODULE)
>   File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
>     __import__(name)
>   File "/opt/awx/embedded/lib/python2.7/site-packages/awx/settings/production.py", line 93, in <module>
>     include(settings_file, optional(settings_files), scope=locals())
>   File "/opt/awx/embedded/lib/python2.7/site-packages/split_settings/tools.py", line 102, in include
>     exec(compile(to_compile.read(), included_file, 'exec'), scope)
>   File "/etc/awx/settings.py", line 36, in <module>
>     CELERY_ROUTES['awx.main.tasks.cluster_node_heartbeat'] = {'queue': CLUSTER_HOST_ID, 'routing_key': CLUSTER_HOST_ID}
> TypeError: 'tuple' object does not support item assignment

Since the instruction followed today, not sure what and where it went wrong.   A month ago, I followed same instruction on CentOS 7.4, it was perfect.

**Comment by MrMEEE** [comment]
Hi.. as far as I can see, the awx guys broke something with the latest update...

I'm trying to figure out what's wrong...

Try to go with version 1.0.6.7 instead..

**Comment by MrMEEE** [comment]
Nope.. no f...-up.. they just changed things :)...

Just use version 1.0.6.8.. and comment out these two lines in /etc/awx/settings.py:

CELERY_ROUTES['awx.main.tasks.cluster_node_heartbeat'] = {'queue': CLUSTER_HOST_ID, 'routing_key': CLUSTER_HOST_ID}
CELERY_ROUTES['awx.main.tasks.purge_old_stdout_files'] = {'queue': CLUSTER_HOST_ID, 'routing_key': CLUSTER_HOST_ID}

Then it seems to work here :)

**Comment by shibinj** [comment]
That suggestion worked well.

**Comment by shibinj** [comment]
Now I have new issue when `Initializing configuration`.

> [root@awx01 ~]# echo "from django.contrib.auth.models import User; User.objects.create_superuser('adm                                                    in', 'root@localhost', 'password')" | sudo -u awx /opt/awx/bin/awx-manage shell


> [root@awx01 ~]# sudo -u awx /opt/awx/bin/awx-manage create_preload_data
> Traceback (most recent call last):
>   File "/opt/awx/bin/awx-manage", line 11, in <module>
>     sys.exit(manage())
>   File "/opt/awx/embedded/lib/python2.7/site-packages/awx/__init__.py", line 109, in manage
>     execute_from_command_line(sys.argv)
>   File "/opt/awx/embedded/lib64/python2.7/site-packages/django/core/management/__init__.py", line 364, in                                                     execute_from_command_line
>     utility.execute()
>   File "/opt/awx/embedded/lib64/python2.7/site-packages/django/core/management/__init__.py", line 356, in                                                     execute
>     self.fetch_command(subcommand).run_from_argv(self.argv)
>   File "/opt/awx/embedded/lib64/python2.7/site-packages/django/core/management/base.py", line 283, in run_                                                    from_argv
>     self.execute(*args, **cmd_options)
>   File "/opt/awx/embedded/lib64/python2.7/site-packages/django/core/management/base.py", line 330, in exec                                                    ute
>     output = self.handle(*args, **options)
>   File "/opt/awx/embedded/lib/python2.7/site-packages/awx/main/management/commands/create_preload_data.py"                                                    , line 47, in handle
>     created_by=superuser)
>   File "/opt/awx/embedded/lib64/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_                                                    method
>     return getattr(self.get_queryset(), name)(*args, **kwargs)
>   File "/opt/awx/embedded/lib64/python2.7/site-packages/django/db/models/query.py", line 394, in create
>     obj.save(force_insert=True, using=self.db)
>   File "/opt/awx/embedded/lib/python2.7/site-packages/awx/main/models/inventory.py", line 700, in save
>     super(Host, self).save(*args, **kwargs)
>   File "/opt/awx/embedded/lib/python2.7/site-packages/awx/main/models/base.py", line 275, in save
>     super(PrimordialModel, self).save(*args, **kwargs)
>   File "/opt/awx/embedded/lib/python2.7/site-packages/awx/main/models/base.py", line 164, in save
>     super(CreatedModifiedModel, self).save(*args, **kwargs)
>   File "/opt/awx/embedded/lib64/python2.7/site-packages/django/db/models/base.py", line 808, in save
>     force_update=force_update, update_fields=update_fields)
>   File "/opt/awx/embedded/lib64/python2.7/site-packages/django/db/models/base.py", line 848, in save_base
>     update_fields=update_fields, raw=raw, using=using,
>   File "/opt/awx/embedded/lib64/python2.7/site-packages/django/dispatch/dispatcher.py", line 193, in send
>     for receiver in self._live_receivers(sender)
>   File "/opt/awx/embedded/lib/python2.7/site-packages/awx/main/signals.py", line 146, in emit_update_inven                                                    tory_on_created_or_deleted
>     update_inventory_computed_fields.delay(inventory.id, True)
>   File "/opt/awx/embedded/lib/python2.7/site-packages/celery/app/task.py", line 461, in delay
>     return self.apply_async(args, kwargs)
>   File "/opt/awx/embedded/lib/python2.7/site-packages/celery/app/task.py", line 573, in apply_async
>     **dict(self._get_exec_options(), **options)
>   File "/opt/awx/embedded/lib/python2.7/site-packages/celery/app/base.py", line 345, in send_task
>     options = router.route(options, name, args, kwargs)
>   File "/opt/awx/embedded/lib/python2.7/site-packages/celery/app/routes.py", line 50, in route
>     route = self.lookup_route(task, args, kwargs)
>   File "/opt/awx/embedded/lib/python2.7/site-packages/celery/app/routes.py", line 78, in lookup_route
>     return _first_route(self.routes, task, args, kwargs)
>   File "/opt/awx/embedded/lib/python2.7/site-packages/celery/utils/functional.py", line 233, in _matcher
>     answer = getattr(maybe_evaluate(obj), method)(*args, **kwargs)
>   File "/opt/awx/embedded/lib/python2.7/site-packages/awx/main/utils/ha.py", line 58, in route_for_task
>     (changed, instance) = Instance.objects.get_or_register()
>   File "/opt/awx/embedded/lib/python2.7/site-packages/awx/main/managers.py", line 106, in get_or_register
>     return (False, self.me())
>   File "/opt/awx/embedded/lib/python2.7/site-packages/awx/main/managers.py", line 88, in me
>     raise RuntimeError("No instance found with the current cluster host id")
> RuntimeError: No instance found with the current cluster host id
>

**Comment by MrMEEE** [comment]
That error is normally caused by incorrect/unresolvable hostname...

Doublecheck the hostname...

**Comment by shibinj** [comment]
Thank you.   I found hostname was missing in /etc/hosts file.  Now all looks good.  It's just that not listening to port 8050 - 8052 .. seems I need to dig on ngnix.

**Comment by shibinj** [comment]
AWX tower is up now .. will close this thread now.

**Comment by MrMEEE** [comment]
Thanks for the feedback.. you will probably have problems running jobs... 

Try these migration steps...

https://github.com/MrMEEE/awx-build/blob/master/migrations.md
