### ISSUE TITLE
zipp Requirements error after Update

### ISSUE THREAD

**Issue by DGne-Nurag** [MrMEEE/awx-build#211]
I've updated today with help of the standard upgrade method:
https://awx.wiki/upgrade/standard-upgrade-method

But now the daphne service is restarting in a loop with the following error:
`scl: pkg_resources.ContextualVersionConflict: (zipp 0.0.0 (/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages), Requirement.parse('zipp>=0.5'), {'importlib-metadata'})`

i've tried to reinstall all python pakages and only this one but nothing helped (yum reinstall rh-python36-zipp). 

Thank you for your help!

UPDATE:
after downgrade from rh-python36-zipp-2.0.0-1.noarch.rpm to rh-python36-zipp-1.0.0-1.noarch.rpm it is working again.

It seems there is a problem with the last build of the zipp package.

**Comment by MrMEEE** [comment]
Yeah, I realized.. Thanks for the headsup.. that zipp-2.0.0 package has been removed from the repo
