### ISSUE TITLE
Unable to run awx on https

### ISSUE THREAD

**Issue by kushwaha2488** [MrMEEE/awx-build#212]
HI MrMee, 

I m trying to run my awx on https ..but its showing samee behaviour. Sometimes It works but sometimes shows "bad gateway error" and shows pop up like "unable to get api or something else".

Please help me on this .

**Comment by mjaperta** [comment]
Hi

What have you changed going to https?

What errors/info do you get in web.log and the nginx logs?

**Comment by kushwaha2488** [comment]
Please see the logs --

**access_log**

10.X.X.X - - [22/Jan/2020:06:25:47 +0000] "GET /websocket/ HTTP/1.1" 502 559 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36" "-"
10.X.X.X - - [22/Jan/2020:06:25:52 +0000] "GET /api/v2/job_templates/12/launch/ HTTP/2.0" 502 559 "https://10.X.X.X/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36" "-"


Web.log

compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 25 January 2019 15:51:17
os: Linux-3.10.0-1062.4.3.el7.x86_64 #1 SMP Tue Nov 12 10:42:40 EST 2019
nodename: 0i
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /
detected binary path: /opt/rh/rh-python36/root/usr/bin/uwsgi
setgid() to 986
setuid() to 989
your processes number limit is 31765
your memory page size is 4096 bytes
*** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers ***
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8050 fd 3
Python version: 3.6.9 (default, Sep 11 2019, 16:40:19)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x21395e0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 609552 bytes (595 KB) for 5 cores
*** Operational MODE: preforking ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 123990)
spawned uWSGI worker 1 (pid: 124000, cores: 1)
spawned uWSGI worker 2 (pid: 124001, cores: 1)
spawned uWSGI worker 3 (pid: 124002, cores: 1)
spawned uWSGI worker 4 (pid: 124003, cores: 1)
spawned uWSGI worker 5 (pid: 124004, cores: 1)
WSGI app 0 (mountpoint='') ready in 5 seconds on interpreter 0x21395e0 pid: 124002 (default app)

**Comment by MrMEEE** [comment]
Are you sure that you are not facing #213 ???

**Comment by MrMEEE** [comment]
Project has been updated and moved...

Please move to the new version and report any issues

PROJECT MOVED: https://github.com/miracle-as/AWX-RPM

Issues at: https://github.com/miracle-as/AWX-RPM/issues

**Install guide, tools, utilities are located at: https://awx.wiki

**LinkedIn group for Questions, support, talk and more: https://www.linkedin.com/groups/13694893/**
