### ISSUE TITLE
upgrading from 9.1.0 to 9.1.1 broke the install. 9.1.1 install seems to be broken as well.

### ISSUE THREAD

**Issue by cs-laurentiuvasiescu** [MrMEEE/awx-build#213]
I receive a lot of 502 and then bad gateway from Nginx. 

Both in the case of upgrade (local db) and install with external db.

"Failed to get config. GET returned status: 502" after upgrade. When logging in.

Or Failed to read /api. GET status: 502

"Invalid search term entered. GET returned: 502" when saving something.

**Comment by MrMEEE** [comment]
Hi.. A too new dependecy was pulled in, which breaks the daphne (websockets) part...

try:

```
yum -y downgrade rh-python36-zipp
systemctl restart awx-daphne
```

**Comment by cs-laurentiuvasiescu** [comment]
Thanks a bunch, that solved it.

**Comment by Dofamin** [comment]
I have same issue, but in my case it mostly for some reason is blame on rabbitmq.
Restart of rabbitmq is fixing issue.

**Comment by chaleyeah** [comment]
> I have same issue, but in my case it mostly for some reason is blame on rabbitmq.
> Restart of rabbitmq is fixing issue.

Same thing is happening to me on version 9.2.0.  Restarting rabbitmq-server.service doesn't fix the issues. 
I also downgraded the rh-python36-zipp software and I'm still seeing the issues.

**Comment by Nekasas** [comment]
I don't have rh-python36-zipp and rabbitmq is restarted, but still facing same problem. I upgraded from 9.1.1 to 9.2.0.261-1.el7

I did all standard commands after migration, but still can't connect

`Feb 27 09:10:49 awx scl: 2020-02-27 07:10:49,122 - INFO - runworker - Using single-threaded worker.
Feb 27 09:10:49 awx scl: 2020-02-27 07:10:49,122 - INFO - runworker - Running worker against channel layer default (asgi_amqp.core.AMQPChannelLayer)
Feb 27 09:10:49 awx scl: 2020-02-27 07:10:49,123 - INFO - worker - Listening on channels websocket.connect, websocket.disconnect, websocket.receive
Feb 27 09:10:49 awx scl: 2020-02-27 07:10:49,518 WARNING  awx.main.commands.run_callback_receiver scaling up worker pid:15638
Feb 27 09:10:49 awx scl: 2020-02-27 07:10:49,518 WARNING  awx.main.commands.run_callback_receiver scaling up worker pid:15638
Feb 27 09:10:49 awx scl: 2020-02-27 07:10:49,525 WARNING  awx.main.commands.run_callback_receiver scaling up worker pid:15639
Feb 27 09:10:49 awx scl: 2020-02-27 07:10:49,525 WARNING  awx.main.commands.run_callback_receiver scaling up worker pid:15639
Feb 27 09:10:49 awx scl: 2020-02-27 07:10:49,530 WARNING  awx.main.commands.run_callback_receiver scaling up worker pid:15640
Feb 27 09:10:49 awx scl: 2020-02-27 07:10:49,530 WARNING  awx.main.commands.run_callback_receiver scaling up worker pid:15640
Feb 27 09:10:49 awx scl: 2020-02-27 07:10:49,537 WARNING  awx.main.commands.run_callback_receiver scaling up worker pid:15641
Feb 27 09:10:49 awx scl: 2020-02-27 07:10:49,537 WARNING  awx.main.commands.run_callback_receiver scaling up worker pid:15641
Feb 27 09:10:50 awx systemd: awx-dispatcher.service holdoff time over, scheduling restart.
Feb 27 09:10:50 awx systemd: Stopping AWX daphne service...
Feb 27 09:10:50 awx scl: 2020-02-27 07:10:50,352 WARNING  awx.main.commands.run_callback_receiver received SIGTERM, stopping
Feb 27 09:10:50 awx scl: 2020-02-27 07:10:50,352 WARNING  awx.main.commands.run_callback_receiver received SIGTERM, stopping
Feb 27 09:10:50 awx systemd: Stopped AWX Dispatcher.
Feb 27 09:10:50 awx scl: 2020-02-27 07:10:50,359 - INFO - worker - Shutdown signal received while idle, terminating immediately
`

`Feb 27 09:14:14 awx scl: File "/opt/rh/rh-python36/root/usr/bin/awx-manage", line 11, in <module>
Feb 27 09:14:14 awx scl: load_entry_point('awx==9.2.0', 'console_scripts', 'awx-manage')()
Feb 27 09:14:14 awx scl: File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/__init__.py", line 152, in manage
Feb 27 09:14:14 awx scl: execute_from_command_line(sys.argv)
Feb 27 09:14:14 awx scl: File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
Feb 27 09:14:14 awx scl: utility.execute()
Feb 27 09:14:14 awx scl: File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
Feb 27 09:14:14 awx scl: self.fetch_command(subcommand).run_from_argv(self.argv)
Feb 27 09:14:14 awx scl: File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 224, in fetch_command
Feb 27 09:14:14 awx scl: klass = load_command_class(app_name, subcommand)
Feb 27 09:14:14 awx scl: File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 36, in load_command_class
Feb 27 09:14:14 awx scl: module = import_module('%s.management.commands.%s' % (app_name, name))
Feb 27 09:14:14 awx scl: File "/opt/rh/rh-python36/root/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
Feb 27 09:14:14 awx scl: return _bootstrap._gcd_import(name[level:], package, level)
Feb 27 09:14:14 awx scl: File "<frozen importlib._bootstrap>", line 994, in _gcd_import
Feb 27 09:14:14 awx scl: File "<frozen importlib._bootstrap>", line 971, in _find_and_load
Feb 27 09:14:14 awx scl: File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
Feb 27 09:14:14 awx scl: File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
Feb 27 09:14:14 awx scl: File "<frozen importlib._bootstrap_external>", line 678, in exec_module
Feb 27 09:14:14 awx scl: File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
Feb 27 09:14:14 awx scl: File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/management/commands/run_dispatcher.py", line 17, in <module>
Feb 27 09:14:14 awx scl: from awx.main.dispatch import periodic
Feb 27 09:14:14 awx scl: File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/dispatch/periodic.py", line 7, in <module>
Feb 27 09:14:14 awx scl: from schedule import Scheduler
Feb 27 09:14:14 awx scl: ModuleNotFoundError: No module named 'schedule'
`

**Comment by MrMEEE** [comment]
I think you are missing dependecies..

could you please try to run the installation of dependecies again?

Please attach the output

**Comment by Nekasas** [comment]
about which dependencies you are talking? 

my previous update looks like

> 
     Updated ansible-2.9.2-1.el7.noarch                                 @epel
    Update          2.9.3-1.el7.noarch                                 @epel
    Updated ansible-awx-9.1.1.167-1.el7.x86_64                        @copr:copr.fedorainfracloud.org:mrmeee:ansible-awx
    Update              9.2.0.261-1.el7.x86_64                         @copr:copr.fedorainfracloud.org:mrmeee:ansible-awx
    Updated binutils-2.27-41.base.el7_7.1.x86_64                       @updates
    Update           2.27-41.base.el7_7.2.x86_64                       @updates
    Updated curl-7.29.0-54.el7_7.1.x86_64                              @updates
    Update       7.29.0-54.el7_7.2.x86_64                              @updates
    Updated firewalld-0.6.3-2.el7_7.2.noarch                           @updates
    Update            0.6.3-2.el7_7.3.noarch                           @updates
    Updated firewalld-filesystem-0.6.3-2.el7_7.2.noarch                @updates
    Update                       0.6.3-2.el7_7.3.noarch                @updates
    Updated iprutils-2.4.17.1-2.el7.x86_64                             @base
    Update           2.4.17.1-3.el7_7.x86_64                           @updates
    Updated python-firewall-0.6.3-2.el7_7.2.noarch                     @updates
    Update                  0.6.3-2.el7_7.3.noarch                     @updates
    Updated python-perf-3.10.0-1062.9.1.el7.x86_64                     @updates
    Update              3.10.0-1062.12.1.el7.x86_64                    @updates
    Updated python2-future-0.16.0-15.20181019gitbee0f3b.el7.noarch     @epel
    Update                 0.18.2-2.el7.noarch                         @epel
    Updated rabbitmq-server-3.7.23-1.el7.noarch                        @bintraybintray-rabbitmq-rpm
    Update                  3.7.24-1.el7.noarch                        @bintraybintray-rabbitmq-rpm
    Updated rh-git218-git-2.18.1-3.el7.x86_64                          @centos-sclo-rh
    Update                2.18.2-1.el7.x86_64                          @centos-sclo-rh
    Updated rh-git218-git-core-2.18.1-3.el7.x86_64                     @centos-sclo-rh
    Update                     2.18.2-1.el7.x86_64                     @centos-sclo-rh
    Updated rh-git218-git-core-doc-2.18.1-3.el7.noarch                 @centos-sclo-rh
    Update                         2.18.2-1.el7.noarch                 @centos-sclo-rh
    Updated rh-git218-perl-Git-2.18.1-3.el7.noarch                     @centos-sclo-rh
    Update                     2.18.2-1.el7.noarch                     @centos-sclo-rh
    Updated rh-python36-Django-2.2.8-1.noarch                          @copr:copr.fedorainfracloud.org:mrmeee:ansible-awx
    Update                     2.2.10-1.noarch                         @copr:copr.fedorainfracloud.org:mrmeee:ansible-awx
    Updated rh-python36-Werkzeug-0.16.1-1.noarch                       @copr:copr.fedorainfracloud.org:mrmeee:ansible-awx
    Update                       1.0.0-1.noarch                        @copr:copr.fedorainfracloud.org:mrmeee:ansible-awx
    Updated rh-python36-ansible-2.9.4-1.noarch                         @copr:copr.fedorainfracloud.org:mrmeee:ansible-awx
    Update                      2.9.5-1.noarch                         @copr:copr.fedorainfracloud.org:mrmeee:ansible-awx
    Updated rh-python36-cffi-1.13.2-1.x86_64                           @copr:copr.fedorainfracloud.org:mrmeee:ansible-awx
    Update                   1.14.0-1.x86_64                           @copr:copr.fedorainfracloud.org:mrmeee:ansible-awx
    Updated rh-python36-idna-2.8-1.noarch                              @copr:copr.fedorainfracloud.org:mrmeee:ansible-awx
    Update                   2.9-1.noarch                              @copr:copr.fedorainfracloud.org:mrmeee:ansible-awx
    Updated rh-python36-importlib_metadata-1.4.0-1.noarch              @copr:copr.fedorainfracloud.org:mrmeee:ansible-awx
    Update                                 1.5.0-1.noarch              @copr:copr.fedorainfracloud.org:mrmeee:ansible-awx
    Updated rh-python36-jsonpatch-1.24-1.noarch                        @copr:copr.fedorainfracloud.org:mrmeee:ansible-awx
    Update                        1.25-1.noarch                        @copr:copr.fedorainfracloud.org:mrmeee:ansible-awx
    Updated rh-python36-msrest-0.6.10-1.noarch                         @copr:copr.fedorainfracloud.org:mrmeee:ansible-awx
    Update                     0.6.11-1.noarch                         @copr:copr.fedorainfracloud.org:mrmeee:ansible-awx
    Updated rh-python36-openstacksdk-0.31.1-1.noarch                   @copr:copr.fedorainfracloud.org:mrmeee:ansible-awx
    Update                           0.37.0-1.noarch                   @copr:copr.fedorainfracloud.org:mrmeee:ansible-awx
    Updated rh-python36-python-jinja2-2.11.0-1.noarch                  @copr:copr.fedorainfracloud.org:mrmeee:ansible-awx
    Update                            2.11.1-1.noarch                  @copr:copr.fedorainfracloud.org:mrmeee:ansible-awx
    Updated rh-python36-requests-2.22.0-1.noarch                       @copr:copr.fedorainfracloud.org:mrmeee:ansible-awx
    Update                       2.23.0-1.noarch                       @copr:copr.fedorainfracloud.org:mrmeee:ansible-awx
    Updated rh-python36-wheel-0.30.0-1.noarch                          @copr:copr.fedorainfracloud.org:mrmeee:ansible-awx
    Update                    0.33.6-1.noarch                          @copr:copr.fedorainfracloud.org:mrmeee:ansible-awx

>

**Comment by MrMEEE** [comment]
did you run the command:
```
yum -y install --disablerepo='*' --enablerepo='copr:copr.fedorainfracloud.org:mrmeee:ansible-awx, base' -x *-debuginfo rh-python36*
```
??

**Comment by Nekasas** [comment]
> did you run the command:
> 
> ```
> yum -y install --disablerepo='*' --enablerepo='copr:copr.fedorainfracloud.org:mrmeee:ansible-awx, base' -x *-debuginfo rh-python36*
> ```
> 
> ??

nope, but now is working :) Big thanks for you!
Do you know if it will be mandatory to run this command for future updates?

**Comment by MrMEEE** [comment]
Good..

Yes, for now it's mandatory to run the command, as also described in the update guide:

https://www.awx.wiki/upgrade/standard-upgrade-method
