### ISSUE TITLE
Make Ansible installable on an AWX Server

### ISSUE THREAD

**Issue by MrMEEE** [MrMEEE/awx-build#22]
Right now AWX breaks horrible if Ansible is installed on the same server (#15)

**Comment by Aglidic** [comment]
when you run a job and check is status through the api we can saw that you have added a pythonpath on embeded awx with the module. But if you check you can yalso see that it's looking to a virtual env python in /var/lib/awx.

When you check a "tower" install all python modules are directly install in this virtualenv.

create a venv awx and put all necessary python modules there
create a venv ansible and put all necessay python modules there

Maybe we can do the same.

**Comment by MrMEEE** [comment]
This should be fixed with AWX-RPM 3.0.0
