### ISSUE TITLE
Version Conflict (zipp 0.0.0)

### ISSUE THREAD

**Issue by 6sossomons** [MrMEEE/awx-build#221]
Upgraded my dev environment this morning and got this little gem happening in the logs for Daphne:

scl: Traceback (most recent call last):
scl: File "/opt/rh/rh-python36/root/usr/bin/awx-manage", line 11, in <module>
scl: load_entry_point('awx==9.2.0', 'console_scripts', 'awx-manage')()
scl: File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/__init__.py", line 152, in manage
scl: execute_from_command_line(sys.argv)
scl: File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
scl: utility.execute()
scl: File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
scl: self.fetch_command(subcommand).run_from_argv(self.argv)
scl: File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
scl: self.execute(*args, **cmd_options)
scl: File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
scl: output = self.handle(*args, **options)
scl: File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/channels/management/commands/runworker.py", line 42, in handle
scl: self.channel_layer = channel_layers[options.get("layer", DEFAULT_CHANNEL_LAYER)]
scl: File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/channels/asgi.py", line 70, in __getitem__
scl: self.backends[key] = self.make_backend(key)
scl: File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/channels/asgi.py", line 33, in make_backend
scl: return self._make_backend(name, config)
scl: File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/channels/asgi.py", line 48, in _make_backend
scl: backend_class = import_string(self.configs[name]['BACKEND'])
scl: File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/utils/module_loading.py", line 17, in import_string
scl: module = import_module(module_path)
scl: File "/opt/rh/rh-python36/root/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
scl: return _bootstrap._gcd_import(name[level:], package, level)
scl: File "<frozen importlib._bootstrap>", line 994, in _gcd_import
scl: File "<frozen importlib._bootstrap>", line 971, in _find_and_load
scl: File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
scl: File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
scl: File "<frozen importlib._bootstrap_external>", line 678, in exec_module
scl: File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
scl: File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/asgi_amqp/__init__.py", line 7, in <module>
scl: __version__ = pkg_resources.require('asgi_amqp')[0].version
scl: File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 981, in require
scl: needed = self.resolve(parse_requirements(requirements))
scl: File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 872, in resolve
scl: raise VersionConflict(dist, req).with_context(dependent_req)
scl: pkg_resources.ContextualVersionConflict: (zipp 0.0.0 (/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages), Requirement.parse('zipp>=0.5'), {'importlib-metadata'})
systemd: awx-channels-worker.service: main process exited, code=exited, status=1/FAILURE

I tried to downgrade zipp
# yum -y downgrade rh-python36-zipp
Nothing to do

Thoughts?

**Comment by MrMEEE** [comment]
try to downgrade to rh-python36-zipp-1.0.0.. it should work

**Comment by 6sossomons** [comment]
# yum list rh-python36-zipp --show-duplicates
Installed Packages
rh-python36-zipp.noarch                                                                              3.1.0-1                                                                               @copr:copr.fedorainfracloud.org:mrmeee:ansible-awx
Available Packages
rh-python36-zipp.noarch                                                                              3.1.0-1                                                                               copr:copr.fedorainfracloud.org:mrmeee:ansible-awx
Uploading Enabled Repositories Report

**Comment by bamason14** [comment]
I have the same issue. I do not show any other version of rh-python36-zipp besides 3.1.0-1.

**Comment by MrMEEE** [comment]
I have just done a rebuild of 1.0.0.. Should be available now.. Remember to clear your yum cache..

**Comment by bamason14** [comment]
It's working for me now. Thank you.

**Comment by 6sossomons** [comment]
Same, thank you!
