### ISSUE TITLE
cannot login to awx ansible with default credentials 

### ISSUE THREAD

**Issue by gefela** [MrMEEE/awx-build#222]
I cannot login into the web ui even with resetting awx

**Comment by cbetan** [comment]
same here. Anybody has any hints?

I have also tried changing the password to no avail:
`sudo -u awx scl enable rh-python36 rh-postgresql10 rh-git29 "GIT_PYTHON_REFRESH=quiet awx-manage changepassword admin"`

Furthemore, I created a new superuser, but also can't login with this new user!
`sudo -u awx scl enable rh-python36 rh-postgresql10 rh-git29 "GIT_PYTHON_REFRESH=quiet awx-manage createsuperuser" `

**Comment by MrMEEE** [comment]
Project has been updated and moved...

Please move to the new version and report any issues

PROJECT MOVED: https://github.com/miracle-as/AWX-RPM

Issues at: https://github.com/miracle-as/AWX-RPM/issues

**Install guide, tools, utilities are located at: https://awx.wiki

**LinkedIn group for Questions, support, talk and more: https://www.linkedin.com/groups/13694893/**
