### ISSUE TITLE
Failed to get instance groups Info. GET returned status : 502 

### ISSUE THREAD

**Issue by gefela** [MrMEEE/awx-build#223]
When I try to navigate the various feature of AWX , I get the following error message 

Failed to get instance groups Info. GET returned status : 502

**Comment by gefela** [comment]
![awx error](https://user-images.githubusercontent.com/30554569/76221347-db82c280-6210-11ea-90ce-7458434296c9.png)

**Comment by hypemedia** [comment]
I have the same problem but in several pages. If I refresh a few times it works. Also everything loads very slow compared to older versions. 

Call to /api/v2/system_job_templates/?order_by=name failed. Return status: 502

**Comment by MrMEEE** [comment]
Project has been updated and moved...

Please move to the new version and report any issues

PROJECT MOVED: https://github.com/miracle-as/AWX-RPM

Issues at: https://github.com/miracle-as/AWX-RPM/issues

**Install guide, tools, utilities are located at: https://awx.wiki

**LinkedIn group for Questions, support, talk and more: https://www.linkedin.com/groups/13694893/**
