### ISSUE TITLE
facts is not loading on awx

### ISSUE THREAD

**Issue by Tamilvananb** [MrMEEE/awx-build#228]
ansible facts is not loading on the hosts .i had ran setup module and tried but facts is not loading.any solutions?

**Comment by Tamilvananb** [comment]
![Screenshot_57](https://user-images.githubusercontent.com/43129537/77829615-2c6b4400-7149-11ea-99ca-ab43cd29edd5.png)

**Comment by MrMEEE** [comment]
Project has been updated and moved...

Please move to the new version and report any issues

PROJECT MOVED: https://github.com/miracle-as/AWX-RPM

Issues at: https://github.com/miracle-as/AWX-RPM/issues

**Install guide, tools, utilities are located at: https://awx.wiki

**LinkedIn group for Questions, support, talk and more: https://www.linkedin.com/groups/13694893/**
