### ISSUE TITLE
Rename awx-rpm repo and awx.spec file to ansible-awx

### ISSUE THREAD

**Issue by nkadel** [MrMEEE/awx-build#229]
I didn't see an "issues" for the "awx-rpm" repo, and it's apparently referred to here. Since the RPM it builds is "ansible-awx", wouldn't it make more sense to call the repository "ansible-awx" and the spec file "ansible-awx.spec" ? Tweaking that would also require changes here.

**Comment by MrMEEE** [comment]
hi

You are completely right..

A complete rewrite of the build process is in the works, and this will definitely be a part of it...

**Comment by nkadel** [comment]
Good. I've also taken a shot at porting the relevant modules to the now directly available Python 3.6 from CentOS 7, and to CentOS 8, rather than ushing the rh-python3.6 tools. You're welcome to it. It's at https://github.com/nkadel/awxrepo/ . I've been working from "mock" based builds, which isolate the  build environment from pypi.org during the build, and compelled me to build RPM's for *everything* rather than rely on pulled in modules and updates from pypi.org. Unfortunately, after building roughly 150 RPM's to get everything, I ran into "pluggy", which has conflicting version dependencies from different python modules and which confuses the heck out of build-time version reporting.

You're welcome to any and all of it.

**Comment by MrMEEE** [comment]
Thanks for the headsup.. As I mentioned in another thread, I do also isolate the builds.. just more manually, as I had problems with the mock builds earlier..

But I will definitely look into your builds, and see what we can do to get the best of both..

**Comment by nkadel** [comment]
I managed to build the stack except for ansible-awx.spec itself 1.32 SRPMs built on CentOS 8, with another 20 or so that I'd *tried* to build when I started under CentOS 7 and eventually gave up due to adventures using the built-in python 3.6 rather than SCLO, and with "mock" keeping me on the straight and narrow for dependencies. python3-docutils has a confluct at installation time with the "modular" RPM published in CentOS, and I have come to loathe modularity with a passion inspired by my troubles. But it's a starting point. I'd also recommend using CentOS 8 by default rather than CentOs 7, the updates start interfering with system packages without caution.

**Comment by dominiquearpin** [comment]
Just wondering if you have any updates?

**Comment by MrMEEE** [comment]
@dominiquearpin I'm getting a lot closer... dependencies for both EL7 and EL8 are almost done.. Hope to have something ready next week

**Comment by rokat** [comment]
Hello, just checked a bit, but it seems rh-git29 is no longer available from SCL. 
It seems to have been replaced by rh-git218
I dunno if that would be an issue for the dependencies.
But thanks a lot for your efforts :)

**Comment by MrMEEE** [comment]
Project has been updated and moved...

Please move to the new version and report any issues

PROJECT MOVED: https://github.com/miracle-as/AWX-RPM

Issues at: https://github.com/miracle-as/AWX-RPM/issues

**Install guide, tools, utilities are located at: https://awx.wiki

**LinkedIn group for Questions, support, talk and more: https://www.linkedin.com/groups/13694893/**
