### ISSUE TITLE
Hi I am getting error when I try to install AWX in new centos machine

### ISSUE THREAD

**Issue by Ashjoker24** [MrMEEE/awx-build#231]
Hi I am getting error when I try to install AWX in new centos machine
and the error was
_createuser: creation of new role failed: ERROR:  role "awx" already exists_

**Comment by Ashjoker24** [comment]
![image](https://user-images.githubusercontent.com/43417210/78675453-bada8500-7902-11ea-8514-1879ff5d8bd9.png)

**Comment by pankajps** [comment]
You can try pip to install it

/opt/rh/rh-python36/root/usr/bin/python3.6 /opt/rh/rh-python36/root/usr/bin/pip install Django==2.2.8

**Comment by MrMEEE** [comment]
Project has been updated and moved...

Please move to the new version and report any issues

PROJECT MOVED: https://github.com/miracle-as/AWX-RPM

Issues at: https://github.com/miracle-as/AWX-RPM/issues

**Install guide, tools, utilities are located at: https://awx.wiki

**LinkedIn group for Questions, support, talk and more: https://www.linkedin.com/groups/13694893/**
