### ISSUE TITLE
502 bad gateway 

### ISSUE THREAD

**Issue by gefela** [MrMEEE/awx-build#232]
I am getting this when I try to access awx ? 
What should be looking at ?

**Comment by pankajps** [comment]
Check awx-web.service service, if this service is not running then this error comes.

**Comment by gefela** [comment]
How do you enable this service and check for it ?
I am new to AWX ansible ..

**Comment by pankajps** [comment]
it depends on the OS, If you are using Centos 7

systemctl status awx-web
systemctl enable awx-web
systemctl start awx-web

**Comment by MrMEEE** [comment]
Project has been updated and moved...

Please move to the new version and report any issues

PROJECT MOVED: https://github.com/miracle-as/AWX-RPM

Issues at: https://github.com/miracle-as/AWX-RPM/issues

**Install guide, tools, utilities are located at: https://awx.wiki

**LinkedIn group for Questions, support, talk and more: https://www.linkedin.com/groups/13694893/**
