### ISSUE TITLE
 Invalid virtual environment selected

### ISSUE THREAD

**Issue by hypemedia** [MrMEEE/awx-build#235]
After upgrading to the latest version 9.3.0 and doing a lot modifications I was able to make AWX work.
The problem is that now when I try to run a job I get this error:

Invalid virtual environment selected: /opt/rh/rh-python36/root/

rh-python36-ansible.noarch     2.9.6-1   mrmeee-ansible-awx

Any ideas on what I can do?

**Comment by MrMEEE** [comment]
Project has been updated and moved...

Please move to the new version and report any issues

PROJECT MOVED: https://github.com/miracle-as/AWX-RPM

Issues at: https://github.com/miracle-as/AWX-RPM/issues

**Install guide, tools, utilities are located at: https://awx.wiki

**LinkedIn group for Questions, support, talk and more: https://www.linkedin.com/groups/13694893/**
