### ISSUE TITLE
regarding awx ha

### ISSUE THREAD

**Issue by chakri1998** [MrMEEE/awx-build#237]
i have enabled awx ha i have created 2 task containers in aws instances it is showing 2 instances are available but when i assign task to the 2nd instance the instance is getting unavailable. how to resolve this issue please help me.

**Comment by bryanasdev000** [comment]
> i have enabled awx ha i have created 2 task containers in aws instances it is showing 2 instances are available but when i assign task to the 2nd instance the instance is getting unavailable. how to resolve this issue please help me.

Hey @chakri1998,
maybe this link ([https://github.com/sujiar37/AWX-HA-InstanceGroup/issues/26](url)) can illuminate you in what to do, it has some ideas to have the a cluster of AWX 11.X.X with Redis up and running.

HA in the latest versions has changed dramatically.

The example uses containers but it shouldn't be difficult to use awx rpm instead.

**Comment by MrMEEE** [comment]
I'm pretty sure that communication is done directly to the postgres (not sure), so be sure that the database port is open?

**Comment by MrMEEE** [comment]
Project has been updated and moved...

Please move to the new version and report any issues

PROJECT MOVED: https://github.com/miracle-as/AWX-RPM

Issues at: https://github.com/miracle-as/AWX-RPM/issues

**Install guide, tools, utilities are located at: https://awx.wiki

**LinkedIn group for Questions, support, talk and more: https://www.linkedin.com/groups/13694893/**
