### ISSUE TITLE
AWX 11 install failure on centos 7

### ISSUE THREAD

**Issue by Lobout** [MrMEEE/awx-build#239]
[root@awx ~]# ./awx-setup -i
This is going to install AWX-RPM and all dependencies.. This installer is meant to be easy, not customizable..
Check https://awx.wiki for advanced install methods and more info..
Do you want to continue?  [y/N] y
Setting up AWX-RPM
Configuring SELinux
Package policycoreutils-python-2.5-34.el7.x86_64 already installed and latest version

Configuring Firewall (Disabling for now/TODO)

Configure Repositories
Adding EPEL

Adding AWX-RPM Repo
Installing Redis
warning: /var/cache/yum/x86_64/7/epel/packages/jemalloc-3.6.0-1.el7.x86_64.rpm: Header V3 RSA/SHA256 Signature, key ID 352c64e5: NOKEY
Importing GPG key 0x352C64E5:
 Userid     : "Fedora EPEL (7) <epel@fedoraproject.org>"
 Fingerprint: 91e9 7d7c 4a5e 96f1 7f3e 888f 6a2f aea2 352c 64e5
 Package    : epel-release-7-11.noarch (@extras)
 From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7
Public key for jemalloc-3.6.0-1.el7.x86_64.rpm is not installed

Installing PostgreSQL
warning: /var/cache/yum/x86_64/7/centos-sclo-rh/packages/rh-postgresql10-postgresql-libs-10.12-2.el7.x86_64.rpm: Header V4 RSA/SHA1 Signature, key ID f2ee9d55: NOKEY
Importing GPG key 0xF2EE9D55:
 Userid     : "CentOS SoftwareCollections SIG (https://wiki.centos.org/SpecialInterestGroup/SCLo) <security@centos.org>"
 Fingerprint: c4db d535 b1fb ba14 f8ba 64a8 4eb8 4e71 f2ee 9d55
 Package    : centos-release-scl-rh-2-3.el7.centos.noarch (@extras)
 From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-SIG-SCLo
Public key for rh-postgresql10-postgresql-libs-10.12-2.el7.x86_64.rpm is not installed

Installing Memcached

Installing NGINX

Installing AWX-RPM
warning: /var/cache/yum/x86_64/7/ansible-awx/packages/python3-Pygments-2.6.1-1.4.noarch.rpm: Header V3 RSA/SHA1 Signature, key ID b545ff52: NOKEY
Importing GPG key 0xB545FF52:
 Userid     : "private OBS (key without passphrase) <defaultkey@localobs>"
 Fingerprint: 996c cb80 cf2d d9bd 4356 13c1 c3ad d35f b545 ff52
 From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-AWX-RPM

Transaction check error:
  file /usr/bin/chardetect from install of python3-chardet-3.0.4-5.8.noarch conflicts with file from package python-chardet-2.2.1-3.el7.noarch

Error Summary
-------------

Public key for python3-Pygments-2.6.1-1.4.noarch.rpm is not installed

Initialising PostgreSQL
WARNING: using obsoleted argument syntax, try --help
WARNING: arguments transformed to: postgresql-setup --initdb --unit rh-postgresql10-postgresql
 * Initializing database in '/var/opt/rh/rh-postgresql10/lib/pgsql/data'
 * Initialized, logs are in /var/lib/pgsql/initdb_rh-postgresql10-postgresql.log

Starting PostgreSQL

Creating AWX postgreSQL user and Database
Installing pwgen
could not change directory to "/root": Permission denied
could not change directory to "/root": Permission denied

Generating Secret key
/bin/sh: /etc/tower/SECRET_KEY: No such file or directory

**Comment by Lobout** [comment]
once i corrected the package conflict install was able to progress then got a python error regarding a missing module "rpm"

Creating initial Ansible VENV
Traceback (most recent call last):
  File "/usr/bin/awx-create-venv", line 3, in <module>
    import sys, getopt, os, datetime, rpm
ModuleNotFoundError: No module named 'rpm'

**Comment by MrMEEE** [comment]
What kind of installation are you running on? I don't think that python-chardet is installed as default?? But it should be changed so both can be installed..

**Comment by MrMEEE** [comment]
The rpm stuff should be fixed in the latest version...

**Comment by gpavinteractiv** [comment]
I am on awx-rpm 9.0.1, is the rpm upgrade to awx 11 supported?

**Comment by Lobout** [comment]
> I am on awx-rpm 9.0.1, is the rpm upgrade to awx 11 supported?

Not currently.

**Comment by Lobout** [comment]
current build install is successful on centos7 with the same caveat as centos 8.  the about information does not show ansible version until you install the ansible package

 ______________ 
<  AWX 11.2.0  >
 -------------- 
        \   ^__^
         \  (oo)\_______
            (__)      A )\/\
                ||----w |
                ||     ||

Ansible unknown
Copyright © 2019 Red Hat, Inc.
Visit Ansible.com for more information.

**Comment by MrMEEE** [comment]
@gpavinteractiv I hope to have an upgrade guide ready soon...

@Lobout I have created #243 .. will close this
