### ISSUE TITLE
AWX rh-git29 not found

### ISSUE THREAD

**Issue by nikita199220** [MrMEEE/awx-build#240]
Hi,

 I was trying to install awx on my azure centos 7.7 server but firstof all i was having rh-git29 not found while running below command :

sudo -u awx scl enable rh-python36 rh-postgresql10 rh-git29 "GIT_PYTHON_REFRESH=quiet awx-manage migrate"

After that i removed rh-git29 then i had below issue:

 No module named 'asgiref.local'

Then i downgraded some of Django package after that it was working fine.

so you could you please suggest is there any way that we have evreything in ansible-awx repo only or is there any other way to troubleshoot this error

**Comment by MrMEEE** [comment]
hi.. there is now a new installation in beta (the old one will be gone soon)... 

yum -y install python36
https://raw.githubusercontent.com/MrMEEE/awx-rpm/master/awx-setup
chmod +x awx-setup
./awx-setup -i

**Comment by nikita199220** [comment]
Still i am having below issue:

After Installing pwgen :
awx commands are not working...




Creating AWX postgreSQL user and Database
could not change directory to "/root": Permission denied
createuser: creation of new role failed: ERROR:  role "awx" already exists

could not change directory to "/root": Permission denied
createdb: database creation failed: ERROR:  database "awx" already exists

Installing pwgen

Generating Secret key
/bin/sh: /etc/tower/SECRET_KEY: No such file or directory

Initial database migration
sudo: unknown user: awx
sudo: unable to initialize policy plugin

Creating Admin user
sudo: unknown user: awx
sudo: unable to initialize policy plugin

Adding example data and registering AWX-RPM Instance in database
sudo: unknown user: awx
sudo: unable to initialize policy plugin

sudo: unknown user: awx
sudo: unable to initialize policy plugin

sudo: unknown user: awx
sudo: unable to initialize policy plugin

Installing NGINX Configuration
/bin/cp: cannot stat '/usr/share/doc/ansible-awx/nginx.conf.example': No such file or directory

Configuring Redis
gpasswd: user 'awx' does not exist

Creating initial Ansible VENV
/bin/sh: awx-create-venv: command not found

Locking package versions for AWX-RPM and dependencies
Traceback (most recent call last):
  File "./awx-setup", line 373, in <module>
    main(sys.argv[1:])
  File "./awx-setup", line 304, in main
    with open("/usr/share/doc/ansible-awx/awx-locks.txt", "r") as a_file:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/doc/ansible-awx/awx-locks.txt'

**Comment by MrMEEE** [comment]
Could you please post the entire installation log...

**Comment by nikita199220** [comment]
sure:


[root@awxtest ~]# ./awx-setup -i

This is going to install AWX-RPM and all dependencies.. This installer is
meant to be easy, not customizable..

Check https://awx.wiki for advanced install methods and more info..

Do you want to continue?  [y/N] y

Setting up AWX-RPM

Configuring SELinux


ValueError: Port tcp/8050 already defined


Configuring Firewall (Disabling for now/TODO)


Configure Repositories

Adding EPEL


Adding AWX-RPM Repo

Installing Redis


Installing PostgreSQL


Installing Memcached


Installing NGINX


Installing AWX-RPM

Error: Transaction check error:

  file /usr/lib64/python3.6/site-packages/_
ruamel_yaml.cpython-36m-x86_64-linux-gnu.so conflicts between attempted
installs of python3-ruamel.yaml.clib-0.2.0-11.1.x86_64 and
python3-ruamel-yaml-0.15.41-2.el8.x86_64



Initialising PostgreSQL

WARNING: using obsoleted argument syntax, try --help

WARNING: arguments transformed to: postgresql-setup --initdb --unit
postgresql

 * Initializing database in '/var/lib/pgsql/data'

ERROR: Data directory /var/lib/pgsql/data is not empty!

ERROR: Initializing database failed, possibly see
/var/lib/pgsql/initdb_postgresql.log


Starting PostgreSQL


Creating AWX postgreSQL user and Database

could not change directory to "/root": Permission denied

createuser: creation of new role failed: ERROR:  role "awx" already exists


could not change directory to "/root": Permission denied

createdb: database creation failed: ERROR:  database "awx" already exists


Installing pwgen


Generating Secret key

/bin/sh: /etc/tower/SECRET_KEY: No such file or directory


Initial database migration

sudo: unknown user: awx

sudo: unable to initialize policy plugin


Creating Admin user

sudo: unknown user: awx

sudo: unable to initialize policy plugin


Adding example data and registering AWX-RPM Instance in database

sudo: unknown user: awx

sudo: unable to initialize policy plugin


sudo: unknown user: awx

sudo: unable to initialize policy plugin


sudo: unknown user: awx

sudo: unable to initialize policy plugin


Installing NGINX Configuration

/bin/cp: cannot stat '/usr/share/doc/ansible-awx/nginx.conf.example': No
such file or directory


Configuring Redis

gpasswd: user 'awx' does not exist


Creating initial Ansible VENV

/bin/sh: awx-create-venv: command not found


Locking package versions for AWX-RPM and dependencies

Traceback (most recent call last):

  File "./awx-setup", line 373, in <module>

    main(sys.argv[1:])

  File "./awx-setup", line 304, in main

    with open("/usr/share/doc/ansible-awx/awx-locks.txt", "r") as a_file:

FileNotFoundError: [Errno 2] No such file or directory:
'/usr/share/doc/ansible-awx/awx-locks.txt'

**Comment by nikita199220** [comment]
Now again i tried on one resh new server of Azure Centos 8.1

Again it is failing with below issue:

[root@awxnewrepo ~]# chmod +x awx-setup
[root@awxnewrepo ~]# ./awx-setup -i
This is going to install AWX-RPM and all dependencies.. This installer is meant to be easy, not customizable.. 
Check https://awx.wiki for advanced install methods and more info..
Do you want to continue?  [y/N] y
Setting up AWX-RPM
Configuring SELinux


Configuring Firewall (Disabling for now/TODO)

Configure Repositories
Adding EPEL

Adding AWX-RPM Repo
Installing Redis

Installing PostgreSQL

Installing Memcached

Installing NGINX

Installing AWX-RPM
Error: 
 Problem: problem with installed package vdo-6.2.1.134-11.el8.x86_64
  - package vdo-6.2.1.134-11.el8.x86_64 requires python3-PyYAML >= 3.10, but none of the providers can be installed
  - cannot install both python3-pyyaml-5.3.1-4.1.x86_64 and python3-pyyaml-3.12-12.el8.x86_64
  - package ansible-awx-11.2.0-12.1.x86_64 requires python3-pyyaml >= 5.3.1, but none of the providers can be installed
  - conflicting requests

Initialising PostgreSQL
WARNING: using obsoleted argument syntax, try --help
WARNING: arguments transformed to: postgresql-setup --initdb --unit postgresql
 * Initializing database in '/var/lib/pgsql/data'
 * Initialized, logs are in /var/lib/pgsql/initdb_postgresql.log

Starting PostgreSQL

Creating AWX postgreSQL user and Database
could not change directory to "/root": Permission denied

could not change directory to "/root": Permission denied

Installing pwgen
warning: /var/cache/dnf/epel-6519ee669354a484/packages/pwgen-2.08-3.el8.x86_64.rpm: Header V3 RSA/SHA256 Signature, key ID 2f86d6a1: NOKEY
Importing GPG key 0x2F86D6A1:
 Userid     : "Fedora EPEL (8) <epel@fedoraproject.org>"
 Fingerprint: 94E2 79EB 8D8F 25B2 1810 ADF1 21EA 45AB 2F86 D6A1
 From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-8

Generating Secret key
/bin/sh: /etc/tower/SECRET_KEY: No such file or directory

Initial database migration
sudo: unknown user: awx
sudo: unable to initialize policy plugin

Creating Admin user
sudo: unknown user: awx
sudo: unable to initialize policy plugin

Adding example data and registering AWX-RPM Instance in database
sudo: unknown user: awx
sudo: unable to initialize policy plugin

sudo: unknown user: awx
sudo: unable to initialize policy plugin

sudo: unknown user: awx
sudo: unable to initialize policy plugin

Installing NGINX Configuration
/bin/cp: cannot stat '/usr/share/doc/ansible-awx/nginx.conf.example': No such file or directory

Configuring Redis
gpasswd: user 'awx' does not exist

Creating initial Ansible VENV
/bin/sh: awx-create-venv: command not found

Locking package versions for AWX-RPM and dependencies
Traceback (most recent call last):
  File "./awx-setup", line 373, in <module>
    main(sys.argv[1:])
  File "./awx-setup", line 304, in main
    with open("/usr/share/doc/ansible-awx/awx-locks.txt", "r") as a_file:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/doc/ansible-awx/awx-locks.txt'
[root@awxnewrepo ~]#

**Comment by MrMEEE** [comment]
Could you try the installer again.. should be fixed now...

**Comment by nikita199220** [comment]
Hi,
I tested it with below build on centos 8:
https://github.com/MrMEEE/awx-build/files/4578637/awx-setup.zip
it is working perfect....Thanks

**Comment by MrMEEE** [comment]
Project has been updated and moved...

Please move to the new version and report any issues

PROJECT MOVED: https://github.com/miracle-as/AWX-RPM

Issues at: https://github.com/miracle-as/AWX-RPM/issues

**Install guide, tools, utilities are located at: https://awx.wiki

**LinkedIn group for Questions, support, talk and more: https://www.linkedin.com/groups/13694893/**
