### ISSUE TITLE
AWX 11 on RHEL8

### ISSUE THREAD

**Issue by Lobout** [MrMEEE/awx-build#241]
I see the following issues when attempting to install on RHEL8:

1.  Package conflict due to insights-client

Error:
 Problem: cannot install the best update candidate for package insights-client-3.0.13-1.el8_1.noarch
  - problem with installed package insights-client-3.0.13-1.el8_1.noarch
  - package insights-client-3.0.13-1.el8_1.noarch requires python3-PyYAML, but none of the providers can be installed
  - cannot install the best update candidate for package python3-pyyaml-3.12-12.el8.x86_64
  - cannot install both python3-pyyaml-5.3.1-4.1.x86_64 and python3-pyyaml-3.12-12.el8.x86_64
  - cannot install both python3-pyyaml-3.12-12.el8.x86_64 and python3-pyyaml-5.3.1-4.1.x86_64
(try to add '--skip-broken' to skip uninstallable packages)

2.  Package version conflicts with AWX package requirements

Installing AWX-RPM
Error:
 Problem: problem with installed package python3-ipalib-4.8.0-10.module+el8.1.0+4107+4a66eb87.noarch
  - package python3-ipalib-4.8.0-10.module+el8.1.0+4107+4a66eb87.noarch requires python3-pyasn1-modules >= 0.3.2-2, but none of the providers can be installed
  - package python3-ipalib-4.7.1-11.module+el8+2843+a16c4825.noarch requires python3-pyasn1-modules >= 0.3.2-2, but none of the providers can be installed
  - cannot install both python3-pyasn1-modules-0.2.8-3.1.noarch and python3-pyasn1-modules-0.3.7-6.el8.noarch
  - cannot install both python3-pyasn1-modules-0.3.7-6.el8.noarch and python3-pyasn1-modules-0.2.8-3.1.noarch
  - package ansible-awx-11.2.0-11.1.x86_64 requires python3-pyasn1-modules = 0.2.8, but none of the providers can be installed
  - conflicting requests
  - package python3-ipalib-4.8.0-11.module+el8.1.0+4247+9f3fd721.noarch is excluded
  - package python3-ipalib-4.7.1-11.module+el8+2842+7481110c.noarch is excluded
  - package python3-ipalib-4.8.0-13.module+el8.1.0+4923+c6efe041.noarch is excluded

It looks like you are not installing the EL8 specific packages as part of the awx-rpm requirments

**Comment by MrMEEE** [comment]
I was trying to tie down to the specific packages needed for AWX.. that is why I overload EL8/7 packages.. hmmm..

**Comment by MrMEEE** [comment]
Is the ipalib packages part of ipa-client?

**Comment by MrMEEE** [comment]
Could you try again.. I have loosened up the requirements

**Comment by Lobout** [comment]
> Is the ipalib packages part of ipa-client?

yes it is part of the ipa-client

**Comment by Lobout** [comment]
Same issue with RHEL8 python package conflicts.

**Comment by Lobout** [comment]
[rhel8_errors.txt](https://github.com/MrMEEE/awx-build/files/4587009/rhel8_errors.txt)

**Comment by Lobout** [comment]
install still fails on RHEL8.  first error is with insights python conflicts:
Installing AWX-RPM
Error:
 Problem: problem with installed package insights-client-3.0.13-1.el8_1.noarch
  - package insights-client-3.0.13-1.el8_1.noarch requires python3-PyYAML, but none of the providers can be installed
  - package insights-client-3.0.5-4.el8.noarch requires python3-PyYAML, but none of the providers can be installed
  - package insights-client-3.0.8-0.el8_0.noarch requires python3-PyYAML, but none of the providers can be installed
  - package insights-client-3.0.8-4.el8_1.noarch requires python3-PyYAML, but none of the providers can be installed
  - cannot install both python3-pyyaml-5.3.1-4.1.x86_64 and python3-pyyaml-3.12-12.el8.x86_64
  - cannot install both python3-pyyaml-3.12-12.el8.x86_64 and python3-pyyaml-5.3.1-4.1.x86_64
  - package ansible-awx-11.2.0-15.1.x86_64 requires python3-pyyaml >= 5.3.1, but none of the providers can be installed
  - conflicting requests


Then if i remove insights(which won't really fly in a production environment) I get the other packages


Error: Transaction check error:
  file /usr/lib/python3.6/site-packages/pyasn1/__init__.py from install of python36-pyasn1-0.4.8-4.1.noarch conflicts with file from package python3-pyasn1-0.3.7-6.el8.noarch
  file /usr/lib/python3.6/site-packages/pyasn1/__pycache__/__init__.cpython-36.opt-1.pyc from install of python36-pyasn1-0.4.8-4.1.noarch conflicts with file from package python3-pyasn1-0.3.7-6.el8.noarch
  file /usr/lib/python3.6/site-packages/pyasn1/__pycache__/__init__.cpython-36.pyc from install of python36-pyasn1-0.4.8-4.1.noarch conflicts with file from package python3-pyasn1-0.3.7-6.el8.noarch
  file /usr/lib/python3.6/site-packages/pyasn1/__pycache__/debug.cpython-36.opt-1.pyc from install of python36-pyasn1-0.4.8-4.1.noarch conflicts with file from package python3-pyasn1-0.3.7-6.el8.noarch
  file /usr/lib/python3.6/site-packages/pyasn1/__pycache__/debug.cpython-36.pyc from install of python36-pyasn1-0.4.8-4.1.noarch conflicts with file from package python3-pyasn1-0.3.7-6.el8.noarch
  file /usr/lib/python3.6/site-packages/pyasn1/__pycache__/error.cpython-36.opt-1.pyc from install of python36-pyasn1-0.4.8-4.1.noarch conflicts with file from package python3-pyasn1-0.3.7-6.el8.noarch
  file /usr/lib/python3.6/site-packages/pyasn1/__pycache__/error.cpython-36.pyc from install of python36-pyasn1-0.4.8-4.1.noarch conflicts with file from package python3-pyasn1-0.3.7-6.el8.noarch
  file /usr/lib/python3.6/site-packages/pyasn1/codec/__pycache__/__init__.cpython-36.opt-1.pyc from install of python36-pyasn1-0.4.8-4.1.noarch conflicts with file from package python3-pyasn1-0.3.7-6.el8.noarch
  file /usr/lib/python3.6/site-packages/pyasn1/codec/__pycache__/__init__.cpython-36.pyc from install of python36-pyasn1-0.4.8-4.1.noarch conflicts with file from package python3-pyasn1-0.3.7-6.el8.noarch
  file /usr/lib/python3.6/site-packages/pyasn1/codec/ber/__pycache__/__init__.cpython-36.opt-1.pyc from install of python36-pyasn1-0.4.8-4.1.noarch conflicts with file from package python3-pyasn1-0.3.

**Comment by MrMEEE** [comment]
Project has been updated and moved...

Please move to the new version and report any issues

PROJECT MOVED: https://github.com/miracle-as/AWX-RPM

Issues at: https://github.com/miracle-as/AWX-RPM/issues

**Install guide, tools, utilities are located at: https://awx.wiki

**LinkedIn group for Questions, support, talk and more: https://www.linkedin.com/groups/13694893/**
