### ISSUE TITLE
Getting this Virtual ENV error on CentOS7.8 installation.

### ISSUE THREAD

**Issue by kim98356** [MrMEEE/awx-build#244]
Creating initial Ansible VENV
/bin/sh: virtualenv: command not found
/bin/sh: /var/lib/awx/venv/python3-ansible2.9.7-852020/bin/pip3: No such file or directory
/bin/sh: /var/lib/awx/venv/python3-ansible2.9.7-852020/bin/pip3: No such file or directory
/bin/sh: /var/lib/awx/venv/python3-ansible2.9.7-852020/bin/pip3: No such file or directory
/bin/sh: /var/lib/awx/venv/python3-ansible2.9.7-852020/bin/pip3: No such file or directory
/bin/sh: /var/lib/awx/venv/python3-ansible2.9.7-852020/bin/pip3: No such file or directory
/bin/sh: /var/lib/awx/venv/python3-ansible2.9.7-852020/bin/pip3: No such file or directory
/bin/sh: /var/lib/awx/venv/python3-ansible2.9.7-852020/bin/pip3: No such file or directory
...
/bin/sh: /var/lib/awx/venv/python3-ansible2.9.7-852020/bin/pip3: No such file or directory
/bin/sh: /var/lib/awx/venv/python3-ansible2.9.7-852020/bin/pip3: No such file or directory

Create Virtual Enviroment at:
  /var/lib/awx/venv/python3-ansible2.9.7-852020

Using Python 3

Installing Ansible 2.9.7
   
No default Ansible is set, using this environment: /var/lib/awx/venv/python3-ansible2.9.7-852020
------------------
[root@ynblixvlpawx01 venv]# ls -la
total 0
drwxr-xr-x 2 awx  awx  20 May  8 02:38 .
drwxr-xr-x 6 awx  awx  97 May  8 02:39 ..
lrwxrwxrwx 1 root root 45 May  8 02:38 ansible -> /var/lib/awx/venv/python3-ansible2.9.7-852020

[root@ynblixvlpawx01 venv]# ls -la /var/lib/awx/venv/python3-ansible2.9.7-852020
ls: cannot access /var/lib/awx/venv/python3-ansible2.9.7-852020: No such file or directory

[root@ynblixvlpawx01 venv]# which ansible
/bin/ansible

[root@ynblixvlpawx01 venv]# ansible --version
ansible 2.9.7
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Apr  2 2020, 13:16:51) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

**Comment by MrMEEE** [comment]
Please try the installer again..

**Comment by kim98356** [comment]
VENVs look good now.  The reinstallation was completed w/o any errors.
-------------------------------
[root@ynblixvlpawx02 src]# ls -la /var/lib/awx/venv/
total 0
drwxr-xr-x 3 awx  awx  54 May  9 22:41 .
drwxr-xr-x 6 awx  awx  97 May  9 22:42 ..
lrwxrwxrwx 1 root root 45 May  9 22:41 ansible -> /var/lib/awx/venv/python3-ansible2.9.7-952020
drwxr-xr-x 6 root root 89 May  9 22:40 python3-ansible2.9.7-952020
[root@ynblixvlpawx02 src]# ls -la /var/lib/awx/venv/python3-ansible2.9.7-952020/
total 8
drwxr-xr-x 6 root root   89 May  9 22:40 .
drwxr-xr-x 3 awx  awx    54 May  9 22:41 ..
drwxr-xr-x 3 root root 4096 May  9 22:40 bin
drwxr-xr-x 2 root root   23 May  9 22:37 include
drwxr-xr-x 3 root root   22 May  9 22:37 lib
lrwxrwxrwx 1 root root    3 May  9 22:37 lib64 -> lib
-rw-r--r-- 1 root root   59 May  9 22:37 pip-selfcheck.json
drwxr-xr-x 3 root root   16 May  9 22:40 share
[root@ynblixvlpawx02 src]# 
-----------

Thanks!

**Comment by MrMEEE** [comment]
Project has been updated and moved...

Please move to the new version and report any issues

PROJECT MOVED: https://github.com/miracle-as/AWX-RPM

Issues at: https://github.com/miracle-as/AWX-RPM/issues

**Install guide, tools, utilities are located at: https://awx.wiki

**LinkedIn group for Questions, support, talk and more: https://www.linkedin.com/groups/13694893/**
