### ISSUE TITLE
Unable to install awx

### ISSUE THREAD

**Issue by ghost** [MrMEEE/awx-build#25]
-bash-4.2# ls -lrt  /etc/yum.repos.d/
total 44
-rw-r--r--. 1 root root 1012 Sep 20  2016 pgdg-96-centos.repo
-rw-r--r--. 1 root root 3830 Aug 30  2017 CentOS-Vault.repo
-rw-r--r--. 1 root root 1331 Aug 30  2017 CentOS-Sources.repo
-rw-r--r--. 1 root root  630 Aug 30  2017 CentOS-Media.repo
-rw-r--r--. 1 root root  314 Aug 30  2017 CentOS-fasttrack.repo
-rw-r--r--. 1 root root  649 Aug 30  2017 CentOS-Debuginfo.repo
-rw-r--r--. 1 root root 1309 Aug 30  2017 CentOS-CR.repo
-rw-r--r--. 1 root root 1664 Aug 30  2017 CentOS-Base.repo
-rw-r--r--. 1 root root 1050 Oct  2  2017 epel-testing.repo
-rw-r--r--. 1 root root  951 Oct  2  2017 epel.repo
-rw-r--r--. 1 root root  212 Jun  2 19:31 rabbitmq-erlang.repo
-bash-4.2# yum install -y awx
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: linux.mirrors.es.net
 * epel: linux.mirrors.es.net
 * extras: mirror.centos.org
 * updates: mirror.centos.org
No package awx available.
Error: Nothing to do
-bash-4.2#

**Comment by MrMEEE** [comment]
Have you remembered to run this command:


wget -O /etc/yum.repos.d/awx-rpm.repo https://copr.fedorainfracloud.org/coprs/mrmeee/awx-dev/repo/epel-7/mrmeee-awx-dev-epel-7.repo

**Comment by ghost** [comment]
Sorry ... It is my bad ... I forget to run the above wget command. Thanks for your quick help and support.

**Comment by ghost** [comment]
Another issue : 


-bash-4.2# sudo -u awx /opt/awx/bin/awx-manage create_preload_data
Traceback (most recent call last):
  File "/opt/awx/bin/awx-manage", line 11, in <module>
    sys.exit(manage())
  File "/opt/awx/embedded/lib/python2.7/site-packages/awx/__init__.py", line 109, in manage
    execute_from_command_line(sys.argv)
  File "/opt/awx/embedded/lib64/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/opt/awx/embedded/lib64/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/awx/embedded/lib64/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/awx/embedded/lib64/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/opt/awx/embedded/lib/python2.7/site-packages/awx/main/management/commands/create_preload_data.py", line 47, in handle
    created_by=superuser)
  File "/opt/awx/embedded/lib64/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/awx/embedded/lib64/python2.7/site-packages/django/db/models/query.py", line 394, in create
    obj.save(force_insert=True, using=self.db)
  File "/opt/awx/embedded/lib/python2.7/site-packages/awx/main/models/inventory.py", line 700, in save
    super(Host, self).save(*args, **kwargs)
  File "/opt/awx/embedded/lib/python2.7/site-packages/awx/main/models/base.py", line 275, in save
    super(PrimordialModel, self).save(*args, **kwargs)
  File "/opt/awx/embedded/lib/python2.7/site-packages/awx/main/models/base.py", line 164, in save
    super(CreatedModifiedModel, self).save(*args, **kwargs)
  File "/opt/awx/embedded/lib64/python2.7/site-packages/django/db/models/base.py", line 808, in save
    force_update=force_update, update_fields=update_fields)
  File "/opt/awx/embedded/lib64/python2.7/site-packages/django/db/models/base.py", line 848, in save_base
    update_fields=update_fields, raw=raw, using=using,
  File "/opt/awx/embedded/lib64/python2.7/site-packages/django/dispatch/dispatcher.py", line 193, in send
    for receiver in self._live_receivers(sender)
  File "/opt/awx/embedded/lib/python2.7/site-packages/awx/main/signals.py", line 146, in emit_update_inventory_on_created_or_deleted
    update_inventory_computed_fields.delay(inventory.id, True)
  File "/opt/awx/embedded/lib/python2.7/site-packages/celery/app/task.py", line 461, in delay
    return self.apply_async(args, kwargs)
  File "/opt/awx/embedded/lib/python2.7/site-packages/celery/app/task.py", line 573, in apply_async
    **dict(self._get_exec_options(), **options)
  File "/opt/awx/embedded/lib/python2.7/site-packages/celery/app/base.py", line 345, in send_task
    options = router.route(options, name, args, kwargs)
  File "/opt/awx/embedded/lib/python2.7/site-packages/celery/app/routes.py", line 50, in route
    route = self.lookup_route(task, args, kwargs)
  File "/opt/awx/embedded/lib/python2.7/site-packages/celery/app/routes.py", line 78, in lookup_route
    return _first_route(self.routes, task, args, kwargs)
  File "/opt/awx/embedded/lib/python2.7/site-packages/celery/utils/functional.py", line 233, in _matcher
    answer = getattr(maybe_evaluate(obj), method)(*args, **kwargs)
  File "/opt/awx/embedded/lib/python2.7/site-packages/awx/main/utils/ha.py", line 58, in route_for_task
    (changed, instance) = Instance.objects.get_or_register()
  File "/opt/awx/embedded/lib/python2.7/site-packages/awx/main/managers.py", line 106, in get_or_register
    return (False, self.me())
  File "/opt/awx/embedded/lib/python2.7/site-packages/awx/main/managers.py", line 88, in me
    raise RuntimeError("No instance found with the current cluster host id")
RuntimeError: No instance found with the current cluster host id
-bash-4.2#

**Comment by ghost** [comment]
-bash-4.2# cat /etc/hosts
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
192.168.0.51 centos2
-bash-4.2# cat /etc/hostname
centos2
-bash-4.2# hostname -f
centos2
-bash-4.2#

**Comment by ghost** [comment]
Now different issue 
-bash-4.2# systemctl status nginx.service
● nginx.service - The nginx HTTP and reverse proxy server
   Loaded: loaded (/usr/lib/systemd/system/nginx.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Sat 2018-06-02 23:17:56 BST; 8s ago
  Process: 13455 ExecStartPre=/usr/sbin/nginx -t (code=exited, status=1/FAILURE)
  Process: 13453 ExecStartPre=/usr/bin/rm -f /run/nginx.pid (code=exited, status=0/SUCCESS)

Jun 02 23:17:56 centos2 systemd[1]: Starting The nginx HTTP and reverse proxy server...
Jun 02 23:17:56 centos2 nginx[13455]: nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
Jun 02 23:17:56 centos2 nginx[13455]: nginx: [emerg] bind() to 0.0.0.0:8052 failed (13: Permission denied)
Jun 02 23:17:56 centos2 nginx[13455]: nginx: configuration file /etc/nginx/nginx.conf test failed
Jun 02 23:17:56 centos2 systemd[1]: nginx.service: control process exited, code=exited status=1
Jun 02 23:17:56 centos2 systemd[1]: Failed to start The nginx HTTP and reverse proxy server.
Jun 02 23:17:56 centos2 systemd[1]: Unit nginx.service entered failed state.
Jun 02 23:17:56 centos2 systemd[1]: nginx.service failed.
-bash-4.2#

**Comment by ghost** [comment]
All the components and packages are installed, started and verified. 

-bash-4.2# systemctl status rabbitmq-server
● rabbitmq-server.service - RabbitMQ broker
   Loaded: loaded (/usr/lib/systemd/system/rabbitmq-server.service; enabled; vendor preset: disabled)
   Active: active (running) since Sun 2018-06-03 02:20:00 BST; 2h 46min ago
 Main PID: 1023 (beam.smp)
   Status: "Initialized"
   CGroup: /system.slice/rabbitmq-server.service
           ├─1023 /usr/lib64/erlang/erts-9.3.1/bin/beam.smp -W w -A 64 -P 1048576 -t 5000000 -stbt db -zdbbl 1280000 -K true -- -root /u...
           ├─1349 /usr/lib64/erlang/erts-9.3.1/bin/epmd -daemon
           ├─1583 erl_child_setup 1024
           ├─1645 inet_gethost 4
           └─1646 inet_gethost 4

Jun 03 02:19:56 centos2 rabbitmq-server[1023]: ##  ##
Jun 03 02:19:56 centos2 rabbitmq-server[1023]: ##  ##      RabbitMQ 3.7.5. Copyright (C) 2007-2018 Pivotal Software, Inc.
Jun 03 02:19:56 centos2 rabbitmq-server[1023]: ##########  Licensed under the MPL.  See http://www.rabbitmq.com/
Jun 03 02:19:56 centos2 rabbitmq-server[1023]: ######  ##
Jun 03 02:19:56 centos2 rabbitmq-server[1023]: ##########  Logs: /var/log/rabbitmq/rabbit@centos2.log
Jun 03 02:19:56 centos2 rabbitmq-server[1023]: /var/log/rabbitmq/rabbit@centos2_upgrade.log
Jun 03 02:19:56 centos2 rabbitmq-server[1023]: Starting broker...
Jun 03 02:20:00 centos2 rabbitmq-server[1023]: systemd unit for activation check: "rabbitmq-server.service"
Jun 03 02:20:00 centos2 systemd[1]: Started RabbitMQ broker.
Jun 03 02:20:02 centos2 rabbitmq-server[1023]: completed with 0 plugins.
-bash-4.2# systemctl status postgresql-9.6
● postgresql-9.6.service - PostgreSQL 9.6 database server
   Loaded: loaded (/usr/lib/systemd/system/postgresql-9.6.service; enabled; vendor preset: disabled)
   Active: active (running) since Sun 2018-06-03 02:19:28 BST; 2h 46min ago
     Docs: https://www.postgresql.org/docs/9.6/static/
  Process: 1015 ExecStartPre=/usr/pgsql-9.6/bin/postgresql96-check-db-dir ${PGDATA} (code=exited, status=0/SUCCESS)
 Main PID: 1071 (postmaster)
   CGroup: /system.slice/postgresql-9.6.service
           ├─1071 /usr/pgsql-9.6/bin/postmaster -D /var/lib/pgsql/9.6/data/
           ├─1175 postgres: logger process
           ├─1219 postgres: checkpointer process
           ├─1220 postgres: writer process
           ├─1221 postgres: wal writer process
           ├─1222 postgres: autovacuum launcher process
           ├─1223 postgres: stats collector process
           ├─1626 postgres: awx awx [local] idle
           ├─1633 postgres: awx awx [local] idle
           └─1665 postgres: awx awx [local] idle

Jun 03 02:19:25 centos2 systemd[1]: Starting PostgreSQL 9.6 database server...
Jun 03 02:19:27 centos2 postmaster[1071]: < 2018-06-03 02:19:27.809 BST > LOG:  redirecting log output to logging collector process
Jun 03 02:19:27 centos2 postmaster[1071]: < 2018-06-03 02:19:27.809 BST > HINT:  Future log output will appear in directory "pg_log".
Jun 03 02:19:28 centos2 systemd[1]: Started PostgreSQL 9.6 database server.
-bash-4.2# systemctl status memcached
● memcached.service - Memcached
   Loaded: loaded (/usr/lib/systemd/system/memcached.service; enabled; vendor preset: disabled)
   Active: active (running) since Sun 2018-06-03 02:19:25 BST; 2h 46min ago
 Main PID: 1019 (memcached)
   CGroup: /system.slice/memcached.service
           └─1019 /usr/bin/memcached -u memcached -p 11211 -m 64 -c 1024

Jun 03 02:19:25 centos2 systemd[1]: Started Memcached.
Jun 03 02:19:25 centos2 systemd[1]: Starting Memcached...
-bash-4.2# systemctl status nginx
● nginx.service - The nginx HTTP and reverse proxy server
   Loaded: loaded (/usr/lib/systemd/system/nginx.service; enabled; vendor preset: disabled)
   Active: active (running) since Sun 2018-06-03 02:19:26 BST; 2h 46min ago
  Process: 1077 ExecStart=/usr/sbin/nginx (code=exited, status=0/SUCCESS)
  Process: 1028 ExecStartPre=/usr/sbin/nginx -t (code=exited, status=0/SUCCESS)
  Process: 1022 ExecStartPre=/usr/bin/rm -f /run/nginx.pid (code=exited, status=0/SUCCESS)
 Main PID: 1079 (nginx)
   CGroup: /system.slice/nginx.service
           ├─1079 nginx: master process /usr/sbin/nginx
           └─1080 nginx: worker process

Jun 03 02:19:25 centos2 systemd[1]: Starting The nginx HTTP and reverse proxy server...
Jun 03 02:19:26 centos2 nginx[1028]: nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
Jun 03 02:19:26 centos2 nginx[1028]: nginx: configuration file /etc/nginx/nginx.conf test is successful
Jun 03 02:19:26 centos2 systemd[1]: Failed to read PID from file /run/nginx.pid: Invalid argument
Jun 03 02:19:26 centos2 systemd[1]: Started The nginx HTTP and reverse proxy server.
-bash-4.2# systemctl status awx-cbreceiver
● awx-cbreceiver.service - AWX cbreceiver service
   Loaded: loaded (/usr/lib/systemd/system/awx-cbreceiver.service; enabled; vendor preset: disabled)
   Active: active (running) since Sun 2018-06-03 02:19:25 BST; 2h 46min ago
 Main PID: 1013 (python2)
   CGroup: /system.slice/awx-cbreceiver.service
           ├─1013 python2 /opt/awx/bin/awx-manage run_callback_receiver
           ├─1628 python2 /opt/awx/bin/awx-manage run_callback_receiver
           ├─1629 python2 /opt/awx/bin/awx-manage run_callback_receiver
           ├─1630 python2 /opt/awx/bin/awx-manage run_callback_receiver
           └─1631 python2 /opt/awx/bin/awx-manage run_callback_receiver

Jun 03 02:19:25 centos2 systemd[1]: Started AWX cbreceiver service.
Jun 03 02:19:25 centos2 systemd[1]: Starting AWX cbreceiver service...
-bash-4.2# systemctl status awx-celery-beat
● awx-celery-beat.service - AWX Celery beat service
   Loaded: loaded (/usr/lib/systemd/system/awx-celery-beat.service; enabled; vendor preset: disabled)
   Active: active (running) since Sun 2018-06-03 02:19:25 BST; 2h 46min ago
 Main PID: 1026 (python2)
   CGroup: /system.slice/awx-celery-beat.service
           └─1026 python2 /opt/awx/bin/celery beat -A awx -l info --pidfile= -s /var/lib/awx/beat.db

Jun 03 05:04:44 centos2 celery[1026]: [2018-06-03 04:04:44,446: INFO/MainProcess] Scheduler: Sending due task task_manager (awx....manager)
Jun 03 05:05:02 centos2 celery[1026]: [2018-06-03 04:05:02,506: INFO/MainProcess] Scheduler: Sending due task cluster_heartbeat ...artbeat)
Jun 03 05:05:02 centos2 celery[1026]: [2018-06-03 04:05:02,520: INFO/MainProcess] Scheduler: Sending due task tower_scheduler (a...heduler)
Jun 03 05:05:04 centos2 celery[1026]: [2018-06-03 04:05:04,447: INFO/MainProcess] Scheduler: Sending due task task_manager (awx....manager)
Jun 03 05:05:06 centos2 celery[1026]: [2018-06-03 04:05:06,727: INFO/MainProcess] Scheduler: Sending due task isolated_heartbeat...artbeat)
Jun 03 05:05:24 centos2 celery[1026]: [2018-06-03 04:05:24,451: INFO/MainProcess] Scheduler: Sending due task task_manager (awx....manager)
Jun 03 05:05:32 centos2 celery[1026]: [2018-06-03 04:05:32,521: INFO/MainProcess] Scheduler: Sending due task tower_scheduler (a...heduler)
Jun 03 05:05:44 centos2 celery[1026]: [2018-06-03 04:05:44,459: INFO/MainProcess] Scheduler: Sending due task task_manager (awx....manager)
Jun 03 05:06:02 centos2 celery[1026]: [2018-06-03 04:06:02,506: INFO/MainProcess] Scheduler: Sending due task cluster_heartbeat ...artbeat)
Jun 03 05:06:02 centos2 celery[1026]: [2018-06-03 04:06:02,521: INFO/MainProcess] Scheduler: Sending due task tower_scheduler (a...heduler)
Hint: Some lines were ellipsized, use -l to show in full.
-bash-4.2# systemctl status awx-celery-worker
● awx-celery-worker.service - AWX Celery worker service
   Loaded: loaded (/usr/lib/systemd/system/awx-celery-worker.service; enabled; vendor preset: disabled)
   Active: active (running) since Sun 2018-06-03 02:19:25 BST; 2h 46min ago
 Main PID: 1012 (python2)
   CGroup: /system.slice/awx-celery-worker.service
           ├─ 1012 python2 /opt/awx/bin/celery worker -A awx -B -l info --autoscale=50,4 -Ofair -s /var/lib/awx/beat.db -n celery@%(ENV_...
           ├─ 1638 python2 /opt/awx/bin/celery worker -A awx -B -l info --autoscale=50,4 -Ofair -s /var/lib/awx/beat.db -n celery@%(ENV_...
           ├─12555 python2 /opt/awx/bin/celery worker -A awx -B -l info --autoscale=50,4 -Ofair -s /var/lib/awx/beat.db -n celery@%(ENV_...
           ├─12563 python2 /opt/awx/bin/celery worker -A awx -B -l info --autoscale=50,4 -Ofair -s /var/lib/awx/beat.db -n celery@%(ENV_...
           └─12564 python2 /opt/awx/bin/celery worker -A awx -B -l info --autoscale=50,4 -Ofair -s /var/lib/awx/beat.db -n celery@%(ENV_...

Jun 03 05:05:45 centos2 celery[1012]: 2018-06-03 04:05:45,191 DEBUG    awx.main.scheduler Starting Scheduler
Jun 03 05:05:45 centos2 celery[1012]: [2018-06-03 04:05:45,210: INFO/MainProcess] Task awx.main.scheduler.tasks.run_task_manager...1s: None
Jun 03 05:06:02 centos2 celery[1012]: [2018-06-03 04:06:02,511: INFO/MainProcess] Received task: awx.main.tasks.cluster_node_hea...3+00:00]
Jun 03 05:06:02 centos2 celery[1012]: [2018-06-03 04:06:02,529: INFO/MainProcess] Received task: awx.main.tasks.awx_periodic_sch...7+00:00]
Jun 03 05:06:02 centos2 celery[1012]: [2018-06-03 04:06:02,529: INFO/MainProcess] Scaling up 1 processes.
Jun 03 05:06:02 centos2 celery[1012]: [2018-06-03 04:06:02,821: INFO/MainProcess] Received task: awx.main.tasks.handle_ha_toplog...8836eab]
Jun 03 05:06:02 centos2 celery[1012]: [2018-06-03 04:06:02,822: INFO/MainProcess] Scaling up 1 processes.
Jun 03 05:06:02 centos2 celery[1012]: [2018-06-03 04:06:02,965: INFO/MainProcess] Task awx.main.tasks.cluster_node_heartbeat[26b...9s: None
Jun 03 05:06:03 centos2 celery[1012]: [2018-06-03 04:06:03,020: INFO/MainProcess] Task awx.main.tasks.awx_periodic_scheduler[4fc...4s: None
Jun 03 05:06:03 centos2 celery[1012]: [2018-06-03 04:06:03,039: INFO/MainProcess] Task awx.main.tasks.handle_ha_toplogy_changes[...8s: None
Hint: Some lines were ellipsized, use -l to show in full.
-bash-4.2# systemctl status awx-channels-worker
● awx-channels-worker.service - AWX channels worker service
   Loaded: loaded (/usr/lib/systemd/system/awx-channels-worker.service; enabled; vendor preset: disabled)
   Active: active (running) since Sun 2018-06-03 02:20:00 BST; 2h 46min ago
 Main PID: 1652 (python2)
   CGroup: /system.slice/awx-channels-worker.service
           └─1652 python2 /opt/awx/bin/awx-manage runworker --only-channels websocket.*

Jun 03 02:20:00 centos2 systemd[1]: awx-channels-worker.service holdoff time over, scheduling restart.
Jun 03 02:20:00 centos2 systemd[1]: Started AWX channels worker service.
Jun 03 02:20:00 centos2 systemd[1]: Starting AWX channels worker service...
Jun 03 02:20:02 centos2 awx-manage[1652]: 2018-06-03 01:20:02,867 - INFO - runworker - Using single-threaded worker.
Jun 03 02:20:02 centos2 awx-manage[1652]: 2018-06-03 01:20:02,867 - INFO - runworker - Running worker against channel layer defau...lLayer)
Jun 03 02:20:02 centos2 awx-manage[1652]: 2018-06-03 01:20:02,868 - INFO - worker - Listening on channels websocket.connect, webs...receive
Hint: Some lines were ellipsized, use -l to show in full.
-bash-4.2# systemctl status awx-daphne
● awx-daphne.service - AWX daphne service
   Loaded: loaded (/usr/lib/systemd/system/awx-daphne.service; enabled; vendor preset: disabled)
   Active: active (running) since Sun 2018-06-03 02:19:25 BST; 2h 46min ago
 Main PID: 1021 (python2)
   CGroup: /system.slice/awx-daphne.service
           └─1021 python2 /opt/awx/bin/daphne -b 127.0.0.1 -p 8051 awx.asgi:channel_layer

Jun 03 02:19:25 centos2 systemd[1]: Started AWX daphne service.
Jun 03 02:19:25 centos2 systemd[1]: Starting AWX daphne service...
Jun 03 02:19:53 centos2 daphne[1021]: 2018-06-03 01:19:53,431 INFO     Starting server at tcp:port=8051:interface=127.0.0.1, cha...l_layer.
Jun 03 02:19:53 centos2 daphne[1021]: 2018-06-03 01:19:53,431 INFO     HTTP/2 support not enabled (install the http2 and tls Twi... extras)
Jun 03 02:19:53 centos2 daphne[1021]: 2018-06-03 01:19:53,432 INFO     Using busy-loop synchronous mode on channel layer
Jun 03 02:19:53 centos2 daphne[1021]: 2018-06-03 01:19:53,432 INFO     Listening on endpoint tcp:port=8051:interface=127.0.0.1
Jun 03 02:19:53 centos2 daphne[1021]: 2018-06-03 01:19:53,507 ERROR    Error trying to receive messages: [Errno 111] Connection refused
Jun 03 02:19:58 centos2 daphne[1021]: 2018-06-03 01:19:58,514 ERROR    Error trying to receive messages: [Errno 111] Connection refused
Hint: Some lines were ellipsized, use -l to show in full.
-bash-4.2# systemctl status awx-web
● awx-web.service - AWX web service
   Loaded: loaded (/usr/lib/systemd/system/awx-web.service; enabled; vendor preset: disabled)
   Active: active (running) since Sun 2018-06-03 02:19:25 BST; 2h 46min ago
 Main PID: 1024 (uwsgi)
   CGroup: /system.slice/awx-web.service
           ├─1024 /opt/awx/bin/uwsgi --socket 127.0.0.1:8050 --module=awx.wsgi:application --logto=/var/log/awx/web.log --die-on-term --...
           ├─1036 /opt/awx/bin/uwsgi --socket 127.0.0.1:8050 --module=awx.wsgi:application --logto=/var/log/awx/web.log --die-on-term --...
           ├─1037 /opt/awx/bin/uwsgi --socket 127.0.0.1:8050 --module=awx.wsgi:application --logto=/var/log/awx/web.log --die-on-term --...
           ├─1038 /opt/awx/bin/uwsgi --socket 127.0.0.1:8050 --module=awx.wsgi:application --logto=/var/log/awx/web.log --die-on-term --...
           ├─1039 /opt/awx/bin/uwsgi --socket 127.0.0.1:8050 --module=awx.wsgi:application --logto=/var/log/awx/web.log --die-on-term --...
           └─1040 /opt/awx/bin/uwsgi --socket 127.0.0.1:8050 --module=awx.wsgi:application --logto=/var/log/awx/web.log --die-on-term --...

Jun 03 02:19:25 centos2 systemd[1]: Started AWX web service.
Jun 03 02:19:25 centos2 systemd[1]: Starting AWX web service...
-bash-4.2#


But http://<hostname>:8052 or  http://<hostname>:8050 are not working. 

Please help.

**Comment by MrMEEE** [comment]
RTFM: Disable SELinux and Firewall.. or make policies and rules
