### ISSUE TITLE
virtual environment failure on v11.2

### ISSUE THREAD

**Issue by Lobout** [MrMEEE/awx-build#250]
looks like some modules are being depreciated.  not sure if this is an issue you can resolve or if it is a virtual environment build issue

ERROR: Command errored out with exit status 1:
     command: /var/lib/awx/venv/python3-ansible2.9.9-1952020/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-2wn3dcgo/azure-storage/setup.py'"'"'; __file__='"'"'/tmp/pip-install-2wn3dcgo/azure-storage/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-wmlx50e2
         cwd: /tmp/pip-install-2wn3dcgo/azure-storage/
    Complete output (19 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-2wn3dcgo/azure-storage/setup.py", line 55, in <module>
        raise RuntimeError(message)
    RuntimeError:

    Starting with v0.37.0, the 'azure-storage' meta-package is deprecated and cannot be installed anymore.
    Please install the service specific packages prefixed by `azure` needed for your application.

    The complete list of available packages can be found at:
    https://aka.ms/azsdk/python/all

    Here's a non-exhaustive list of common packages:

    - [azure-storage-blob](https://pypi.org/project/azure-storage-blob) : Blob storage client
    - [azure-storage-file-share](https://pypi.org/project/azure-storage-file-share) : Storage file share client
    - [azure-storage-file-datalake](https://pypi.org/project/azure-storage-file-datalake) : ADLS Gen2 client
    - [azure-storage-queue](https://pypi.org/project/azure-storage-queue): Queue storage client

    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by nilsrb** [comment]
Used the awx-setup-script today and got the same error message...

**Comment by bryanasdev000** [comment]
I had this problem too, I imagine it is some library that has to be updated in requirements.txt. Even so after waiting a few moments the installation apparently happened OK and the AWX was up and running.

NOTE: Issue #247 deals with the same subject.

**Comment by MrMEEE** [comment]
Project has been updated and moved...

Please move to the new version and report any issues

PROJECT MOVED: https://github.com/miracle-as/AWX-RPM

Issues at: https://github.com/miracle-as/AWX-RPM/issues

**Install guide, tools, utilities are located at: https://awx.wiki

**LinkedIn group for Questions, support, talk and more: https://www.linkedin.com/groups/13694893/**
