### ISSUE TITLE
python3-docutils package not built for CentOS8

### ISSUE THREAD

**Issue by cbetan** [MrMEEE/awx-build#252]
Although the source package exists for [python3-docutils](https://rpm.miracle.dk/AWX-RPM/CentOS_8/src/python3-docutils-0.16-3.3.src.rpm) in the src folder of CentOS8 repository, the corresponding package is not present in the "[binary](https://rpm.miracle.dk/AWX-RPM/CentOS_8/x86_64/)" folder.

It looks like the build process didn't build this package.

The installation of ansible-awx package in CentOS fails with the following message:

> Error: 
>  Problem: package ansible-awx-11.2.0-20.1.x86_64 requires python3-docutils = 0.16, but none of the providers can be installed
>   - conflicting requests
>   - package python3-docutils-0.16-3.3.noarch is excluded

Looking into the yum info, the Architecture is set to "src". Weird:

> yum info python3-docutils
> Name         : python3-docutils
> Version      : 0.16
> Release      : 3.3
> **Architecture : src**
> Size         : 1.9 M
> Source       : None
> **Repository   : ansible-awx**
> Summary      : Docutils -- Python Documentation Utilities
> URL          : http://docutils.sourceforge.net/
> License      : public domain, Python, 2-Clause BSD, GPL 3 (see COPYING.txt)
> Description  : Docutils is a modular system for processing documentation
>              : into useful formats, such as HTML, XML, and LaTeX.  For
>              : input Docutils supports reStructuredText, an easy-to-read,
>              : what-you-see-is-what-you-get plaintext markup syntax.

**This issue only affects CentOS8** -- the python3-docutils package is indeed present in the CentOS7 repository.

**Comment by MrMEEE** [comment]
it's right here? -> https://rpm.miracle.dk/AWX-RPM/CentOS_8/noarch/python3-docutils-0.16-3.3.noarch.rpm

**Comment by cbetan** [comment]
Oops... I was looking for it in the x86_64 folder. 

Still, I wonder why the installation of ansible-awx cannot resolve the dependency. 

Perhaps I should add an extra repository pointing to the “noarch” architecture folder?

Or perhaps the repodata is not up to date, and thus yum cannot find the binary package?

**Comment by cbetan** [comment]
I found the root cause: the package python3-docutils also exists in the AppStream repository, but it is a lower version (v0.14). It looks like the AppStream repository has higher precedence. 

The ansible-awx package required python3-docutils = 0.16 but the system tries to install 0.14 from AppStream.

The solution is to add "module_hotfixes=True" to the Ansible AWX repository definition.

This was already **solved in the awx-setup python installer**, which I was not using. My bad.

Thanks for your help, and for the awesome work on AWX-RPM!
