### ISSUE TITLE
Installation AWX on CentOS 7.8.2003

### ISSUE THREAD

**Issue by sdechasajja** [MrMEEE/awx-build#254]
I would like to install AWX on CentOS 7.8.2003 (Core). But I got stuck at below step. Could you please advise? 

**step**
yum -y install --disablerepo='*' --enablerepo='copr:copr.fedorainfracloud.org:mrmeee:ansible-awx, base' -x *-debuginfo rh-python36*

**Transaction check error:**
  file /opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/msgpack/__init__.py conflicts between attempted installs of rh-python36-msgpack-python-0.5.6-1.x86_64 and rh-python36-msgpack-0.6.2-1.x86_64
  file /opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/msgpack/__pycache__/__init__.cpython-36.opt-1.pyc conflicts between attempted installs of rh-python36-msgpack-python-0.5.6-1.x86_64 and rh-python36-msgpack-0.6.2-1.x86_64
  file /opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/msgpack/__pycache__/__init__.cpython-36.pyc conflicts between attempted installs of rh-python36-msgpack-python-0.5.6-1.x86_64 and rh-python36-msgpack-0.6.2-1.x86_64
  file /opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/msgpack/__pycache__/_version.cpython-36.opt-1.pyc conflicts between attempted installs of rh-python36-msgpack-python-0.5.6-1.x86_64 and rh-python36-msgpack-0.6.2-1.x86_64
  file /opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/msgpack/__pycache__/_version.cpython-36.pyc conflicts between attempted installs of rh-python36-msgpack-python-0.5.6-1.x86_64 and rh-python36-msgpack-0.6.2-1.x86_64
  file /opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/msgpack/__pycache__/exceptions.cpython-36.opt-1.pyc conflicts between attempted installs of rh-python36-msgpack-python-0.5.6-1.x86_64 and rh-python36-msgpack-0.6.2-1.x86_64
  file /opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/msgpack/__pycache__/exceptions.cpython-36.pyc conflicts between attempted installs of rh-python36-msgpack-python-0.5.6-1.x86_64 and rh-python36-msgpack-0.6.2-1.x86_64
  file /opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/msgpack/__pycache__/fallback.cpython-36.opt-1.pyc conflicts between attempted installs of rh-python36-msgpack-python-0.5.6-1.x86_64 and rh-python36-msgpack-0.6.2-1.x86_64
  file /opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/msgpack/__pycache__/fallback.cpython-36.pyc conflicts between attempted installs of rh-python36-msgpack-python-0.5.6-1.x86_64 and rh-python36-msgpack-0.6.2-1.x86_64
  file /opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/msgpack/_version.py conflicts between attempted installs of rh-python36-msgpack-python-0.5.6-1.x86_64 and rh-python36-msgpack-0.6.2-1.x86_64
  file /opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/msgpack/exceptions.py conflicts between attempted installs of rh-python36-msgpack-python-0.5.6-1.x86_64 and rh-python36-msgpack-0.6.2-1.x86_64
  file /opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/msgpack/fallback.py conflicts between attempted installs of rh-python36-msgpack-python-0.5.6-1.x86_64 and rh-python36-msgpack-0.6.2-1.x86_64
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/__init__.py conflicts between attempted installs of rh-python36-gitdb2-2.0.6-1.noarch and rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/__pycache__/__init__.cpython-36.opt-1.pyc conflicts between attempted installs of rh-python36-gitdb2-2.0.6-1.noarch and rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/__pycache__/__init__.cpython-36.pyc conflicts between attempted installs of rh-python36-gitdb2-2.0.6-1.noarch and rh-python36-gitdb-4.0.2-1.noarch

**Comment by MrMEEE** [comment]
https://awx.wiki/blog/new-build-server-new-installer-new-maintainers-same-project

**Comment by sdechasajja** [comment]
@MrMEEE  I also did tried with https://www.awx.wiki/blog/new-build-server-new-installer-new-maintainers-same-project but it still have an error.


This is going to install AWX-RPM and all dependencies.. This installer is meant to be easy, not customizable..
Check https://awx.wiki for advanced install methods and more info..
Do you want to continue?  [y/N] y
Setting up AWX-RPM
Configuring SELinux
Package policycoreutils-python-2.5-34.el7.x86_64 already installed and latest version

setsebool:  SELinux is disabled.

Configuring Firewall (Disabling for now/TODO)

Configure Repositories
Adding EPEL
Package epel-release-7-12.noarch already installed and latest version

Package centos-release-scl-rh-2-3.el7.centos.noarch already installed and latest version

Adding AWX-RPM Repo
Installing Redis
Package redis-3.2.12-2.el7.x86_64 already installed and latest version

Installing PostgreSQL
Package rh-postgresql10-postgresql-server-10.12-2.el7.x86_64 already installed and latest version

Installing Memcached
Package memcached-1.4.15-10.el7_3.1.x86_64 already installed and latest version

Installing NGINX
Package 1:nginx-1.18.0-1.el7.ngx.x86_64 already installed and latest version

Installing AWX-RPM


Transaction check error:
  file /usr/bin/pygmentize from install of python3-Pygments-2.6.1-1.5.noarch conflicts with file from package python-pygments-1.4-10.el7.noarch
  file /usr/bin/markdown_py from install of python3-markdown-3.2.1-8.3.noarch conflicts with file from package python-markdown-2.4.1-1.el7.centos.noarch
  file /usr/bin/asadmin from install of python3-boto-2.49.0-3.8.noarch conflicts with file from package python-boto-2.25.0-2.el7.centos.noarch
  file /usr/bin/bundle_image from install of python3-boto-2.49.0-3.8.noarch conflicts with file from package python-boto-2.25.0-2.el7.centos.noarch
  file /usr/bin/cfadmin from install of python3-boto-2.49.0-3.8.noarch conflicts with file from package python-boto-2.25.0-2.el7.centos.noarch
  file /usr/bin/cq from install of python3-boto-2.49.0-3.8.noarch conflicts with file from package python-boto-2.25.0-2.el7.centos.noarch
  file /usr/bin/cwutil from install of python3-boto-2.49.0-3.8.noarch conflicts with file from package python-boto-2.25.0-2.el7.centos.noarch
  file /usr/bin/dynamodb_dump from install of python3-boto-2.49.0-3.8.noarch conflicts with file from package python-boto-2.25.0-2.el7.centos.noarch
  file /usr/bin/dynamodb_load from install of python3-boto-2.49.0-3.8.noarch conflicts with file from package python-boto-2.25.0-2.el7.centos.noarch
  file /usr/bin/elbadmin from install of python3-boto-2.49.0-3.8.noarch conflicts with file from package python-boto-2.25.0-2.el7.centos.noarch
  file /usr/bin/fetch_file from install of python3-boto-2.49.0-3.8.noarch conflicts with file from package python-boto-2.25.0-2.el7.centos.noarch
  file /usr/bin/glacier from install of python3-boto-2.49.0-3.8.noarch conflicts with file from package python-boto-2.25.0-2.el7.centos.noarch
  file /usr/bin/instance_events from install of python3-boto-2.49.0-3.8.noarch conflicts with file from package python-boto-2.25.0-2.el7.centos.noarch
  file /usr/bin/kill_instance from install of python3-boto-2.49.0-3.8.noarch conflicts with file from package python-boto-2.25.0-2.el7.centos.noarch
  file /usr/bin/launch_instance from install of python3-boto-2.49.0-3.8.noarch conflicts with file from package python-boto-2.25.0-2.el7.centos.noarch
  file /usr/bin/list_instances from install of python3-boto-2.49.0-3.8.noarch conflicts with file from package python-boto-2.25.0-2.el7.centos.noarch
  file /usr/bin/lss3 from install of python3-boto-2.49.0-3.8.noarch conflicts with file from package python-boto-2.25.0-2.el7.centos.noarch
  file /usr/bin/mturk from install of python3-boto-2.49.0-3.8.noarch conflicts with file from package python-boto-2.25.0-2.el7.centos.noarch
  file /usr/bin/pyami_sendmail from install of python3-boto-2.49.0-3.8.noarch conflicts with file from package python-boto-2.25.0-2.el7.centos.noarch
  file /usr/bin/route53 from install of python3-boto-2.49.0-3.8.noarch conflicts with file from package python-boto-2.25.0-2.el7.centos.noarch
  file /usr/bin/s3put from install of python3-boto-2.49.0-3.8.noarch conflicts with file from package python-boto-2.25.0-2.el7.centos.noarch
  file /usr/bin/sdbadmin from install of python3-boto-2.49.0-3.8.noarch conflicts with file from package python-boto-2.25.0-2.el7.centos.noarch
  file /usr/bin/taskadmin from install of python3-boto-2.49.0-3.8.noarch conflicts with file from package python-boto-2.25.0-2.el7.centos.noarch

Error Summary
-------------


Initialising PostgreSQL
WARNING: using obsoleted argument syntax, try --help
WARNING: arguments transformed to: postgresql-setup --initdb --unit rh-postgresql10-postgresql
 * Initializing database in '/var/opt/rh/rh-postgresql10/lib/pgsql/data'
ERROR: Data directory /var/opt/rh/rh-postgresql10/lib/pgsql/data is not empty!
ERROR: Initializing database failed, possibly see /var/lib/pgsql/initdb_rh-postgresql10-postgresql.log

Starting PostgreSQL

Creating AWX postgreSQL user and Database
could not change directory to "/root": Permission denied
createuser: creation of new role failed: ERROR:  role "awx" already exists

Installing pwgen
Package pwgen-2.08-1.el7.x86_64 already installed and latest version

Generating Secret key
/bin/sh: /etc/tower/SECRET_KEY: No such file or directory

Initial database migration
sudo: unknown user: awx
sudo: unable to initialize policy plugin

Creating Admin user
sudo: unknown user: awx
sudo: unable to initialize policy plugin

Adding example data and registering AWX-RPM Instance in database
sudo: unknown user: awx
sudo: unable to initialize policy plugin

sudo: unknown user: awx
sudo: unable to initialize policy plugin

sudo: unknown user: awx
sudo: unable to initialize policy plugin

Installing NGINX Configuration
/bin/cp: cannot stat ‘/usr/share/doc/ansible-awx/nginx.conf.example’: No such file or directory

Configuring Redis
gpasswd: user 'awx' does not exist

Creating initial Ansible VENV
/bin/sh: awx-create-venv: command not found

Locking package versions for AWX-RPM and dependencies
Traceback (most recent call last):
  File "/root/awx-setup", line 385, in <module>
    main(sys.argv[1:])
  File "/root/awx-setup", line 316, in main
    with open("/usr/share/doc/ansible-awx/awx-locks.txt", "r") as a_file:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/doc/ansible-awx/awx-locks.txt'

**Comment by cbetan** [comment]
Did you install python36 before running the installer?

yum -y install python36

**Comment by sdechasajja** [comment]
yes, I already installed it before running the installer.

[root@hk-bipoc-2001 AWX]# yum -y install python36
Package python3-3.6.8-13.el7.x86_64 already installed and latest version

**Comment by MrMEEE** [comment]
Have you tried with a minimal server install?

**Comment by sdechasajja** [comment]
@MrMEEE I've tried with minimal server but it still have an error as below.

This is going to install AWX-RPM and all dependencies.. This installer is meant to be easy, not customizable..
Check https://awx.wiki for advanced install methods and more info..
Do you want to continue?  [y/N] y
Setting up AWX-RPM
Configuring SELinux
Package policycoreutils-python-2.5-34.el7.x86_64 already installed and latest version

setsebool:  SELinux is disabled.

Configuring Firewall (Disabling for now/TODO)

Configure Repositories
Adding EPEL

http://hk.mirrors.thegigabit.com/epel/7/x86_64/repodata/repomd.xml: [Errno 14] HTTP Error 503 - Service Unavailable
Trying other mirror.
https://mirrors.tuna.tsinghua.edu.cn/epel/7/x86_64/repodata/d6e58e5779d94deebc62a0dde11e23a7ab83cea776b5ac5c7407361c13cfa866-updateinfo.xml.bz2: [Errno 14] curl#22 - "The requested URL returned error: 503"
Trying other mirror.

Adding AWX-RPM Repo
Installing Redis
http://mirrors.icidc.com/centos/7.8.2003/sclo/x86_64/rh/repodata/repomd.xml: [Errno 14] HTTP Error 503 - Service Unavailable
Trying other mirror.
http://repo.virtualhosting.hk/centos/7.8.2003/sclo/x86_64/rh/repodata/repomd.xml: [Errno 14] HTTP Error 503 - Service Unavailable
Trying other mirror.
http://mirror.xtom.com.hk/centos/7.8.2003/sclo/x86_64/rh/repodata/repomd.xml: [Errno 14] HTTP Error 503 - Service Unavailable
Trying other mirror.
http://mirror-hk.koddos.net/centos/7.8.2003/sclo/x86_64/rh/repodata/repomd.xml: [Errno 14] HTTP Error 503 - Service Unavailable
Trying other mirror.
http://centos.01link.hk/7.8.2003/sclo/x86_64/rh/repodata/repomd.xml: [Errno 14] HTTP Error 503 - Service Unavailable
Trying other mirror.
http://mirror.worria.com/centos/7.8.2003/sclo/x86_64/rh/repodata/repomd.xml: [Errno 14] HTTP Error 503 - Service Unavailable
Trying other mirror.
http://centos.uhost.hk/7.8.2003/sclo/x86_64/rh/repodata/repomd.xml: [Errno 14] HTTP Error 503 - Service Unavailable
Trying other mirror.
http://centos.nethub.com.hk/7.8.2003/sclo/x86_64/rh/repodata/repomd.xml: [Errno 14] HTTP Error 503 - Service Unavailable
Trying other mirror.
http://mirror.hkt.cc/centos/7.8.2003/sclo/x86_64/rh/repodata/repomd.xml: [Errno 14] HTTP Error 503 - Service Unavailable
Trying other mirror.
warning: /var/cache/yum/x86_64/7/epel/packages/redis-3.2.12-2.el7.x86_64.rpm: Header V3 RSA/SHA256 Signature, key ID 352c64e5: NOKEY
Importing GPG key 0x352C64E5:
 Userid     : "Fedora EPEL (7) <epel@fedoraproject.org>"
 Fingerprint: 91e9 7d7c 4a5e 96f1 7f3e 888f 6a2f aea2 352c 64e5
 Package    : epel-release-7-11.noarch (@extras)
 From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7
Public key for redis-3.2.12-2.el7.x86_64.rpm is not installed

Installing PostgreSQL
warning: /var/cache/yum/x86_64/7/centos-sclo-rh/packages/rh-postgresql10-postgresql-libs-10.12-2.el7.x86_64.rpm: Header V4 RSA/SHA1 Signature, key ID f2ee9d55: NOKEY
Importing GPG key 0xF2EE9D55:
 Userid     : "CentOS SoftwareCollections SIG (https://wiki.centos.org/SpecialInterestGroup/SCLo) <security@centos.org>"
 Fingerprint: c4db d535 b1fb ba14 f8ba 64a8 4eb8 4e71 f2ee 9d55
 Package    : centos-release-scl-rh-2-3.el7.centos.noarch (@extras)
 From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-SIG-SCLo
Public key for rh-postgresql10-postgresql-libs-10.12-2.el7.x86_64.rpm is not installed

Installing Memcached

Installing NGINX
----------------------------------------------------------------------

Thanks for using nginx!

Please find the official documentation for nginx here:
* http://nginx.org/en/docs/

Please subscribe to nginx-announce mailing list to get
the most important news about nginx:
* http://nginx.org/en/support.html

Commercial subscriptions for nginx are available on:
* http://nginx.com/products/

----------------------------------------------------------------------

Installing AWX-RPM
warning: /var/cache/yum/x86_64/7/ansible-awx/packages/python3-Pygments-2.6.1-1.5.noarch.rpm: Header V3 RSA/SHA1 Signature, key ID b545ff52: NOKEY
Importing GPG key 0xB545FF52:
 Userid     : "private OBS (key without passphrase) <defaultkey@localobs>"
 Fingerprint: 996c cb80 cf2d d9bd 4356 13c1 c3ad d35f b545 ff52
 From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-AWX-RPM


Transaction check error:
  file /usr/bin/pygmentize from install of python3-Pygments-2.6.1-1.5.noarch conflicts with file from package python-pygments-1.4-10.el7.noarch
  file /usr/bin/markdown_py from install of python3-markdown-3.2.1-8.3.noarch conflicts with file from package python-markdown-2.4.1-1.el7.centos.noarch
  file /usr/bin/asadmin from install of python3-boto-2.49.0-3.8.noarch conflicts with file from package python-boto-2.25.0-2.el7.centos.noarch
  file /usr/bin/bundle_image from install of python3-boto-2.49.0-3.8.noarch conflicts with file from package python-boto-2.25.0-2.el7.centos.noarch
  file /usr/bin/cfadmin from install of python3-boto-2.49.0-3.8.noarch conflicts with file from package python-boto-2.25.0-2.el7.centos.noarch
  file /usr/bin/cq from install of python3-boto-2.49.0-3.8.noarch conflicts with file from package python-boto-2.25.0-2.el7.centos.noarch
  file /usr/bin/cwutil from install of python3-boto-2.49.0-3.8.noarch conflicts with file from package python-boto-2.25.0-2.el7.centos.noarch
  file /usr/bin/dynamodb_dump from install of python3-boto-2.49.0-3.8.noarch conflicts with file from package python-boto-2.25.0-2.el7.centos.noarch
  file /usr/bin/dynamodb_load from install of python3-boto-2.49.0-3.8.noarch conflicts with file from package python-boto-2.25.0-2.el7.centos.noarch
  file /usr/bin/elbadmin from install of python3-boto-2.49.0-3.8.noarch conflicts with file from package python-boto-2.25.0-2.el7.centos.noarch
  file /usr/bin/fetch_file from install of python3-boto-2.49.0-3.8.noarch conflicts with file from package python-boto-2.25.0-2.el7.centos.noarch
  file /usr/bin/glacier from install of python3-boto-2.49.0-3.8.noarch conflicts with file from package python-boto-2.25.0-2.el7.centos.noarch
  file /usr/bin/instance_events from install of python3-boto-2.49.0-3.8.noarch conflicts with file from package python-boto-2.25.0-2.el7.centos.noarch
  file /usr/bin/kill_instance from install of python3-boto-2.49.0-3.8.noarch conflicts with file from package python-boto-2.25.0-2.el7.centos.noarch
  file /usr/bin/launch_instance from install of python3-boto-2.49.0-3.8.noarch conflicts with file from package python-boto-2.25.0-2.el7.centos.noarch
  file /usr/bin/list_instances from install of python3-boto-2.49.0-3.8.noarch conflicts with file from package python-boto-2.25.0-2.el7.centos.noarch
  file /usr/bin/lss3 from install of python3-boto-2.49.0-3.8.noarch conflicts with file from package python-boto-2.25.0-2.el7.centos.noarch
  file /usr/bin/mturk from install of python3-boto-2.49.0-3.8.noarch conflicts with file from package python-boto-2.25.0-2.el7.centos.noarch
  file /usr/bin/pyami_sendmail from install of python3-boto-2.49.0-3.8.noarch conflicts with file from package python-boto-2.25.0-2.el7.centos.noarch
  file /usr/bin/route53 from install of python3-boto-2.49.0-3.8.noarch conflicts with file from package python-boto-2.25.0-2.el7.centos.noarch
  file /usr/bin/s3put from install of python3-boto-2.49.0-3.8.noarch conflicts with file from package python-boto-2.25.0-2.el7.centos.noarch
  file /usr/bin/sdbadmin from install of python3-boto-2.49.0-3.8.noarch conflicts with file from package python-boto-2.25.0-2.el7.centos.noarch
  file /usr/bin/taskadmin from install of python3-boto-2.49.0-3.8.noarch conflicts with file from package python-boto-2.25.0-2.el7.centos.noarch

Error Summary
-------------

Public key for python3-Pygments-2.6.1-1.5.noarch.rpm is not installed

Initialising PostgreSQL
WARNING: using obsoleted argument syntax, try --help
WARNING: arguments transformed to: postgresql-setup --initdb --unit rh-postgresql10-postgresql
 * Initializing database in '/var/opt/rh/rh-postgresql10/lib/pgsql/data'
 * Initialized, logs are in /var/lib/pgsql/initdb_rh-postgresql10-postgresql.log

Starting PostgreSQL

Creating AWX postgreSQL user and Database
could not change directory to "/root": Permission denied
could not change directory to "/root": Permission denied

Installing pwgen

Generating Secret key
/bin/sh: /etc/tower/SECRET_KEY: No such file or directory

Initial database migration
sudo: unknown user: awx
sudo: unable to initialize policy plugin

Creating Admin user
sudo: unknown user: awx
sudo: unable to initialize policy plugin

Adding example data and registering AWX-RPM Instance in database
sudo: unknown user: awx
sudo: unable to initialize policy plugin

sudo: unknown user: awx
sudo: unable to initialize policy plugin

sudo: unknown user: awx
sudo: unable to initialize policy plugin

Installing NGINX Configuration
/bin/cp: cannot stat ‘/usr/share/doc/ansible-awx/nginx.conf.example’: No such file or directory

Configuring Redis
gpasswd: user 'awx' does not exist

Creating initial Ansible VENV
/bin/sh: awx-create-venv: command not found

Locking package versions for AWX-RPM and dependencies
Traceback (most recent call last):
  File "/root/awx-setup", line 385, in <module>
    main(sys.argv[1:])
  File "/root/awx-setup", line 316, in main
    with open("/usr/share/doc/ansible-awx/awx-locks.txt", "r") as a_file:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/doc/ansible-awx/awx-locks.txt'

**Comment by riahc3** [comment]
[Errno 14] HTTP Error 503 - Service Unavailable

Did you get those errors the first time around?

Just to know.

**Comment by MrMEEE** [comment]
I have no problems accessing the EPEL sites.. maybe some kind of firewall ??

**Comment by sdechasajja** [comment]
I've manual stopped and disabled firewall. No problems accessing the EPEL sites. However, I still have got a python conflict issue. It would be great if you could advise me on this.

`[root@hk-bipoc-2002 ~]# systemctl stop firewalld
[root@hk-bipoc-2002 ~]# systemctl disable firewalld
[root@hk-bipoc-2002 ~]# /root/awx-setup -i
This is going to install AWX-RPM and all dependencies.. This installer is meant to be easy, not customizable..
Check https://awx.wiki for advanced install methods and more info..
Do you want to continue?  [y/y
Setting up AWX-RPM
Configuring SELinux
Package policycoreutils-python-2.5-34.el7.x86_64 already installed and latest version

Configuring Firewall (Disabling for now/TODO)

Configure Repositories
Adding EPEL
Delta RPMs disabled because /usr/bin/applydeltarpm not installed.

Package centos-release-scl-rh-2-3.el7.centos.noarch already installed and latest version

Adding AWX-RPM Repo
Installing Redis
Package redis-3.2.12-2.el7.x86_64 already installed and latest version

Installing PostgreSQL
Package rh-postgresql10-postgresql-server-10.12-2.el7.x86_64 already installed and latest version

Installing Memcached
Package memcached-1.4.15-10.el7_3.1.x86_64 already installed and latest version

Installing NGINX
Package 1:nginx-1.18.0-1.el7.ngx.x86_64 already installed and latest version

Installing AWX-RPM


Transaction check error:
  file /usr/bin/pygmentize from install of python3-Pygments-2.6.1-1.5.noarch conflicts with file from package python-pygments-1.4-10.el7.noarch
  file /usr/bin/markdown_py from install of python3-markdown-3.2.1-8.3.noarch conflicts with file from package python-markdown-2.4.1-1.el7.centos.noarch
  file /usr/bin/asadmin from install of python3-boto-2.49.0-3.8.noarch conflicts with file from package python-boto-2.25.0-2.el7.centos.noarch
  file /usr/bin/bundle_image from install of python3-boto-2.49.0-3.8.noarch conflicts with file from package python-boto-2.25.0-2.el7.centos.noarch
  file /usr/bin/cfadmin from install of python3-boto-2.49.0-3.8.noarch conflicts with file from package python-boto-2.25.0-2.el7.centos.noarch
  file /usr/bin/cq from install of python3-boto-2.49.0-3.8.noarch conflicts with file from package python-boto-2.25.0-2.el7.centos.noarch
  file /usr/bin/cwutil from install of python3-boto-2.49.0-3.8.noarch conflicts with file from package python-boto-2.25.0-2.el7.centos.noarch
  file /usr/bin/dynamodb_dump from install of python3-boto-2.49.0-3.8.noarch conflicts with file from package python-boto-2.25.0-2.el7.centos.noarch
  file /usr/bin/dynamodb_load from install of python3-boto-2.49.0-3.8.noarch conflicts with file from package python-boto-2.25.0-2.el7.centos.noarch
  file /usr/bin/elbadmin from install of python3-boto-2.49.0-3.8.noarch conflicts with file from package python-boto-2.25.0-2.el7.centos.noarch
  file /usr/bin/fetch_file from install of python3-boto-2.49.0-3.8.noarch conflicts with file from package python-boto-2.25.0-2.el7.centos.noarch
  file /usr/bin/glacier from install of python3-boto-2.49.0-3.8.noarch conflicts with file from package python-boto-2.25.0-2.el7.centos.noarch
  file /usr/bin/instance_events from install of python3-boto-2.49.0-3.8.noarch conflicts with file from package python-boto-2.25.0-2.el7.centos.noarch
  file /usr/bin/kill_instance from install of python3-boto-2.49.0-3.8.noarch conflicts with file from package python-boto-2.25.0-2.el7.centos.noarch
  file /usr/bin/launch_instance from install of python3-boto-2.49.0-3.8.noarch conflicts with file from package python-boto-2.25.0-2.el7.centos.noarch
  file /usr/bin/list_instances from install of python3-boto-2.49.0-3.8.noarch conflicts with file from package python-boto-2.25.0-2.el7.centos.noarch
  file /usr/bin/lss3 from install of python3-boto-2.49.0-3.8.noarch conflicts with file from package python-boto-2.25.0-2.el7.centos.noarch
  file /usr/bin/mturk from install of python3-boto-2.49.0-3.8.noarch conflicts with file from package python-boto-2.25.0-2.el7.centos.noarch
  file /usr/bin/pyami_sendmail from install of python3-boto-2.49.0-3.8.noarch conflicts with file from package python-boto-2.25.0-2.el7.centos.noarch
  file /usr/bin/route53 from install of python3-boto-2.49.0-3.8.noarch conflicts with file from package python-boto-2.25.0-2.el7.centos.noarch
  file /usr/bin/s3put from install of python3-boto-2.49.0-3.8.noarch conflicts with file from package python-boto-2.25.0-2.el7.centos.noarch
  file /usr/bin/sdbadmin from install of python3-boto-2.49.0-3.8.noarch conflicts with file from package python-boto-2.25.0-2.el7.centos.noarch
  file /usr/bin/taskadmin from install of python3-boto-2.49.0-3.8.noarch conflicts with file from package python-boto-2.25.0-2.el7.centos.noarch

Error Summary
-------------


Initialising PostgreSQL
WARNING: using obsoleted argument syntax, try --help
WARNING: arguments transformed to: postgresql-setup --initdb --unit rh-postgresql10-postgresql
 * Initializing database in '/var/opt/rh/rh-postgresql10/lib/pgsql/data'
ERROR: Data directory /var/opt/rh/rh-postgresql10/lib/pgsql/data is not empty!
ERROR: Initializing database failed, possibly see /var/lib/pgsql/initdb_rh-postgresql10-postgresql.log

Starting PostgreSQL

Creating AWX postgreSQL user and Database
could not change directory to "/root": Permission denied
createuser: creation of new role failed: ERROR:  role "awx" already exists

Installing pwgen
Package pwgen-2.08-1.el7.x86_64 already installed and latest version

Generating Secret key
/bin/sh: /etc/tower/SECRET_KEY: No such file or directory

Initial database migration
sudo: unknown user: awx
sudo: unable to initialize policy plugin

Creating Admin user
sudo: unknown user: awx
sudo: unable to initialize policy plugin

Adding example data and registering AWX-RPM Instance in database
sudo: unknown user: awx
sudo: unable to initialize policy plugin

sudo: unknown user: awx
sudo: unable to initialize policy plugin

sudo: unknown user: awx
sudo: unable to initialize policy plugin

Installing NGINX Configuration
/bin/cp: cannot stat ‘/usr/share/doc/ansible-awx/nginx.conf.example’: No such file or directory

Configuring Redis
gpasswd: user 'awx' does not exist

Creating initial Ansible VENV
/bin/sh: awx-create-venv: command not found

Locking package versions for AWX-RPM and dependencies
Traceback (most recent call last):
  File "/root/awx-setup", line 385, in <module>
    main(sys.argv[1:])
  File "/root/awx-setup", line 316, in main
    with open("/usr/share/doc/ansible-awx/awx-locks.txt", "r") as a_file:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/doc/ansible-awx/awx-locks.txt'`

**Comment by sdechasajja** [comment]
@MrMEEE I'm able to install AWX with following steps. During the installation, it found error because  the 'azure-storage' meta-package is deprecated and cannot be installed anymore. However, it installed successfully. Should this package be removed from the installation file?


### **Installation final message**
Congratulations, AWX-RPM is now installed, and hopefully running on http://hk-qabipoc-2003.
Login:
  user: admin
  password: password (remember to change)

Please report any issues at: https://github.com/MrMEEE/awx-build/issues

awx-create-env can be used for creating virtual ansible python environments (VENVs)..

awx-setup can be used for updating and managing VENVs..

Have fun!!!

### **Error during installation**
Creating initial Ansible VENV
    ERROR: Command errored out with exit status 1:
     command: /var/lib/awx/venv/python3-ansible2.10.0a3-2172020/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-p5vegnd_/azure-storage/setup.py'"'"'; __file__='"'"'/tmp/pip-install-p5vegnd_/azure-storage/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-o08xqwg6
         cwd: /tmp/pip-install-p5vegnd_/azure-storage/
    Complete output (19 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-p5vegnd_/azure-storage/setup.py", line 55, in <module>
        raise RuntimeError(message)
    RuntimeError:
    Starting with v0.37.0, the 'azure-storage' meta-package is deprecated and cannot be installed anymore.
    Please install the service specific packages prefixed by `azure` needed for your application.
    The complete list of available packages can be found at:
    https://aka.ms/azsdk/python/all
    Here's a non-exhaustive list of common packages:
    - [azure-storage-blob](https://pypi.org/project/azure-storage-blob) : Blob storage client
    - [azure-storage-file-share](https://pypi.org/project/azure-storage-file-share) : Storage file share client
    - [azure-storage-file-datalake](https://pypi.org/project/azure-storage-file-datalake) : ADLS Gen2 client
    - [azure-storage-queue](https://pypi.org/project/azure-storage-queue): Queue storage client
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

### **Installation steps**
**1. Add AWX user on server ** 
adduser awx
passwd awx

**2. Install python36**
yum -y install python36

**3. Get AWX setup package**
curl -o /opt/awx/awx-setup https://raw.githubusercontent.com/MrMEEE/awx-rpm/master/awx-setup
chmod -R 777 /opt/awx/awx-setup

**4. Remove python packages to avoid python conflict error**
yum info [conflict package name]
yum remove  [conflict package name]
yum remove python-markdown
yum remove python-boto
yum remove python-pygments

**5. Run the installation script**
/opt/awx/awx-setup -i

Note: If any other python conflicts found, we have to remove it before run installation as mentioned in step 4.

**Comment by MrMEEE** [comment]
Project has been updated and moved...

Please move to the new version and report any issues

PROJECT MOVED: https://github.com/miracle-as/AWX-RPM

Issues at: https://github.com/miracle-as/AWX-RPM/issues

**Install guide, tools, utilities are located at: https://awx.wiki

**LinkedIn group for Questions, support, talk and more: https://www.linkedin.com/groups/13694893/**
