### ISSUE TITLE
How we can deploy this in HA?using new awx11 setup 

### ISSUE THREAD

**Issue by nikita199220** [MrMEEE/awx-build#258]

**Comment by rokat** [comment]
Hello after tinkering a bit with the new AWX installer and read a bit about the doc of clustering for the new AWX.

RabbitMQ dependency is removed so not necessary anymore. 
It has been replaced by Redis which is simpler !

The "clustering" is only done by sharing the same postgres DB and provisioning the AWX instance group
(as user awx on any awx tower node). As AWX communicates between eachother by webservices.
awx-manage provision_instance --hostname=$(hostname)

And finally on one tower node (master )

awx-manage register_queue --queuename=tower --hostnames="node1,node2,node3 ..."

That should do the trick

Inspired by the work of powertim source: 
https://github.com/powertim/deploy_awx-rpm

I have tried multiple setups having one tower on CentOS 7 & other on 8. works as a charm :) (but did not launched playbooks yet)

**Comment by nikita199220** [comment]
Hi,

I tried your playbook but my playbook is failing with below issue:

    "ansible_loop_var": "item",
    "changed": false,
    "invocation": {
        "module_args": {
            "name": [
                "awx_ansible_awx_repo"
            ],
            "purge": false,
            "state": "enabled"
        }
    },
    "item": "awx_ansible_awx_repo",
    "results": [
        "awx_ansible_awx_repo is not a valid repository ID"
    ]
}

MSG:

awx_ansible_awx_repo is not a valid repository ID


Do I need to download this repo seperately?

**Comment by MrMEEE** [comment]
Project has been updated and moved...

Please move to the new version and report any issues

PROJECT MOVED: https://github.com/miracle-as/AWX-RPM

Issues at: https://github.com/miracle-as/AWX-RPM/issues

**Install guide, tools, utilities are located at: https://awx.wiki

**LinkedIn group for Questions, support, talk and more: https://www.linkedin.com/groups/13694893/**
