### ISSUE TITLE
Cannot pull git detail from Ansible AWX RPM : Invalid virtual environment selected: /var/lib/awx/venv/ansible/ 

### ISSUE THREAD

**Issue by gefela** [MrMEEE/awx-build#259]
When I create a job template , I cannot do a SCM update and it is failing with a error message Invalid virtual environment selected: /var/lib/awx/venv/ansible/

**Comment by MrMEEE** [comment]
Project has been updated and moved...

Please move to the new version and report any issues

PROJECT MOVED: https://github.com/miracle-as/AWX-RPM

Issues at: https://github.com/miracle-as/AWX-RPM/issues

**Install guide, tools, utilities are located at: https://awx.wiki

**LinkedIn group for Questions, support, talk and more: https://www.linkedin.com/groups/13694893/**
