### ISSUE TITLE
awx 12 

### ISSUE THREAD

**Issue by Lobout** [MrMEEE/awx-build#260]
any update on when we can test v12 build?

**Comment by MrMEEE** [comment]
I'm really busy at work right now, and we are still trying to transition the project to rest of the team, so I won't make any guarantees.. other than saying that I won't let the project die...

**Comment by Lobout** [comment]
No worries.  I know the day job can sometimes get crazy

**Comment by angystardust** [comment]
meanwhile, 13.0.0 is out... https://github.com/ansible/awx/blob/devel/CHANGELOG.md#1300-jun-23-2020

**Comment by dominiquearpin** [comment]
And 15.0.0 is out....  Some new about the 11.2 version, is stable enough to try in production?

**Comment by Lobout** [comment]
i wouldn't run 11.2 in production, as there are several known issues with 
inventory jobs, as well as others.

**Comment by MrMEEE** [comment]
Project has been updated and moved...

Please move to the new version and report any issues

PROJECT MOVED: https://github.com/miracle-as/AWX-RPM

Issues at: https://github.com/miracle-as/AWX-RPM/issues

**Install guide, tools, utilities are located at: https://awx.wiki

**LinkedIn group for Questions, support, talk and more: https://www.linkedin.com/groups/13694893/**
