### ISSUE TITLE
user python automated installation script some problem

### ISSUE THREAD

**Issue by cddisk2000** [MrMEEE/awx-build#261]
I use the following instruction to install ansible awx No problem

yum -y install python36
curl -o /root/awx-setup https://raw.githubusercontent.com/MrMEEE/awx-rpm/master/awx-setup
chmod +x /root/awx-setup
/root/awx-setup -i

but use ansible awx ui Need to modify these places，I don't understand why but it is used successfully

# step one
cd /var/lib/awx/venv/
mv python3-ansible2.9.9-1662020 ansible

# step two
ln -s /var/lib/awx/venv/ansible/bin/ansible-playbook /usr/local/bin/

# step three
vi /var/lib/awx/venv/ansible/bin/ansible-playbook
#!/var/lib/awx/venv/ansible/bin/python3

# step four ( cehck ansible version )
ansible-playbook --version

Now I Can User Ansible Awx ，Hope to help other friends

**Comment by MrMEEE** [comment]
Project has been updated and moved...

Please move to the new version and report any issues

PROJECT MOVED: https://github.com/miracle-as/AWX-RPM

Issues at: https://github.com/miracle-as/AWX-RPM/issues

**Install guide, tools, utilities are located at: https://awx.wiki

**LinkedIn group for Questions, support, talk and more: https://www.linkedin.com/groups/13694893/**
