### ISSUE TITLE
Repo Location

### ISSUE THREAD

**Issue by cidms212** [MrMEEE/awx-build#262]
Currently we are experimenting with using AWX Rpm within our production environment, however our work environment doesn't allow access to the repo domain referenced within the install script. Is there any future plans on providing an alternate repo location within GitHub?

**Comment by bluikko** [comment]
I would like to see a repo that can be mirrored, preferably with rsync...

We could probably provide the space if needed (we host a few repositories already) but that might not work well for others since we're geographically very far from everyone.

**Comment by cidms212** [comment]
Yea that was my initial thought just to rsync or wget the whole thing, however cant reach the .dk domain at work and unable to transfer via offline media. Most ideal solution would be to have a copy of the repo here on git hub for download.

**Comment by MrMEEE** [comment]
This is something that we'll have to look into, but in general the repo will be present at rpm.miracle.dk

**Comment by MrMEEE** [comment]
Project has been updated and moved...

Please move to the new version and report any issues

PROJECT MOVED: https://github.com/miracle-as/AWX-RPM

Issues at: https://github.com/miracle-as/AWX-RPM/issues

**Install guide, tools, utilities are located at: https://awx.wiki

**LinkedIn group for Questions, support, talk and more: https://www.linkedin.com/groups/13694893/**
