### ISSUE TITLE
Centos7 - awx rpm - Fresh install using 9 may 2020 procedure, but error when upgrading OS after that

### ISSUE THREAD

**Issue by Exitneox** [MrMEEE/awx-build#263]
I followed the procedure described in [awx-rpm blog as of 9 may 2020](https://awx.wiki/blog/new-build-server-new-installer-new-maintainers-same-project)
Install run fine on centos7 minimal

basic testing (inventory and ping of machine) confirm all is fine

But if I try to update the system after the awx-setup, it says it is broken as this

`yum update

[...]

Error: Package: ansible-awx-11.2.0-20.1.x86_64 (@ansible-awx)
           Requires: python36-future = 0.16.0
           Removing: python36-future-0.16.0-8.1.noarch (@ansible-awx)
               python36-future = 0.16.0-8.1
           Updated By: python36-future-0.18.2-2.el7.noarch (epel)
               python36-future = 0.18.2-2.el7
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
`

**yum update --skip-broken** also failed but with

`Packages skipped because of dependency problems:
    python36-future-0.18.2-2.el7.noarch from epel

Transaction check error:
  file /usr/bin/easy_install from install of python3-setuptools-41.6.0-2.1.noarch conflicts with file from package python-setuptools-0.9.8-7.el7.noarch`

**Comment by MrMEEE** [comment]
https://awx.wiki/blog/new-build-server-new-installer-new-maintainers-same-project

**Comment by arthurpoortman** [comment]
I've the same issue, ran it today and wordks perfect but cannot upgrade OS anymore, see below for more info.
OS: centos-release-7-8.2003.0.el7.centos.x86_64 (Minimal Install)

[root@thisismyhostname ~]# yum upgrade
Loaded plugins: fastestmirror, versionlock
Loading mirror speeds from cached hostfile
 * base: mirror.ipserv.nl
 * centos-sclo-rh: centos.mirror.triple-it.nl
 * epel: mirrors.glesys.net
 * extras: ams.edge.kernel.org
 * updates: mirror.sitbv.nl
Resolving Dependencies
--> Running transaction check
---> Package epel-release.noarch 0:7-11 will be updated
---> Package epel-release.noarch 0:7-12 will be an update
---> Package python3-setuptools.noarch 0:39.2.0-10.el7 will be updated
---> Package python3-setuptools.noarch 0:41.6.0-2.1 will be an update
---> Package python36-future.noarch 0:0.16.0-8.1 will be updated
--> Processing Dependency: python36-future = 0.16.0 for package: ansible-awx-11.2.0-20.1.x86_64
---> Package python36-future.noarch 0:0.18.2-2.el7 will be an update
---> Package sqlite.x86_64 0:3.7.17-8.el7_7.1 will be updated
---> Package sqlite.x86_64 0:3.8.6-4.2 will be an update
--> Finished Dependency Resolution
Error: Package: ansible-awx-11.2.0-20.1.x86_64 (@ansible-awx)
           Requires: python36-future = 0.16.0
           Removing: python36-future-0.16.0-8.1.noarch (@ansible-awx)
               python36-future = 0.16.0-8.1
           Updated By: python36-future-0.18.2-2.el7.noarch (epel)
               python36-future = 0.18.2-2.el7
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

**Comment by Exitneox** [comment]
as the output look like 2 versions of python36-future try to be installed from EPEL and from AWX, I give a try to disable EPEL repo for the OS upgrade

This provides more info and look it goes a bit further, but keeps says their are error and nothing else install.
I guess I could disable awx-rpm repo to upgrade other packages first, but unsure yet of doing it.

`Downloading packages:
Running transaction check
Running transaction test


Transaction check error:
  file /usr/bin/easy_install from install of python3-setuptools-41.6.0-2.1.noarch conflicts with file from package python-setuptools-0.9.8-7.el7.noarch

Error Summary`

**Comment by MrMEEE** [comment]
Project has been updated and moved...

Please move to the new version and report any issues

PROJECT MOVED: https://github.com/miracle-as/AWX-RPM

Issues at: https://github.com/miracle-as/AWX-RPM/issues

**Install guide, tools, utilities are located at: https://awx.wiki

**LinkedIn group for Questions, support, talk and more: https://www.linkedin.com/groups/13694893/**
