### ISSUE TITLE
awx tower

### ISSUE THREAD

**Issue by gefela** [MrMEEE/awx-build#266]
I can seem to find the location for the logs when the playbooks . I have checked var/log/tower and var/log/supervisor but cannot find anything 

Where are the logs from running a playbook stored ?

**Comment by MrMEEE** [comment]
I believe they are in the database only..

**Comment by gefela** [comment]
I have trying to setting up logging to splunk but it does not work

**Comment by MrMEEE** [comment]
Project has been updated and moved...

Please move to the new version and report any issues

PROJECT MOVED: https://github.com/miracle-as/AWX-RPM

Issues at: https://github.com/miracle-as/AWX-RPM/issues

**Install guide, tools, utilities are located at: https://awx.wiki

**LinkedIn group for Questions, support, talk and more: https://www.linkedin.com/groups/13694893/**
