### ISSUE TITLE
Version definition for awx installation

### ISSUE THREAD

**Issue by BrotherLavarius** [MrMEEE/awx-build#269]
Good day! I was wondering can we please have a option to control the installation version via the augments?

```
 options:
  -i, --install              Setup and configure AWX-RPM, standard installation, single server
  -d, --default-venv         Set default virtual environment, located in /var/lib/awx/venv/
  -l, --list-venvs           List available virtual environments
  -u, --update               Update AWX-RPM to latest version
   ''')

```
At the current state it might be not production ready due to this(i mean when you tested the minor, and the next day when you want to update the prod env, a new minor will suddenly appear, and you will have to test again)

**Comment by MrMEEE** [comment]
This is a great idea.. as soon as we have the builds up running, this will be high on the todo list

**Comment by BrotherLavarius** [comment]
> 
> 
> This is a great idea.. as soon as we have the builds up running, this will be high on the todo list

Thank you :)!
