### ISSUE TITLE
ppc64le availabililty

### ISSUE THREAD

**Issue by flynn1973** [MrMEEE/awx-build#271]
i read somewhere (in your wiki), that ppc64le packages are absent for now. i dont checked back, but will this packages return?

**Comment by MrMEEE** [comment]
Hi

We are really busy right now, trying to get the builds to run smoothly.. but the PPC64LE packages are on the todo-list..

**Comment by flynn1973** [comment]
as ppc64le packages are not going to happen, any change you providing me your build scripts/toolchain, so i can run my own internally?

**Comment by flynn1973** [comment]
if some help/input is required to speed up the development process , especially on the ppc64le front, i am willing to jump in.
