### ISSUE TITLE
AWX unable to pull inventory from Foreman

### ISSUE THREAD

**Issue by poulterer** [MrMEEE/awx-build#273]
AWX is configured to use Foreman (Satellite 6) as an inventory source but fails on python error show below. Running "ansible-inventory -i /etc/ansible/sherlock.foreman.yaml --graph" with file below works. The same user and credentials are used in AWX. Attached file has (I think) relevant facts.
[awx.txt](https://github.com/MrMEEE/awx-build/files/4904515/awx.txt)

**Comment by MrMEEE** [comment]
Project has been updated and moved...

Please move to the new version and report any issues

PROJECT MOVED: https://github.com/miracle-as/AWX-RPM

Issues at: https://github.com/miracle-as/AWX-RPM/issues

**Install guide, tools, utilities are located at: https://awx.wiki

**LinkedIn group for Questions, support, talk and more: https://www.linkedin.com/groups/13694893/**
