### ISSUE TITLE
windows issue

### ISSUE THREAD

**Issue by Godfrey48** [MrMEEE/awx-build#275]
Windows is able to ping. But unable to execute the playbook and show as below
**The module setup was redirected to ansible.windows.setup.ps1, which could not be loaded.**

**Comment by techiesanjay** [comment]
Can you share some additional facts on the problem you are facing?

**Comment by Godfrey48** [comment]
![awx](https://user-images.githubusercontent.com/61176778/88359776-87c4e000-cd91-11ea-9e4f-99a29c1016dd.png)
at the initial stage of running a playbook against a windows node

**Comment by ghost** [comment]
This is an ansible bug
https://github.com/ansible/ansible/pull/70158

**Comment by MrMEEE** [comment]
Project has been updated and moved...

Please move to the new version and report any issues

PROJECT MOVED: https://github.com/miracle-as/AWX-RPM

Issues at: https://github.com/miracle-as/AWX-RPM/issues

**Install guide, tools, utilities are located at: https://awx.wiki

**LinkedIn group for Questions, support, talk and more: https://www.linkedin.com/groups/13694893/**
