### ISSUE TITLE
Ansible.cfg file location.

### ISSUE THREAD

**Issue by campos0491** [MrMEEE/awx-build#276]
Hi,

I need to modify an ansible parameter on the file ansible.cfg, where is this file located?

Regards.

**Comment by dominiquearpin** [comment]
[root ~]# locate ansible.cfg
/etc/ansible/ansible.cfg

**Comment by MrMEEE** [comment]
Project has been updated and moved...

Please move to the new version and report any issues

PROJECT MOVED: https://github.com/miracle-as/AWX-RPM

Issues at: https://github.com/miracle-as/AWX-RPM/issues

**Install guide, tools, utilities are located at: https://awx.wiki

**LinkedIn group for Questions, support, talk and more: https://www.linkedin.com/groups/13694893/**
