### ISSUE TITLE
Upgrade and Fresh install  11.2

### ISSUE THREAD

**Issue by dominiquearpin** [MrMEEE/awx-build#278]
Hi,

I can see some people did an upgrade from 9.3.0 to 11.2.  But I just wondering if it will be better to do a fresh install or to perform the upgrade?  If the upgrade its working fine, maybe a small documentation with all the steps?

Regards,

Dominique

**Comment by psmola** [comment]
Hi,
In my opinion always better is do fresh installation if we are talking about new AWX instance. Of course if AWX instance already exists then upgrade is a option. 
For upgrade process from AWX 9.2 to 11 here you have playbook: https://github.com/psmola/awx_patching
with all needed steps. One important thing . In version 11.2 RabbitMQ is no longer used and replaced by redis/db solution.

Regards,
Pawel

**Comment by MrMEEE** [comment]
Project has been updated and moved...

Please move to the new version and report any issues

PROJECT MOVED: https://github.com/miracle-as/AWX-RPM

Issues at: https://github.com/miracle-as/AWX-RPM/issues

**Install guide, tools, utilities are located at: https://awx.wiki

**LinkedIn group for Questions, support, talk and more: https://www.linkedin.com/groups/13694893/**
