### ISSUE TITLE
ansible-awx dependency requiring python36-future 0.16.0

### ISSUE THREAD

**Issue by jwinderWCB** [MrMEEE/awx-build#279]
It appears the ansible-awx package has a dependency on python36-future 0.16.0. This package is no longer available in the EPEL repository as it has been updated to 0.18.0.

I was able to get around this issue by downloading the package from https://koji.fedoraproject.org/koji/buildinfo?buildID=1262066 and installing it outside the awx-setup script.

**Comment by Exitneox** [comment]
Same here, centos7 fresh install and uptodate, AWX installed with `awx-setup -i` script
yum update failed with this dependency issue

I fixit it with `yum version lock python36-future`

Then I have python3-setuptools that conflicts with python-setuptools :/

`Transaction check error:
  file /usr/bin/easy_install from install of python3-setuptools-41.6.0-2.2.noarch conflicts with file from package python-setuptools-0.9.8-7.el7.noarch`

**Comment by MrMEEE** [comment]
Project has been updated and moved...

Please move to the new version and report any issues

PROJECT MOVED: https://github.com/miracle-as/AWX-RPM

Issues at: https://github.com/miracle-as/AWX-RPM/issues

**Install guide, tools, utilities are located at: https://awx.wiki

**LinkedIn group for Questions, support, talk and more: https://www.linkedin.com/groups/13694893/**
