### ISSUE TITLE
PPA for debian/ubuntu ?

### ISSUE THREAD

**Issue by kocoten1992** [MrMEEE/awx-build#28]
Hi @MrMEEE , some of us still use ubuntu/debian for server, do we have plan for support these OS ?

**Comment by MrMEEE** [comment]
Hi

I would have to redo the complete build environment.. Probably not anytime soon..

**Comment by MrMEEE** [comment]
I have just done the build of the source/python virtual env on Ubuntu, and seems to work ok.. but then I need to do the packaging as well.. and of course testing, which will be the biggest part...

If you are interested in doing the testing and bugfixing related to the Ubuntu build, I might be able to setup some automatic builds for Ubuntu...

**Comment by kocoten1992** [comment]
Could I ask how was the experience using awx ? I'm quite worry because they required an enormous resources to run.
```
At leasts 4GB of memory
At least 2 cpu cores
At least 20GB of space
```
I imaging running it on some cheap vps , 512MB memory, 0.5 core, 5 GB of space 
Does your experience good, the software worth it ? :worried: 

P/s: my use case is to manage my home labs ~9 machines, but even so, if the stack only a binary file and a database, I think it will be much much less resources intensive

**Comment by MrMEEE** [comment]
Hi..

I don't think that AWX requires enormous resources.. but, I don't think you'll get it running smoothly without at least 4GB ram.. The space and core requirements of course depends on your usage...

**Comment by MrMEEE** [comment]
Can I close this?

**Comment by kocoten1992** [comment]
sure, thank you :smile:
