### ISSUE TITLE
AWX Email Notification Not Working

### ISSUE THREAD

**Issue by gp185132-ncr** [MrMEEE/awx-build#281]
Hi ,

Iam new to AWX , and iam trying to send an Email Notification on state success of   my Job Template which takes Backup of Configuration in a Device . 

The Job template is running fine with success but the Email Notification is not being generated on success .

I would like to confirm on below Necessary parameters (*) while configuring Email type Notifcation 

What should be given in below parameters :-

1. HOST:- Is it the Host/Server where AWX GUI is installed or some other host?
2.  PORT :- is it the Port of AWX GUI which is 80/443 or is it Mail Client/SMTP port and what port number ?
3. SENDER EMAIL :- is it my user made on AWX GUI server  or from  root user ?

![EMAIL_Notification](https://user-images.githubusercontent.com/70205964/91452919-ca9c3b00-e89c-11ea-82fe-cc2b692b897a.JPG)

**Comment by MrMEEE** [comment]
Project has been updated and moved...

Please move to the new version and report any issues

PROJECT MOVED: https://github.com/miracle-as/AWX-RPM

Issues at: https://github.com/miracle-as/AWX-RPM/issues

**Install guide, tools, utilities are located at: https://awx.wiki

**LinkedIn group for Questions, support, talk and more: https://www.linkedin.com/groups/13694893/**
