### ISSUE TITLE
No such file or directory : /usr/share/doc/ansible-awx/awx-locks.txt

### ISSUE THREAD

**Issue by karthikgitrepo** [MrMEEE/awx-build#282]
Issue on centos 7
./awx-setup -i

Installing AWX-RPM

Transaction check error:
  file /usr/bin/jsonschema from install of python3-jsonschema-3.2.0-4.8.noarch conflicts with file from package python2-jsonschema-2.5.1-4.el7.noarch

Error Summary
-------------

Initialising PostgreSQL
WARNING: using obsoleted argument syntax, try --help
WARNING: arguments transformed to: postgresql-setup --initdb --unit rh-postgresql10-postgresql
 * Initializing database in '/var/opt/rh/rh-postgresql10/lib/pgsql/data'
ERROR: Data directory /var/opt/rh/rh-postgresql10/lib/pgsql/data is not empty!
ERROR: Initializing database failed, possibly see /var/lib/pgsql/initdb_rh-postgresql10-postgresql.log

Starting PostgreSQL

Creating AWX postgreSQL user and Database
could not change directory to "/root": Permission denied
createuser: creation of new role failed: ERROR:  role "awx" already exists

Installing pwgen
Package pwgen-2.08-1.el7.x86_64 already installed and latest version

Generating Secret key
/bin/sh: /etc/tower/SECRET_KEY: No such file or directory

Initial database migration
sudo: unknown user: awx
sudo: unable to initialize policy plugin

Creating Admin user
sudo: unknown user: awx
sudo: unable to initialize policy plugin

Adding example data and registering AWX-RPM Instance in database
sudo: unknown user: awx
sudo: unable to initialize policy plugin

sudo: unknown user: awx
sudo: unable to initialize policy plugin

sudo: unknown user: awx
sudo: unable to initialize policy plugin

Installing NGINX Configuration
/bin/cp: cannot stat â/usr/share/doc/ansible-awx/nginx.conf.exampleâ: No such file or directory

Configuring Redis
gpasswd: user 'awx' does not exist

Creating initial Ansible VENV
/bin/sh: awx-create-venv: command not found

Locking package versions for AWX-RPM and dependencies
Traceback (most recent call last):
  File "./awx-setup", line 375, in <module>
    main(sys.argv[1:])
  File "./awx-setup", line 317, in main
    with open("/usr/share/doc/ansible-awx/awx-locks.txt", "r") as a_file:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/doc/ansible-awx/awx-locks.txt'

**Comment by MrMEEE** [comment]
Project has been updated and moved...

Please move to the new version and report any issues

PROJECT MOVED: https://github.com/miracle-as/AWX-RPM

Issues at: https://github.com/miracle-as/AWX-RPM/issues

**Install guide, tools, utilities are located at: https://awx.wiki

**LinkedIn group for Questions, support, talk and more: https://www.linkedin.com/groups/13694893/**
