### ISSUE TITLE
trying to upgrade to 9.3 from 9.2.

### ISSUE THREAD

**Issue by astateofmind01** [MrMEEE/awx-build#284]
1. When doing  `yum install --disablerepo='*' --enablerepo='copr:copr.fedorainfracloud.org:mrmeee:ansible-awx, base' -x *-debuginfo rh-python36*`

i get the errors:

`Transaction check error:
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/__init__.py from install of rh-python36-gitdb-4.0.2-1.noarch conflicts with file from package rh-python36-gitdb2-2.0.6-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/db/__init__.py from install of rh-python36-gitdb-4.0.2-1.noarch conflicts with file from package rh-python36-gitdb2-2.0.6-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/test/__init__.py from install of rh-python36-gitdb-4.0.2-1.noarch conflicts with file from package rh-python36-gitdb2-2.0.6-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/__pycache__/__init__.cpython-36.opt-1.pyc from install of rh-python36-gitdb-4.0.2-1.noarch conflicts with file from package rh-python36-gitdb2-2.0.6-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/db/__pycache__/__init__.cpython-36.opt-1.pyc from install of rh-python36-gitdb-4.0.2-1.noarch conflicts with file from package rh-python36-gitdb2-2.0.6-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/test/__pycache__/__init__.cpython-36.opt-1.pyc from install of rh-python36-gitdb-4.0.2-1.noarch conflicts with file from package rh-python36-gitdb2-2.0.6-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/utils/__pycache__/__init__.cpython-36.opt-1.pyc from install of rh-python36-gitdb-4.0.2-1.noarch conflicts with file from package rh-python36-gitdb2-2.0.6-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/__pycache__/__init__.cpython-36.pyc from install of rh-python36-gitdb-4.0.2-1.noarch conflicts with file from package rh-python36-gitdb2-2.0.6-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/db/__pycache__/__init__.cpython-36.pyc from install of rh-python36-gitdb-4.0.2-1.noarch conflicts with file from package rh-python36-gitdb2-2.0.6-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/test/__pycache__/__init__.cpython-36.pyc from install of rh-python36-gitdb-4.0.2-1.noarch conflicts with file from package rh-python36-gitdb2-2.0.6-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/utils/__pycache__/__init__.cpython-36.pyc from install of rh-python36-gitdb-4.0.2-1.noarch conflicts with file from package rh-python36-gitdb2-2.0.6-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/__pycache__/base.cpython-36.opt-1.pyc from install of rh-python36-gitdb-4.0.2-1.noarch conflicts with file from package rh-python36-gitdb2-2.0.6-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/db/__pycache__/base.cpython-36.opt-1.pyc from install of rh-python36-gitdb-4.0.2-1.noarch conflicts with file from package rh-python36-gitdb2-2.0.6-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/__pycache__/base.cpython-36.pyc from install of rh-python36-gitdb-4.0.2-1.noarch conflicts with file from package rh-python36-gitdb2-2.0.6-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/db/__pycache__/base.cpython-36.pyc from install of rh-python36-gitdb-4.0.2-1.noarch conflicts with file from package rh-python36-gitdb2-2.0.6-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/__pycache__/const.cpython-36.opt-1.pyc from install of rh-python36-gitdb-4.0.2-1.noarch conflicts with file from package rh-python36-gitdb2-2.0.6-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/__pycache__/const.cpython-36.pyc from install of rh-python36-gitdb-4.0.2-1.noarch conflicts with file from package rh-python36-gitdb2-2.0.6-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/__pycache__/exc.cpython-36.opt-1.pyc from install of rh-python36-gitdb-4.0.2-1.noarch conflicts with file from package rh-python36-gitdb2-2.0.6-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/__pycache__/exc.cpython-36.pyc from install of rh-python36-gitdb-4.0.2-1.noarch conflicts with file from package rh-python36-gitdb2-2.0.6-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/__pycache__/fun.cpython-36.opt-1.pyc from install of rh-python36-gitdb-4.0.2-1.noarch conflicts with file from package rh-python36-gitdb2-2.0.6-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/__pycache__/fun.cpython-36.pyc from install of rh-python36-gitdb-4.0.2-1.noarch conflicts with file from package rh-python36-gitdb2-2.0.6-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/__pycache__/pack.cpython-36.opt-1.pyc from install of rh-python36-gitdb-4.0.2-1.noarch conflicts with file from package rh-python36-gitdb2-2.0.6-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/db/__pycache__/pack.cpython-36.opt-1.pyc from install of rh-python36-gitdb-4.0.2-1.noarch conflicts with file from package rh-python36-gitdb2-2.0.6-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/__pycache__/pack.cpython-36.pyc from install of rh-python36-gitdb-4.0.2-1.noarch conflicts with file from package rh-python36-gitdb2-2.0.6-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/db/__pycache__/pack.cpython-36.pyc from install of rh-python36-gitdb-4.0.2-1.noarch conflicts with file from package rh-python36-gitdb2-2.0.6-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/__pycache__/stream.cpython-36.opt-1.pyc from install of rh-python36-gitdb-4.0.2-1.noarch conflicts with file from package rh-python36-gitdb2-2.0.6-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/__pycache__/stream.cpython-36.pyc from install of rh-python36-gitdb-4.0.2-1.noarch conflicts with file from package rh-python36-gitdb2-2.0.6-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/__pycache__/typ.cpython-36.opt-1.pyc from install of rh-python36-gitdb-4.0.2-1.noarch conflicts with file from package rh-python36-gitdb2-2.0.6-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/__pycache__/typ.cpython-36.pyc from install of rh-python36-gitdb-4.0.2-1.noarch conflicts with file from package rh-python36-gitdb2-2.0.6-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/__pycache__/util.cpython-36.opt-1.pyc from install of rh-python36-gitdb-4.0.2-1.noarch conflicts with file from package rh-python36-gitdb2-2.0.6-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/__pycache__/util.cpython-36.pyc from install of rh-python36-gitdb-4.0.2-1.noarch conflicts with file from package rh-python36-gitdb2-2.0.6-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/base.py from install of rh-python36-gitdb-4.0.2-1.noarch conflicts with file from package rh-python36-gitdb2-2.0.6-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/db/base.py from install of rh-python36-gitdb-4.0.2-1.noarch conflicts with file from package rh-python36-gitdb2-2.0.6-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/const.py from install of rh-python36-gitdb-4.0.2-1.noarch conflicts with file from package rh-python36-gitdb2-2.0.6-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/db/__pycache__/git.cpython-36.opt-1.pyc from install of rh-python36-gitdb-4.0.2-1.noarch conflicts with file from package rh-python36-gitdb2-2.0.6-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/db/__pycache__/git.cpython-36.pyc from install of rh-python36-gitdb-4.0.2-1.noarch conflicts with file from package rh-python36-gitdb2-2.0.6-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/db/__pycache__/loose.cpython-36.opt-1.pyc from install of rh-python36-gitdb-4.0.2-1.noarch conflicts with file from package rh-python36-gitdb2-2.0.6-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/db/__pycache__/loose.cpython-36.pyc from install of rh-python36-gitdb-4.0.2-1.noarch conflicts with file from package rh-python36-gitdb2-2.0.6-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/db/__pycache__/mem.cpython-36.opt-1.pyc from install of rh-python36-gitdb-4.0.2-1.noarch conflicts with file from package rh-python36-gitdb2-2.0.6-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/db/__pycache__/mem.cpython-36.pyc from install of rh-python36-gitdb-4.0.2-1.noarch conflicts with file from package rh-python36-gitdb2-2.0.6-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/db/__pycache__/ref.cpython-36.opt-1.pyc from install of rh-python36-gitdb-4.0.2-1.noarch conflicts with file from package rh-python36-gitdb2-2.0.6-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/db/__pycache__/ref.cpython-36.pyc from install of rh-python36-gitdb-4.0.2-1.noarch conflicts with file from package rh-python36-gitdb2-2.0.6-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/db/git.py from install of rh-python36-gitdb-4.0.2-1.noarch conflicts with file from package rh-python36-gitdb2-2.0.6-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/db/loose.py from install of rh-python36-gitdb-4.0.2-1.noarch conflicts with file from package rh-python36-gitdb2-2.0.6-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/db/mem.py from install of rh-python36-gitdb-4.0.2-1.noarch conflicts with file from package rh-python36-gitdb2-2.0.6-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/db/pack.py from install of rh-python36-gitdb-4.0.2-1.noarch conflicts with file from package rh-python36-gitdb2-2.0.6-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/pack.py from install of rh-python36-gitdb-4.0.2-1.noarch conflicts with file from package rh-python36-gitdb2-2.0.6-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/db/ref.py from install of rh-python36-gitdb-4.0.2-1.noarch conflicts with file from package rh-python36-gitdb2-2.0.6-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/exc.py from install of rh-python36-gitdb-4.0.2-1.noarch conflicts with file from package rh-python36-gitdb2-2.0.6-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/fun.py from install of rh-python36-gitdb-4.0.2-1.noarch conflicts with file from package rh-python36-gitdb2-2.0.6-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/stream.py from install of rh-python36-gitdb-4.0.2-1.noarch conflicts with file from package rh-python36-gitdb2-2.0.6-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/test/__pycache__/lib.cpython-36.opt-1.pyc from install of rh-python36-gitdb-4.0.2-1.noarch conflicts with file from package rh-python36-gitdb2-2.0.6-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/test/__pycache__/lib.cpython-36.pyc from install of rh-python36-gitdb-4.0.2-1.noarch conflicts with file from package rh-python36-gitdb2-2.0.6-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/test/__pycache__/test_base.cpython-36.opt-1.pyc from install of rh-python36-gitdb-4.0.2-1.noarch conflicts with file from package rh-python36-gitdb2-2.0.6-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/test/__pycache__/test_base.cpython-36.pyc from install of rh-python36-gitdb-4.0.2-1.noarch conflicts with file from package rh-python36-gitdb2-2.0.6-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/test/__pycache__/test_example.cpython-36.opt-1.pyc from install of rh-python36-gitdb-4.0.2-1.noarch conflicts with file from package rh-python36-gitdb2-2.0.6-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/test/__pycache__/test_example.cpython-36.pyc from install of rh-python36-gitdb-4.0.2-1.noarch conflicts with file from package rh-python36-gitdb2-2.0.6-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/test/__pycache__/test_pack.cpython-36.opt-1.pyc from install of rh-python36-gitdb-4.0.2-1.noarch conflicts with file from package rh-python36-gitdb2-2.0.6-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/test/__pycache__/test_pack.cpython-36.pyc from install of rh-python36-gitdb-4.0.2-1.noarch conflicts with file from package rh-python36-gitdb2-2.0.6-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/test/__pycache__/test_stream.cpython-36.opt-1.pyc from install of rh-python36-gitdb-4.0.2-1.noarch conflicts with file from package rh-python36-gitdb2-2.0.6-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/test/__pycache__/test_stream.cpython-36.pyc from install of rh-python36-gitdb-4.0.2-1.noarch conflicts with file from package rh-python36-gitdb2-2.0.6-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/test/__pycache__/test_util.cpython-36.opt-1.pyc from install of rh-python36-gitdb-4.0.2-1.noarch conflicts with file from package rh-python36-gitdb2-2.0.6-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/test/__pycache__/test_util.cpython-36.pyc from install of rh-python36-gitdb-4.0.2-1.noarch conflicts with file from package rh-python36-gitdb2-2.0.6-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/test/lib.py from install of rh-python36-gitdb-4.0.2-1.noarch conflicts with file from package rh-python36-gitdb2-2.0.6-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/test/test_base.py from install of rh-python36-gitdb-4.0.2-1.noarch conflicts with file from package rh-python36-gitdb2-2.0.6-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/test/test_example.py from install of rh-python36-gitdb-4.0.2-1.noarch conflicts with file from package rh-python36-gitdb2-2.0.6-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/test/test_pack.py from install of rh-python36-gitdb-4.0.2-1.noarch conflicts with file from package rh-python36-gitdb2-2.0.6-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/test/test_stream.py from install of rh-python36-gitdb-4.0.2-1.noarch conflicts with file from package rh-python36-gitdb2-2.0.6-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/test/test_util.py from install of rh-python36-gitdb-4.0.2-1.noarch conflicts with file from package rh-python36-gitdb2-2.0.6-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/typ.py from install of rh-python36-gitdb-4.0.2-1.noarch conflicts with file from package rh-python36-gitdb2-2.0.6-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/util.py from install of rh-python36-gitdb-4.0.2-1.noarch conflicts with file from package rh-python36-gitdb2-2.0.6-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/utils/__pycache__/encoding.cpython-36.opt-1.pyc from install of rh-python36-gitdb-4.0.2-1.noarch conflicts with file from package rh-python36-gitdb2-2.0.6-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/utils/__pycache__/encoding.cpython-36.pyc from install of rh-python36-gitdb-4.0.2-1.noarch conflicts with file from package rh-python36-gitdb2-2.0.6-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/utils/encoding.py from install of rh-python36-gitdb-4.0.2-1.noarch conflicts with file from package rh-python36-gitdb2-2.0.6-1.noarch
  file /opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/msgpack/__init__.py from install of rh-python36-msgpack-0.6.2-1.x86_64 conflicts with file from package rh-python36-msgpack-python-0.5.6-1.x86_64
  file /opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/msgpack/__pycache__/__init__.cpython-36.opt-1.pyc from install of rh-python36-msgpack-0.6.2-1.x86_64 conflicts with file from package rh-python36-msgpack-python-0.5.6-1.x86_64
  file /opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/msgpack/__pycache__/__init__.cpython-36.pyc from install of rh-python36-msgpack-0.6.2-1.x86_64 conflicts with file from package rh-python36-msgpack-python-0.5.6-1.x86_64
  file /opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/msgpack/__pycache__/_version.cpython-36.opt-1.pyc from install of rh-python36-msgpack-0.6.2-1.x86_64 conflicts with file from package rh-python36-msgpack-python-0.5.6-1.x86_64
  file /opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/msgpack/__pycache__/_version.cpython-36.pyc from install of rh-python36-msgpack-0.6.2-1.x86_64 conflicts with file from package rh-python36-msgpack-python-0.5.6-1.x86_64
  file /opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/msgpack/__pycache__/exceptions.cpython-36.opt-1.pyc from install of rh-python36-msgpack-0.6.2-1.x86_64 conflicts with file from package rh-python36-msgpack-python-0.5.6-1.x86_64
  file /opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/msgpack/__pycache__/exceptions.cpython-36.pyc from install of rh-python36-msgpack-0.6.2-1.x86_64 conflicts with file from package rh-python36-msgpack-python-0.5.6-1.x86_64
  file /opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/msgpack/__pycache__/fallback.cpython-36.opt-1.pyc from install of rh-python36-msgpack-0.6.2-1.x86_64 conflicts with file from package rh-python36-msgpack-python-0.5.6-1.x86_64
  file /opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/msgpack/__pycache__/fallback.cpython-36.pyc from install of rh-python36-msgpack-0.6.2-1.x86_64 conflicts with file from package rh-python36-msgpack-python-0.5.6-1.x86_64
  file /opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/msgpack/_version.py from install of rh-python36-msgpack-0.6.2-1.x86_64 conflicts with file from package rh-python36-msgpack-python-0.5.6-1.x86_64
  file /opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/msgpack/exceptions.py from install of rh-python36-msgpack-0.6.2-1.x86_64 conflicts with file from package rh-python36-msgpack-python-0.5.6-1.x86_64
  file /opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/msgpack/fallback.py from install of rh-python36-msgpack-0.6.2-1.x86_64 conflicts with file from package rh-python36-msgpack-python-0.5.6-1.x86_64`

Skipping the packages the gave errors with `yum install --disablerepo='*' --enablerepo='copr:copr.fedorainfracloud.org:mrmeee:ansible-awx, base' -x *-debuginfo,rh-python36-gitdb,rh-python36-msgpack rh-python36*

But then when i try the next step:

`sudo -u awx scl enable rh-postgresql10 rh-python36 "GIT_PYTHON_REFRESH=quiet awx-manage makemigrations"  

 Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/bin/awx-manage", line 11, in <module>
    load_entry_point('awx==9.3.0', 'console_scripts', 'awx-manage')()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/__init__.py", line 152, in manage
    execute_from_command_line(sys.argv)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/oauth2_provider/models.py", line 11, in <module>
    from django.utils.encoding import python_2_unicode_compatible
ImportError: cannot import name 'python_2_unicode_compatible'`

Please advise.

**Comment by MrMEEE** [comment]
Project has been updated and moved...

Please move to the new version and report any issues

PROJECT MOVED: https://github.com/miracle-as/AWX-RPM

Issues at: https://github.com/miracle-as/AWX-RPM/issues

**Install guide, tools, utilities are located at: https://awx.wiki

**LinkedIn group for Questions, support, talk and more: https://www.linkedin.com/groups/13694893/**
