### ISSUE TITLE
Error while running awx-setup 

### ISSUE THREAD

**Issue by terrorpup** [MrMEEE/awx-build#286]
Creating initial Ansible VENV
    ERROR: Command errored out with exit status 1:
     command: /var/lib/awx/venv/python3-ansible2.10.0rc1-1592020/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-dq5iphjj/azure-storage/setup.py'"'"'; __file__='"'"'/tmp/pip-install-dq5iphjj/azure-storage/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-94xcosad
         cwd: /tmp/pip-install-dq5iphjj/azure-storage/
    Complete output (19 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-dq5iphjj/azure-storage/setup.py", line 55, in <module>
        raise RuntimeError(message)
    RuntimeError:

    Starting with v0.37.0, the 'azure-storage' meta-package is deprecated and cannot be installed anymore.
    Please install the service specific packages prefixed by `azure` needed for your application.

    The complete list of available packages can be found at:
    https://aka.ms/azsdk/python/all

    Here's a non-exhaustive list of common packages:

    - [azure-storage-blob](https://pypi.org/project/azure-storage-blob) : Blob storage client
    - [azure-storage-file-share](https://pypi.org/project/azure-storage-file-share) : Storage file share client
    - [azure-storage-file-datalake](https://pypi.org/project/azure-storage-file-datalake) : ADLS Gen2 client
    - [azure-storage-queue](https://pypi.org/project/azure-storage-queue): Queue storage client

    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by sainigurdeep** [comment]
Installation script install all python modules listed in /usr/share/doc/ansible-awx/ansible-core-reqs.txt file. azure-storage module is being installed from this file but it is deprecated now.  As a work around I updated awx-setup script to remove azure-storage and add modules listed below in /usr/share/doc/ansible-awx/ansible-core-reqs.txt file.

azure-storage-blob
azure-storage-file-share
azure-storage-file-datalake
azure-storage-queue

Permanent fix will be to update /usr/share/doc/ansible-awx/ansible-core-reqs.txt in RPM package.

**Comment by MrMEEE** [comment]
Project has been updated and moved...

Please move to the new version and report any issues

PROJECT MOVED: https://github.com/miracle-as/AWX-RPM

Issues at: https://github.com/miracle-as/AWX-RPM/issues

**Install guide, tools, utilities are located at: https://awx.wiki

**LinkedIn group for Questions, support, talk and more: https://www.linkedin.com/groups/13694893/**
