### ISSUE TITLE
Latency recommendation between multiple region for 3 node cluster setup in AWS (public cloud)

### ISSUE THREAD

**Issue by ompals92** [MrMEEE/awx-build#287]
Hi Team,

There is a requirement to deploy AWX cluster setup and perform API endpoint callups across multiple regions on AWS Cloud.
Latency between two region is ranging from 100-200 ms. can this latency be supported by AWX-tower if not, please suggest a possible workaround. 
what would be the standard recommendation for latency that is required for the setup?

**Comment by MrMEEE** [comment]
Project has been updated and moved...

Please move to the new version and report any issues

PROJECT MOVED: https://github.com/miracle-as/AWX-RPM

Issues at: https://github.com/miracle-as/AWX-RPM/issues

**Install guide, tools, utilities are located at: https://awx.wiki

**LinkedIn group for Questions, support, talk and more: https://www.linkedin.com/groups/13694893/**
