### ISSUE TITLE
RoadMap or Time line

### ISSUE THREAD

**Issue by dominiquearpin** [MrMEEE/awx-build#289]
Hi,

I could be great to known the time line for the next release or some news about this project.  Do you need some beta tester?

Regards,

**Comment by MrMEEE** [comment]
**Project has been updated and moved...

Please move to the new version and report any issues

PROJECT MOVED: https://github.com/miracle-as/AWX-RPM

Issues at: https://github.com/miracle-as/AWX-RPM/issues

**Install guide, tools, utilities are located at: https://awx.wiki

**LinkedIn group for Questions, support, talk and more: https://www.linkedin.com/groups/13694893/****
