### ISSUE TITLE
Add pip to default installation

### ISSUE THREAD

**Issue by rthill** [MrMEEE/awx-build#29]
I am missing the pip command in the default installation on Centos 7. Would be nice to integrate the command in the RPM package to be able to load additional python modules such as pyvmomi.

Or do you consider other scripts like used in the inventory scripts should make use of another Python virtual environment?

**Comment by MrMEEE** [comment]
Hi

I think I would rather keep addition scripts in their own environments to make sure that they don't interfere...

**Comment by rthill** [comment]
Ok, perfect I'll create my own virtualenv to run my scripts.                                                                                                                                      Cheers,Raoul                                                                                                                                                                           From: notifications@github.comSent: June 16, 2018 12:14 AMTo: awx-build@noreply.github.comReply-to: reply@reply.github.comCc: raoul.thill@gmail.com; author@noreply.github.comSubject: Re: [MrMEEE/awx-build] Add pip to default installation (#29)  Hi
I think I would rather keep addition scripts in their own environments to make sure that they don't interfere...
