### ISSUE TITLE
yum -y install --disablerepo='*' --enablerepo='mrmeee-ansible-awx, base' -x *-debuginfo rh-python36*

### ISSUE THREAD

**Issue by vipulkothifoda** [MrMEEE/awx-build#290]
file /opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/msgpack/__init__.py conflicts between attempted installs of rh-python36-msgpack-python-0.5.6-1.x86_64 and rh-python36-msgpack-0.6.2-1.x86_64
  file /opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/msgpack/__pycache__/__init__.cpython-36.opt-1.pyc conflicts between attempted installs of rh-python36-msgpack-python-0.5.6-1.x86_64 and rh-python36-msgpack-0.6.2-1.x86_64
  file /opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/msgpack/__pycache__/__init__.cpython-36.pyc conflicts between attempted installs of rh-python36-msgpack-python-0.5.6-1.x86_64 and rh-python36-msgpack-0.6.2-1.x86_64
  file /opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/msgpack/__pycache__/_version.cpython-36.opt-1.pyc conflicts between attempted installs of rh-python36-msgpack-python-0.5.6-1.x86_64 and rh-python36-msgpack-0.6.2-1.x86_64
  file /opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/msgpack/__pycache__/_version.cpython-36.pyc conflicts between attempted installs of rh-python36-msgpack-python-0.5.6-1.x86_64 and rh-python36-msgpack-0.6.2-1.x86_64
  file /opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/msgpack/__pycache__/exceptions.cpython-36.opt-1.pyc conflicts between attempted installs of rh-python36-msgpack-python-0.5.6-1.x86_64 and rh-python36-msgpack-0.6.2-1.x86_64
  file /opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/msgpack/__pycache__/exceptions.cpython-36.pyc conflicts between attempted installs of rh-python36-msgpack-python-0.5.6-1.x86_64 and rh-python36-msgpack-0.6.2-1.x86_64
  file /opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/msgpack/__pycache__/fallback.cpython-36.opt-1.pyc conflicts between attempted installs of rh-python36-msgpack-python-0.5.6-1.x86_64 and rh-python36-msgpack-0.6.2-1.x86_64
  file /opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/msgpack/__pycache__/fallback.cpython-36.pyc conflicts between attempted installs of rh-python36-msgpack-python-0.5.6-1.x86_64 and rh-python36-msgpack-0.6.2-1.x86_64
  file /opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/msgpack/_version.py conflicts between attempted installs of rh-python36-msgpack-python-0.5.6-1.x86_64 and rh-python36-msgpack-0.6.2-1.x86_64
  file /opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/msgpack/exceptions.py conflicts between attempted installs of rh-python36-msgpack-python-0.5.6-1.x86_64 and rh-python36-msgpack-0.6.2-1.x86_64
  file /opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/msgpack/fallback.py conflicts between attempted installs of rh-python36-msgpack-python-0.5.6-1.x86_64 and rh-python36-msgpack-0.6.2-1.x86_64
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/__init__.py from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/db/__init__.py from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/test/__init__.py from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/__pycache__/__init__.cpython-36.opt-1.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/db/__pycache__/__init__.cpython-36.opt-1.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/test/__pycache__/__init__.cpython-36.opt-1.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/utils/__pycache__/__init__.cpython-36.opt-1.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/__pycache__/__init__.cpython-36.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/db/__pycache__/__init__.cpython-36.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/test/__pycache__/__init__.cpython-36.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/utils/__pycache__/__init__.cpython-36.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/__pycache__/util.cpython-36.opt-1.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/__pycache__/util.cpython-36.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/util.py from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/__pycache__/base.cpython-36.opt-1.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/db/__pycache__/base.cpython-36.opt-1.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/__pycache__/base.cpython-36.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/db/__pycache__/base.cpython-36.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/base.py from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/db/base.py from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/utils/__pycache__/encoding.cpython-36.opt-1.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/utils/__pycache__/encoding.cpython-36.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/utils/encoding.py from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/__pycache__/exc.cpython-36.opt-1.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/__pycache__/exc.cpython-36.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/exc.py from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/__pycache__/fun.cpython-36.opt-1.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/__pycache__/fun.cpython-36.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/__pycache__/typ.cpython-36.opt-1.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/__pycache__/typ.cpython-36.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/fun.py from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/typ.py from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/test/__pycache__/test_base.cpython-36.opt-1.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/test/__pycache__/test_base.cpython-36.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/test/__pycache__/test_util.cpython-36.opt-1.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/test/__pycache__/test_util.cpython-36.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/test/__pycache__/lib.cpython-36.opt-1.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/test/__pycache__/lib.cpython-36.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/test/lib.py from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/test/test_base.py from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/test/test_util.py from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/db/__pycache__/git.cpython-36.opt-1.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/db/__pycache__/git.cpython-36.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/db/git.py from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/__pycache__/const.cpython-36.opt-1.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/__pycache__/const.cpython-36.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/const.py from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/__pycache__/pack.cpython-36.opt-1.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/db/__pycache__/pack.cpython-36.opt-1.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/__pycache__/pack.cpython-36.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/db/__pycache__/pack.cpython-36.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/__pycache__/stream.cpython-36.opt-1.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/__pycache__/stream.cpython-36.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/db/__pycache__/loose.cpython-36.opt-1.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/db/__pycache__/loose.cpython-36.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/db/__pycache__/mem.cpython-36.opt-1.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/db/__pycache__/mem.cpython-36.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/db/__pycache__/ref.cpython-36.opt-1.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/db/__pycache__/ref.cpython-36.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/db/loose.py from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/db/mem.py from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/db/pack.py from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/pack.py from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/db/ref.py from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/stream.py from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/test/__pycache__/test_example.cpython-36.opt-1.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/test/__pycache__/test_example.cpython-36.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/test/__pycache__/test_pack.cpython-36.opt-1.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/test/__pycache__/test_pack.cpython-36.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/test/__pycache__/test_stream.cpython-36.opt-1.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/test/__pycache__/test_stream.cpython-36.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/test/test_example.py from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/test/test_pack.py from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/test/test_stream.py from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch

Error Summary
-------------

**Comment by vipulkothifoda** [comment]
Hi there,
any thoughts on this issue?

**Comment by sblee3** [comment]
I'm having the same problem since the new rpm build with 'awx-setup; has been established. I have an Oracle Linux 7.8 system but have the same problem using the scl from both Oracle Linux or CentOS. Our systems use RedHat kernels so either scl repo should work.  All the instructions point to using the scl 'rh-python3' but the conflicts are generated when trying to install awx.  This is a non-docker installation. Are we better off to use the epel python3?? Please - help.

**Comment by vipulkothifoda** [comment]
Hi, Please respond on this issue.

**Comment by lexmoe** [comment]
Hello Guys, is the new installer.

yum -y install python36
curl -o /root/awx-setup https://raw.githubusercontent.com/MrMEEE/awx-rpm/master/awx-setup
chmod +x /root/awx-setup
/root/awx-setup -i

https://awx.wiki/blog/new-build-server-new-installer-new-maintainers-same-project

BR,

**Comment by MrMEEE** [comment]
Project has been updated and moved...

Please move to the new version and report any issues

PROJECT MOVED: https://github.com/miracle-as/AWX-RPM

Issues at: https://github.com/miracle-as/AWX-RPM/issues

**Install guide, tools, utilities are located at: https://awx.wiki

**LinkedIn group for Questions, support, talk and more: https://www.linkedin.com/groups/13694893/**
