### ISSUE TITLE
Localhost.localdomain not getting loaded

### ISSUE THREAD

**Issue by surbhijain1502** [MrMEEE/awx-build#291]
Hi, 

My installation has completed successfully. 
At the end, got the message below: 
**Congratulations, AWX-RPM is now installed, and hopefully running on http://localhost.localdomain.**
When browsed at the mention location, I have got 

![image](https://user-images.githubusercontent.com/58592939/98675239-ff8a3b00-237f-11eb-9a76-7db9867c9a8e.png)

Is I am missing something? Please help.

**Comment by MrMEEE** [comment]
Project has been updated and moved...

Please move to the new version and report any issues

PROJECT MOVED: https://github.com/miracle-as/AWX-RPM

Issues at: https://github.com/miracle-as/AWX-RPM/issues

**Install guide, tools, utilities are located at: https://awx.wiki

**LinkedIn group for Questions, support, talk and more: https://www.linkedin.com/groups/13694893/**
