### ISSUE TITLE
AWX 11.2 Logstash Error

### ISSUE THREAD

**Issue by timesy** [MrMEEE/awx-build#292]
##### ISSUE TYPE
* Bug Report
 
##### SUMMARY
AWX is not able to send logs to Logstash (same issue as #https://github.com/ansible/awx/issues/6794, which was opened with my old github account). The "Test" Button tells me that the test was sent successfully. In the /var/log/tower/web.log I can see the following log messages:
 
```
2020-11-12 04:47:15,786 ERROR    awx AWX Connection Test Message
ERROR:awx:AWX Connection Test Message
[pid: 1356|app: 0|req: 247/1150] 131.152.2.38 () {56 vars in 2598 bytes} [Thu Nov 12 04:47:15 2020] POST /api/v2/settings/logging/test/ => generated 0 bytes in 116 msecs (HTTP/1.1 202) 9 headers in 280 bytes (1 switches on core 0)
```
Now I suspect it has something to do with rsyslog as in the other issue. However I am not sure where to start looking, as there is no supervisor.conf to use, which shows what is running and what not. rsyslog is running:
 
```
root     17429  0.0  0.2 373024 16860 ?        Ssl  Nov11   0:06 /usr/sbin/rsyslogd -n
```

In /var/lib/awx/rsyslog/rsyslog.conf I also see the following lines:
 ```
$WorkDirectory /var/lib/awx/rsyslog
$MaxMessageSize 700000
$IncludeConfig /var/lib/awx/rsyslog/conf.d/*.conf
main_queue(queue.spoolDirectory="/var/lib/awx" queue.maxdiskspace="1g" queue.type="Disk" queue.filename="awx-external-logger-backlog")
module(load="imuxsock" SysSock.Use="off")
input(type="imuxsock" Socket="/var/run/awx-rsyslog/rsyslog.sock" unlink="on")
template(name="awx" type="string" string="%rawmsg-after-pri%")
action(type="omfwd" target="redacted" port="5044" protocol="tcp" action.resumeRetryCount="-1" action.resumeInterval="5" template="awx")
```

However there is no such conf.d folder. There is also no /var/run/awx-rsyslog/rsyslog.sock file or awx-rsyslog folder. Do you have any pointers how to debug this further?
 
##### ENVIRONMENT
* AWX version: 11.2.0
* AWX install method: RPM
* Ansible version:  2.9.14
* Operating System: CentOS 7.8.2003
* Web Browser: Safari
 
##### STEPS TO REPRODUCE
Trying to send a test message to Logstash.
 
##### EXPECTED RESULTS
A new log entry should be visible in Kibana.
 
##### ACTUAL RESULTS
No log entry in Kibana.

**Comment by MrMEEE** [comment]
Project has been updated and moved...

Please move to the new version and report any issues

PROJECT MOVED: https://github.com/miracle-as/AWX-RPM

Issues at: https://github.com/miracle-as/AWX-RPM/issues

**Install guide, tools, utilities are located at: https://awx.wiki

**LinkedIn group for Questions, support, talk and more: https://www.linkedin.com/groups/13694893/**
