### ISSUE TITLE
Update high availability 

### ISSUE THREAD

**Issue by Nikkurer** [MrMEEE/awx-build#293]
Please add this repo https://github.com/fitbeard/awx-ha-cluster to the High availability page. It's newer than sujiar37's and supports latest AWX versions.

**Comment by powertim** [comment]
Hi @Nikkurer  it seems that is not using the RPM version there...

**Comment by Nikkurer** [comment]
Hi @powertim 
But in the "Interesting Links" part you have a link for https://github.com/sujiar37/AWX-HA-InstanceGroup but it doesn't use the RPM too. And there is in README written that it is the deprecated role.
So I don't see why you can't add a link to actual and useful repo instead or in addition to old and deprecated.
I believe it will help many people to find the right way to install AWX in the HA variant.

**Comment by MrMEEE** [comment]
Project has been updated and moved...

Please move to the new version and report any issues

PROJECT MOVED: https://github.com/miracle-as/AWX-RPM

Issues at: https://github.com/miracle-as/AWX-RPM/issues

**Install guide, tools, utilities are located at: https://awx.wiki

**LinkedIn group for Questions, support, talk and more: https://www.linkedin.com/groups/13694893/**
