### ISSUE TITLE
New repo https://rpm.miracle.dk/AWX_RPM is not accessible now and throwing error

### ISSUE THREAD

**Issue by ghost** [MrMEEE/awx-build#294]
Please let us know whether the link is temporarily down or permanent. Is there any alternative link for us to access?
![error mess](https://user-images.githubusercontent.com/70003352/100373738-3d9a8680-3031-11eb-8970-0a704caf1701.JPG)

**Comment by apoorvp2** [comment]
Is there an update on the workaround for this issue. The AWX installer script does a callup to the link  https://rpm.miracle.dk/AWX-RPM/CentOS_7" for downloading the package but its failing as the link is down . Pls help with any suggestion or workaround for the issue.

**Comment by MrMEEE** [comment]
Should be back up now..

**Comment by apoorvp2** [comment]
Hello Martin,

The issue with  https://rpm.miracle.dk/AWX-RPM/CentOS_7 has resurfaced . The URL is not reachable anymore. It gives the exception stating Application is not available.

Kindly suggest a suitable workaround for the same.

**Comment by kapilkhub88** [comment]
Hi Martin,

For some reason, the url https://rpm.miracle.dk/ is currently not available and not allowing to proceed ahead with ansible awx deployment. Can you please help in resolving this issue.
