### ISSUE TITLE
Issues with AWX-RPM About Screen in AWX

### ISSUE THREAD

**Issue by crupib** [MrMEEE/awx-build#295]
______________ 
<  AWX 11.2.0  >
 -------------- 
        \   ^__^
         \  (oo)\_______
            (__)      A )\/\
                ||----w |
                ||     ||

**Ansible unknown**
Copyright © 2019 Red Hat, Inc.
Visit Ansible.com for more information.

Why does Ansible say unknown and do you know how to fix it?

**Comment by sainigurdeep** [comment]
Installing ansible using yum will fix this issue.
sudo yum install ansible

**Comment by MrMEEE** [comment]
Project has been updated and moved...

Please move to the new version and report any issues

PROJECT MOVED: https://github.com/miracle-as/AWX-RPM

Issues at: https://github.com/miracle-as/AWX-RPM/issues

**Install guide, tools, utilities are located at: https://awx.wiki

**LinkedIn group for Questions, support, talk and more: https://www.linkedin.com/groups/13694893/**
