### ISSUE TITLE
URL not available

### ISSUE THREAD

**Issue by tfprelvas** [MrMEEE/awx-build#296]
Hello,

When i've tried to install (from https://awx.wiki/blog/new-build-server-new-installer-new-maintainers-same-project ) the awx-setup I can't get the xml file:
 
Errors during downloading metadata for repository 'ansible-awx':
  - Status code: 503 for https://rpm.miracle.dk/AWX-RPM/CentOS_8/repodata/repomd.xml (IP: 81.19.233.33)
Error: Failed to download metadata for repo 'ansible-awx': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried

Can you help me ?

**Comment by MrMEEE** [comment]
Repo is back up..
