### ISSUE TITLE
Build not working on rhel 8 or centos 8 

### ISSUE THREAD

**Issue by tfprelvas** [MrMEEE/awx-build#298]
Hello,

Everytime I try to install on CentOS 8 or RHEL 8 it pops out this error:

Creating initial Ansible VENV
/bin/sh: awx-create-venv: command not found

Locking package versions for AWX-RPM and dependencies
Traceback (most recent call last):
  File "./awx-setup", line 385, in <module>
    main(sys.argv[1:])
  File "./awx-setup", line 316, in main
    with open("/usr/share/doc/ansible-awx/awx-locks.txt", "r") as a_file:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/doc/ansible-awx/awx-locks.txt'

Traceback (most recent call last):
  File "./awx-setup", line 385, in <module>
    main(sys.argv[1:])
  File "./awx-setup", line 338, in main
    open(install_status_file, 'a').close()
FileNotFoundError: [Errno 2] No such file or directory: '/etc/tower/INSTALLED'

On CentOS 7 works perfect the same procedure.

Procedure:
yum -y install python36
curl -o /root/awx-setup https://raw.githubusercontent.com/MrMEEE/awx-rpm/master/awx-setup
chmod +x /root/awx-setup
/root/awx-setup -i

Thanks in advance

**Comment by MrMEEE** [comment]
Project has been updated and moved...

Please move to the new version and report any issues

PROJECT MOVED: https://github.com/miracle-as/AWX-RPM

Issues at: https://github.com/miracle-as/AWX-RPM/issues

**Install guide, tools, utilities are located at: https://awx.wiki

**LinkedIn group for Questions, support, talk and more: https://www.linkedin.com/groups/13694893/**
