### ISSUE TITLE
Project awx-build

### ISSUE THREAD

**Issue by kyklos** [MrMEEE/awx-build#299]
Is the project still being maintained and will future AWX updates be expected? I ask because AWX 16.0.0 has already been released.

**Comment by MrMEEE** [comment]
Hi

We are still in a development process of getting dependencies to build correctly.. This project is NOT dead in any way.. even though it has been quite a long slumber... 

I hope that we we'll have releases up to date within a month or so...

**Comment by kyklos** [comment]
Great, I'm glad to hear that. Good luck

**Comment by dominiquearpin** [comment]
Some news? Maybe the project will awake soon?

**Comment by MrMEEE** [comment]
We hope so.. Corona has given us way to much work, so we are struggling to get any work done on AWX-RPM.. We still hop to have something to share with you guys soon...

**Comment by dominiquearpin** [comment]
yep. its me again with same question...  I think  I will get the same response?  I hope not... ;)
