### ISSUE TITLE
Release changelog

### ISSUE THREAD

**Issue by rthill** [MrMEEE/awx-build#30]
Hi,

with each new RPM package the changelog only contains the information `New Git version build: 1.0.x.y`. How can I find the real information e.g: current revision from AWX repository when the RPM package is built or link to the original changelog?

Thanks

**Comment by MrMEEE** [comment]
This is actually something that I have wanted todo myself... but haven't gotten around to it..

I'm just pulling the code from the upstream repo and building it..

**Comment by rthill** [comment]
To get the current commit hash of HEAD, you can run the command: `git rev-parse --short HEAD` or without the short if you like the long version of the commit hash. With this information the different release are at least a bit trackable.

**Comment by tjyang** [comment]
Just a note to myself.

* Example of how  "awx-2.1.2.32-1.el7.x86_64" rpm got 2.1.2.32 version string
```
RELEASE=`git describe --long |cut -f1-2 -d- |sed 's/-/./'`
[me@awx01 awx]$ cat /etc/redhat-release
CentOS Linux release 7.6.1810 (Core)
[me@awx01 awx]$ git describe --long
2.1.2-32-gaa8cda0
[me@awx01 awx]$ git describe --long  |cut -f1-2 -d- |sed 's/-/./'
2.1.2.32
[me@awx01 awx]$ pwd
/home/me/github/awx
[me@awx01 awx]$

```
* so 2.1.2-32 is up to [qaa8cda0 commit](https://github.com/ansible/awx/commit/aa8cda0001ee9e8be35b0ca1a999e16a1ac8b899). Under [awx devel branch](https://github.com/ansible/awx/commits/devel)
