### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe7 in position 333: invalid continuation byte.

### ISSUE THREAD

**Issue by gmanera** [MrMEEE/awx-build#301]
Hello Guys,

Greetings from Brazil.

When I run the following task using Ansible / AWX-RPM, I'm facing the error message: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe7 in position 333: invalid continuation byte.

Task:
- name: POST update_inventory
  uri: 
    url: http://awx:port/api/v2/inventories/1/hosts/
    user: "{{ user_awx }}"
    password: "{{ password_awx }}"
    method: POST
    body: "{{ lookup('template','update_inventory.json.j2') }}"
    force_basic_auth: yes
    status_code:
      - 200
      - 400
    validate_certs: false
    timeout: 180
    body_format: json

Output of the error message:

Jan 19 09:24:30 ansible-unj scl: 2021-01-19 12:24:30,209 ERROR    awx.main.tasks job 915 (running) Exception occurred while running task
Jan 19 09:24:30 ansible-unj scl: Traceback (most recent call last):
Jan 19 09:24:30 ansible-unj scl: File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/tasks.py", line 1404, in run
Jan 19 09:24:30 ansible-unj scl: res = ansible_runner.interface.run(**params)
Jan 19 09:24:30 ansible-unj scl: File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/ansible_runner/interface.py", line 178, in run
Jan 19 09:24:30 ansible-unj scl: r.run()
Jan 19 09:24:30 ansible-unj scl: File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/ansible_runner/runner.py", line 205, in run
Jan 19 09:24:30 ansible-unj scl: searchwindowsize=100)
Jan 19 09:24:30 ansible-unj scl: File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/pexpect/spawnbase.py", line 341, in expect
Jan 19 09:24:30 ansible-unj scl: timeout, searchwindowsize, async_)
Jan 19 09:24:30 ansible-unj scl: File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/pexpect/spawnbase.py", line 369, in expect_list
Jan 19 09:24:30 ansible-unj scl: return exp.expect_loop(timeout)
Jan 19 09:24:30 ansible-unj scl: File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/pexpect/expect.py", line 111, in expect_loop
Jan 19 09:24:30 ansible-unj scl: incoming = spawn.read_nonblocking(spawn.maxread, timeout)
Jan 19 09:24:30 ansible-unj scl: File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/pexpect/pty_spawn.py", line 500, in read_nonblocking
Jan 19 09:24:30 ansible-unj scl: return super(spawn, self).read_nonblocking(size)
Jan 19 09:24:30 ansible-unj scl: File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/pexpect/spawnbase.py", line 178, in read_nonblocking
Jan 19 09:24:30 ansible-unj scl: s = self._decoder.decode(s, final=False)
Jan 19 09:24:30 ansible-unj scl: File "/opt/rh/rh-python36/root/usr/lib64/python3.6/codecs.py", line 321, in decode
Jan 19 09:24:30 ansible-unj scl: (result, consumed) = self._buffer_decode(data, self.errors, final)
Jan 19 09:24:30 ansible-unj scl: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe7 in position 333: invalid continuation byte

![image](https://user-images.githubusercontent.com/31084313/105041783-2fba1e00-5a42-11eb-8a11-f6c18d5640ef.png)

AWX: ansible-awx-9.3.0.104-1.el7.x86_64
Ansible: rh-python36-ansible-2.9.6-1.noarch

**Comment by MrMEEE** [comment]
Project has been updated and moved...

Please move to the new version and report any issues

PROJECT MOVED: https://github.com/miracle-as/AWX-RPM

Issues at: https://github.com/miracle-as/AWX-RPM/issues

**Install guide, tools, utilities are located at: https://awx.wiki

**LinkedIn group for Questions, support, talk and more: https://www.linkedin.com/groups/13694893/**
