### ISSUE TITLE
AWX job error after proper AWX installation

### ISSUE THREAD

**Issue by aankit10mu** [MrMEEE/awx-build#302]
Hi, I have installed Ansible AWX with redis 4 Node setup, Installation was successful without any error. But After setup when tried to execute adhoc ping job on localhost and target , i run into the error.

Please suggest how to resolve the issue. Below are the error.

Traceback (most recent call last):
  File "/bin/ansible", line 62, in <module>
    import ansible.constants as C
  File "/usr/lib/python2.7/site-packages/ansible/constants.py", line 19, in <module>
    from ansible.config.manager import ConfigManager, ensure_type, get_ini_config_value
  File "/usr/lib/python2.7/site-packages/ansible/config/manager.py", line 17, in <module>
    from yaml import load as yaml_load
  File "/var/lib/awx/venv/ansible/lib/python3.6/site-packages/yaml/__init__.py", line 399
    class YAMLObject(metaclass=YAMLObjectMetaclass):
                              ^
SyntaxError: invalid syntax

**Comment by MrMEEE** [comment]
Project has been updated and moved...

Please move to the new version and report any issues

PROJECT MOVED: https://github.com/miracle-as/AWX-RPM

Issues at: https://github.com/miracle-as/AWX-RPM/issues

**Install guide, tools, utilities are located at: https://awx.wiki

**LinkedIn group for Questions, support, talk and more: https://www.linkedin.com/groups/13694893/**
