### ISSUE TITLE
AWX HA setup with redis

### ISSUE THREAD

**Issue by aankit10mu** [MrMEEE/awx-build#303]
Hi, 

Can anyone suggest how to setup Ansible AWX installation in cluster/HA mode with redis, As rabbitmq has been depricated in the latest build.

**Comment by MrMEEE** [comment]
Project has been updated and moved...

Please move to the new version and report any issues

PROJECT MOVED: https://github.com/miracle-as/AWX-RPM

Issues at: https://github.com/miracle-as/AWX-RPM/issues

**Install guide, tools, utilities are located at: https://awx.wiki

**LinkedIn group for Questions, support, talk and more: https://www.linkedin.com/groups/13694893/**
