### ISSUE TITLE
Installer failing

### ISSUE THREAD

**Issue by ntwrkguy** [MrMEEE/awx-build#304]
When attempting the install, it has errors

This is going to install AWX-RPM and all dependencies.. This installer is meant to be easy, not customizable..
Check https://awx.wiki for advanced install methods and more info..
Do you want to continue?  [y/N] y
Setting up AWX-RPM
Configuring SELinux

ValueError: Port tcp/8050 already defined

Configuring Firewall (Disabling for now/TODO)

Configure Repositories
Adding EPEL

Adding AWX-RPM Repo
Installing Redis

Installing PostgreSQL

Installing Memcached

Installing NGINX

Installing AWX-RPM
Error:
 Problem: problem with installed package vdo-6.2.3.114-14.el8.x86_64
  - package vdo-6.2.3.114-14.el8.x86_64 requires python3-PyYAML >= 3.10, but none of the providers can be installed
  - cannot install both python3-pyyaml-5.3.1-4.14.x86_64 and python3-pyyaml-3.12-12.el8.x86_64
  - package ansible-awx-11.2.0-20.12.x86_64 requires python3-pyyaml = 5.3.1, but none of the providers can be installed
  - conflicting requests

Initialising PostgreSQL
WARNING: using obsoleted argument syntax, try --help
WARNING: arguments transformed to: postgresql-setup --initdb --unit postgresql
 * Initializing database in '/var/lib/pgsql/data'
ERROR: Data directory /var/lib/pgsql/data is not empty!
ERROR: Initializing database failed, possibly see /var/lib/pgsql/initdb_postgresql.log

Starting PostgreSQL

Creating AWX postgreSQL user and Database
could not change directory to "/root": Permission denied
createuser: creation of new role failed: ERROR:  role "awx" already exists

could not change directory to "/root": Permission denied
createdb: database creation failed: ERROR:  database "awx" already exists

Installing pwgen

Generating Secret key
/bin/sh: /etc/tower/SECRET_KEY: Is a directory

Initial database migration
sudo: awx-manage: command not found

Creating Admin user
sudo: awx-manage: command not found

Adding example data and registering AWX-RPM Instance in database
sudo: awx-manage: command not found

sudo: awx-manage: command not found

sudo: awx-manage: command not found

Installing NGINX Configuration
/bin/cp: cannot stat '/usr/share/doc/ansible-awx/nginx.conf.example': No such file or directory

Configuring Redis
Adding user awx to group redis

Creating initial Ansible VENV
/bin/sh: awx-create-venv: command not found

Locking package versions for AWX-RPM and dependencies
Traceback (most recent call last):
  File "/root/awx-setup", line 385, in <module>
    main(sys.argv[1:])
  File "/root/awx-setup", line 316, in main
    with open("/usr/share/doc/ansible-awx/awx-locks.txt", "r") as a_file:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/doc/ansible-awx/awx-locks.txt'

**Comment by MrMEEE** [comment]
Project has been updated and moved...

Please move to the new version and report any issues

PROJECT MOVED: https://github.com/miracle-as/AWX-RPM

Issues at: https://github.com/miracle-as/AWX-RPM/issues

**Install guide, tools, utilities are located at: https://awx.wiki

**LinkedIn group for Questions, support, talk and more: https://www.linkedin.com/groups/13694893/**
