### ISSUE TITLE
Centos 7 build fail azure-storage

### ISSUE THREAD

**Issue by razvan01** [MrMEEE/awx-build#305]
Installing on Centos 7 with all packages up-to date generate the following error related to azure-storage python package.

`    ERROR: Command errored out with exit status 1:
     command: /var/lib/awx/venv/python3-ansible3.0.0rc1-1032021/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-qquabl1v/azure-storage_c6981547584b40c19536aad5b4599f7c/setup.py'"'"'; __file__='"'"'/tmp/pip-install-qquabl1v/azure-storage_c6981547584b40c19536aad5b4599f7c/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-pn96fh2q
         cwd: /tmp/pip-install-qquabl1v/azure-storage_c6981547584b40c19536aad5b4599f7c/
    Complete output (19 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-qquabl1v/azure-storage_c6981547584b40c19536aad5b4599f7c/setup.py", line 55, in <module>
        raise RuntimeError(message)
    RuntimeError:
    
    Starting with v0.37.0, the 'azure-storage' meta-package is deprecated and cannot be installed anymore.
    Please install the service specific packages prefixed by `azure` needed for your application.
    
    The complete list of available packages can be found at:
    https://aka.ms/azsdk/python/all
    
    Here's a non-exhaustive list of common packages:
    
    - [azure-storage-blob](https://pypi.org/project/azure-storage-blob) : Blob storage client
    - [azure-storage-file-share](https://pypi.org/project/azure-storage-file-share) : Storage file share client
    - [azure-storage-file-datalake](https://pypi.org/project/azure-storage-file-datalake) : ADLS Gen2 client
    - [azure-storage-queue](https://pypi.org/project/azure-storage-queue): Queue storage client
`
Can you tell me which package I need to install manually to make it work?
Thanks

**Comment by MrMEEE** [comment]
Project has been updated and moved...

Please move to the new version and report any issues

PROJECT MOVED: https://github.com/miracle-as/AWX-RPM

Issues at: https://github.com/miracle-as/AWX-RPM/issues

**Install guide, tools, utilities are located at: https://awx.wiki

**LinkedIn group for Questions, support, talk and more: https://www.linkedin.com/groups/13694893/**
