### ISSUE TITLE
Upgrade from 9.1.1 to the latest version

### ISSUE THREAD

**Issue by MichalRatzke** [MrMEEE/awx-build#307]
Hello All

Could someone please advise what would be the best upgrade steps to bring AWX to the latest version from 9.1.1? I saw one recommendation on this forum to use playbook, but it is descirbed for version from 9.2.
I tried upgrade current version of AWX using recommended upgrade steps, but there were plenty of dependency errors.
All help will be much appreciated 

Thank you

**Comment by MichalRatzke** [comment]
Hi

Forgot to add, it is currently running on Centos 7.7

Thank you

**Comment by MrMEEE** [comment]
Project has been updated and moved...

Please move to the new version and report any issues

PROJECT MOVED: https://github.com/miracle-as/AWX-RPM

Issues at: https://github.com/miracle-as/AWX-RPM/issues

**Install guide, tools, utilities are located at: https://awx.wiki

**LinkedIn group for Questions, support, talk and more: https://www.linkedin.com/groups/13694893/**
