### ISSUE TITLE
Project awx-build

### ISSUE THREAD

**Issue by dominiquearpin** [MrMEEE/awx-build#308]
Hi,

I could be interesting to have some news about the next release.  I asked, because AWX 19.0 was released this week.

Could you share a road map for the next release, do you need some "beta" tester?

Regards,

**Comment by dominiquearpin** [comment]
@MrMEEE: the 17.1 release, its the last version supported under docker.  They change the installer with new version, is that something will impact your project?

**Comment by david-sieg** [comment]
@MrMEEE: Is such Project still alive?

**Comment by dominiquearpin** [comment]
Seem the projet is alive...https://awx.wiki/blog/getting-back-in-gear
