### ISSUE TITLE
Popup window from "About" not updated with newer version number

### ISSUE THREAD

**Issue by tjyang** [MrMEEE/awx-build#31]
* upgrade to 1.0.6.28 from 1.0.6.26 
```
[root@awx ~]# rpm -qa |grep awx
awx-1.0.6.28-1.el7.x86_64
[root@awx ~]# date
Sat Jul 14 06:11:07 EDT 2018
[root@awx ~]# rpm -qi awx
Name        : awx
Version     : 1.0.6.28
Release     : 1.el7
Architecture: x86_64
Install Date: Sat 14 Jul 2018 05:56:46 AM EDT
Group       : AWX
Size        : 391721680
License     : GPLv3
Signature   : RSA/SHA1, Fri 13 Jul 2018 12:56:26 PM EDT, Key ID eb9bbd0a3cdbce5b
Source RPM  : awx-1.0.6.28-1.el7.src.rpm
Build Date  : Fri 13 Jul 2018 12:55:42 PM EDT
Build Host  : 6d2f2b6b272b4c5883b090e9e23962b2
Relocations : /opt/awx
Vendor      : AWX
Summary     : Ansible AWX
Description :
Ansible AWX
[root@awx ~]#

```
* Popup window from "About" not updated with newer version number
![image](https://user-images.githubusercontent.com/378638/42723523-b8efdb54-8724-11e8-9156-439aa30f8458.png)

* version info from tower-cli

```
[root@awx ~]# tower-cli version
Tower CLI 3.3.0
API v2
AWX 1.0.6.26
Ansible 2.5.0
[root@awx ~]#

```

**Comment by MrMEEE** [comment]
hmmm... not seeing that here.. have you restarted the services after ??

systemctl restart awx-celery-worker awx-cbreceiver awx-celery-beat awx-channels-worker awx-daphne awx-web

[root@akiva ~]# tower-cli version
Tower CLI 3.3.0
API v2
AWX 1.0.6.28
Ansible 2.5.0

![awx28](https://user-images.githubusercontent.com/768031/42728804-d7e52b32-87c3-11e8-8f54-3cf647e96dfe.png)

**Comment by tjyang** [comment]
My bad, I didn't restart awx services.

```
[root@awx ~]# tower-cli version
Tower CLI 3.3.0
API v2
AWX 1.0.6.26
Ansible 2.5.0
[root@awx ~]# systemctl restart awx-\*
[root@awx ~]# tower-cli version
Tower CLI 3.3.0
API v2
AWX 1.0.6.28
Ansible 2.5.0
[root@awx ~]#

```
