### ISSUE TITLE
install rabbitmq-server - HTTPS Error 403 - Forbidden

### ISSUE THREAD

**Issue by RufusCool** [MrMEEE/awx-build#310]
error with repository access

`yum -y install rabbitmq-server
Loaded plugins: fastestmirror, langpacks
Determining fastest mirrors
epel/x86_64/metalink                                                                                                                                                                            |  53 kB  00:00:00
 * base: ftp.unicamp.br
 * centos-sclo-rh: ftp.unicamp.br
 * centos-sclo-sclo: ftp.unicamp.br
 * epel: mirror1.cl.netactuate.com
 * extras: ftp.unicamp.br
 * updates: ftp.unicamp.br
base                                                                                                                                                                                            | 3.6 kB  00:00:00
https://dl.bintray.com/rabbitmq-erlang/rpm/erlang/21/el/7/repodata/repomd.xml: [Errno 14] HTTPS Error 403 - Forbidden
Trying other mirror.
To address this issue please refer to the below wiki article

https://wiki.centos.org/yum-errors

If above article doesn't help to resolve this issue please use https://bugs.centos.org/.

 One of the configured repositories failed (bintray-rabbitmq-erlang-rpm),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=bintraybintray-rabbitmq-erlang-rpm ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable bintraybintray-rabbitmq-erlang-rpm
        or
            subscription-manager repos --disable=bintraybintray-rabbitmq-erlang-rpm

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=bintraybintray-rabbitmq-erlang-rpm.skip_if_unavailable=true

failure: repodata/repomd.xml from bintraybintray-rabbitmq-erlang-rpm: [Errno 256] No more mirrors to try.
https://dl.bintray.com/rabbitmq-erlang/rpm/erlang/21/el/7/repodata/repomd.xml: [Errno 14] HTTPS Error 403 - Forbidden
`

**Comment by MrMEEE** [comment]
Project has been updated and moved...

Please move to the new version and report any issues

PROJECT MOVED: https://github.com/miracle-as/AWX-RPM

Issues at: https://github.com/miracle-as/AWX-RPM/issues

**Install guide, tools, utilities are located at: https://awx.wiki

**LinkedIn group for Questions, support, talk and more: https://www.linkedin.com/groups/13694893/**
