### ISSUE TITLE
No directory for Centos7 on https://rpm.miracle.dk/AWX-RPM

### ISSUE THREAD

**Issue by yassertba** [MrMEEE/awx-build#311]
Hello,

A bit linked to #309 but not quite.

It seems that https://rpm.miracle.dk/AWX-RPM/ is accessible but  the whole directory for Centos7 is missing 

When visiting the URL only the directory for Centos8 is visible.

And this causes the installation to fail for Centos7 OS : 
`failure: repodata/repomd.xml from ansible-awx: [Errno 256] No more mirrors to try.
https://rpm.miracle.dk/AWX-RPM/CentOS_7/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
`

has the support for centos7 been dropped ?

Thanks

**Comment by thomasbrigsted** [comment]
Due to us working on the AWX-rpm turnkey application, this code was unfortunately messed up for a period of time. We are sorry for the incovenience.
Everything should be working fine again now. If now, please let us know.

**Comment by yassertba** [comment]
Hello @thomasbrigsted ,
The centos7 repo seems to be available again 

Thanks
