### ISSUE TITLE
The CentOS_7 repo has x86_64, noarch, and source all in the same repodata

### ISSUE THREAD

**Issue by nkadel** [MrMEEE/awx-build#312]
It's not typical to publish both binary and source RPM's in the same yum repo. It's normally to publish one per architecture and a distinct one for source. This also improves the speed of yum queries and yum downloads, which do not normally need metadata of source packages, and the .repo file would refer to one repo for the binaries of the particular repo, and one for the source.

**Comment by MrMEEE** [comment]
Project has been updated and moved...

Please move to the new version and report any issues

PROJECT MOVED: https://github.com/miracle-as/AWX-RPM

Issues at: https://github.com/miracle-as/AWX-RPM/issues

**Install guide, tools, utilities are located at: https://awx.wiki

**LinkedIn group for Questions, support, talk and more: https://www.linkedin.com/groups/13694893/**

**Comment by nkadel** [comment]
Why the move? And is there any code for the new repo?

**Comment by MrMEEE** [comment]
**https://awx.wiki/blog/new-build-server-new-installer-new-maintainers-same-project**
