### ISSUE TITLE
 .spec files from SRPMs use "python3-" rather than "python%{python3_pkgversion}"

### ISSUE THREAD

**Issue by nkadel** [MrMEEE/awx-build#313]
The .spec files, which are apparently autogenerated from the pypi.org published modules by a script, consistently use the "python3-" prefix rather than "python%{python3_pkgversion}-" prefix. The result is that the packages may be based on python 3.6, but operating systems such as Amazon Linux which use python 3.7 for "python3" instead, become vary, very confused. Please use the python3_pkgversion syntax for packaging clarity, and for consistency with EPEL published package names.

**Comment by MrMEEE** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  Hi NicoThanks for all of the feedback..All of the package/spec generation has been completely redone, so when the new releases of AWX-RPM drops (hopefully very soon) all of this should be fixed..

**Comment by nkadel** [comment]
No problem: I started chewing my way through the .spec files to try the revisions I'm suggesting. Is there any way I can talk you or your .spec file generating tool into listing, as the first line, what tool and its command line arguments are, much as pyp2rpm does?

**Comment by MrMEEE** [comment]
Project has been updated and moved...

Please move to the new version and report any issues

PROJECT MOVED: https://github.com/miracle-as/AWX-RPM

Issues at: https://github.com/miracle-as/AWX-RPM/issues

**Install guide, tools, utilities are located at: https://awx.wiki

**LinkedIn group for Questions, support, talk and more: https://www.linkedin.com/groups/13694893/**
