### ISSUE TITLE
Stop setting "%release" twice

### ISSUE THREAD

**Issue by nkadel** [MrMEEE/awx-build#314]
The '%define release 1" in the .spec files of the SRPMs is overridden the "Release: 1.11.2" or whatever other value is set further down the .spec file. Either use the %{release} value much as the %{name} value is set, or discard the first '%define release 1' statement in these .spec files. It's almost immediately overridden and therefore confusing.

**Comment by MrMEEE** [comment]
Project has been updated and moved...

Please move to the new version and report any issues

PROJECT MOVED: https://github.com/miracle-as/AWX-RPM

Issues at: https://github.com/miracle-as/AWX-RPM/issues

**Install guide, tools, utilities are located at: https://awx.wiki

**LinkedIn group for Questions, support, talk and more: https://www.linkedin.com/groups/13694893/**
