### ISSUE TITLE
Name .spec files consistently

### ISSUE THREAD

**Issue by nkadel** [MrMEEE/awx-build#315]
.spec files named things like 'chardet.spec' which generate an SRPM called "python3-chardet-%{version}-%{release}.src.rpm" are confusing. Please name the .spec files to match the SRPMs.

EPEL normally names them things like "python-chardet.spec", but also builds both python2 and python3 modules from them. python3-chardet.spec and the like to limit the build process to python3 is reasonable, but can we be consistent about these names?

**Comment by MrMEEE** [comment]
Project has been updated and moved...

Please move to the new version and report any issues

PROJECT MOVED: https://github.com/miracle-as/AWX-RPM

Issues at: https://github.com/miracle-as/AWX-RPM/issues

**Install guide, tools, utilities are located at: https://awx.wiki

**LinkedIn group for Questions, support, talk and more: https://www.linkedin.com/groups/13694893/**
