### ISSUE TITLE
.spec files lack %license and %doc files, and lack '%check' or documenting stanzas

### ISSUE THREAD

**Issue by nkadel** [MrMEEE/awx-build#316]
EPEL .spec files and pyp2rpm generated .spec files have '%check' stanzas, and typically use sphinx to generate documentation for a "-doc" package. I realize that resolving the sphinx dependencies can be a nightmare, especially when more than 100 packages each have their own subtle documentation formats and the same sphinx release will not be possible to use for all of them. But tools like pyp2rpm at least take a shot at configuring this. It can be disabled for packages that it just fails with, but it might be much easier to get many of these modules accepted for RHEL or EPEL if they have these features.

Is there are a reference repo or repos now for the .spec files? I could set one up, I've done it before, but I'd much rather work from a clone of your repo than start over with all the recent changes.

**Comment by MrMEEE** [comment]
Project has been updated and moved...

Please move to the new version and report any issues

PROJECT MOVED: https://github.com/miracle-as/AWX-RPM

Issues at: https://github.com/miracle-as/AWX-RPM/issues

**Install guide, tools, utilities are located at: https://awx.wiki

**LinkedIn group for Questions, support, talk and more: https://www.linkedin.com/groups/13694893/**
