### ISSUE TITLE
Add '%{?dist}' to "Release:" line on all .spec files

### ISSUE THREAD

**Issue by nkadel** [MrMEEE/awx-build#317]
Most contemporary RHEL and CentOS .spec files have '%{?dist}' in the Release: line, to distinguish among the releases for which the RPM was built.

**Comment by MrMEEE** [comment]
Project has been updated and moved...

Please move to the new version and report any issues

PROJECT MOVED: https://github.com/miracle-as/AWX-RPM

Issues at: https://github.com/miracle-as/AWX-RPM/issues

**Install guide, tools, utilities are located at: https://awx.wiki

**LinkedIn group for Questions, support, talk and more: https://www.linkedin.com/groups/13694893/**
