### ISSUE TITLE
AWX Installation on RHEL 8.X

### ISSUE THREAD

**Issue by apoorvp2** [MrMEEE/awx-build#318]
Hi ,

Need a confirmation regarding an issue related to AWX installation via RPM. Is it supported on RHEL 8.x series OS platform if installation is carried out with the current setup file available at below location :-

/root/awx-setup https://raw.githubusercontent.com/MrMEEE/awx-rpm/master/awx-setup

Please help specify the possible versions in RHEL 8.X series that can support rpm based AWX installation

Regards,
Apoorv

**Comment by MrMEEE** [comment]
Project has been updated and moved...

Please move to the new version and report any issues

PROJECT MOVED: https://github.com/miracle-as/AWX-RPM

Issues at: https://github.com/miracle-as/AWX-RPM/issues

**Install guide, tools, utilities are located at: https://awx.wiki

**LinkedIn group for Questions, support, talk and more: https://www.linkedin.com/groups/13694893/**
