### ISSUE TITLE
Status of awx-rpm project ?

### ISSUE THREAD

**Issue by tjyang** [MrMEEE/awx-build#319]
Hi @MrMEEE 

Please update the status of this project.

I see  it is close yet looks like stale since 08/06/2021.
![image](https://user-images.githubusercontent.com/378638/137720312-959f0db9-de77-476c-a465-51bad4de246f.png)

**Comment by MrMEEE** [comment]
Project has been updated and moved...

Please move to the new version and report any issues

PROJECT MOVED: https://github.com/miracle-as/AWX-RPM

Issues at: https://github.com/miracle-as/AWX-RPM/issues

**Install guide, tools, utilities are located at: https://awx.wiki

**LinkedIn group for Questions, support, talk and more: https://www.linkedin.com/groups/13694893/**
