### ISSUE TITLE
Repo not working 

### ISSUE THREAD

**Issue by javierdobles** [MrMEEE/awx-build#320]
I installed AWX the last Friday and it was working, for tracking purposes I tried to remove everything and install it again today but now I'm having repo issues:

Https://rpm.miracle.dk/AWX-RPM/CentOS_7/repodata/repomd.xml with status code 404

**Comment by javierdobles** [comment]
Let me know which other details you want me to provide and thanks before hand @MrMEEE

**Comment by MrMEEE** [comment]
Hi

We are just about to release a new, updated and improved version (hopefully within days).. The old repo is available at 

Https://rpm.miracle.dk/AWX-RPM-OLD/CentOS_7/

If you need it..

Regards

**Comment by javierdobles** [comment]
Thank you! You're a life saver, I'll be pending checking the repos
