### ISSUE TITLE
Unable to update projects in AWX-RPM

### ISSUE THREAD

**Issue by javierdobles** [MrMEEE/awx-build#321]
Hi,
I was able to install AWX-RPM, however I'm facing some issues with the project update, when I click the refresh, is just throwing an error:
`traceback(most recent call last):
File "/bin/ansible-playbook", line 34, in <module>
  From ansible import context
File "/usr/lib/python2.7/sites-packages/ansible/__init__.py", line 25, in <module>
  From jinja2.filters import pass_context as _passctx, pass_environment as _passenv, pass_eval_context as _passevalctx
File "/var/lib/awx/venv/ansible/lib/python3.6/sites-packages/jinga2/__init__.py", line 5, in <module>
  From .bccache import ByteCodeCache as BytecodeCache
File "/var/lib/awx/venv/ansible/lib/python3.6/sites-packages/jinja2/bccache.py", line 26
  def get(self, key:str) -> bytes
                      ^
syntaxerror: Invalid syntax`

I'm using centos7 and I ran everything with the awx-setup script, I'm also using an external database.

Seems like a redis issue but not quite sure

Any help will be appreciate it.

Regards!.

**Comment by MrMEEE** [comment]
Project has been updated and moved...

Please move to the new version and report any issues

PROJECT MOVED: https://github.com/miracle-as/AWX-RPM

Issues at: https://github.com/miracle-as/AWX-RPM/issues

**Install guide, tools, utilities are located at: https://awx.wiki

**LinkedIn group for Questions, support, talk and more: https://www.linkedin.com/groups/13694893/**
