### ISSUE TITLE
Missing symlink for requirements.yaml

### ISSUE THREAD

**Issue by powertim** [MrMEEE/awx-build#36]
Hi,

I used Ansible Galaxy to create my playbook tree for the role I use requirements.yaml and I found an issue affecting the command.
We need to add the symlink : /opt/awx/bin/ansible-galaxy -> /opt/awx/bin/ansible-galaxy/ansible.
Thanks for updating the package.

Best regards,

Tim.

**Comment by MrMEEE** [comment]
Thanks...

I have made the change to the build spec.. Should be included in the next build...

**Comment by powertim** [comment]
Thanks to you !

**Comment by MrMEEE** [comment]
Hi

/opt/awx/bin/ansible-galaxy/ansible isn't present on my system? did you add this yourself?

**Comment by powertim** [comment]
Hi,
Sorry for the HUGE delay...
It was installed with the ansible RPM.
Only did a `sudo yum install ansible` on RHEL7.

**Comment by MrMEEE** [comment]
Hi

Can you please do a:

rpm -aq ansible
and
rpm -ql ansible

Thanks

**Comment by powertim** [comment]
Hi,

Sorry I forgot to reply.

`$ rpm -aq ansible`
`ansible-2.6.5-1.el7.noarch`

`$ rpm -ql ansible`
[rpm-qlansible.txt](https://github.com/MrMEEE/awx-build/files/2495118/rpm-qlansible.txt)

Best,

Tim.

**Comment by MrMEEE** [comment]
hi.. 

I think this is fixed in AWX-RPM 3.0.0..
