### ISSUE TITLE
Upgrade ansible version

### ISSUE THREAD

**Issue by ghost** [MrMEEE/awx-build#39]
Hi, I understand we can't use external ansible, but only ansible in rpm file.
Why continue to use old ansible's version? In spec file I see ansible 2.5.0 while now we have 2.6.3.
I tried to build my rpm with ansible 2.6.3 and work without issues.
Is there a possibility to have a rpm with new version of ansible or use an external ansible, maybe as dependency of rpm?
Thank you

**Comment by MrMEEE** [comment]
Pushed Ansible to 2.6.3 for the next build.. 

It's possible to run with external versions of ansible from within AWX.. (Ansible Environments)

**Comment by ghost** [comment]
Sorry for my newbie question. Where I can change this setting?

**Comment by MrMEEE** [comment]
Good question.. maybe the feature is only in Ansible Tower?.. can't remember where I have seen it..
