### ISSUE TITLE
Need guide to convert awx source code to .rpm

### ISSUE THREAD

**Issue by bangnh1** [MrMEEE/awx-build#4]
Hi,
Thanks for your repo, I was able to follow the install doc (https://github.com/MrMEEE/awx-build/blob/master/installguide) to the end and it worked perfectly.
I want to build .rpm file for myself. I did not understand your awx-build.spec file.
Can you share a guide or your awx-1.0.x.x.tar.gz file?

**Comment by MrMEEE** [comment]
Hi

The awx-1.x.x.x.x.tar.gz is build from the awx source.. 

Please look at my build-script "update-build.sh" in the build-scripts folder for inspiration :)

**Comment by bangnh1** [comment]
Where can i find buid.sh file? So I don't know what is in the link "/home/build/awx-rpm-build/awx"

![1](https://user-images.githubusercontent.com/29230374/36723577-43244d30-1be3-11e8-8e3a-47618f71694e.PNG)

**Comment by MrMEEE** [comment]
https://github.com/subuk/awx-rpm

**Comment by MrMEEE** [comment]
What is the reason why you want to build the rpm's yourself??

**Comment by bangnh1** [comment]
The docker version have few limitations, I wasn't able handle them. I hope AWX can connect to server via socks proxy.

**Comment by MrMEEE** [comment]
Yeah, I know.. but I meant, why can't you just use my RPM's?

**Comment by bangnh1** [comment]
I want to customize some features from the source code. Awx was great but it could still be better

**Comment by bangnh1** [comment]
Finally, I could build rpm for myself. I have built 2 versions from released source code, version 1.0.2 and 1.0.4.
Version 1.0.2: everything goes smoothly, I'm done with several tasks.
Version 1.0.4: Tasks couldn't be done. It's blank.

Did you experience the same issues? Any ideas to solve the issues or catch logs

![capture](https://user-images.githubusercontent.com/29230374/36846421-1ecfe8ee-1d8d-11e8-9c68-55e7cf9b9b8a.jpg)

**Comment by Lobout** [comment]
Can you upgrade your build to awx 1.0.4?

**Comment by MrMEEE** [comment]
Does it work now?

**Comment by bangnh1** [comment]
After many trials, I decided to go back to the docker version. I have built a local image. I think it more stable and easier to solve issues.

**Comment by Lobout** [comment]
I have not had a chance to test yet.  I'll try and get to it soon and let 
you know.
