### ISSUE TITLE
Job does not start (after migrate from 1.0.6.47 > 1.0.7.3)

### ISSUE THREAD

**Issue by pontostroy** [MrMEEE/awx-build#41]
Migration was successful, celery-worker fixed. 

But now after selecting a template, setting limits, and after pressing the next button nothing happens, the job window does not disappear.

Project and inventory updates, ad-hoc commands are successful.

**Comment by MrMEEE** [comment]
try to check if rabbitmq-server is running?

Any errors in the logs?

**Comment by pontostroy** [comment]
rabbitmq-server is running and updated.
I can not find anything that would help me to find an error, fresh install with  tower recieve\send works fine.

**Comment by pontostroy** [comment]
Shift + Ctrl + R (refresh without cache) on chrome solved the problem.

**Comment by MrMEEE** [comment]
Cool.. thanks for the feedback
