### ISSUE TITLE
1.0.7.4: job status urls not working / empty page

### ISSUE THREAD

**Issue by flynn1973** [MrMEEE/awx-build#44]
job status urls (e.g: http://towerhost.some.domain/#/jobs/playbook/13) just showing blank/white page.
rabbitmq and all other services are running.

**Comment by MrMEEE** [comment]
Have you tried force-refreshing (ctrl+alt+r/f5)?

**Comment by flynn1973** [comment]
hmm...was indeed a browser problem (outdated firefox). works with latest.
