### ISSUE TITLE
rhev python module not found

### ISSUE THREAD

**Issue by Aglidic** [MrMEEE/awx-build#45]
Hello i still have some issue with the rhev python module.

Last time to make the inventory sync to work i had to create a python venv in /var/lib/awx (like in tower) and for the sync it works.

But now when i try to use the rhev module in playbook it doesn't work.

For what i understand in your rpm package you are copying python module in /opt/awx/embedded right.

But in the bin folder i can't see the activate ... So i can't add module by myself.

Please in next build can you try to finish the venv ?

regards

**Comment by Aglidic** [comment]
hum nevermind it seems that it's possible to set custom environement per job template now.
i will try to do that

**Comment by MrMEEE** [comment]
Did you get it to work?

**Comment by Aglidic** [comment]
so at the end what we have done is to follow the install of the tower version.

It means we have created 2 venv in /var/lib/awx/venv.

One called awx and the second one called ansible. We install necessary module on the awx venv and we reinstall ansible in the ansible venv plus necessary module.

After that everything is working fine.

Since 1.7 you can also use custom venv if you want specific modul od multiple version of ansible for example.

**Comment by Aglidic** [comment]
So yes everything is working fine.

Just have to play a little with python venv

**Comment by MrMEEE** [comment]
Great.. Thanks for the update :)
