### ISSUE TITLE
1.0.7.4 to 1.0.8.14 upgrade note

### ISSUE THREAD

**Issue by tjyang** [MrMEEE/awx-build#46]
Hi 

Just an FYI, I was able do the upgrade using following commands.
"--merge" was added for this time per error message suggested.

```
yum update -y && \
sudo -u awx /opt/awx/bin/awx-manage makemigrations --merge  && \
sudo -u awx /opt/awx/bin/awx-manage migrate && reboot
```

**Comment by MrMEEE** [comment]
Hi

Thanks for the update..

I actually upgraded earlier today, but didn't get around to petting it into the dokumentation.. But nice to get feedback :) thanks...
