### ISSUE TITLE
About space requirements

### ISSUE THREAD

**Issue by Neurozone** [MrMEEE/awx-build#47]
Hello.
I've a question about the fs and space needed by the installation.

Which are the directories needed by the installation of awx ? (Because we have some predefined partitions on lvm) and what is the size needed for the deployement ?

I haven't seen anything related on your documentation about this.

Florianne

**Comment by mjcasalogic** [comment]
Hi..

AWX is primarily resident in /opt/awx, where it takes up around 500MB...

It's works is done in tmp and /var/lib/awx.. but shouldn't take up much space...

I would say that a server with 10GB of space should be more than enough to start with.. Of course this depends on your playbooks..

Martin

**Comment by MrMEEE** [comment]
Hi..

AWX is primarily resident in /opt/awx, where it takes up around 500MB...

It's works is done in tmp and /var/lib/awx.. but shouldn't take up much space...

I would say that a server with 10GB of space should be more than enough to start with.. Of course this depends on your playbooks..

Martin

**Comment by Neurozone** [comment]
Thank you for the answer, and this brings me to the next issue:
Can we relocate the installation on another fs/partition like /var/product ?

And where is located the database ?
Sorry for all theses questions but it's "enterprise policy", you know...
Florianne

**Comment by MrMEEE** [comment]
No problem..

Database is located in /var/lib/pgsql if you are using CentOS and following the guide.. it's under /opt/rh/ if you are using software collections or the RHEL installations guide..

AWX is packaged in a RPM, so you shouldn't move the installation (could be done, but you won't be able to update, and there will be alot of issues to fix).. you can mount in a file system in /opt or /opt/awx before installing, and that will work just fine...

If you are considering running this in production, you should take a look into Ansible Tower.. it's more enterprise ready..

**Comment by Neurozone** [comment]
> 
> 
> No problem..
> 
> Database is located in /var/lib/pgsql if you are using CentOS and following the guide.. it's under /opt/rh/ if you are using software collections or the RHEL installations guide..
> 
> AWX is packaged in a RPM, so you shouldn't move the installation (could be done, but you won't be able to update, and there will be alot of issues to fix).. you can mount in a file system in /opt or /opt/awx before installing, and that will work just fine...
> 
> If you are considering running this in production, you should take a look into Ansible Tower.. it's more enterprise ready..

Budget costs ? ^^

Thank you for you replies.
At least we will give a try to your installation :)

Florianne

**Comment by MrMEEE** [comment]
Well, if money is an issue, then go ahead :)..

Let me hear how it goes..

**Comment by powertim** [comment]
Hi Florianne,

Same issue with budget !
It's possible to build an HA setup for AWX if you need it.

@MrMEEE btw I was able to do all upgrade paths mentioned on page https://github.com/MrMEEE/awx-build/blob/master/installguide.md from 1.0.7.4 to 2.0.0 and configuration for HA setup is still the same as found in #35 :
`ExecStart=/opt/awx/bin/celery worker -A awx -l debug --autoscale=50,4 -Ofair -n celery@%H`
Do you think it would be possible ton implement some installation options like HA setup and files location ?
If I can help just let me know, I still appreciate all the work you did on this RPM version !

**Comment by Neurozone** [comment]
> 
> 
> Hi Florianne,
> 
> Same issue with budget !
> It's possible to build an HA setup for AWX if you need it.
> 
> @MrMEEE btw I was able to do all upgrade paths mentioned on page https://github.com/MrMEEE/awx-build/blob/master/installguide.md from 1.0.7.4 to 2.0.0 and configuration for HA setup is still the same as found in #35 :
> `ExecStart=/opt/awx/bin/celery worker -A awx -l debug --autoscale=50,4 -Ofair -n celery@%H`
> Do you think it would be possible ton implement some installation options like HA setup and files location ?
> If I can help just let me know, I still appreciate all the work you did on this RPM version !

We don't need HA setup, we works with vmware and have some VM who can switch from  a DC to another ^^

And yes ! Thank you for the work @MrMEEE

**Comment by powertim** [comment]
@FlorianneRaven FYI It's more about load balancing than HA but do as your convenient. Just added this message to inform you that it's possible in replacement of Tower.
