### ISSUE TITLE
Missing rpm dependencies

### ISSUE THREAD

**Issue by ghost** [MrMEEE/awx-build#49]
I'm writing a playbook which use lookup dig and module mssql_db and I discovered that I have missing rpm on my system: python2-pymssql.x86_64 and python-dns.noarch already distribuited in repo's base from Centos/Redhat. 
It might be useful add a require in spec's file. Maybe python2-pymssql.x86_64 is not very used, but python-dns.noarch is useful.

**Comment by MrMEEE** [comment]
Thanks for the feedback.. I will consider this
