### ISSUE TITLE
Ansible Version Question

### ISSUE THREAD

**Issue by bamason14** [MrMEEE/awx-build#54]
It appears in AWX version 2.0.1 the Ansible version is set to 2.7.0 where in 2.1.0, Ansible version is 2.6.6. Is there a reason why it's been downgraded?

**Comment by MrMEEE** [comment]
Hi..

I saw some issues with the mailing module.. so I rolled back.. 

If you want/need 2.7.0 you can just add a virtualenv with the 2.7.0 version.. (https://github.com/MrMEEE/awx-build/issues/48)

I will probably bump it to 2.7.1 as soon as I have had the time to verify that the issue has been fixed..

**Comment by bamason14** [comment]
Awesome. I do need version 2.7 for some of the newer modules. Thank you for the explanation.
