### ISSUE TITLE
Not Able to Run the template

### ISSUE THREAD

**Issue by jijendiranR** [MrMEEE/awx-build#55]
![screenshot 114](https://user-images.githubusercontent.com/32735542/48351417-36a1b500-e6b0-11e8-9908-387cf63904a9.png)

Not able to execute jobs
It is in the paused state not able to run any job and moreover no error in the web-log. Suggest solutions to fix this.

**Comment by MrMEEE** [comment]
Hi

I usually see this when:

1. RabbitMQ is not running
2. awx-dispatcher is not running

Have it worked before? is this after an upgrade??

**Comment by jijendiranR** [comment]
> Hi
> 
> I usually see this when:
> 
> 1. RabbitMQ is not running
> 2. awx-dispatcher is not running
> 
> Have it worked before? is this after an upgrade??

My awx-dispatcher is not started later I updated my AWX now it's working fine. Thank's for helping to fix it soon.
![screenshot 115](https://user-images.githubusercontent.com/32735542/48396539-cabb5d00-e740-11e8-9cf4-b50c9498ad74.png)
