### ISSUE TITLE
Unable to update project from Github

### ISSUE THREAD

**Issue by vosetrov-mdlive** [MrMEEE/awx-build#57]
awx Version     : 2.1.0.151
os: CentOS Linux release 7.5.1804
Python 2.7.5
Firewall and selinux are disabled
I can manually run git clone from the instance with the same credentials and it works.
I'm getting the error:
ssh_exchange_identification: Connection closed by remote host fatal: Could not read from remote repository. Please make sure you have the correct access rights and the repository exists.
When I started to troubleshoot the issue I figured out AWX even doesn't try to hit github servers during the project sync
``
[root@mdlprodv2awx01 ~]#  tcpdump -i any not host 192.168.2.92 and port 22 or port 9418
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on any, link-type LINUX_SLL (Linux cooked), capture size 262144 bytes
^C
0 packets captured
0 packets received by filter
``

I noticed that Job Type is Check for the job
Here is the logs:
``
Nov 15 17:45:24 mdlprodv2awx01 awx-manage: 2018-11-15 17:45:24,264 DEBUG    awx.main.dispatch delivered c800afd7-7ac7-4070-a1f8-f62da116d096 to worker[1691] qsize 0
Nov 15 17:45:24 mdlprodv2awx01 awx-manage: 2018-11-15 17:45:24,265 DEBUG    awx.main.dispatch task c800afd7-7ac7-4070-a1f8-f62da116d096 starting awx.main.scheduler.tasks.run_task_manager(*[])
Nov 15 17:45:24 mdlprodv2awx01 awx-manage: 2018-11-15 17:45:24,267 DEBUG    awx.main.scheduler Running Tower task manager.
Nov 15 17:45:24 mdlprodv2awx01 awx-manage: 2018-11-15 17:45:24,277 DEBUG    awx.main.scheduler Starting Scheduler
Nov 15 17:45:24 mdlprodv2awx01 awx-manage: 2018-11-15 17:45:24,324 DEBUG    awx.main.scheduler Starting project_update 83 (pending) in group tower instance mdlprodv2awx01.mdlive.prod (remaining_capacity=48)
Nov 15 17:45:24 mdlprodv2awx01 awx-manage: 2018-11-15 17:45:24,328 INFO     awx.main.scheduler Submitting project_update 83 (waiting) to <instance group, instance> <1,mdlprodv2awx01.mdlive.prod>.
Nov 15 17:45:24 mdlprodv2awx01 awx-manage: 2018-11-15 17:45:24,359 DEBUG    awx.main.scheduler project_update 83 (waiting) consumed 1 capacity units from tower with prior total of 0
Nov 15 17:45:24 mdlprodv2awx01 awx-manage: 2018-11-15 17:45:24,369 DEBUG    awx.main.dispatch publish awx.main.tasks.RunProjectUpdate(d05fdd17-c444-4720-a5ff-a7e1988b8c9c, queue=mdlprodv2awx01.mdlive.prod)
Nov 15 17:45:24 mdlprodv2awx01 awx-manage: 2018-11-15 17:45:24,382 DEBUG    awx.main.dispatch delivered d05fdd17-c444-4720-a5ff-a7e1988b8c9c to worker[1690] qsize 0
Nov 15 17:45:24 mdlprodv2awx01 awx-manage: 2018-11-15 17:45:24,384 DEBUG    awx.main.dispatch task d05fdd17-c444-4720-a5ff-a7e1988b8c9c starting awx.main.tasks.RunProjectUpdate(*[83])
Nov 15 17:45:24 mdlprodv2awx01 awx-manage: 2018-11-15 17:45:24,386 DEBUG    awx.main.dispatch task c800afd7-7ac7-4070-a1f8-f62da116d096 is finished
Nov 15 17:45:25 mdlprodv2awx01 awx-manage: 2018-11-15 17:45:25,448 DEBUG    awx.main.dispatch delivered c0b1a4e5-705e-4d49-a484-c1dc5347a549 to worker[1686] qsize 0
Nov 15 17:45:25 mdlprodv2awx01 awx-manage: 2018-11-15 17:45:25,452 DEBUG    awx.main.dispatch delivered a094dcb6-c511-4894-bacf-103fe7c96b5a to worker[1687] qsize 0
Nov 15 17:45:25 mdlprodv2awx01 awx-manage: 2018-11-15 17:45:25,457 DEBUG    awx.main.dispatch delivered a5443765-05df-48fe-a283-0aea9f354349 to worker[1687] qsize 1
Nov 15 17:45:25 mdlprodv2awx01 awx-manage: 2018-11-15 17:45:25,480 DEBUG    awx.main.dispatch delivered 000d3a00-83ea-a98b-c45c-000000000006 to worker[1688] qsize 0
Nov 15 17:45:25 mdlprodv2awx01 awx-manage: 2018-11-15 17:45:25,490 DEBUG    awx.main.dispatch delivered 000d3a00-83ea-a98b-c45c-000000000008 to worker[1686] qsize 0
Nov 15 17:45:25 mdlprodv2awx01 awx-manage: 2018-11-15 17:45:25,520 DEBUG    awx.main.dispatch delivered 37bcfd04-7b5e-4081-bc10-4b06170c8014 to worker[1686] qsize 1
Nov 15 17:45:25 mdlprodv2awx01 awx-manage: 2018-11-15 17:45:25,523 DEBUG    awx.main.dispatch task c0b1a4e5-705e-4d49-a484-c1dc5347a549 is finished
Nov 15 17:45:25 mdlprodv2awx01 awx-manage: 2018-11-15 17:45:25,523 DEBUG    awx.main.dispatch task 000d3a00-83ea-a98b-c45c-000000000006 is finished
Nov 15 17:45:25 mdlprodv2awx01 awx-manage: 2018-11-15 17:45:25,524 DEBUG    awx.main.dispatch task a094dcb6-c511-4894-bacf-103fe7c96b5a is finished
Nov 15 17:45:25 mdlprodv2awx01 awx-manage: 2018-11-15 17:45:25,534 DEBUG    awx.main.dispatch delivered 000d3a00-83ea-a98b-c45c-00000000000a to worker[1688] qsize 0
Nov 15 17:45:25 mdlprodv2awx01 awx-manage: 2018-11-15 17:45:25,542 DEBUG    awx.main.dispatch task 000d3a00-83ea-a98b-c45c-000000000008 is finished
Nov 15 17:45:25 mdlprodv2awx01 awx-manage: 2018-11-15 17:45:25,552 DEBUG    awx.main.dispatch task a5443765-05df-48fe-a283-0aea9f354349 is finished
Nov 15 17:45:25 mdlprodv2awx01 awx-manage: 2018-11-15 17:45:25,559 DEBUG    awx.main.dispatch delivered a3c10ecb-4954-4f2d-a038-311299aa30ac to worker[1686] qsize 0
Nov 15 17:45:25 mdlprodv2awx01 awx-manage: 2018-11-15 17:45:25,576 DEBUG    awx.main.dispatch task 000d3a00-83ea-a98b-c45c-00000000000a is finished
Nov 15 17:45:25 mdlprodv2awx01 awx-manage: 2018-11-15 17:45:25,576 DEBUG    awx.main.dispatch delivered 000d3a00-83ea-a98b-c45c-00000000000c to worker[1686] qsize 1
Nov 15 17:45:25 mdlprodv2awx01 awx-manage: 2018-11-15 17:45:25,585 DEBUG    awx.main.dispatch task 37bcfd04-7b5e-4081-bc10-4b06170c8014 is finished
Nov 15 17:45:25 mdlprodv2awx01 awx-manage: 2018-11-15 17:45:25,625 DEBUG    awx.main.dispatch task a3c10ecb-4954-4f2d-a038-311299aa30ac is finished
Nov 15 17:45:25 mdlprodv2awx01 awx-manage: 2018-11-15 17:45:25,641 DEBUG    awx.main.dispatch task 000d3a00-83ea-a98b-c45c-00000000000c is finished
Nov 15 17:45:25 mdlprodv2awx01 python: ansible-git Invoked with depth=None executable=None force=False track_submodules=False reference=None dest=/var/lib/awx/projects/_11__github recursive=True clone=True accept_hostkey=True update=True ssh_opts=None repo= umask=None version=HEAD bare=False verify_commit=False remote=origin key_file=None archive=None refspec=None
Nov 15 17:45:25 mdlprodv2awx01 awx-manage: 2018-11-15 17:45:25,939 DEBUG    awx.main.dispatch delivered d83b1f1b-94f1-4e79-9a42-de8d64616a87 to worker[1689] qsize 0
Nov 15 17:45:25 mdlprodv2awx01 awx-manage: 2018-11-15 17:45:25,948 DEBUG    awx.main.dispatch delivered 30e14ab6-c3fb-445e-b43b-0e8e63fbab74 to worker[1686] qsize 0
Nov 15 17:45:25 mdlprodv2awx01 awx-manage: 2018-11-15 17:45:25,964 DEBUG    awx.main.dispatch task d83b1f1b-94f1-4e79-9a42-de8d64616a87 is finished
Nov 15 17:45:25 mdlprodv2awx01 awx-manage: 2018-11-15 17:45:25,989 DEBUG    awx.main.dispatch task 30e14ab6-c3fb-445e-b43b-0e8e63fbab74 is finished
Nov 15 17:45:26 mdlprodv2awx01 awx-manage: 2018-11-15 17:45:26,085 INFO     awx.main.tasks project_update 83 (running) finished running, producing 11 events.
Nov 15 17:45:26 mdlprodv2awx01 awx-manage: 2018-11-15 17:45:26,085 DEBUG    awx.main.dispatch delivered d58e7166-880a-499f-8fcf-54e80457ffab to worker[1689] qsize 0
Nov 15 17:45:26 mdlprodv2awx01 awx-manage: 2018-11-15 17:45:26,087 INFO     awx.main.commands.run_callback_receiver Event processing is finished for Job 83, sending notifications
Nov 15 17:45:26 mdlprodv2awx01 awx-manage: 2018-11-15 17:45:26,087 INFO     awx.main.commands.run_callback_receiver Event processing is finished for Job 83, sending notifications
Nov 15 17:45:26 mdlprodv2awx01 awx-manage: 2018-11-15 17:45:26,152 WARNING  awx.main.dispatch project_update 83 (failed) encountered an error (rc=2), please see task stdout for details.
Nov 15 17:45:26 mdlprodv2awx01 awx-manage: 2018-11-15 17:45:26,154 DEBUG    awx.main.dispatch task d05fdd17-c444-4720-a5ff-a7e1988b8c9c starting awx.main.tasks.handle_work_error(*[u'd05fdd17-c444-4720-a5ff-a7e1988b8c9c'])
Nov 15 17:45:26 mdlprodv2awx01 awx-manage: 2018-11-15 17:45:26,154 DEBUG    awx.main.tasks Executing error task id d05fdd17-c444-4720-a5ff-a7e1988b8c9c, subtasks: [{u'type': u'project_update', u'id': 83}]
Nov 15 17:45:26 mdlprodv2awx01 awx-manage: 2018-11-15 17:45:26,161 DEBUG    awx.main.dispatch publish awx.main.scheduler.tasks.run_task_manager(9fe899b1-4901-4129-9561-207f1e9d6100, queue=awx_private_queue)
Nov 15 17:45:26 mdlprodv2awx01 awx-manage: 2018-11-15 17:45:26,173 DEBUG    awx.main.dispatch delivered 9fe899b1-4901-4129-9561-207f1e9d6100 to worker[1693] qsize 0
Nov 15 17:45:26 mdlprodv2awx01 awx-manage: 2018-11-15 17:45:26,174 DEBUG    awx.main.dispatch task d05fdd17-c444-4720-a5ff-a7e1988b8c9c starting awx.main.tasks.handle_work_success(*[])
Nov 15 17:45:26 mdlprodv2awx01 awx-manage: 2018-11-15 17:45:26,177 DEBUG    awx.main.dispatch task 9fe899b1-4901-4129-9561-207f1e9d6100 starting awx.main.scheduler.tasks.run_task_manager(*[])
Nov 15 17:45:26 mdlprodv2awx01 awx-manage: 2018-11-15 17:45:26,183 DEBUG    awx.main.scheduler Running Tower task manager.
Nov 15 17:45:26 mdlprodv2awx01 awx-manage: 2018-11-15 17:45:26,183 DEBUG    awx.main.dispatch publish awx.main.scheduler.tasks.run_task_manager(366f23f0-c91f-4afa-85ca-e527ff73ad80, queue=awx_private_queue)
Nov 15 17:45:26 mdlprodv2awx01 awx-manage: 2018-11-15 17:45:26,197 DEBUG    awx.main.scheduler Starting Scheduler
Nov 15 17:45:26 mdlprodv2awx01 awx-manage: 2018-11-15 17:45:26,198 DEBUG    awx.main.dispatch delivered 366f23f0-c91f-4afa-85ca-e527ff73ad80 to worker[1691] qsize 0
Nov 15 17:45:26 mdlprodv2awx01 awx-manage: 2018-11-15 17:45:26,200 DEBUG    awx.main.dispatch task d05fdd17-c444-4720-a5ff-a7e1988b8c9c is finished
Nov 15 17:45:26 mdlprodv2awx01 awx-manage: 2018-11-15 17:45:26,200 DEBUG    awx.main.dispatch task 366f23f0-c91f-4afa-85ca-e527ff73ad80 starting awx.main.scheduler.tasks.run_task_manager(*[])
Nov 15 17:45:26 mdlprodv2awx01 awx-manage: 2018-11-15 17:45:26,204 DEBUG    awx.main.scheduler Running Tower task manager.
Nov 15 17:45:26 mdlprodv2awx01 awx-manage: 2018-11-15 17:45:26,205 DEBUG    awx.main.dispatch publish awx.main.scheduler.tasks.run_task_manager(6029d802-e105-406b-b968-f6a6437626f3, queue=awx_private_queue)
Nov 15 17:45:26 mdlprodv2awx01 awx-manage: [2018-11-15 17:45:26,205: DEBUG/Process-1] publish awx.main.scheduler.tasks.run_task_manager(6029d802-e105-406b-b968-f6a6437626f3, queue=awx_private_queue)
Nov 15 17:45:26 mdlprodv2awx01 awx-manage: 2018-11-15 17:45:26,218 DEBUG    awx.main.scheduler Not running scheduler, another task holds lock
Nov 15 17:45:26 mdlprodv2awx01 awx-manage: 2018-11-15 17:45:26,221 DEBUG    awx.main.dispatch task 366f23f0-c91f-4afa-85ca-e527ff73ad80 is finished
Nov 15 17:45:26 mdlprodv2awx01 awx-manage: 2018-11-15 17:45:26,228 DEBUG    awx.main.dispatch task 9fe899b1-4901-4129-9561-207f1e9d6100 is finished
Nov 15 17:45:26 mdlprodv2awx01 awx-manage: 2018-11-15 17:45:26,229 DEBUG    awx.main.dispatch delivered 6029d802-e105-406b-b968-f6a6437626f3 to worker[1690] qsize 0
Nov 15 17:45:26 mdlprodv2awx01 awx-manage: 2018-11-15 17:45:26,231 DEBUG    awx.main.dispatch task 6029d802-e105-406b-b968-f6a6437626f3 starting awx.main.scheduler.tasks.run_task_manager(*[])
Nov 15 17:45:26 mdlprodv2awx01 awx-manage: 2018-11-15 17:45:26,232 DEBUG    awx.main.scheduler Running Tower task manager.
Nov 15 17:45:26 mdlprodv2awx01 awx-manage: 2018-11-15 17:45:26,253 DEBUG    awx.main.scheduler Starting Scheduler
Nov 15 17:45:26 mdlprodv2awx01 awx-manage: 2018-11-15 17:45:26,270 DEBUG    awx.main.dispatch task 6029d802-e105-406b-b968-f6a6437626f3 is finished
Nov 15 17:45:27 mdlprodv2awx01 awx-manage: 2018-11-15 17:45:27,110 DEBUG    awx.main.dispatch task d58e7166-880a-499f-8fcf-54e80457ffab is finished
``

**Comment by MrMEEE** [comment]
Hi

Which version are you running??

rpm -qa awx

**Comment by vosetrov-mdlive** [comment]
I added the awx version at the first line of my message
[root@mdlprodv2awx01 ~]# rpm -qa awx
awx-2.1.0.151-1.el7.x86_64
Actually, the problem not only in github update. I added a template and run it and I don't see any traffic on the network interface, in other words looks like ansible playbooks are not trying to reach out destination IPs

**Comment by vosetrov-mdlive** [comment]
I was able to reproduce the issue on a pure clean installation and awx version 2.1.0.0. I created a project and tried to sync it, the same error and no outgoing traffic on the network interface to the git source IP.

**Comment by MrMEEE** [comment]
Have just installed a fresh new awx-2.1.0.241-1.el7.x86_64 here.. following the install guide step by step.. and it works..

Any custom steps?

Seems like you are two, that have the same issue: https://github.com/MrMEEE/awx-build/issues/56

**Comment by vosetrov-mdlive** [comment]
I followed the installation guide and didn't do any custom steps. I noticed that inventory scripts work, but not ansible playbooks.

**Comment by MrMEEE** [comment]
Have you added custom venvs??

**Comment by sturgeonson** [comment]
No, everything is by default. (I'm writing from the second github account)

**Comment by MrMEEE** [comment]
Did you get this to work?

**Comment by sturgeonson** [comment]
I rebuilt the server and chose stable repo. Now it works on 
Version     : 2.1.0.0

**Comment by vosetrov-mdlive** [comment]
I think I found the issue. When I configure a project to use github via ssh (git@github.com:xxxxxxxx/ansible.git) I see:
 /bin/git clone --origin origin '' /var/lib/awx/projects/_8__github
It means the github url is not passing for some reason.
If I change the url to https ( https://github.com/xxxxxxxxxxx/ansible.git):
I see in output:
/bin/git clone --origin origin https://github.com/xxxxxxxxxxxxx/ansible.git /var/lib/awx/projects/_8__github

**Comment by MrMEEE** [comment]
ahh... that makes sense .. maybe report this upstream, and they might fix it in the future :)
