### ISSUE TITLE
Latest build of awx

### ISSUE THREAD

**Issue by Lobout** [MrMEEE/awx-build#6]
Do you plan on updating this to the latest build of awx (1.0.4) and ansible(2.4.3)?

**Comment by MrMEEE** [comment]
Should already be in the dev repo?..

**Comment by Lobout** [comment]
ok.  i went with the stable repo, assumed 1.0.4 would be part of that.

**Comment by MrMEEE** [comment]
It will be, just haven't had the time.. The dev repo is automatically updated
 Sendt fra min BlackBerry - den sikreste mobilenhed Fra: notifications@github.com Sendt: 5. marts 2018 10.14 PM Til: awx-build@noreply.github.com Svar til: reply@reply.github.com Cc: mj@casalogic.dk; comment@noreply.github.com Emne: Re: [MrMEEE/awx-build] Latest build of awx (#6)
ok.  i went with the stable repo, assumed 1.0.4 would be part of that.

**Comment by Lobout** [comment]
ok just installed based off the dev repo, awx build shows 1.0.4.46, but ansible version still reflects 2.3.1.0, and I am not able to get passed the login screen(pulled this information from the api/v1/config page)

**Comment by MrMEEE** [comment]
Ok.. 1.0.4.48 should have ansible 2.4.3.. 

I have the same issue, can't get passed the login screen.. don't know what causes this yet... 

I have tried creating a ticket at awx, but they closed it... https://github.com/ansible/awx/issues/1423

Will try IRC...

**Comment by sunilsankar** [comment]
Hi can you please check whether this is because this variable

https://github.com/ansible/awx/commit/0e9a8d559255761e5e902634374cee7b75c1dca8

CELERY_BROKER_URL to BROKER_URL

**Comment by Lobout** [comment]
sunil-  tried making those changes and couldn't get the build to install, so there is something a bit more, but that seems to be on the right track.

**Comment by MrMEEE** [comment]
I think the login issues are related to my build process (not doing a clean, so old deps are left behind)..

Builds 1.0.4.49 and 50 should have this fixed, but I haven't had the time to test.. Will do this later..

**Comment by MrMEEE** [comment]
Ok.. just updated to 1.0.4.52..

Now login is working again :)..

Websockets are not :(... looking into it

**Comment by sunilsankar** [comment]
cool, I will also have a look into the code.

**Comment by MrMEEE** [comment]
Daphne fails:

mar 06 22:20:04 akiva.outerrim.lan daphne[10618]: 2018-03-06 22:20:04,844 WARNING  The current value "{u'ACCESS_TOKEN_EXPIRE_SECONDS': 31536000000, u'REFRESH_TOKEN_EXPIRE_SECONDS': 31536000000, u'AUTHORIZATION_CODE
mar 06 22:20:04 akiva.outerrim.lan daphne[10618]: Traceback (most recent call last):
mar 06 22:20:04 akiva.outerrim.lan daphne[10618]: File "/opt/awx/embedded/lib/python2.7/site-packages/awx/conf/settings.py", line 371, in _get_local
mar 06 22:20:04 akiva.outerrim.lan daphne[10618]: return field.run_validation(value)
mar 06 22:20:04 akiva.outerrim.lan daphne[10618]: File "/opt/awx/embedded/lib/python2.7/site-packages/rest_framework/fields.py", line 523, in run_validation
mar 06 22:20:04 akiva.outerrim.lan daphne[10618]: value = self.to_internal_value(data)
mar 06 22:20:04 akiva.outerrim.lan daphne[10618]: File "/opt/awx/embedded/lib/python2.7/site-packages/awx/api/fields.py", line 88, in to_internal_value
mar 06 22:20:04 akiva.outerrim.lan daphne[10618]: self.fail('invalid_key_names', invalid_key_names=', '.join(list(invalid_flags)))
mar 06 22:20:04 akiva.outerrim.lan daphne[10618]: File "/opt/awx/embedded/lib/python2.7/site-packages/rest_framework/fields.py", line 585, in fail
mar 06 22:20:04 akiva.outerrim.lan daphne[10618]: raise ValidationError(message_string, code=key)
mar 06 22:20:04 akiva.outerrim.lan daphne[10618]: ValidationError: [u'Invalid key names: REFRESH_TOKEN_EXPIRE_SECONDS']

**Comment by MrMEEE** [comment]
https://github.com/ansible/awx/issues/1464

**Comment by MrMEEE** [comment]
I think I fixed it.. added a line to the configuration (/etc/awx/settings.py):

ANSIBLE_VENV_PATH = '/opt/awx/embedded'

and created folder

mkdir /var/lib/awx/venv && chown awx:awx /var/lib/awx/venv

and

yum install bubblewrap

It seems to work here now :)

**Comment by MrMEEE** [comment]
@sunilsankar Can you confirm that this works now???

**Comment by sunilsankar** [comment]
I will test it and let you know last time I did it failed will do it today

Regards
Sunil

**Comment by MrMEEE** [comment]
Did you get it to work???

**Comment by sunilsankar** [comment]
it works great we can close this. Sorry for testing it late
