### ISSUE TITLE
AWX blank login 

### ISSUE THREAD

**Issue by andysmagana** [MrMEEE/awx-build#61]
AWX RPM setup login page works locally. 
From a remote computer AWX login page is blank. 

SELINUX is off
Firewall is off
private ip for AWX is 192.168.4.33 using port setup with semanage port using port 8052
browser used if firefox 
OS is Centos 7.5 on AWX and other server. 
AWX /etc/nginx/nginx.conf file 

`#user awx;

worker_processes  1;

error_log  /var/log/nginx/error_log warn;
pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access_log  main;

    map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
    }

    sendfile        on;
    #tcp_nopush     on;
    #gzip  on;

    upstream uwsgi {
        server 127.0.0.1:8050;
        }

    upstream daphne {
        server 127.0.0.1:8051;
    }

    server {
 #       listen 8052 default_server;
#Modified to listen on port 80
        listen 8052 default_server;
        # If you have a domain name, this is where to add it
        server_name _;
        keepalive_timeout 65;

        # HSTS (ngx_http_headers_module is required) (15768000 seconds = 6 months)
        add_header Strict-Transport-Security max-age=15768000;

        location /static/ {
            alias /opt/awx/static;
        }

        location /favicon.ico { alias /opt/awx/static/favicon.ico; }

        location /websocket {
            # Pass request to the upstream alias
            proxy_pass http://awx.example.com:8052;
            # Require http version 1.1 to allow for upgrade requests
            proxy_http_version 1.1;
            # We want proxy_buffering off for proxying to websockets.
            proxy_buffering off;
            # http://en.wikipedia.org/wiki/X-Forwarded-For
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            # enable this if you use HTTPS:
            proxy_set_header X-Forwarded-Proto https;
            # pass the Host: header from the client for the sake of redirects
            proxy_set_header Host $http_host;
            # We've set the Host header, so we don't need Nginx to muddle
            # about with redirects
            proxy_redirect off;
            # Depending on the request value, set the Upgrade and
            # connection headers
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
        }

        location / {
            # Add trailing / if missing
            rewrite ^(.*)$http_host(.*[^/])$ $1$http_host$2/ permanent;
            uwsgi_read_timeout 120s;
            uwsgi_pass uwsgi;
            include /etc/nginx/uwsgi_params;
        }
    }
}
`

[root@awx nginx]# systemctl restart nginx
[root@awx nginx]# setenforce 0
[root@awx nginx]# getenforce
Permissive
[root@awx nginx]# systemctl stop firewalld
[root@awx nginx]# vim /etc/nginx/nginx.conf

**Comment by MrMEEE** [comment]
have you looked in the log files??

new installation or upgrade?? Have it worked before?

**Comment by andysmagana** [comment]
I am going to re-install from the mrmeee copy awx-repo again and try to accomplish logging in to awx from another computer.

**Comment by MrMEEE** [comment]
Did you get it to work?
