### ISSUE TITLE
Ansible version in AWX rpm

### ISSUE THREAD

**Issue by tjyang** [MrMEEE/awx-build#62]
Hi @MrMEEE 

Do you know when ansible 2.7 will be bundled into AWX ? 
The centos 7 ansible system rpm is updated to  ansible 2.7 already.

* ansible showing version is 2.6.6 from command line.

```
[me@awx01 ~]$ rpm -q awx
awx-2.1.0.384-1.el7.x86_64
[me@awx01 ~]$ /opt/awx/bin/ansible --version
ansible 2.6.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/me/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/awx/embedded/lib/python2.7/site-packages/ansible
  executable location = /opt/awx/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
[me@awx01 ~]$

* So as in info from GUI.
```
![image](https://user-images.githubusercontent.com/378638/49472284-a77e4d80-f7d4-11e8-8d69-d5da7b467e38.png)

**Comment by MrMEEE** [comment]
Hi

I had some issues with 2.7.0, but haven't tested it sinde.. But the answer is, probably soon..

Else you can use venvs?

**Comment by tjyang** [comment]
I am a salstack user and trying to switch over to ansible.  I haven't run big playbook yet, so I may not experience your ansible 2.7 issue.

I see [ansible 2.7 support OS reboot](https://docs.ansible.com/ansible/2.7/modules/reboot_module.html) and I like to try out reboot in AWX controlled nodes, thus the asking.

**Comment by MrMEEE** [comment]
Ok.. If you want 2.7 right now, you can use venvs:
https://docs.ansible.com/ansible-tower/latest/html/upgrade-migration-guide/virtualenv.html

Just notice that there is a Bug that means that there needs to be created at least two venvs for them to show in AWX: https://github.com/MrMEEE/awx-build/issues/62

**Comment by MrMEEE** [comment]
From now on, AWX should be built with the newest available Ansible inside :)
