### ISSUE TITLE
2.1.1.* versions breaks building (Waiting for pull request)

### ISSUE THREAD

**Issue by MrMEEE** [MrMEEE/awx-build#63]
When bumping their builds from 2.1.0 to 2.1.1, the AWX team forgot to bump the VERSION file..

This means that the resulting tar.gz file is named wrongly and so is the contained folder..

Waiting for them to merge:
https://github.com/ansible/awx/pull/2875

**Comment by mjcasalogic** [comment]
Upstream bug: https://github.com/ansible/awx/issues/2876

**Comment by angystardust** [comment]
2.1.2 was just released and it seems ok... https://github.com/ansible/awx/blob/2.1.2/VERSION

**Comment by MrMEEE** [comment]
Yeah.. they just merged my patch before bumping the version to 2.1.2.. either way.. now they forgot to tag the release to 2.1.2 :P
