### ISSUE TITLE
Fix structure

### ISSUE THREAD

**Issue by MrMEEE** [MrMEEE/awx-build#64]
sorry for the delay. What I mean is: on a Tower setup the awx and ansible binaries are inside a default venv while on your rpm the binaries are inside /opt/awx/bin

_Originally posted by @angystardust in https://github.com/MrMEEE/awx-build/issues/48#issuecomment-437454204_

**Comment by angystardust** [comment]
Thanks a lot for working on that :+1:

**Comment by MrMEEE** [comment]
Structure completely changed in 3.0.0 and forward.. any comments are welcome..

**Comment by angystardust** [comment]
As soon as I will have time upgrade&test, I'll report here the results ;)
Thanks

**Comment by MrMEEE** [comment]
Did you get a chance to check it out?

**Comment by angystardust** [comment]
I’ll do in the next days. thanks for keeping on hold

**Comment by MrMEEE** [comment]
Did you get a change to look at it?

**Comment by MrMEEE** [comment]
I think this is fixed.. please reopen and correct me if i'm wrong
