### ISSUE TITLE
Cannot create new inventory

### ISSUE THREAD

**Issue by Neurozone** [MrMEEE/awx-build#66]
After upgrading to :+1: yum info awx.x86_64
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
Installed Packages
Name        : awx
Arch        : x86_64
Version     : 2.1.2.34
Release     : 1.el7
Size        : 363 M
Repo        : installed
From repo   : mrmeee-awx-dev
Summary     : Ansible AWX
License     : GPLv3
Description : Ansible AWX

We cannot create new inventory by cliking on the "+" button
It does nothing.
It seems it only the inventories who are impacted.

**Comment by Neurozone** [comment]
The issue seems related to one of thoses files:

/opt/awx/static/js  ll
total 5672
-rwxr-xr-x 1 awx awx 2913967 Jan  2 20:58 app.7bd14d087353b3079b43.js
-rwxr-xr-x 1 awx awx 2888260 Jan  2 20:58 vendor.3b65b1cff200dd76a44d.js

**Comment by MrMEEE** [comment]
Hi

Thanks for reporting...

I have fixed the issue (new node version) in 2.1.2.36-3.. it should be available very soon

**Comment by ghost** [comment]
I tried the new version and fix the issue, thank you. 
I suggest to use no dev repo for production, today I see you release a stable version 2.1 on no dev repo, with the follow commands I downgraded awx.

    yum clean all
    # change the baseurl repository to https://copr-be.cloud.fedoraproject.org/results/mrmeee/awx/epel-7-$basearch/
    yum downgrade awx

**Comment by tjyang** [comment]
FYI.
* I updated awx from 2.1.2.32 to 2.1.2.40 and the inventory creation is now working.

![image](https://user-images.githubusercontent.com/378638/51040544-64ef2400-157d-11e9-8316-1d718bea4da0.png)
* The rpm updated to.
```
[root@awx01 ~]#  rpm -q awx;date
awx-2.1.2.40-1.el7.x86_64
Fri Jan 11 09:30:52 EST 2019
[root@awx01 ~]#

```

**Comment by MrMEEE** [comment]
Cool.. thanks for the feedback
