### ISSUE TITLE
ansible_connection: network_cli require external rpm ansible

### ISSUE THREAD

**Issue by ghost** [MrMEEE/awx-build#67]
I have the latest version of awx rpm from both repository dev and not on 2 vm for testing.
I never installed rpm ansible because I see ansible is already included in awx's rpm under /opt/awx/bin, but I tried to develop a playbook which use network_cli as connection, but I receive the error:

    "msg": "Unable to find location of 'ansible-connection'"

the only way for resolve the issue is install also ansible rpm. So on no dev vm, I have 2 different versions of ansible 2.7.4 and 2.7.5. I think is better put ansible out of rpm, and add a require in spec's file.

**Comment by MrMEEE** [comment]
Hi..

You can just virtualenv's for different versions of ansible:

https://docs.ansible.com/ansible-tower/latest/html/upgrade-migration-guide/virtualenv.html

**Comment by ghost** [comment]
I explain better my issue, if I use awx rpm I can't use playbook which use network_cli, because /bin/network_cli is not included in rpm.
For solve my issue I need to install ansible rpm from repository epel, so now I have 2 ansible installed on my server, I think is wrong.

**Comment by MrMEEE** [comment]
It's actually part of the design in AWX/Tower to have multiple Ansible venv (multiple versions) installed..

I haven't checked in AWX 2.1.2.. but in 3.0.0 it seems like the network_cli is there:

/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/ansible/plugins/connection/network_cli.py

**Comment by MrMEEE** [comment]
@etmatrix Did you get it to work?

**Comment by MrMEEE** [comment]
Please reopen if this issue persists
