### ISSUE TITLE
Old AWX RPM Unavailable

### ISSUE THREAD

**Issue by bwosborne** [MrMEEE/awx-build#69]
I am currently using your awx-2.0.1-1.el7.x86_64 rpm.

I cannot get REST API tokens with the newer RPMs but the older one is unavailable.

Is the 2.0.1 rpm archived anywhere? 

I tried a procedure to build it myself but got a tar.gz instead of an RPM. I want to do some heavy testing so I do not want the "official" dockerized version.

**Comment by MrMEEE** [comment]
Hi..

You can grab it here:

http://martin-juhl.dk/awx/awx-2.0.1-1.el7.x86_64.rpm

**Comment by bwosborne** [comment]
Thank you for the link.

I assume the new REST API token pieces are still being developed. They are moving to be more compatible with OAuth,
