### ISSUE TITLE
VirtualEnv Issue

### ISSUE THREAD

**Issue by adambirds** [MrMEEE/awx-build#70]
I get the below issue when trying to load a project from git after installing through this method:

`Traceback (most recent call last): File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/tasks.py", line 978, in run env = self.build_env(instance, **kwargs) File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/tasks.py", line 1525, in build_env env = self.add_ansible_venv(settings.ANSIBLE_VENV_PATH, env) File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/tasks.py", line 790, in add_ansible_venv 'a valid Python virtualenv does not exist at {}'.format(venv_path) RuntimeError: a valid Python virtualenv does not exist at /opt/awx/embedded`

**Comment by MrMEEE** [comment]
Hi

Thanks for the feedback..

in /etc/tower/settings.py

Try to change:

ANSIBLE_VENV_PATH = '/opt/awx/embedded'
to
ANSIBLE_VENV_PATH = '/opt/rh/rh-python36/root/usr/'

restart all awx services, and tell me if it works?

**Comment by adambirds** [comment]
Hi @MrMEEE,

Looks like that has worked the project task running, not got time tonight, but will finish setting the job templates off Wednesday and confirm if those are working too.

But looks positive.

Thanks.

**Comment by MrMEEE** [comment]
Ok.. great.. else try:

ANSIBLE_VENV_PATH = '/opt/rh/rh-python36/root/'

I can see that I have used that during testing :)

**Comment by MrMEEE** [comment]
Fixed in v.3.0.0.0-8.. please reopen if you still have this issue
