### ISSUE TITLE
latyest pycurl 7.43 prevents from connecting to any RHV/ovirt job

### ISSUE THREAD

**Issue by natman** [MrMEEE/awx-build#72]
ISSUE TYPE

    Bug Report

COMPONENT NAME

    embedded pycurl 7.43 and nss
    ovirt4.py

SUMMARY

    /opt/awx/embedded/lib64/python2.7/site-packages/pycurl-7.43.0.1 is not compiled with nss support and prevents ovirt ansible module from connecting to the ovirt/RHV engine API.
    It also breaks ovirt4.py which is called by the synchronization of the inventories with RHV credentials.

ENVIRONMENT

    AWX version: 2.1.2
    AWX install method: RPM with repo from wget -O /etc/yum.repos.d/ansible-awx.repo https://copr.fedorainfracloud.org/coprs/mrmeee/ansible-awx/repo/epel-7/mrmeee-ansible-awx-epel-7.repo
    https://github.com/MrMEEE/awx-build/blob/master/installguide.md
    Ansible version: 2.7.4
    Operating System: centos 7.6
    Web Browser: firefox esr 60.4

STEPS TO REPRODUCE

When trying to add dynamic inventory from RHV, the job fails with this error:
...
ERROR! No inventory was parsed, please check your configuration and options.

It is like ovirt4.py couldn't generate the json exepcted file supposed to be read by ansible-inventory.
EXPECTED RESULTS

    inventory synchronization from RHV/ovirt is ok
    ovirt related playbooks successfully connects to the RHV API

ACTUAL RESULTS

When trying to add dynamic inventory from RHV, the job fails with this error:
...
ERROR! No inventory was parsed, please check your configuration and options.
ADDITIONAL INFORMATION

I successfully tested the command manually with awx-manage:

sudo -u awx /opt/awx/bin/awx-manage inventory_import --inventory-name Infra --source ovirt_source

cat ovirt_source
#!/bin/bash
/var/lib/awx/venv/ovirt/bin/ansible-inventory -i ovirt4.py --list
so credentials and url are ok.
/opt/awx/embedded/lib64/python2.7/site-packages/ovirtsdk4 which is broken due to 7.43 pycurl embedded version.

Two ways for fixing it:

1. pycurl 7.19 in a venv resolves the issue
2. also in the venv, compiling 7.43 with nss support:
export PYCURL_SSL_LIBRARY=nss; pip install pycurl --compile --no-cache-dir

Then, I rsynced the 7.43 pycurl from venv to /opt/embedded to check if the issue was the same... and this time ovirtsdk4 worked!

So obviously, /opt/awx/embedded/lib64/python2.7/site-packages/pycurl-7.43.0.1 sould be compiled with the nss support,

**Comment by MrMEEE** [comment]
AWX-RPM v.3.0.0 has completely changed the structure of the installation.. every python dep has been split out to separate rpms.. which means that stuff like this will be much easier to fix...

Could you upgrade to 3.0.0 and tell me if this issue is still present??

**Comment by MrMEEE** [comment]
please reopen if this persists in 3.0

**Comment by natman** [comment]
Sorry to reopen, but I've just upgraded to 7.0 and the issue is the same with a full python3 venv.
pycurl is 7.43.0.3 version. When using the pip provided pycurl, ovirt4.py can't find ovirt-engine-sdk > 4.0.0 and the dynamic inventory fails.
while installing pycurl 7.19 was a workaround with python 2.x, it doesn't do the trick anymore there. The only way to make ovirt-engine-sdk work is to uninstall and recompile pycurl with NSS support:
export PYCURL_SSL_LIBRARY=nss; pip install pycurl --compile --no-cache-dir

This library should be included by default with the default pycurl, otherwise none of RHV/ovirt related stuff will work (inventories and playbooks)

**Comment by MrMEEE** [comment]
Hi

I will look into this, and if it doesn't break any other stuff, I will implement your suggestion..

As a workaround for now, I would suggest that you create a venv with the PYCURL_SSL_LIBRARY=nss enabled.. 

One way is using the awx-create-venv command..

**Comment by natman** [comment]
That's what I already did, and it works as expected

**Comment by MrMEEE** [comment]
Ok.. good.. I will get back to this..

**Comment by gpavinteractiv** [comment]
I opened a separate issued before finding this one (thanks Nathan for your answer to gianluca on ovirt-user ml)

However creation of python2 venv fails with followinf errors :
````
[root@vs-inf-int-awx-fr-301 ~]# /opt/rh/rh-python36/root/usr/bin/awx-create-venv -n ovirt -p 2

Create Virtual Enviroment at:
  /var/lib/awx/venv/ovirt

Using Python 2

Installing Ansible 
   
New python executable in /var/lib/awx/venv/ovirt/bin/python
Installing setuptools, pip, wheel...done.

You are using pip version 9.0.1, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting python-memcached
  Using cached https://files.pythonhosted.org/packages/f5/90/19d3908048f70c120ec66a39e61b92c253e834e6e895cd104ce5e46cbe53/python_memcached-1.59-py2.py3-none-any.whl
Collecting psutil
  Using cached https://files.pythonhosted.org/packages/73/93/4f8213fbe66fc20cb904f35e6e04e20b47b85bee39845cc66a0bcf5ccdcb/psutil-5.6.7.tar.gz
Collecting six>=1.4.0 (from python-memcached)
  Using cached https://files.pythonhosted.org/packages/65/26/32b8464df2a97e6dd1b656ed26b2c194606c16fe163c695a992b36c11cdf/six-1.13.0-py2.py3-none-any.whl
Building wheels for collected packages: psutil
  Running setup.py bdist_wheel for psutil: started
  Running setup.py bdist_wheel for psutil: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/52/41/b0/bf50409fe2b1d3b79afa3eed71b54b3e30fe5b695db2c7ba2e
Successfully built psutil
Installing collected packages: six, python-memcached, psutil
Successfully installed psutil-5.6.7 python-memcached-1.59 six-1.13.0

  Could not find a version that satisfies the requirement ansible== (from versions: 1.0, 1.1, 1.2, 1.2.1, 1.2.2, 1.2.3, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.4, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.4.5, 1.5, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.6, 1.6.1, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.6.6, 1.6.7, 1.6.8, 1.6.9, 1.6.10, 1.7, 1.7.1, 1.7.2, 1.8, 1.8.1, 1.8.2, 1.8.3, 1.8.4, 1.9.0.1, 1.9.1, 1.9.2, 1.9.3, 1.9.4, 1.9.5, 1.9.6, 2.0.0.0, 2.0.0.1, 2.0.0.2, 2.0.1.0, 2.0.2.0, 2.1.0.0, 2.1.1.0, 2.1.2.0, 2.1.3.0, 2.1.4.0, 2.1.5.0, 2.1.6.0, 2.2.0.0, 2.2.1.0, 2.2.2.0, 2.2.3.0, 2.3.0.0, 2.3.1.0, 2.3.2.0, 2.3.3.0, 2.4.0.0, 2.4.1.0, 2.4.2.0, 2.4.3.0, 2.4.4.0, 2.4.5.0, 2.4.6.0, 2.5.0a1, 2.5.0b1, 2.5.0b2, 2.5.0rc1, 2.5.0rc2, 2.5.0rc3, 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.5.4, 2.5.5, 2.5.6, 2.5.7, 2.5.8, 2.5.9, 2.5.10, 2.5.11, 2.5.12, 2.5.13, 2.5.14, 2.5.15, 2.6.0a1, 2.6.0a2, 2.6.0rc1, 2.6.0rc2, 2.6.0rc3, 2.6.0rc4, 2.6.0rc5, 2.6.0, 2.6.1, 2.6.2, 2.6.3, 2.6.4, 2.6.5, 2.6.6, 2.6.7, 2.6.8, 2.6.9, 2.6.10, 2.6.11, 2.6.12, 2.6.13, 2.6.14, 2.6.15, 2.6.16, 2.6.17, 2.6.18, 2.6.19, 2.6.20, 2.7.0.dev0, 2.7.0a1, 2.7.0b1, 2.7.0rc1, 2.7.0rc2, 2.7.0rc3, 2.7.0rc4, 2.7.0, 2.7.1, 2.7.2, 2.7.3, 2.7.4, 2.7.5, 2.7.6, 2.7.7, 2.7.8, 2.7.9, 2.7.10, 2.7.11, 2.7.12, 2.7.13, 2.7.14, 2.7.15, 2.8.0a1, 2.8.0b1, 2.8.0rc1, 2.8.0rc2, 2.8.0rc3, 2.8.0, 2.8.1, 2.8.2, 2.8.3, 2.8.4, 2.8.5, 2.8.6, 2.8.7, 2.9.0b1, 2.9.0rc1, 2.9.0rc2, 2.9.0rc3, 2.9.0rc4, 2.9.0rc5, 2.9.0, 2.9.1)
No matching distribution found for ansible==
You are using pip version 9.0.1, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting ansible==

[root@vs-inf-int-awx-fr-301 ~]# /opt/rh/rh-python36/root/usr/bin/awx-create-venv -n ovirt -p 2 -a 2.9.1
2.9.1 is an invalid ansible version
[root@vs-inf-int-awx-fr-301 ~]# /opt/rh/rh-python36/root/usr/bin/awx-create-venv -n ovirt -p 2 -a 2.9.0
2.9.0 is an invalid ansible version
````

**Comment by gpavinteractiv** [comment]
I got the same error and opened a different issue before seeing this one.
I tried following Nathan's adivce seen on ovirt-user ML : "create a pyhton2 venv ans build pycurl with nss" , but that still does not work.

See issue 183 : https://github.com/MrMEEE/awx-build/issues/183
