### ISSUE TITLE
how to use port 80 for awx ?

### ISSUE THREAD

**Issue by Neurozone** [MrMEEE/awx-build#74]
Hello.
I want to use port 80 for the web interface but i'm lost in the settings.
How can I configure awx to use the default port 80 ?

Thank you !

**Comment by MrMEEE** [comment]
Hi

If you change any occurance in nginx.conf of 8052 to 80, and restart nginx.. That should fix it

**Comment by Neurozone** [comment]
Ok thank you, i was afraid to break something if I changed the port number.

**Comment by MrMEEE** [comment]
You might also need to change a line in /etc/tower/settings.py.. Also just look for 8052 and change to 80

**Comment by Neurozone** [comment]
I think it's in /etc/awx/settings.py   ;)

**Comment by MrMEEE** [comment]
Moved to /etc/tower from v.3.0.0 :)

**Comment by Neurozone** [comment]
So, it works !
