### ISSUE TITLE
Need docs for new awx-rpm developer

### ISSUE THREAD

**Issue by tjyang** [MrMEEE/awx-build#75]
Hi @MrMEEE 

Can you trouble you to write a  guide to on-board  new awx-rpm developer ? 
This way we can attract more contributors and spread the rpm maintenance load.

For example I try(not very hard)  setup my own awx-rpm rpm build environment  but failed to finish the whole process.  Thinks I done so far.

1. create fedora account
2. prep my centos 7 rpm build environment ...

perhaps enable wiki page of this project to document awx-rpm developer guide.

Thanks.

**Comment by MrMEEE** [comment]
Hi

Well.. good point.. I'll get around it, as soon as I have the time..

Right now, the build process is split..

1. ansible-awx, which is autobuilt on my local AWX Server and then pushed to copr, if the build is successful

2. the dependencies, which are, for now, handbuilt by the use of some scripts.. I have added the scripts (they needs alot of cleaning) to the https://github.com/MrMEEE/ansible-awx-depends repo..

Where are you stuck??

**Comment by tjyang** [comment]
* Assuming ./build.sh is the main script to build dependency.
* how can I download all the python requirement pkg's tar.gz files  ? 
* Here is the error

```
[pi@centos7 scripts]$ cat /etc/redhat-release;pwd;git remote -v;./build.sh
CentOS Linux release 7.6.1810 (Core)
/home/pi/github/ansible-awx-depends/scripts
origin  https://github.com/MrMEEE/ansible-awx-depends.git (fetch)
origin  https://github.com/MrMEEE/ansible-awx-depends.git (push)
tar (child): requirements/*.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
tar (child): requirements/*.tar.bz2: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
unzip:  cannot find or open requirements/*.zip, requirements/*.zip.zip or requirements/*.zip.ZIP.

No zipfiles found.
./build.sh: line 17: cd: /home/pi/github/ansible-awx-depends/scripts/requirements-source/*: No such file or directory
ls: cannot access requirements: No such file or directory
Number of source files: 0
Number of rpm files: 0
[pi@centos7 scripts]$

```

**Comment by MrMEEE** [comment]
Hi..

There is currently not much automation.. so there is no main script... just a lot of scattered scripts..

the order should be something like:

1. Download source:
Download source for a specific package:
./download-pip-source.sh "pyrad==2.1"

Download sources from requirements file:
./download-pip-source.sh "-r requirements.txt"

2. unpack source and build spec files:
./build.sh

3. move spec files from requirements-source/*/dist/*.spec to a SPECS folder
mkdir SPECS
mv requirements-source/*/dist/*.spec SPECS/

4. use the lines in todo.sh on the spec files (the script doesn't work, you have to do it manually or fix it)

5. copy source files from requirements to your SOURCES folder

6. spawn a docker build image (replace the paths to the sources and buildscripts):
exec docker run --rm -i -v /etc/rpm/macros.python3-default:/etc/rpm/macros.python3-default -v /home/awx/depends/python3/SOURCES:/root/rpmbuild/SOURCES -v /home/awx/depends/python3/:/source -v /home/awx/depends/python3/BUILDROOT:/root/rpmbuild/BUILDROOT -v /home/awx/depends/python3/BUILD:/root/rpmbuild/BUILD -v /home/awx/depends/python3/RPMS:/root/rpmbuild/RPMS -v /home/awx/depends/python3/SRPMS:/root/rpmbuild/SRPMS ctbuild/centos:7

This will not prompt with a # as a normal bash... try to "ls" or something to see if it is ready..

7. run the installdeps.sh script inside the docker image

8. use ./buildspec <name of specfile> to build the rpm of a specific spec file..

And now debugging starts... some of the packages will build out of the box, but alot will not.. 

All of the specs in the repo should be fine.. except for the azure packages, which will build, but contains some of the same files.. so they can't be simultaneous installed.. Would love if you could fix that...

**Comment by MrMEEE** [comment]
My autobuild playbooks for ansible-awx are available here.. (I'm maintaining them on my own local git, but will update them here from time to time):

https://github.com/MrMEEE/ansible-awx-auto-build

**Comment by tjyang** [comment]
>./download-pip-source.sh "-r requirements.txt"

where is reqirements.txt that contains all the python module need to be built ?

**Comment by MrMEEE** [comment]
They are in the source for awx, in the requirements folder... 
requirements_git.txt and requirements.txt are needed for AWX and 

requirements_ansible.txt and requirements_ansible_git.txt are needed for the "embedded" ansible (ansible as pip module)

Note that the _git.txt files are not parse able by the download-pip-source.sh script.. as they contain links to git repos and not pip names.. these have to be fetched manually

**Comment by tjyang** [comment]
I am testing and learning your [build procedure in my gdoc](https://docs.google.com/document/d/1M0bMi7Jbh1GXz7010jKakrEDST4ajcFhKTiaYnG4-kM/edit#heading=h.lwvmvgl2kmud)

**Comment by MrMEEE** [comment]
This stuff should be added to the wiki
