### ISSUE TITLE
[OK]: 3.0.1.97 to 3.0.1.107  upgrade 02/22/2019 

### ISSUE THREAD

**Issue by tjyang** [MrMEEE/awx-build#81]
My [upgrade note](https://docs.google.com/document/d/1M0bMi7Jbh1GXz7010jKakrEDST4ajcFhKTiaYnG4-kM/edit#heading=h.fn0wcbvtnkqn) using my awx01.test.lan VM.

**Comment by MrMEEE** [comment]
Thanks
