### ISSUE TITLE
unable to find package rh-postgresql10

### ISSUE THREAD

**Issue by jijendiranR** [MrMEEE/awx-build#83]
Is there any other way to install  rh-postgresql10 apart from yum installer getting no package found an exception. Unable to proceed flow after this step

**Comment by MrMEEE** [comment]
Hi

Have you remembered to install the "centos-release-scl-rh" package, before installing rh-postgresql10?

Are you on RHEL or CentOS?

**Comment by jijendiranR** [comment]
I am currently using Red Hat Enterprise Linux Server release 7.6 (Maipo).
getting the following error while skipping it

Error: Package: ansible-awx-3.0.1.219-1.el7.x86_64 (mrmeee-ansible-awx)
           Requires: rh-postgresql10-postgresql-devel
Error: Package: rh-python36-psycopg2-2.7.3.2-1.x86_64 (mrmeee-ansible-awx)
           Requires: libpq.so.rh-postgresql10-5()(64bit)

**Comment by MrMEEE** [comment]
As described in the installation (even though it might need a re-visit), you need the Red Hat Software Collections (rhscl) repo enabled

**Comment by MrMEEE** [comment]
Did you get it to work?

**Comment by jijendiranR** [comment]
The issue still exists after installing rhscl, is there a way to use lower version i.e 2.0+ instead of moving to 3.0+ version. The lower version is working fine as of now.

**Comment by MrMEEE** [comment]
could you please do a:
subscription-manager list
subscriptoin-manager repos --list-enabled
yum search rh-postgresql

**Comment by jijendiranR** [comment]
This is my result for the yum repo search

[root@vm-ansible01-p001 opc]# yum search rh-postgresql
Loaded plugins: langpacks, rhnplugin, ulninfo
This system is not registered with ULN.
You can use uln_register to register.
ULN Classic support will be disabled.
====================================================================== N/S matched: rh-postgresql ======================================================================
rh-postgresql95.x86_64 : Package that installs rh-postgresql95
rh-postgresql95-runtime.x86_64 : Package that handles rh-postgresql95 Software Collection.
rh-postgresql95-scldevel.x86_64 : Package shipping development files for rh-postgresql95
rh-postgresql96.x86_64 : Package that installs rh-postgresql96
rh-postgresql96-postgresql-contrib-syspaths.x86_64 : Convenient wrappers for the rh-postgresql96-postgresql-contrib package; replaces the postgresql-contrib package
rh-postgresql96-postgresql-server-syspaths.x86_64 : Convenient wrappers for the rh-postgresql96-postgresql-server package; replaces the postgresql-server package
rh-postgresql96-postgresql-syspaths.x86_64 : Convenient wrappers for the rh-postgresql96-postgresql package; replaces the postgresql package
rh-postgresql96-runtime.x86_64 : Package that handles rh-postgresql96 Software Collection.
rh-postgresql96-scldevel.x86_64 : Package shipping development files for rh-postgresql96
rh-postgresql96-syspaths.x86_64 : System-wide wrappers for the rh-postgresql96 Software Collection
rh-postgresql95-build.x86_64 : Package shipping basic build configuration
rh-postgresql95-postgresql.x86_64 : PostgreSQL client programs
rh-postgresql95-postgresql-contrib.x86_64 : Extension modules distributed with PostgreSQL
rh-postgresql95-postgresql-devel.x86_64 : PostgreSQL development header files and libraries
rh-postgresql95-postgresql-docs.x86_64 : Extra documentation for PostgreSQL
rh-postgresql95-postgresql-libs.x86_64 : The shared libraries required for any PostgreSQL clients
rh-postgresql95-postgresql-plperl.x86_64 : The Perl procedural language for PostgreSQL
rh-postgresql95-postgresql-plpython.x86_64 : The Python2 procedural language for PostgreSQL
rh-postgresql95-postgresql-pltcl.x86_64 : The Tcl procedural language for PostgreSQL
rh-postgresql95-postgresql-server.x86_64 : The programs needed to create and run a PostgreSQL server
rh-postgresql95-postgresql-static.x86_64 : Statically linked PostgreSQL libraries
rh-postgresql95-postgresql-test.x86_64 : The test suite distributed with PostgreSQL
rh-postgresql96-build.x86_64 : Package shipping basic build configuration
rh-postgresql96-postgresql.x86_64 : PostgreSQL client programs
rh-postgresql96-postgresql-contrib.x86_64 : Extension modules distributed with PostgreSQL
rh-postgresql96-postgresql-devel.x86_64 : PostgreSQL development header files and libraries
rh-postgresql96-postgresql-docs.x86_64 : Extra documentation for PostgreSQL
rh-postgresql96-postgresql-libs.x86_64 : The shared libraries required for any PostgreSQL clients
rh-postgresql96-postgresql-plperl.x86_64 : The Perl procedural language for PostgreSQL
rh-postgresql96-postgresql-plpython.x86_64 : The Python2 procedural language for PostgreSQL
rh-postgresql96-postgresql-pltcl.x86_64 : The Tcl procedural language for PostgreSQL
rh-postgresql96-postgresql-server.x86_64 : The programs needed to create and run a PostgreSQL server
rh-postgresql96-postgresql-static.x86_64 : Statically linked PostgreSQL libraries
rh-postgresql96-postgresql-test.x86_64 : The test suite distributed with PostgreSQL


Can I use version rh-postgresql96 and continue with my configuration.

**Comment by MrMEEE** [comment]
Please send the output of the two first commands as well:

subscription-manager list
subscriptoin-manager repos --list-enabled

postgresql96 won't work

**Comment by jijendiranR** [comment]
Getting bash command not found exception

**Comment by MrMEEE** [comment]
How did you succeed in removing subscription-manager on a RHEL system?? how do you update your systems??? Sure it's RHEL and not CentOS?

Please do a:

cat /etc/redhat-release

ls -la /etc/yum.repos.d/

cat /etc/yum.repos.d/redhat.repo

**Comment by jijendiranR** [comment]
[root@vm-ansible01-p001 opc]# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.6 (Maipo)

[root@vm-ansible01-p001 opc]# ls -la /etc/yum.repos.d/
total 96
drwxr-xr-x.  2 root root  4096 Nov  1 10:10 .
drwxr-xr-x. 94 root root  8192 Mar 12 10:36 ..
-rw-r--r--.  1 root root   338 Mar  8 13:05 ansible-awx.repo
-rw-r--r--.  1 root root   306 Mar  9 04:51 awx-rpm.repo
-rw-r--r--.  1 root root   916 May 23  2016 CentOS-SCLo-scl.repo
-rw-r--r--.  1 root root   892 Jun 16  2016 CentOS-SCLo-scl-rh.repo
-rw-r--r--.  1 root root   951 Oct  2  2017 epel.repo
-rw-r--r--.  1 root root  1050 Oct  2  2017 epel-testing.repo
-rw-r--r--.  1 root root   479 Mar  7 14:11 ksplice-ol7.repo
-rw-r--r--.  1 root root    70 Feb 19 00:07 .oracle_enable_repolist
-rw-r--r--.  1 root root   242 Feb 19 00:07 oracle-epel-ol7.repo
-rw-r--r--.  1 root root   802 Feb 19 00:07 oraclelinux-developer-ol7.repo
-rw-r--r--.  1 root root  3586 Feb 19 00:11 oracle-linux-ol7.repo
-rw-r--r--.  1 root root   275 Feb 19 00:07 oracle-softwarecollection-ol7.repo
-rw-r--r--.  1 root root  1004 May 18  2017 pgdg-10-redhat.repo
-rw-r--r--.  1 root root 15423 Feb 19 00:03 public-yum-ol7.repo.sav
-rw-r--r--.  1 root root   212 Mar  8 13:06 rabbitmq-erlang.repo
-rw-r--r--.  1 root root  2108 Feb 19 00:11 uek-ol7.repo
-rw-r--r--.  1 root root   225 Feb 19 00:11 virt-ol7.repo

[root@vm-ansible01-p001 opc]# ll /etc/yum.repos.d/
total 76
-rw-r--r--. 1 root root   338 Mar  8 13:05 ansible-awx.repo
-rw-r--r--. 1 root root   306 Mar  9 04:51 awx-rpm.repo
-rw-r--r--. 1 root root   916 May 23  2016 CentOS-SCLo-scl.repo
-rw-r--r--. 1 root root   892 Jun 16  2016 CentOS-SCLo-scl-rh.repo
-rw-r--r--. 1 root root   951 Oct  2  2017 epel.repo
-rw-r--r--. 1 root root  1050 Oct  2  2017 epel-testing.repo
-rw-r--r--. 1 root root   479 Mar  7 14:11 ksplice-ol7.repo
-rw-r--r--. 1 root root   242 Feb 19 00:07 oracle-epel-ol7.repo
-rw-r--r--. 1 root root   802 Feb 19 00:07 oraclelinux-developer-ol7.repo
-rw-r--r--. 1 root root  3586 Feb 19 00:11 oracle-linux-ol7.repo
-rw-r--r--. 1 root root   275 Feb 19 00:07 oracle-softwarecollection-ol7.repo
-rw-r--r--. 1 root root  1004 May 18  2017 pgdg-10-redhat.repo
-rw-r--r--. 1 root root 15423 Feb 19 00:03 public-yum-ol7.repo.sav
-rw-r--r--. 1 root root   212 Mar  8 13:06 rabbitmq-erlang.repo
-rw-r--r--. 1 root root  2108 Feb 19 00:11 uek-ol7.repo
-rw-r--r--. 1 root root   225 Feb 19 00:11 virt-ol7.repo

**Comment by MrMEEE** [comment]
Soooo... you are running RHEL, but updating from Oracle Linux updates?

That's weird..

**Comment by MrMEEE** [comment]
one question... why?

**Comment by MrMEEE** [comment]
It should work with the CentOS-SCLo-scl-rh... postgresql10 is in that repo... just be adviced that this machine is not support by neither Oracle or Red Hat

**Comment by Neurozone** [comment]
You should register your vm to RedHat if you have a valid subscription or going to CentOS.
But mixing repos from different release and OS is not a good idea

**Comment by MrMEEE** [comment]
@FlorianneRaven Completely agree...

**Comment by jijendiranR** [comment]
Is there any other alternate way there to install awx.

**Comment by MrMEEE** [comment]
Well.. there is always the docker install: https://github.com/ansible/awx

But in general I would highly recommend you to get the distributionchaos in order..

**Comment by MrMEEE** [comment]
@jijendiranR Can we close the case?

**Comment by jijendiranR** [comment]
Yes. thanks to the extended support for analyzing the issue.
