### ISSUE TITLE
Email notification is failing

### ISSUE THREAD

**Issue by murali741** [MrMEEE/awx-build#86]
Hi Martin,

I am running a job using tower. I have created a email and slack notification. After completion of my job I am not getting any notification basically those are failing.

What is the possible cause for this error??

Thanks
Murali Medi

**Comment by MrMEEE** [comment]
Hi Murali

I presume that you are using AWX and not Ansible Tower (the Red Hat product)..

I need some more information.. Do you get any errors??

Have you tried looking in the log files in /var/log/tower ??

**Comment by murali741** [comment]
Yeah I am using AWX. I am not getting any errors. When I click on test email notification I am getting email notification is failed. 

I have checked /var/log/tower there is no information about this

**Comment by MrMEEE** [comment]
Can you attach a screenshot?

**Comment by murali741** [comment]
![image](https://user-images.githubusercontent.com/29415599/54220755-7e9ee000-44c8-11e9-92fa-9470fd8333b9.png)

**Comment by MrMEEE** [comment]
Ok.. And some screenshots of the configuration of the notifications as well?

**Comment by murali741** [comment]
![image](https://user-images.githubusercontent.com/29415599/54223261-7d23e680-44cd-11e9-9c96-9ad883e8afbe.png)

**Comment by MrMEEE** [comment]
And you notification template?

**Comment by murali741** [comment]
what is the notification template?

**Comment by MrMEEE** [comment]
If you look at the last pic you sent, there is a link in the upper right corner

**Comment by murali741** [comment]
![image](https://user-images.githubusercontent.com/29415599/54224829-b6118a80-44d0-11e9-96cb-5086d1cb7cb7.png)

**Comment by murali741** [comment]
I have inserted the slack webhook token in the playbook yaml file I am getting the slack notification from the playbook not from the awx

**Comment by MrMEEE** [comment]
Have you made sure that postfix (or another mailserver) is configured?

**Comment by murali741** [comment]
yeah, postfix configured and I have sent email from command line

**Comment by MrMEEE** [comment]
Have you tried checking SELinux logs

sealert -a /var/log/audit/audit.log

Or temporarily disable selinux

setenforce  0

**Comment by murali741** [comment]
I have disabled firewall and selinux still not working

**Comment by MrMEEE** [comment]
Have you checked /var/log/messages for errors?

**Comment by murali741** [comment]
[root@nh-testdocker ~]# tail /var/log/messages
Mar 12 15:14:36 nh-testdocker scl: 2019-03-12 19:14:36,336 DEBUG    awx.main.dispatch task a85b1abc-c8bf-443a-9471-a25634b3affc starting awx.main.tasks.cluster_node_heartbeat(*[])
Mar 12 15:14:36 nh-testdocker scl: 2019-03-12 19:14:36,338 DEBUG    awx.main.tasks Cluster node heartbeat task.
Mar 12 15:14:36 nh-testdocker scl: 2019-03-12 19:14:36,361 DEBUG    awx.main.dispatch task a85b1abc-c8bf-443a-9471-a25634b3affc is finished
Mar 12 15:14:36 nh-testdocker scl: 2019-03-12 19:14:36,562 DEBUG    awx.main.dispatch publish awx.main.tasks.awx_periodic_scheduler(7d38d51a-f59d-4600-8a2b-5675ceca7899, queue=awx_private_queue)
Mar 12 15:14:36 nh-testdocker scl: [2019-03-12 19:14:36,562: DEBUG/Process-1] publish awx.main.tasks.awx_periodic_scheduler(7d38d51a-f59d-4600-8a2b-5675ceca7899, queue=awx_private_queue)
Mar 12 15:14:36 nh-testdocker scl: 2019-03-12 19:14:36,589 DEBUG    awx.main.dispatch delivered 7d38d51a-f59d-4600-8a2b-5675ceca7899 to worker[4249] qsize 0
Mar 12 15:14:36 nh-testdocker scl: 2019-03-12 19:14:36,592 DEBUG    awx.main.dispatch task 7d38d51a-f59d-4600-8a2b-5675ceca7899 starting awx.main.tasks.awx_periodic_scheduler(*[])
Mar 12 15:14:36 nh-testdocker scl: 2019-03-12 19:14:36,606 DEBUG    awx.main.tasks Starting periodic scheduler
Mar 12 15:14:36 nh-testdocker scl: 2019-03-12 19:14:36,611 DEBUG    awx.main.tasks Last scheduler run was: 2019-03-12 19:14:06.611340+00:00
Mar 12 15:14:36 nh-testdocker scl: 2019-03-12 19:14:36,628 DEBUG    awx.main.dispatch task 7d38d51a-f59d-4600-8a2b-5675ceca7899 is finished
[root@nh-testdocker ~]#

**Comment by murali741** [comment]
I have checked the api logs I am seeing below error 

            "created": "2019-03-13T14:18:56.299657Z",
            "modified": "2019-03-13T14:18:56.299688Z",
            "notification_template": 2,
            "error": "[Errno -2] Name or service not known",
            "status": "failed",
            "notifications_sent": 0,
            "notification_type": "email",

**Comment by MrMEEE** [comment]
That is weird.. It's working here.. (Only tested email).. Have you tried the test email button (seem to remember there is on in the notification templates)

**Comment by murali741** [comment]
I am doing with test email only. I have configured the sendmail server details and trying to test the email notification but I am getting the below error

451, b'Open relay not allowed - https://community.mimecast.com/docs/DOC-1369#451

**Comment by MrMEEE** [comment]
Ohh.. That is the configuration of your postfix that is denying you..

**Comment by murali741** [comment]
Do you know how to fix this issue??


Thanks
Murali Medi

**Comment by MrMEEE** [comment]
What is "mynetworks" set to in your main.cf??

**Comment by murali741** [comment]
127.0.0.0/8, 10.10.X.X/24

**Comment by MrMEEE** [comment]
Try to look in the maillog, and see if there is a hint.. networks seems ok..

**Comment by murali741** [comment]
Okay sure Martin.

Thanks for the help

**Comment by aqua-terra** [comment]
@murali741 I have the same issue, can you share what you did to fix this issue on your send? Thanks.
