### ISSUE TITLE
python yum dependency issue with newest (3.x) install instructions

### ISSUE THREAD

**Issue by helgiw** [MrMEEE/awx-build#87]
Hi Martin

I'm having issues with the following yum install line:
yum -y install --disablerepo='' --enablerepo='mrmeee-ansible-awx, base' rh-python36  

yum fails with:
(...)
--> Processing Dependency: /opt/rh/rh-python36/root/usr/bin/python3 for package: rh-python36-ansible-2.7.6-1.noarch
--> Processing Dependency: /opt/rh/rh-python36/root/usr/bin/python3 for package: rh-python36-jmespath-0.9.3-1.noarch
--> Finished Dependency Resolution
Error: Package: rh-python36-social-auth-app-django-2.1.0-1.noarch (mrmeee-ansible-awx)
           Requires: rh-python36-python(abi) = 3.6
Error: Package: rh-python36-django-qsstats-magic-0.7.2-1.noarch (mrmeee-ansible-awx)
           Requires: rh-python36-python(abi) = 3.6
(...) 
x 100

Is it safe to install rh-python36-runtime rh-python36-python rh-python36-python-libs rh-python36-python-pip rh-python36-python-setuptools from centos-sclo-rh  before that install command?

**Comment by murali741** [comment]
yum install -y rh-python36
yum -y install --disablerepo='*' --enablerepo='mrmeee-ansible-awx, base' -x *-debuginfo rh-python36*--exclude=rh-python36-python-typing-3.6.4-1.el7.noarch

will solve the issue 

Thanks

**Comment by MrMEEE** [comment]
Thanks.. Fixed in documentation
