### ISSUE TITLE
SSL Auto Refresh not Working

### ISSUE THREAD

**Issue by rchaud** [MrMEEE/awx-build#88]
Is anyone having issues with job auto refreshing when using SSL? I get all my templates stuck in Pending Status and the gray circle does not move like it used to. 

This is version 2.1.2

**Comment by MrMEEE** [comment]
what does your ssl configuration look like???

**Comment by rchaud** [comment]
Actually I found the issue, it was a 301 redirect from http to https that broke it. I removed the config and just ran it on port 443 and it is working again.
