### ISSUE TITLE
Ansible keeps loading forever

### ISSUE THREAD

**Issue by murali741** [MrMEEE/awx-build#89]
Hi Martin,

I have installed and ansible AWX running fine but after sometime it page loading forever. 

![image](https://user-images.githubusercontent.com/29415599/54400506-7cd84680-4699-11e9-926f-a02a29e38d5a.png)

**Comment by murali741** [comment]
Also, After running the job I am getting the email notification with job details like below

Job #53 had status failed, view details at https://towerhost/#/jobs/playbook/53

how to change the https://towerhost with my AWX host IP?? Does it have any .conf file?? What is the location of configuration file??


Thanks Martin

**Comment by MrMEEE** [comment]
It's in the database...

You have set it with the commands
```
sudo -u awx scl enable rh-python36 rh-postgresql10 "awx-manage provision_instance --hostname=$(hostname)"
sudo -u awx scl enable rh-python36 rh-postgresql10 "awx-manage register_queue --queuename=tower --hostnames=$(hostname)"
```

You should be able change it by rerunning the commands after changing the hostname

In regards to your first issue.. do you get any errors in the log files (/var/log/tower)??

**Comment by MrMEEE** [comment]
Did you get this to work??

**Comment by 6sossomons** [comment]
> Also, After running the job I am getting the email notification with job details like below
> 
> Job #53 had status failed, view details at https://towerhost/#/jobs/playbook/53
> 
> how to change the https://towerhost with my AWX host IP?? Does it have any .conf file?? What is the location of configuration file??
> 
> Thanks Martin

You change this information in the Settings -> System in the GUI as well, no need to run the awx-manage command...

**Comment by MrMEEE** [comment]
@6sossomons Thanks for the update

**Comment by MrMEEE** [comment]
Closing.. please reopen if issue persists
