### ISSUE TITLE
Please update AWX icons

### ISSUE THREAD

**Issue by tjyang** [MrMEEE/awx-build#9]
From angry potato icons to the ones at https://github.com/ansible/awx-logos/tree/master/awx/ui/client/assets

Thanks

**Comment by MrMEEE** [comment]
Noooooo.... I love the angry potato :) I think i'm gonna keep the potato... 

Might do an option for using the other icons though :)

**Comment by tjyang** [comment]
@MrMEEE
 
Thanks for the consideration. I was not aware there is supporter for angry potato ;)
I don't want to attract unnecessary attention for AWX in an Enterprise setting. 
So I replaced it from the instance I installed. Hope this can be fixed/added in rpm.

* [After update.](https://user-images.githubusercontent.com/378638/37990296-76abb820-31cb-11e8-885b-cb9fc4c77417.png)

BTW, great job on making this RPM. Hope I can help out somehow in the future(once AWX is adopted).

**Comment by bangnh1** [comment]
Have you ever replace logo-header.svg in static folder?

**Comment by tjyang** [comment]
@bangnh1 , Yes, I did. But it was a manual process.

**Comment by rthill** [comment]
To prevent logo overwrites just override the logo in you Nginx configuration like the following:

        location /favicon.ico {
            alias /opt/custom/media/favicon.ico;
        }

        location /static/assets/favicon.ico {
            alias /opt/custom/media/favicon.ico;
        }

        location /static/assets/logo-header.svg {
            alias /opt/custom/media/icon_large.svg;
        }

**Comment by tjyang** [comment]
@rthill , thanks for tip, following is my note.
* Grab logo and icon files from https://github.com/ansible/awx-logos/tree/master/awx/ui/client/assets.
   * and put them into /opt/awx/static/assets/awx/, create awx dir under assets. 
*  /etc/nginx/nginx.conf

```
<snipped>
        location /favicon.ico { alias /opt/awx/static/assets/awx/favicon.ico; }
        location /static/assets/favicon.ico { alias /opt/awx/static/assets/awx/favicon.ico; }
        location /static/assets/logo-header.svg {alias /opt/awx/static/assets/awx/logo-header.svg;}
        location /static/assets/logo-login.svg {alias /opt/awx/static/assets/awx/logo-login.svg;}
<snipped>
```
* "system restart nginx" to restart

**Comment by andysmagana** [comment]
I have the awx rpm setup and running and webpage login but I would like to log in from a different server right now the angry potatoe is on the firefox tab of the browser but the page is blank.

**Comment by tjyang** [comment]
Hi Andy,pls open another issue for this problem. And include details info but exclude private info. First guess is your firewall setting. pls try disable selinuxand firewall setting to see if remote web browser can see the login page.

**Comment by MrMEEE** [comment]
@tjyang two thoughts...

1. I would like to keep the angry potato as the default logo, in that way people will also be able to differentiate between AWX-RPM and AWX docker

2. We should put this into an optional RPM-package

**Comment by franzcisco** [comment]
Hi All!
first of all, congrats for the RPM, I am no dev guy but was still able to install AWX just by folloing the ste by step instructions.
Now, I do have a couple of issues, one is related to the logo so I will paste it here.

I followed  @tjyang 's input dated Sept21st (thanks for that) but something broke.
I copied the files, 
Edited the nginx.conf file

and then, I issued "systemctl restart nginx"
The result was that I could no longer access the webpage (page not available), even if the status of nginx seemed OK:

[devnet@VMW-DEVNET-AWX nginx]$ systemctl status nginx
â— nginx.service - The nginx HTTP and reverse proxy server
   Loaded: loaded (/usr/lib/systemd/system/nginx.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2019-06-19 11:56:16 CEST; 40s ago
  Process: 18818 ExecStart=/usr/sbin/nginx (code=exited, status=0/SUCCESS)
  Process: 18817 ExecStartPre=/usr/sbin/nginx -t (code=exited, status=0/SUCCESS)
  Process: 18815 ExecStartPre=/usr/bin/rm -f /run/nginx.pid (code=exited, status=0/SUCCESS)
 Main PID: 18819 (nginx)
   CGroup: /system.slice/nginx.service
           â”œâ”€18819 nginx: master process /usr/sbin/nginx
           â””â”€18820 nginx: worker process

Jun 19 11:56:16 VMW-DEVNET-AWX systemd[1]: Starting The nginx HTTP and reverse proxy server...
Jun 19 11:56:16 VMW-DEVNET-AWX nginx[18817]: nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
Jun 19 11:56:16 VMW-DEVNET-AWX nginx[18817]: nginx: configuration file /etc/nginx/nginx.conf test is successful
Jun 19 11:56:16 VMW-DEVNET-AWX systemd[1]: Started The nginx HTTP and reverse proxy server.

To get the system working again I just reverted to a previous snapshot :-(.
Am I doing something wrong here?

thx

**Comment by MrMEEE** [comment]
This should be the complete guide:
```
mkdir -p /opt/awx/static/assets/awx/
wget -O /opt/awx/static/assets/awx/logo-login.svg https://raw.githubusercontent.com/ansible/awx-logos/master/awx/ui/client/assets/logo-login.svg
wget -O /opt/awx/static/assets/awx/llogo-header.svg https://raw.githubusercontent.com/ansible/awx-logos/master/awx/ui/client/assets/logo-header.svg
```
Then your nginx.conf should look like this:
```
#user awx;

worker_processes  1;

error_log  /var/log/nginx/error_log info;
pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access_log  main;

    map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
    }

    sendfile        on;
    #tcp_nopush     on;
    #gzip  on;

    upstream uwsgi {
        server localhost:8050;
        #server 127.0.0.1:8050;
        }

    upstream daphne {
        server localhost:8051;
        #server 127.0.0.1:8051;.
    }

    server {
        listen 8052 default_server;

        # If you have a domain name, this is where to add it
        server_name _;
        keepalive_timeout 65;

        # HSTS (ngx_http_headers_module is required) (15768000 seconds = 6 months)
        add_header Strict-Transport-Security max-age=15768000;

        location /favicon.ico { alias /opt/awx/static/assets/awx/favicon.ico; }
        location /static/assets/favicon.ico { alias /opt/awx/static/assets/awx/favicon.ico; }
        location /static/assets/logo-header.svg {alias /opt/awx/static/assets/awx/logo-header.svg;}
        location /static/assets/logo-login.svg {alias /opt/awx/static/assets/awx/logo-login.svg;}

        location /static/ {
            alias /opt/awx/static/;
        }

#        location /favicon.ico { alias /opt/awx/static/favicon.ico; }

        location /websocket {
            # Pass request to the upstream alias
            proxy_pass http://daphne;
            # Require http version 1.1 to allow for upgrade requests
            proxy_http_version 1.1;
            # We want proxy_buffering off for proxying to websockets.
            proxy_buffering off;
            # http://en.wikipedia.org/wiki/X-Forwarded-For
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            # enable this if you use HTTPS:
            proxy_set_header X-Forwarded-Proto https;
            # pass the Host: header from the client for the sake of redirects
            proxy_set_header Host $http_host;
            # We've set the Host header, so we don't need Nginx to muddle
            # about with redirects
            proxy_redirect off;
            # Depending on the request value, set the Upgrade and
            # connection headers
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
        }

        location / {
            # Add trailing / if missing
            rewrite ^(.*)$http_host(.*[^/])$ $1$http_host$2/ permanent;
            uwsgi_read_timeout 120s;
            uwsgi_pass uwsgi;
            include /etc/nginx/uwsgi_params;
        }
    }
}
```

**Comment by MrMEEE** [comment]
Please notice that this is not the official logo for AWX-RPM
