### ISSUE TITLE
Do you have a playbook that installs packages and installs AWX standalone ?

### ISSUE THREAD

**Issue by andysmagana** [MrMEEE/awx-build#90]
Do you have a playbook that installs packages and installs AWX standalone ?

**Comment by MrMEEE** [comment]
Hi

My good colleague and friend is doing just that here:

https://gitlab.com/MarcoDePollo/ansible-awx

**Comment by andysmagana** [comment]
Thank  you this is exactly what I am looking for but I did leave a question under Issues over at that gitlab repo but my question is: 

How would I change the role to create the postgres user and create database to an external postgres database and change the postgres10 to postgres96 ?


I work for a DoD facility and just looking for a role that would be able to be used in a disaster recovery situation especially for it to be able to point and connect to  an external PostGres database. 

Thanks.

**Comment by MrMEEE** [comment]
I don't think that he has done the external database stuff.. but it should be really simple, just change the database configuration in /etc/tower/settings.py, before deploying the database and remove the installation of postgres...

Going from PostgreSQL 10 to 9.6 is not possible... AWX is only supported on 10.. (or that is what upstream AWX guys say)

**Comment by andysmagana** [comment]
Hello, 

Regarding pointing to an external database this is what the /etc/tower/settings.py  contains: 

DATABASES = {
    'default': {
        'ATOMIC_REQUESTS': True,
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'awx',
        # 'USER': os.getenv("DATABASE_USER", None),
        # 'PASSWORD': os.getenv("DATABASE_PASSWORD", None),
        # 'HOST': os.getenv("DATABASE_HOST", None),
        # 'PORT': os.getenv("DATABASE_PORT", None),
    }
}

**Comment by MrMEEE** [comment]
Yes, so just change those lines to your configuration, and remove the hashes..??

**Comment by andysmagana** [comment]
Do you mean like this: 


DATABASES = {
'default': {
'ATOMIC_REQUESTS': True,
'ENGINE': 'django.db.backends.postgresql',
'NAME': 'awx',
# 'USER': os.getenv("DATABASE_USER", None),

‘USER’: 'mrmeee',

# 'PASSWORD': os.getenv("DATABASE_PASSWORD", None),

‘PASSWORD’: 'secret',

# 'HOST': os.getenv("DATABASE_HOST", None),

‘HOST’: 'db1.some.place’,

# 'PORT': os.getenv("DATABASE_PORT", None),

‘PORT’: '5432'

}
}

**Comment by MrMEEE** [comment]
yeah.. something like that should work..

**Comment by andysmagana** [comment]
Good morning getting this error running the playbook that can install AWX.  Thanks for your time. 




TASK [awx : shell] *******************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "scl enable rh-postgresql10 \"postgresql-setup initdb\"", "delta": "0:00:00.069039", "end": "2019-03-23 07:14:12.046677", "msg": "non-zero return code", "rc": 1, "start": "2019-03-23 07:14:11.977638", "stderr": "WARNING: using obsoleted argument syntax, try --help\nWARNING: arguments transformed to: postgresql-setup --initdb --unit rh-postgresql10-postgresql\nERROR: The /var/lib/pgsql directory has wrong permissions.\n       Please make sure the directory is writable by awx.", "stderr_lines": ["WARNING: using obsoleted argument syntax, try --help", "WARNING: arguments transformed to: postgresql-setup --initdb --unit rh-postgresql10-postgresql", "ERROR: The /var/lib/pgsql directory has wrong permissions.", "       Please make sure the directory is writable by awx."], "stdout": "", "stdout_lines": []}
 [WARNING]: Could not create retry file '/etc/ansible/roles/install-awx.retry'.         [Errno 13] Permission denied: u'/etc/ansible/roles/install-awx.retry'

**Comment by MrMEEE** [comment]
Hi

This is not my PlayBook.. Can you please report it at the PlayBook source..

**Comment by Neurozone** [comment]
ERROR: The /var/lib/pgsql directory has wrong permissions.
 Please make sure the directory is writable by awx."

the error is really simple it depends on your linuc configuration, add awx to postgres group ?


If you don't know how to solve this, maybe you shouldn't try to install this. It a simple task for a linux sysadmin...

That's why I don't like end user doing commands with root permissions, you can mess up totally your os...

**Comment by andysmagana** [comment]
Wow really ? Maybe this should be put in the AWX install repo.

**Comment by MrMEEE** [comment]
@andysmagana The postgresql folder should only be readable by the postgres user.. my guess here is either:

1. you are running the playbook as the awx user, and it's designed for being runned as root
2. the playbook has a bug, which makes the postgres init run with the wrong user..

**Comment by andysmagana** [comment]
I am looking for exactly like this AWX playbook we use CentOS but what I can say is I need the playbook to point to an external database because we use the Atlassian suite and its database is on postgres96. It would be cool to see this playbook pull all the packages required from an internal repo.  

For example: 

I have to download say for example with yumdownloader to include dependencies. 
Then put everything into an existing repo. 

But the thing would have to create the database and user at an external database.

**Comment by MrMEEE** [comment]
That should be pretty simple? just make the changes.. except that I don't think you'll get it working on PostgreSQL 9.6
