### ISSUE TITLE
SSH error when running job template

### ISSUE THREAD

**Issue by timcgoodman** [MrMEEE/awx-build#94]
This is a fresh install of AWX.  I'm trying to run a job template and I'm getting the following error message - 

1
ansible-playbook 2.7.6
2
  config file = None
3
  configured module search path = ['/var/lib/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
4
  ansible python module location = /opt/rh/rh-python36/root/lib/python3.6/site-packages/ansible
5
  executable location = /opt/rh/rh-python36/root/bin/ansible-playbook
6
  python version = 3.6.3 (default, Mar 20 2018, 13:50:41) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
7
No config file found; using defaults
8
SSH password: 
9
setting up inventory plugins
10
/tmp/awx_43_cy3wrl2s/tmpfscx8n8n did not meet host_list requirements, check plugin documentation if this is unexpected
11
Parsed /tmp/awx_43_cy3wrl2s/tmpfscx8n8n inventory source with script plugin
12
Loading callback plugin awx_display of type stdout, v2.0 from /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/ansible_runner/display_callback/module.py
13
14
PLAYBOOK: recap_awx.yml ********************************************************
15
1 plays in recap_awx.yml
16
17
PLAY [recap] *******************************************************************
18:49:04
18
19
TASK [Gathering Facts] *********************************************************
18:49:04
20
task path: /var/lib/awx/projects/_6__bh_git/recap_awx.yml:2
21
<savrp-puppetmods01.bh.intra> ESTABLISH SSH CONNECTION FOR USER: goodmant
22
<savrp-puppetmods01.bh.intra> SSH: EXEC sshpass -d9 ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o User=goodmant -o ConnectTimeout=10 -o StrictHostKeyChecking=no -o ControlPath=/tmp/awx_43_cy3wrl2s/cp/be0ef2a791 savrp-puppetmods01.bh.intra '/bin/sh -c '"'"'echo ~goodmant && sleep 0'"'"''
23
<savrp-puppetmods01.bh.intra> (255, b'', b'OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 62: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug1: Control socket "/tmp/awx_43_cy3wrl2s/cp/be0ef2a791" does not exist\r\ndebug1: Executing proxy command: exec /usr/bin/sss_ssh_knownhostsproxy -p 22 savrp-puppetmods01.bh.intra\r\ndebug3: timeout: 10000 ms remain after connect\r\ndebug1: permanently_drop_suid: 990\r\ndebug1: key_load_public: No such file or directory\r\ndebug1: identity file /var/lib/awx/.ssh/id_rsa type -1\r\ndebug1: key_load_public: No such file or directory\r\ndebug1: identity file /var/lib/awx/.ssh/id_rsa-cert type -1\r\ndebug1: key_load_public: No such file or directory\r\ndebug1: identity file /var/lib/awx/.ssh/id_dsa type -1\r\ndebug1: key_load_public: No such file or directory\r\ndebug1: identity file /var/lib/awx/.ssh/id_dsa-cert type -1\r\ndebug1: key_load_public: …
24
fatal: [savrp-puppetmods01.bh.intra]: UNREACHABLE! => {
25
    "changed": false,
26
    "msg": "Failed to connect to the host via ssh: OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 62: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug1: Control socket \"/tmp/awx_43_cy3wrl2s/cp/be0ef2a791\" does not exist\r\ndebug1: Executing proxy command: exec /usr/bin/sss_ssh_knownhostsproxy -p 22 savrp-puppetmods01.bh.intra\r\ndebug3: timeout: 10000 ms remain after connect\r\ndebug1: permanently_drop_suid: 990\r\ndebug1: key_load_public: No such file or directory\r\ndebug1: identity file /var/lib/awx/.ssh/id_rsa type -1\r\ndebug1: key_load_public: No such file or directory\r\ndebug1: identity file /var/lib/awx/.ssh/id_rsa-cert type -1\r\ndebug1: key_load_public: No such file or directory\r\ndebug1: identity file /var/lib/awx/.ssh/id_dsa type -1\r\ndebug1: key_load_public: No su…
...
29
30
PLAY RECAP *********************************************************************
18:49:05
31
savrp-puppetmods01.bh.intra : ok=0    changed=0    unreachable=1    failed=0   

I have AWX running in Docker containers with no issues.  Any idea why I'm getting this failure?

**Comment by MrMEEE** [comment]
well, the obviuos, stupid solutions first:
The error says "UNREACHABLE", have you tried doing an ssh from the awx machine to savrp-puppetmods01.bh.intra, just to check that it has nothing to do with firewalls and stuff?

Can I see the configuration of the host?

Is it correct that you are using a proxy?

**Comment by timcgoodman** [comment]
I can ssh from the awx server to the puppetmods server.

I am not using a proxy.

I can send you the configuration, just let me know what you want to see.

**Comment by MrMEEE** [comment]
Ok

Could send complete output of line 23?

Which authentication method do you use?

**Comment by timcgoodman** [comment]
I am using password for authentication.

Here is the output of line 23
<savrp-puppetmods01.bh.intra> (255, b'', b'OpenSSH_7.4p1, OpenSSL
1.0.2k-fips 26 Jan 2017\r\ndebug1: Reading configuration data
/etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 62: Applying
options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug1:
Control socket "/tmp/awx_41_c6l1m3k0/cp/6af56bd988" does not
exist\r\ndebug1: Executing proxy command: exec
/usr/bin/sss_ssh_knownhostsproxy -p 22
savrp-puppetmods01.bh.intra\r\ndebug3: timeout: 10000 ms remain after
connect\r\ndebug1: permanently_drop_suid: 990\r\ndebug1: key_load_public:
No such file or directory\r\ndebug1: identity file /var/lib/awx/.ssh/id_rsa
type -1\r\ndebug1: key_load_public: No such file or directory\r\ndebug1:
identity file /var/lib/awx/.ssh/id_rsa-cert type -1\r\ndebug1:
key_load_public: No such file or directory\r\ndebug1: identity file
/var/lib/awx/.ssh/id_dsa type -1\r\ndebug1: key_load_public: No such file
or directory\r\ndebug1: identity file /var/lib/awx/.ssh/id_dsa-cert type
-1\r\ndebug1: key_load_public: …

I noticed line 26 also got truncated so here is the full output
"unreachable": true,
    "msg": "Failed to connect to the host via ssh: OpenSSH_7.4p1, OpenSSL
1.0.2k-fips  26 Jan 2017\r\ndebug1: Reading configuration data
/etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 62: Applying
options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug1:
Control socket \"/tmp/awx_41_c6l1m3k0/cp/6af56bd988\" does not
exist\r\ndebug1: Executing proxy command: exec
/usr/bin/sss_ssh_knownhostsproxy -p 22
savrp-puppetmods01.bh.intra\r\ndebug3: timeout: 10000 ms remain after
connect\r\ndebug1: permanently_drop_suid: 990\r\ndebug1: key_load_public:
No such file or directory\r\ndebug1: identity file /var/lib/awx/.ssh/id_rsa
type -1\r\ndebug1: key_load_public: No such file or directory\r\ndebug1:
identity file /var/lib/awx/.ssh/id_rsa-cert type -1\r\ndebug1:
key_load_public: No such file or directory\r\ndebug1: identity file
/var/lib/awx/.ssh/id_dsa type -1\r\ndebug1: key_load_public: No such file
or directory\r\ndebug1: identity file /var/lib/awx/.ssh/id_dsa-cert type
-1\r\ndebug1: key_load_public: No such file or directory\r\ndebug1:
identity file /var/lib/awx/.ssh/id_ecdsa type -1\r\ndebug1:
key_load_public: No such file or directory\r\ndebug1: identity file
/var/lib/awx/.ssh/id_ecdsa-cert type -1\r\ndebug1: key_load_public: No such
file or directory\r\ndebug1: identity file /var/lib/awx/.ssh/id_ed25519
type -1\r\ndebug1: key_load_public: No such file or directory\r\ndebug1:
identity file /var/lib/awx/.ssh/id_ed25519-cert type -1\r\ndebug1: Enabling
compatibility mode for protocol 2.0\r\ndebug1: Local version string
SSH-2.0-OpenSSH_7.4\r\ndebug1: ssh_exchange_identification: This account is
currently not available.\n\r\nssh_exchange_identification: Connection
closed by remote host\r\n",
    "changed": false

**Comment by MrMEEE** [comment]
What user are you trying to connect as?

Are you using become? and to what user

**Comment by MrMEEE** [comment]
Just remembered something.. 

Try to run:

usermod -s /bin/bash awx

and then try again

**Comment by timcgoodman** [comment]
I am trying to connect as myself.  I do have the become option selected but
I don't specify a user.

I tried doing usermod -s /bin/bash awx but it still doesn't work.

**Comment by MrMEEE** [comment]
Did you get this to work?
