### ISSUE TITLE
inventory dyn bug with py3.6

### ISSUE THREAD

**Issue by chris93111** [MrMEEE/awx-build#95]
Hi

I try create inventory dyn with vmware and awx not foud the module pyvmomi

 [WARNING]:  * Failed to parse /opt/rh/rh-python36/root/usr/lib/python3.6/site-
packages/awx/plugins/inventory/vmware_inventory.py with script plugin:
Inventory script (/opt/rh/rh-python36/root/usr/lib/python3.6/site-
packages/awx/plugins/inventory/vmware_inventory.py) had an execution error:
### ERROR: This inventory script required 'pyVmomi' Python module, it was not able
to load it
 [WARNING]: Unable to parse /opt/rh/rh-python36/root/usr/lib/python3.6/site-
packages/awx/plugins/inventory/vmware_inventory.py as an inventory source
ERROR! No inventory was parsed, please check your configuration and options.

i have check the module is installed 

[root@xxxxxx inventory]# pip show PyVmomi
Name: pyvmomi
Version: 6.5
Summary: VMware vSphere Python SDK
Home-page: https://github.com/vmware/pyvmomi
Author: VMware, Inc.
Author-email: jhu@vmware.com
License: License :: OSI Approved :: Apache Software License
Location: /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages
Requires: requests, six

**Comment by MrMEEE** [comment]
Have you installed all the dependencies from my repo??

Try to run:
rpm -aq rh-python36-pyvmomi

**Comment by chris93111** [comment]
yes dependencies is installed 

rh-python36-pyvmomi-6.5-2.noarch
rh-python36-pyvmomi.noarch             6.5-2               @mrmeee-ansible-awx

**Comment by chris93111** [comment]
i have restore the path of venv , and i have other error 

    1.900 INFO     Updating inventory 2: xxxxx
    3.140 DEBUG    Using base command: python /opt/rh/rh-python36/root/bin/ansible-inventory -i /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/plugins/inventory/vmware_inventory.py --playbook-dir /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/plugins/inventory
    3.140 INFO     Reading Ansible inventory source: /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/plugins/inventory/vmware_inventory.py
    3.142 INFO     Using VIRTUAL_ENV: /opt/rh/rh-python36/root/
    3.142 INFO     Using PATH: /opt/rh/rh-python36/root/bin:/var/lib/awx/venv/awx/bin:/opt/rh/rh-postgresql10/root/usr/bin:/opt/rh/rh-python36/root/usr/bin:/opt/awx/bin:/bin:/sbin:/usr/bin:/usr/sbin
    3.142 INFO     Using PYTHONPATH: /opt/rh/rh-python36/root/lib/python3.6/site-packages:
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/bin/awx-manage", line 11, in <module>
    sys.exit(manage())
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/__init__.py", line 140, in manage
    execute_from_command_line(sys.argv)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 1138, in handle
    raise exc
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 1028, in handle
    data = AnsibleInventoryLoader(source=source, is_custom=self.is_custom, venv_path=venv_path).load()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 206, in load
    return self.command_to_json(base_args + ['--list'])
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 189, in command_to_json
    self.method, proc.returncode, stdout, stderr))
RuntimeError: ansible-inventory failed (rc=1) with stdout:

stderr:
 [WARNING]:  * Failed to parse /opt/rh/rh-python36/root/usr/lib/python3.6/site-
packages/awx/plugins/inventory/vmware_inventory.py with script plugin:
Inventory script (/opt/rh/rh-python36/root/usr/lib/python3.6/site-
packages/awx/plugins/inventory/vmware_inventory.py) had an execution error:
Traceback (most recent call last):   File "/opt/rh/rh-
python36/root/usr/lib/python3.6/site-
packages/awx/plugins/inventory/vmware_inventory.py", line 772, in <module>
print(VMWareInventory().show())   File "/opt/rh/rh-
python36/root/usr/lib/python3.6/site-
packages/awx/plugins/inventory/vmware_inventory.py", line 145, in __init__
self.do_api_calls_update_cache()   File "/opt/rh/rh-
python36/root/usr/lib/python3.6/site-
packages/awx/plugins/inventory/vmware_inventory.py", line 184, in
do_api_calls_update_cache     self.inventory =
self.instances_to_inventory(self.get_instances())   File "/opt/rh/rh-
python36/root/usr/lib/python3.6/site-
packages/awx/plugins/inventory/vmware_inventory.py", line 351, in get_instances
return self._get_instances(kwargs)   File "/opt/rh/rh-
python36/root/usr/lib/python3.6/site-
packages/awx/plugins/inventory/vmware_inventory.py", line 393, in
_get_instances     for instance in sorted(instances): TypeError: '<' not
supported between instances of 'vim.VirtualMachine' and 'vim.VirtualMachine'

 [WARNING]: Unable to parse /opt/rh/rh-python36/root/usr/lib/python3.6/site-
packages/awx/plugins/inventory/vmware_inventory.py as an inventory source

ERROR! No inventory was parsed, please check your configuration and options.

**Comment by MrMEEE** [comment]
what was your VENV path before??

I would guess that this is because the vmware_inventory.py script isn't updated with support for python3...

https://github.com/ansible/awx/issues/3511

**Comment by chris93111** [comment]
Before I use python 2 and last ansible but i have the same error 

I test with last awx in dockerhub and work with python 3

**Comment by MrMEEE** [comment]
Are you sure that it works in the docker version??

They seem to have the same issue?

https://github.com/ansible/ansible/issues/46727

**Comment by chris93111** [comment]
yes is work 

   2.976 DEBUG    Using base command: python /usr/bin/ansible-inventory -i /var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/plugins/inventory/vmware_inventory.py --playbook-dir /var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/plugins/inventory
    2.976 INFO     Reading Ansible inventory source: /var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/plugins/inventory/vmware_inventory.py
    2.978 INFO     Using VIRTUAL_ENV: /var/lib/awx/venv/ansible
    2.978 INFO     Using PATH: /var/lib/awx/venv/ansible/bin:/var/lib/awx/venv/awx/bin:/var/lib/awx/venv/awx/bin:/var/lib/awx/venv/awx/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    2.978 INFO     Using PYTHONPATH: /var/lib/awx/venv/ansible/lib/python2.7/site-packages:
  834.713 DEBUG    Finished loading from source: /var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/plugins/inventory/vmware_inventory.py
  834.713 INFO     Processing JSON output...
  834.713 DEBUG    Loaded group: all
  834.713 DEBUG    Loaded group: XXXXX
  834.713 DEBUG    Adding child group XXXXXX to parent all

**Comment by MrMEEE** [comment]
Seems like they are still running python2 in the docker version:

2.978 INFO Using PYTHONPATH: /var/lib/awx/venv/ansible/lib/python2.7/site-packages

please try to use awx-create-venv to create a python2 venv

**Comment by chris93111** [comment]
ok i have retry with python2 venv but is the same error, he go to python 3 

ANSIBLE_VENV_PATH = '/var/lib/awx/venv/python2-ansible2.7.9-3032019/

    2.770 DEBUG    Using base command: python /var/lib/awx/venv/python2-ansible2.7.9-3032019/bin/ansible-inventory -i /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/plugins/inventory/vmware_inventory.py --playbook-dir /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/plugins/inventory
    2.770 INFO     Reading Ansible inventory source: /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/plugins/inventory/vmware_inventory.py
    2.772 INFO     Using VIRTUAL_ENV: /var/lib/awx/venv/python2-ansible2.7.9-3032019/
    2.772 INFO     Using PATH: /var/lib/awx/venv/python2-ansible2.7.9-3032019/bin:/var/lib/awx/venv/awx/bin:/opt/rh/rh-postgresql10/root/usr/bin:/opt/rh/rh-python36/root/usr/bin:/opt/awx/bin:/bin:/sbin:/usr/bin:/usr/sbin
    2.772 INFO     ### Using PYTHONPATH: /var/lib/awx/venv/python2-ansible2.7.9-3032019/lib/python3.6/site-packages:
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/bin/awx-manage", line 11, in <module>
    sys.exit(manage())
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/__init__.py", line 140, in manage
    execute_from_command_line(sys.argv)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 1138, in handle
    raise exc
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 1028, in handle
    data = AnsibleInventoryLoader(source=source, is_custom=self.is_custom, venv_path=venv_path).load()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 206, in load
    return self.command_to_json(base_args + ['--list'])
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 189, in command_to_json
    self.method, proc.returncode, stdout, stderr))
RuntimeError: ansible-inventory failed (rc=1) with stdout:
stderr:
 [WARNING]:  * Failed to parse /opt/rh/rh-python36/root/usr/lib/python3.6/site-
packages/awx/plugins/inventory/vmware_inventory.py with script plugin:
Inventory script (/opt/rh/rh-python36/root/usr/lib/python3.6/site-
packages/awx/plugins/inventory/vmware_inventory.py) had an execution error:
Traceback (most recent call last):   File "/opt/rh/rh-
python36/root/usr/lib/python3.6/site-
packages/awx/plugins/inventory/vmware_inventory.py", line 772, in <module>
print(VMWareInventory().show())   File "/opt/rh/rh-
python36/root/usr/lib/python3.6/site-
packages/awx/plugins/inventory/vmware_inventory.py", line 145, in __init__
self.do_api_calls_update_cache()   File "/opt/rh/rh-
python36/root/usr/lib/python3.6/site-
packages/awx/plugins/inventory/vmware_inventory.py", line 184, in
do_api_calls_update_cache     self.inventory =
self.instances_to_inventory(self.get_instances())   File "/opt/rh/rh-
python36/root/usr/lib/python3.6/site-
packages/awx/plugins/inventory/vmware_inventory.py", line 351, in get_instances
return self._get_instances(kwargs)   File "/opt/rh/rh-
python36/root/usr/lib/python3.6/site-
packages/awx/plugins/inventory/vmware_inventory.py", line 393, in
_get_instances     for instance in sorted(instances): TypeError: '<' not
supported between instances of 'vim.VirtualMachine' and 'vim.VirtualMachine'
 [WARNING]: Unable to parse /opt/rh/rh-python36/root/usr/lib/python3.6/site-
packages/awx/plugins/inventory/vmware_inventory.py as an inventory source
ERROR! No inventory was parsed, please check your configuration and options.

**Comment by MrMEEE** [comment]
And what if you try to create a python3 venv?

**Comment by chris93111** [comment]
it's the same 

    2.865 DEBUG    Using base command: python /var/lib/awx/venv/python3-ansible2.7.9-3032019/bin/ansible-inventory -i /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/plugins/inventory/vmware_inventory.py --playbook-dir /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/plugins/inventory
    2.866 INFO     Reading Ansible inventory source: /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/plugins/inventory/vmware_inventory.py
    2.867 INFO     Using VIRTUAL_ENV: /var/lib/awx/venv/python3-ansible2.7.9-3032019
    2.867 INFO     Using PATH: /var/lib/awx/venv/python3-ansible2.7.9-3032019/bin:/var/lib/awx/venv/awx/bin:/opt/rh/rh-postgresql10/root/usr/bin:/opt/rh/rh-python36/root/usr/bin:/opt/awx/bin:/bin:/sbin:/usr/bin:/usr/sbin
    2.867 INFO     Using PYTHONPATH: /var/lib/awx/venv/python3-ansible2.7.9-3032019/lib/python3.6/site-packages:
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/bin/awx-manage", line 11, in <module>
    sys.exit(manage())
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/__init__.py", line 140, in manage
    execute_from_command_line(sys.argv)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 1138, in handle
    raise exc
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 1028, in handle
    data = AnsibleInventoryLoader(source=source, is_custom=self.is_custom, venv_path=venv_path).load()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 206, in load
    return self.command_to_json(base_args + ['--list'])
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 189, in command_to_json
    self.method, proc.returncode, stdout, stderr))
RuntimeError: ansible-inventory failed (rc=1) with stdout:
stderr:
 [WARNING]:  * Failed to parse /opt/rh/rh-python36/root/usr/lib/python3.6/site-
packages/awx/plugins/inventory/vmware_inventory.py with script plugin:
Inventory script (/opt/rh/rh-python36/root/usr/lib/python3.6/site-
packages/awx/plugins/inventory/vmware_inventory.py) had an execution error:
Traceback (most recent call last):   File "/opt/rh/rh-
python36/root/usr/lib/python3.6/site-
packages/awx/plugins/inventory/vmware_inventory.py", line 772, in <module>
print(VMWareInventory().show())   File "/opt/rh/rh-
python36/root/usr/lib/python3.6/site-
packages/awx/plugins/inventory/vmware_inventory.py", line 145, in __init__
self.do_api_calls_update_cache()   File "/opt/rh/rh-
python36/root/usr/lib/python3.6/site-
packages/awx/plugins/inventory/vmware_inventory.py", line 184, in
do_api_calls_update_cache     self.inventory =
self.instances_to_inventory(self.get_instances())   File "/opt/rh/rh-
python36/root/usr/lib/python3.6/site-
packages/awx/plugins/inventory/vmware_inventory.py", line 351, in get_instances
return self._get_instances(kwargs)   File "/opt/rh/rh-
python36/root/usr/lib/python3.6/site-
packages/awx/plugins/inventory/vmware_inventory.py", line 393, in
_get_instances     for instance in sorted(instances): TypeError: '<' not
supported between instances of 'vim.VirtualMachine' and 'vim.VirtualMachine'
 [WARNING]: Unable to parse /opt/rh/rh-python36/root/usr/lib/python3.6/site-
packages/awx/plugins/inventory/vmware_inventory.py as an inventory source
ERROR! No inventory was parsed, please check your configuration and options.

**Comment by angystardust** [comment]
Seems like the same issue I've reported here -> https://github.com/MrMEEE/awx-build/issues/82

**Comment by chris93111** [comment]
@angystardust my installation is fromscratch

**Comment by MrMEEE** [comment]
Hi

Stuff has been merge upstream to fix this issue.. could you try again with 4.0.0.227??

Thanks

**Comment by angystardust** [comment]
Hi @MrMEEE I've just tried with a 2.7 venv and it works

**Comment by MrMEEE** [comment]
Hi, could you try again with python 3.6?

**Comment by MrMEEE** [comment]
Did you get this to work?? please reopen if you didn't

**Comment by mschoenly** [comment]
I had this problem with AWX 7.0.X and was able to fix it using this script:
https://github.com/ansible/ansible/blob/devel/contrib/inventory/vmware_inventory.py

**Comment by DiecoTheBxxst** [comment]
> I had this problem with AWX 7.0.X and was able to fix it using this script:
> https://github.com/ansible/ansible/blob/devel/contrib/inventory/vmware_inventory.py

Sorry, how i have to use the script python you suggest?
