### ISSUE TITLE
Add new instance at INSTANCE_GROUP

### ISSUE THREAD

**Issue by RunicBean** [MrMEEE/awx-build#97]
Hi MrMEEE,

Thanks for your awx rpm solution! I have some questions about adding new instances.
Assuming that I've built one awx MASTER server successfully, and I want to add one new instance for job running. 
First, I did the total same process to build awx NODE except installing rabbitmq, postgresql.
Second, I changed some settings so that the awx NODE connects to the rabbitmq, postgresql server at awx master server.
Third, I added the NODE to instance_group via command: 
`sudo -u awx /opt/awx/bin/awx-manage provision_instance --hostname=$(hostname)
sudo -u awx /opt/awx/bin/awx-manage register_queue --queuename=tower --hostnames=$(hostname)`
Last, I startup awx systemd services.
I found the node ip appeared at INSTANCE_GROUP but it shows as UNAVAILABLE there.

1. What does it drive that UNAVAILABLE appears here? Any table in postgreDB or MASTER call some process API at NODE to see if it can take traffic to run job or not?
2. Based on current building process, what additional actions(e.g. change some settings) should I take to build a new AVAILABLE NODE? And what actions I don't need to take?(e.g. start awx-web or awx-dispatcher etc.)

Thanks again for your help! Any further info please feel free to contact me.

**Comment by MrMEEE** [comment]
Hi there..

I must admit that this is a part of AWX that I haven't really tested that much.. But I should.. so will do this in the near future..

I know that HA is working https://github.com/MrMEEE/awx-build/issues/26.. maybe you can use some inspiration from there?..

Have you tried looking at the documentation from Ansible Tower??

**Comment by RunicBean** [comment]
Hi MrMEEE,

I've tested and it works well as cluster now. Some drafts about how this be built:
1. AWX clusters connect with each other via RabbitMQ so RabbitMQ should be clustered first among AWX clusters. And this action can provide HA solution if RabbitMQ queue is durable.
2. According to current building process, I took two additional actions: Building RabbitMQ clusters and Setting one external PostgreSQL DB.

And yes, I've looked into Tower's Doc about 'clustering'. But the doc's a little drafted and some detailed error occurred during clustering.

**Comment by RunicBean** [comment]
@MrMEEE And hopefully can you please try a general clustering way and merge it into your build module when you are available? Thank you very much!

**Comment by powertim** [comment]
Hi guys,

Finally the playbook is here: https://github.com/powertim/deploy_awx-rpm
Currently designed for RHEL7 x86_64 with Satellite repos.
I will try to update it with manual repos as described on https://awx.wiki/installation/repositories/rhel7-x86_64.
And why not in the future for the different OS supported on the awx.wiki...

Please try first to adapt the playbook before opening an issue.
I'll fill up the README soon.

Best,

Tim
