### ISSUE TITLE
Integrate ARA with AWX

### ISSUE THREAD

**Issue by 6sossomons** [MrMEEE/awx-build#98]
Have you had any luck integrating ARA with your AWX configurations?

**Comment by MrMEEE** [comment]
Hi

Haven't tried, but looks fun :)..

Should be pretty easy to get my setup to build a RPM of ARA.. and then it should be simple to add it into the callback configuration of AWX...

Will look into it, in the near future

**Comment by MrMEEE** [comment]
I have added rh-python36-ara to the repo, and it seems to work when I use it with standalone ansible.. but I can't get it to log anything with AWX (https://github.com/ansible-community/ara/issues/24)

When I (or someone else) gets it to work, I will add systemd scripts for the ara server..

**Comment by bryanasdev000** [comment]
Cool! ARA will greatly improve the reporting functionality of AWX.
